- linkerd/tracing/src/lib.rs
- linkerd/tracing/src/test.rs
The `Settings::build` method is fairly large and complex. This change
splits into a few smaller units and reduces boilerplate--especially
around reading the settings from the environment.
This change is being made in service of #601 to help avoid making the
build method even more complicated.
> tracing: Simplify initialization

- linkerd/app/inbound/src/lib.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/app/src/env.rs
The inbound proxy's layer that switches between routed and passthru
stacks uses an unnecessary explict type for its predicate. In order to
setup for further changes to this stack, this change eliminate the
specialized type in favor of a closure.
We also ditch the use of IndexSet as there's no functional need for it.
> inbound: Simplify protocol-detection skipping

- Cargo.lock
- linkerd/app/core/Cargo.toml
- linkerd/app/inbound/fuzz/Cargo.lock
- linkerd/app/integration/Cargo.toml
- linkerd/proxy/api-resolve/Cargo.toml
- linkerd/proxy/identity/Cargo.toml
- linkerd/proxy/tap/Cargo.toml
- linkerd/proxy/tap/src/grpc/server.rs
- linkerd/service-profiles/Cargo.toml
While we prepare for upcoming policy work, we should move the proxy to
use the updated crate from the main branch of the repo. This updated
version exposes a feature for each API--and for server- and
client-generation--so that we can more narrowly express dependencies in
the proxy.
> proxy-api: Update proxy-api to use the main branch

- linkerd/app/outbound/src/http/logical.rs
- linkerd/http-retry/src/replay.rs
In PR #1020, the retry code was changed so that bodies are only wrapped
in a `ReplayBody` when the request will be retried. The intention was to
remove the `replay::layer` pushed to the stack before the retry layer,
so that bodies are only wrapped when retries are enabled for the route,
and not for all routes in a profile.
However, I somehow managed to not remove the `replay::layer` from the
stack (possibly due to a messed up rebase). Oops. This meant that all
bodies for endpoints with service profiles were wrapped, and when the
route has retries enabled, it's wrapped twice. When wrapped twice, this
means that we potentially buffer the body data *twice* --- which may mean
actually copying bytes, since replaying from the buffer would now yield
a `Data` type that isn't itself `Bytes`, …
> outbound: don't double-wrap replay bodies

- linkerd/app/outbound/src/ingress.rs
The ingress-mode proxy's forwarding stack--used when a request does not
set the `l5d-dst-override` header--has no failfast implemetation. This
means that when a connection can't be obtained for the endpoint,
requests are buffered indefinitely.
This change adds a failfast layer so that these requests are failed
eagerly after 3s of unavailability, causing the serverside connection to
be dropped (so that the application client may re-resolve the endpoint).
This is really a temporary solution. We should probably avoid
implementing reconnection at all in this case so that connection errors
can be used in place of failfast errors.
Related to linkerd/linkerd2#6184
> ingress: Add failfast to the forwarder

- Cargo.lock
- linkerd/proxy/tap/Cargo.toml
- linkerd/proxy/tap/src/grpc/match_.rs
The tap tests were disabled in #568. This change restores these tests,
updating them to use quickcheck v1.
> tap: Restore tap matching tests

- linkerd/proxy/tap/src/grpc/match_.rs
The `quickcheck` tests for tap that were re-enabled in PR #1042 have
caught a bug: when a `PortMatch` message has a `min` value that's
greater than its `max` value, the tests expect that `TcpMatch::try_from`
should return an error (since the range is obviously invalid). However,
we don't currently do that.
This is causing CI to break on an unrelated change:
https://github.com/linkerd/linkerd2-proxy/runs/2797285941#step:3:907
This PR adds a new test reproducing the failing quickcheck inputs, and
fixes the bug (by making `TcpMatch::try_from` return an error in that
case).
Since `quickcheck` inputs are randomly generated and are not
deterministic, I thought it was probably a good idea to have a
hard-coded test to reproduce this case, just in case there are future
regressions. As a side note, …
> tap: return an error when a `PortRange`'s min > max

- linkerd/app/core/src/retry.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/http-box/src/erase_request.rs
- linkerd/http-box/src/request.rs
- linkerd/http-box/src/response.rs
- linkerd/proxy/http/src/lib.rs
- linkerd/retry/Cargo.toml
- linkerd/retry/src/lib.rs
- linkerd/stack/src/lib.rs
A few suggestions on #1043 
- Expose `EraseRequest` via `BoxRequest::erased` -- we don't actually care about the different types--the behavior is basically the same -- there's just some minor differences with regards to preserving marker types. It reads a little bit more naturally if we just hang it all off BoxRequest.
- Renamed the `linkerd_retry::RetryPolicy` trait to `linkerd_retry::PrepareRequest` (to match its only method). It's a bit... _malkovich_ to have both `tower::retry::Policy` and `linkerd_retry::RetryPolicy` which are closely related but different.
- `linkerd_retry` now re-exports relevant `tower::retry` types.
- Renames in `app::core::retry` to reflect actual types. For instance, `NewRetry` is now `NewRetryPolicy` -- since it actually implements `NewPolicy` and has nothing …
> RetryPolicy refactor suggestions

- .github/dependabot.yml
The GitHub UI reports an error with our dependabot config:
> The property '#/updates/0/versioning-strategy' value "increase-if-necessary" did not match one of the following values: lockfile-only, auto
This change removes the version-strategy setting.
Furthermore, this change adds configurations for each fuzzer directory,
since they have separate lockfiles.
> Fixup dependabot configuration

- linkerd/app/outbound/src/tcp/logical.rs
These don't actually *need* to advance the mock clock --- they are just
intended to make the current task yield so the background task can
observe updates. Replacing them with `yield_now` expresses intent more
accurately.
Also, this seems to fix the test failing after upgrading to tokio
1.6.2+, presumably related to tokio-rs/tokio#3852. I'm still trying to
figure out _why_ exactly this fixes the test (and why it breaks in the
first place), but at least this PR will get CI passing on Tokio 1.7.0.
See here for details:
https://github.com/linkerd/linkerd2-proxy/pull/1079#issuecomment-862750060
> outbound: replace `sleep`s in test with `yield_now`

- .github/workflows/coverage.yml
e0e2b3407 updated the coverage action to be skipped when the
`dependencies` label is set, but in practice dependabot sets labels
after the PR is actually created, so the action can fire before the
label is present.
This change updates the coverage action to look at the PR title and skip
coverage when the title begins with `build(deps): `.
> build(deps): Skip coverage by PR title

- Cargo.lock
- Cargo.toml
- linkerd/dns/Cargo.toml
- linkerd/dns/fuzz/Cargo.toml
trust-dns has begun preparations for the v0.21.0 release. This change
updates our git dependency to use the most recent version.
> build(deps): Update trust-dns to v0.21.0-alpha.1

- Cargo.lock
- linkerd/app/core/Cargo.toml
- linkerd/app/core/src/config.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/inbound/src/require_identity.rs
This branch adds a `PortSet` type that's a simple wrapper around
`std::collections::HashSet` but specialized for storing ports (`u16`
values). The `PortSet` type overrides the default hasher so that we
don't have to actually hash ports, and just use their numeric value.
See here for details:
https://github.com/linkerd/linkerd2-proxy/pull/1048#discussion_r653855672
Depends on #1048
> config: add a `PortSet` type

- .github/workflows/advisory.yml
- .github/workflows/release.yml
- .github/workflows/rust.yml
Now that actions versions are managed by dependabot, there's no use in
having to manually maintain version comments.
> build(deps): Remove version comments from Actions

- linkerd/app/core/src/errors.rs
- linkerd/error-metrics/Cargo.toml
- linkerd/error-metrics/src/lib.rs
- linkerd/metrics/src/prom.rs
We currently expose a single `request_errors_total` metric with a
`direction` label that indicates whether the error is on the inbound or
outbound proxy. This is in-line with many of our other metrics; but this
conflicts with prometheus best practices as we do not necessarily
maintain a uniform set of labels for all instances of a metric.  To
correct this, we want to adopt a scheme of using distinct metrics for
differing scopes with differing labels.
This change replaces the single `request_errors_total` metric with two
new metrics: `inbound_http_errors_total` and
`outbound_http_errors_total`.
As it turns out, the `request_errors_total` metric isn't actually
consumed anywhere in the _linkerd2_ repo, so this change can be made
safely without requiring control-plane changes. In follow-up …
> Replace the `request_errors_total` metric

- Cargo.lock
- linkerd/app/Cargo.toml
- linkerd/app/core/Cargo.toml
- linkerd/app/core/src/errors.rs
- linkerd/app/integration/Cargo.toml
- linkerd/opencensus/Cargo.toml
- linkerd/opencensus/src/lib.rs
- linkerd/proxy/api-resolve/Cargo.toml
- linkerd/proxy/api-resolve/src/resolve.rs
- linkerd/proxy/identity/Cargo.toml
- linkerd/proxy/identity/src/certify.rs
- linkerd/proxy/tap/Cargo.toml
- linkerd/service-profiles/Cargo.toml
- linkerd/service-profiles/src/client.rs
- linkerd/service-profiles/src/lib.rs
- linkerd/tonic-watch/Cargo.toml
- linkerd/transport-header/Cargo.toml
- opencensus-proto/Cargo.toml
This updates `prost`, `prost-types`, and `prost-build` to v0.8, which
includes a fix for a panic (and potential denial-of-service attack) when
converting a protobuf duration into a Rust `Duration`. Although we don't
use the vulnerable APIs in the proxy or in `linkerd2-proxy-api`, this is
necessary in order to fix a RUSTSEC advisory warning. In order to update
`prost`, we must also update `tonic` and `tonic-build` to v0.5, which
depends on `prost` 0.8, and update the `linkerd2-proxy-api` crate to
include linkerd/linkerd2-proxy-api#71.
Since these crates all depend on each other, we need to update them all
at the same time. Dependabot has opened separate PRs for these crates,
but none of them will pass CI, since they depend on incompatible
versions. This PR, on the other hand, should pass, …
> build(deps): update `tonic`, `prost`, and  `linkerd2-proxy-api`

- Cargo.lock
- linkerd/error-metrics/Cargo.toml
- linkerd/error-metrics/src/layer.rs
- linkerd/error-metrics/src/lib.rs
- linkerd/error-metrics/src/service.rs
- linkerd/http-metrics/Cargo.toml
- linkerd/http-metrics/src/lib.rs
- linkerd/http-metrics/src/requests/mod.rs
- linkerd/http-metrics/src/requests/report.rs
- linkerd/http-metrics/src/requests/service.rs
- linkerd/http-metrics/src/retries.rs
- linkerd/metrics/Cargo.toml
- linkerd/metrics/src/store.rs
- linkerd/proxy/tap/Cargo.toml
- linkerd/proxy/tap/src/registry.rs
- linkerd/proxy/transport/Cargo.toml
- linkerd/proxy/transport/src/metrics.rs
- linkerd/stack/metrics/Cargo.toml
- linkerd/stack/metrics/src/lib.rs
PR #1117 includes a change to move some uses of `std::sync::Mutex` to
`parking_lot::Mutex`, as the latter implementation is generally more
efficient.
This change updates all telemetry-related uses of Mutex with the
implementation in `parking_lot`.
Co-authored-by: Eliza Weisman <eliza@buoyant.io>
> Use `parking_lot::Mutex` in telemetry

- linkerd/app/core/src/errors.rs
- linkerd/app/core/src/svc.rs
- linkerd/app/inbound/src/http/mod.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/lib.rs
The connect-timeout logic isn't really inbound-specific and may be
useful elsewhere, like on the outbound stack.
This change moves this logic from `Inbound::to_tcp_connect` to
`Stack::push_connect_timeout` and restores `Inbound::to_tcp_connect` to
be responsible for building the TCP connection layer. Our tests go back
to mocking the `to_tcp_connect` layering (as it's quite simple).
> Add Stack::push_connect_timeout

- linkerd/app/integration/src/metrics.rs
- linkerd/app/integration/src/tests/telemetry/mod.rs
Currently, there's a bug in the metrics test code where a metric can
match if it contains *any* of the expected labels, even if some are
missing. This is because the test code assumes a metric will match, and
sets the matched value to `false` if any expected label keys have
unexpected values. However, if a label that the matcher is configured to
expect isn't present *at all* in the actual metric, it is still
considered matched. This allows tests to pass even if required labels
aren't present, which is pretty bad.
This branch fixes that bug by counting how many matches were found, and
comparing it to the number of labels that are expected. If fewer labels
were found, then the metric is not a match, even if all the found labels
had the expected values.
It turns out that a lot of the …
> metrics: fix metrics test code allowing incomplete matches

- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/http/mod.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/http/detect.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/switch_logical.rs
- linkerd/app/outbound/src/tcp/connect.rs
- linkerd/app/outbound/src/tcp/logical.rs
We have 100+ lines of boilerplate from the inbound and outbound stack
builders. This change introduces helpers: `Inbound::map_stack` and
`Outbound::map_stack`. These helpers provide a way to map over the inner
stack type, which eliminates the boilerplate of de/re-structruring the
builder type.
> Reduce stack-builder boilerplate

- linkerd/app/src/env.rs
linkerd/linkerd2#5988 describes a situation where our keepalive settings
are incompatible with with Go's gRPC library's behavior. Until we can
implement behavior that does not conflict with common client/server
implementations, it seems most prudent to simply disable these settings
by default (leaving TCP-level keepalives unchanged).
> Remove HTTP/2 keepalive configuration

- linkerd/app/gateway/src/gateway.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/gateway/src/tests.rs
- linkerd/app/outbound/src/endpoint.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/lib.rs
When testing [linkerd2/PR#6090](https://github.com/linkerd/linkerd2/pull/6090) we noticed that requests to a mirror service from a source cluster to a target cluster would fail on the outbound side of the gateway (in the target cluster) if the profile returned contains an endpoint. [[1]](https://github.com/linkerd/linkerd2/pull/6090#issuecomment-871754124). The failure is related to some changes that we have made previously to support StatefulSets across multicluster ([PR#6260 in linkerd2](https://github.com/linkerd/linkerd2/pull/6260)); when we send a request to an endpoint mirror service (a mirror service that corresponds to a pod), we expect the proxy to connect to it directly instead of building a logical stack.
Currently, the outbound proxy does not handle endpoints when running in …
> Handle profile endpoint in Gateway outbound stack

- linkerd/app/inbound/src/http/mod.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/test/src/http_util.rs
The inbound server stack is fairly large. While sketching out changes to
support inbound policy, it's helpful to split this larger stack into a
few smaller components (using the recently-introduced `map_stack`
helper).
This change:
* Modifies `Inbound::push_http_server` to return a boxed service. This
service was being boxed by `Inbound::into_server`. This change helps
reduce boilerplate in our test utilities, too. (In fact, this change
requires that we eliminate some unnecessary type constraints).
* Changes `Inbound::to_tcp_connect` to `Inbound::into_tcp_connect`. The
internal cloning is not necessary.
* Changes `Inbound::into_server` to `Inbound::push_server`. Internally,
this function now uses several calls to `map_stack` to build the
inbound server stack.
> inbound: Reorganize server into smaller stacks

- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/metrics/tcp_accept_errors.rs
- linkerd/app/core/src/svc.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/inbound/src/target.rs
- linkerd/app/src/tap.rs
- linkerd/detect/src/lib.rs
- linkerd/proxy/tap/src/accept.rs
- linkerd/stack/src/lib.rs
- linkerd/tls/src/server/mod.rs
- linkerd/tls/tests/tls_accept.rs
Stack modules that take configuration take one of two approaches: they
either use the `Param` trait to extract a configuration from the target
or they take configuration at construction-time. For example, the TLS
server module takes its detection timeout as an argument when
constructing its layer. But we want to modify the inbound stack to
configure detection timeouts dynamically, as informed by discovery; so
it will no longer be appropriate to take this configuration when
constructing the layer.
This change introduces the `stack::ExtactParam` trait which lets us
provide a _strategy_ to the TLS server layer. For now, strategy
implementations ignore the target type, continuing to use a fixed
timeout set during stack construction; but in an upcoming change we'll
be able to modify some of …
> stack: Introduce ExtractParam and InsertParam

- linkerd/app/core/src/svc.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/inbound/src/http/mod.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/outbound/src/endpoint.rs
- linkerd/app/outbound/src/http/detect.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/logical.rs
- linkerd/app/outbound/src/switch_logical.rs
- linkerd/app/test/src/http_util.rs
We have BoxHttp and BoxNewHttp aliases that help reduce type
boilerplate. This change adds similar aliases for TCP-forwarding stacks.
> Add BoxTcp and BoxNewTcp service type aliases

- Cargo.lock
- linkerd/app/core/src/retry.rs
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/peer_proxy_errors.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/app/outbound/src/test_util.rs
- linkerd/proxy/http/src/client_handle.rs
- linkerd/proxy/http/src/lib.rs
Suggestions for #1180 
* `outbound` should not pull in `proxy_http`. Instead, we use re-exports from `app_core` like `proxy::http`.
* We don't want to expose inner workings of how a `ClientHandle` is constructed. We have the `Close` & `Closed` types that hide the inner `Arc<Notify>`. This change adds `ClientHandle::new` to build these types without exposing the inner impl.
* I've renamed `add_client_handle` to `set_client_handle` and changed it to take a mutable reference and, rather than return the request, we return a future that fires when the client handle is closed.
* As discussed in https://github.com/linkerd/linkerd2-proxy/pull/1180/files#r683052774, the test seems a bit more complicated than it needs to be. I'd rather have a narrow unit test that exercises the behavior we care …
> Suggestions for #1180

- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/port_policies.rs
- linkerd/app/src/env.rs
The proxy supports a [default port policy][1]. We currently hardcode a
[default policy permitting all connections][2]. We should make this
behavior configurable. This will enable the proxy-injector to set
default behavior for each workload and, more imminently, we will be able
to configure the identity proxy's behavior to require TLS. See
linkerd/linkerd2#6606 for details.
This branch adds a `LINKERD2_PROXY_INBOUND_DEFAULT_POLICY` environment
configuration supporting the following values:
* `authenticated`
* `deny`
* `tis-unauthenticated`
* `unauthenticated`
This was implemented by:
* Adding a new `TlsUnauthenticated` variant to `AllowPolicy`. This
variant allows all TLS connections, regardless of whether they have
valid client identities.
* Adding `FromStr` implementations for …
> inbound: support configurable default port policies

- linkerd/proxy/transport/src/connect.rs
- linkerd/proxy/transport/src/lib.rs
- linkerd/proxy/transport/src/listen.rs
As noted in the todo, once tokio's `TcpStream::into_std` merged we now have a way to convert `tokio` -> `std` `TcpStream`s and use `socket2`'s `Socket::From<TcpStream>` impl to safely set a socket's keepalive option.
> Remove unsafety from setting TcpStream keepalive

- linkerd/app/inbound/src/http/mod.rs
PR #1179 changed the inbound HTTP fuzz logic, and added a mocked
`Target` type similar to other stack tests. However, this introduced a
bug, because the `Target::addr()` function, which returns the socket
address that the mock TCP connector should expect the proxy to try to
connect to, returns the (mocked) original destination address. Since the
stack we build for the fuzz test maps the target IP address to localhost
before calling into the connect stack (as the real proxy currently
does), this means that we attempt to connect to an address the mock
connector doesn't expect. Then, it panics and the fuzz test fails.
This branch fixes this issue by changing `Target::addr` to return
127.0.0.1:80 instead of 192.0.2.2:80. This should match what the proxy
will actually attempt to connect to.
I …
> fuzz: fix inbound fuzz logic expecting wrong IP address

- .github/workflows/coverage.yml
Our coverage action is quite slow and is generally low-value in the
context of a review. Instead of running it on every push to every PR,
let's conserve our CI resources and generate coverage weekly.
> ci: Check test coverage weekly

- linkerd/app/inbound/fuzz/fuzz_targets/fuzz_target_1.rs
- linkerd/dns/fuzz/fuzz_targets/fuzz_target_1.rs
- linkerd/proxy/http/fuzz/fuzz_targets/fuzz_target_1.rs
Something about the behavior of the fuzz logic for `linkerd_dns` is
hitting [a recently added assertion][1] in Tokio's multithreaded runtime
when shutting down. It's unclear what exactly triggers the assertion,
but it appears to be environment-dependent in some way: I can't
reproduce the failure on my machine using the reproducer generated by
`cargo-fuzz`, but it fails reliably in cluster-fuzz (possibly related to
the number of CPU cores on the cluster-fuzz servers?).
Since the purpose of this fuzz test is to fuzz the DNS name parsing
behavior, and this failure isn't actually related to the code being
fuzzed, just the environment the fuzz test runs in, this branch changes
the fuzz logic to use a single-threaded Tokio runtime. We'll continue
trying to get a minimal repro of the crash to …
> fuzzing: change `linkerd_dns::fuzz_target_1` to single-threaded

- linkerd/proxy/api-resolve/src/metadata.rs
Line [22](https://github.com/linkerd/linkerd2-proxy/blob/cde2816a85e2e31ce5e95ba15f41934a178b9a96/linkerd/proxy/api-resolve/src/metadata.rs#L29) of `linkerd/api-resolve/src/metadata.rs` has a grammar issue, where the word "know" is missing.
It's still comprehendable without this PR, but I wanted to contribute
anyways.
> Fix missing word in comment

- linkerd/app/core/src/addr_match.rs
- linkerd/app/gateway/src/tests.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/app/src/env.rs
If we provide a `FromIterator` implementation for `NameAddr`, we need
not have an extra import to construct `NameAddr`s when the type is
known.
> Use FromIterator for NameAddr construction

- linkerd/app/inbound/src/server.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/src/lib.rs
We currently eagerly build the inbound and outbound stacks. In an
upcoming change, however, we'll want to ensure that we've obtained
inbound port policies before initializing the inbound stack.
This change modifies app initialization to move stack initialization
into the proxy's start task. In order to do this, we eagerly bind the
inbound/outbound listeners and provide the stream of incoming sockets to
the stacks at construction-time.
This doesn't actually change any behavior since stack construction was
moved into a task that was run lazily. The change is purely internal,
restructuring how/when this task is built.
> app: Defer stack construction until the proxy starts

- Cargo.lock
- linkerd/app/src/identity.rs
- linkerd/app/src/lib.rs
- linkerd/proxy/identity/Cargo.toml
- linkerd/proxy/identity/src/certify.rs
Currently, the proxy may start serving connections even before identity
is provisioned. This won't be feasible once we introduce policy
discovery--the proxy will have to establish its inbound policy before
serving inbound connections.
This change modifies proxy initialization to block proxy initialization
on identity. When identity isn't established, warnings are logged every
15s.
While this is a behavior change from the proxy's point of view, this
shouldn't be a user-facing change, as container initialization is
blocked on the proxy's readiness, which is dependent on identity
initialization.
> app: Block proxy initialization on identity readiness

- Cargo.lock
- Cargo.toml
- linkerd/app/admin/src/stack.rs
- linkerd/app/core/Cargo.toml
- linkerd/app/core/src/metrics/mod.rs
- linkerd/app/core/src/transport/mod.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/tcp/connect.rs
- linkerd/proxy/transport/Cargo.toml
- linkerd/proxy/transport/src/connect.rs
- linkerd/proxy/transport/src/lib.rs
- linkerd/transport-metrics/Cargo.toml
- linkerd/transport-metrics/src/client.rs
- linkerd/transport-metrics/src/lib.rs
- linkerd/transport-metrics/src/report.rs
- linkerd/transport-metrics/src/sensor.rs
- linkerd/transport-metrics/src/server.rs
Our transport metrics code is fairly old and doesn't take advantage of
newer primitives, namely `ExtractParam`.
This change:
* Moves transport metrics code into a dedicated `transport-metrics crate` (it's got nothing in common with the rest of the proxy-transport code). Each logical chunk of functionality is moved into its own module.
* Renames the `Connect` type to `Client; and `Accept` to `Server` -- this is where we've gone with TLS code, etc.
* Updates both the Connect and Server layers to be parameterized on an `ExtractParams` that is responsible for producing a metrics instance for each target. This eliminates the awkward mapping from target type to label type and in general decouples these layers from the details of how metrics are acquired.
* The `app_core::transport::metrics` …
> Use `ExtractParam` in transport metrics

- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/policy/defaults.rs
- linkerd/app/inbound/src/policy/discover.rs
- linkerd/app/inbound/src/policy/mod.rs
- linkerd/app/inbound/src/policy/tests.rs
- linkerd/app/src/env.rs
- linkerd/server-policy/src/lib.rs
The policy controller supports the default policies
`cluster-authenticated` and `cluster-unauthenticated` but the proxy
would error if configured with these policies. In order to use a single
policy annotation honored by both the policy controller and proxy, this
change adds support for a new configuration,
`LINKERD2_POLICY_CLUSTER_NETWORKS`, that allows the proxy to enforce
cluster-scoped defaults. When this configuration is not specified, the
cluster-scoped defaults are not supported.
This default will apply to all ports that are not documented in the
pod's spec (i.e. ports not in the `LINKERD2_PROXY_INBOUND_PORTS`
configuration).
This change also updates policy labeling to track server and authz labels
independently so that keys may overlap, as is required by …
> policy: Add support for cluster-scoped default policies

- Cargo.lock
- linkerd/app/admin/src/stack.rs
- linkerd/app/core/Cargo.toml
- linkerd/app/core/src/metrics/tcp_accept_errors.rs
- linkerd/app/core/src/transport/labels.rs
- linkerd/app/core/src/transport/mod.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/policy/mod.rs
- linkerd/app/inbound/src/policy/tests.rs
- linkerd/app/inbound/src/server.rs
- linkerd/app/integration/src/tests/telemetry/mod.rs
- linkerd/app/integration/src/tests/transparency.rs
- linkerd/app/outbound/src/endpoint.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/server-policy/src/lib.rs
The inbound server only permits connections that are allowed by a
policy, but this decision is not observable at runtime.
This change modifies the server transport labels to include server and
authorization labels--prefixed by `srv_` and `saz_`, respectively
(matching the shortnames of the `Server` and `ServerAuthorization`
resources).
Furthermore, this change updates the `inbound_tcp_acept_errors_total`
metric to include an `unauthorized` error variant to expose a counter of
connections that were not permitted.
> Expose policy labels on inbound transport metrics

- linkerd/app/core/src/transport/labels.rs
The `target_addr` label encodes both the IP address and port in a single
string. This makes certain grouping operations cumbersome.
In order to support more flexible queries, this change adds `target_ip`
and `target_port` labels in addition to the existing `target_addr`
label. This should have a negligible impact on prometheus, since it
doesn't actually increase timeseries cardinality.
> metrics: Add `target_ip` and `target_port` labels

- linkerd/app/inbound/src/policy/store.rs
- linkerd/app/src/lib.rs
- linkerd/tonic-watch/src/lib.rs
This change ensures that policy watches include tracing spans.
> Set tracing spans on policy client

- linkerd/app/core/src/serve.rs
Currently, the `serve` function spawns tasks `instrument`ed with a
`tracing` span for each accepted connection. This span is at the `DEBUG`
level, so it's disabled with the default tracing configuration. This is
fine, as the per-connection context is relatively verbose and is mainly
useful for debugging.
However, we also rely on this span for propagating the `INFO`-level
spans which indicate which part of the proxy an event occurred in
(inbound, outbound, etc). When the `DEBUG` span is enabled, it will be a
child of these spans, so they are propagated to the spawned tasks.
However, when the `DEBUG` span is _not_ enabled, nothing propagates the
`INFO` spans. Since the default `tracing` configuration enables `INFO`
but not `DEBUG`, we want those spans to be propagated to the tasks
spawned …
> core: fix missing spans in `serve` tasks

- linkerd/proxy/http/src/client.rs
- linkerd/proxy/http/src/h1.rs
- linkerd/proxy/http/src/h2.rs
- linkerd/proxy/http/src/orig_proto.rs
Our error handlers need to account for the fact that HTTP/1 requests may
fail with HTTP/2 errors due to orig-proto upgrading.
To simplify error handling (in an upcoming change), the
`orig_proto::Upgrade` service introduces a new error type,
`orig_proto::DowngradedH2Error` that hides the original error source so
that these errors are not detected as being an `h2::Error`.
> orig-proto: Avoid emiting HTTP/2 errors for upgraded requests

- linkerd/app/outbound/src/http/logical.rs
The outbound proxy did not properly expose route labels to tap on
outbound requests. This change ensures that route labels are set on
outbound requests for display by tap.
> Fix route labels on outbound tap metadata

- linkerd/app/inbound/src/metrics/authz.rs
- linkerd/app/inbound/src/policy/authorize/http.rs
- linkerd/app/inbound/src/policy/config.rs
- linkerd/app/inbound/src/policy/mod.rs
- linkerd/app/inbound/src/policy/store.rs
- linkerd/app/inbound/src/server.rs
- linkerd/app/src/lib.rs
- linkerd/tonic-watch/src/lib.rs
Rather than block inbound communication on policy discovery, this change
modifies policy initialization to use the default policy until policy
has been synced from the control plane. This will allow us to use
policies with the admin server.
> inbound: Load policies lazily

- linkerd/duplex/src/lib.rs
Each forward TCP connection currently allocates 128KB--64KB for each
direction, client-to-server and server-to-client. This is an excessive
amount to allocate, especially since this buffer can currently hold only
a single `read(2)`'s worth of data.
This change reduces the buffer size to 8KB so that each connection
allocates only 16KB. This will substantially reduce memory overhead when
a server must serve many concurrent non-HTTP connections.
> duplex: Reduce copy buffer size from 64KB to 8KB

- linkerd/app/inbound/src/http/router.rs
- linkerd/proxy/http/src/orig_proto.rs
- linkerd/proxy/tap/src/grpc/server.rs
- linkerd/transport-metrics/src/sensor.rs
Rust nightly now catches some warnings that can cause fuzer builds to
fail. This change addresses these issues.
> Fix lints found on nightly

- linkerd/app/core/src/metrics/mod.rs
- linkerd/app/core/src/transport/labels.rs
- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/policy/defaults.rs
- linkerd/app/inbound/src/policy/discover.rs
- linkerd/app/inbound/src/policy/mod.rs
- linkerd/app/inbound/src/policy/tests.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/server-policy/src/lib.rs
Inbound stacks include labels for the inbound server and authorization
names. Every time a stack target is cloned, however, these strings are
re-allocated.
This change modifies these label types to hold an `Arc<str>` so that
cloning the stack target is cheap, reusing the initial allocation.
> inbound: Reduce needless allocation in stack targets

- linkerd/app/core/src/metrics/mod.rs
- linkerd/app/core/src/transport/labels.rs
- linkerd/app/inbound/src/metrics/authz.rs
- linkerd/app/inbound/src/policy/authorize/http.rs
- linkerd/app/inbound/src/policy/authorize/tcp.rs
Our inbound authorization metrics include a target port but include no
client information. This change adds TLS lables to the authorization
metrics so it's possible to identify which types of clients are
allowed/denied to access a service.
> inbound: Include TLS labels in authz metrics

- linkerd/app/core/src/serve.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/integration/src/controller.rs
- linkerd/app/integration/src/server.rs
- linkerd/app/integration/src/tcp.rs
- linkerd/app/src/identity.rs
- linkerd/app/src/lib.rs
- linkerd/app/src/oc_collector.rs
- linkerd/proxy/http/src/h2.rs
`tracing` v0.1.27 added a new [`Span::or_current`] method to aid with
efficiently propagating spans to spawned tasks (or threads). The method
is intended to be used when a spawned task should be instrumented with a
provided span if it is enabled, or the current span if the provided span
is _not_ enabled. `span.or_current()` returns `span` if it is enabled,
or, if `span` is disabled, it clones the current span and returns it.
This offers better performance than writing code like this:
```rust
.instrument(span)
.in_current_span()
```
First, `or_current` will only look up the current span (requiring a
thread-local access) _if_ `span` is not enabled, while
`.instrument(span).in_current_span()` will do this unconditionally.
Second, and more importantly, using `.in_current_span()` will wrap the …
> tracing: use `Span::or_current` when spawning tasks

- linkerd/dns/src/lib.rs
When debugging DNS issues, it's useful to know the TTL for a resolution.
> dns: Log TTL with resolution

- Cargo.lock
- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/errors/mod.rs
- linkerd/app/core/src/errors/respond.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/error-respond/Cargo.toml
- linkerd/error-respond/src/lib.rs
The error responder is currently a `Service` and not a `NewService`
meaning there's no means to configure the responder using the stack
target.
This change introduces a `NewRespondService` type that implements
`NewService` to instrument the error responder. This will be used in
follow-up changes to configure the error responder to only emit headers
in certain conditions.
> error-respond: Support stack target configuration

- linkerd/app/core/src/errors/respond.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/mod.rs
- linkerd/app/outbound/src/http/proxy_connection_close.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/proxy/http/src/strip_header.rs
In 6cf1b2851, we updated the outbound proxy to automatically teardown
connections when the peer proxy sets the `l5d-proxy-error` response
header; but this header may be set in some situations when disconnecting
isn't appropriate and will only generate more load on the system.
This change introduces a `l5d-proxy-connection` header (like the
`connection` and `proxy-connection` headers) that the proxy can use to
signal that the proxied connection should be closed, independently of
the informational `l5d-proxy-error` message.
Some TODOs have been marked for followup improvements.
> Support a `l5d-proxy-connection: close` header

- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/config.rs
- linkerd/app/core/src/errors/respond.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/inbound/src/http/set_identity_header.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/stack/src/arc_new_service.rs
- linkerd/stack/src/lib.rs
The inbound proxy sets the `l5d-proxy-error` and `l5d-proxy-connection`
headers when an error is encountered. This leaks information about the
proxy to potentially untrusted clients.
This change modifies the error handling behavior to only emit these
headers from the inbound proxy when the client uses mesh identity.
In doing so, we modify the `inbound::NewSetIdentiyHeader` layer to use
`ExtractParam<tls::ConditionalServerTls, _>` to parameterize the server
connection's identity to be consistent with the rescue parameters. This
precipitated modifying the default impls for `ExtractParam` so that we
can provide an impl for `()` that simply uses the target type. A new
`CloneParam` type is introduced to replicate the former behavior.
> Avoid emitting informational headers to untrusted clients

- linkerd/app/core/src/svc.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/proxy_connection_close.rs
- linkerd/proxy/http/src/insert.rs
The proxy uses the `l5d-proxy-connection` header to determine when
it should close proxied connections. This header must only be set by a
peer inbound proxy.
This change modifies the outbound proxy so that this connection is only
honored when the peer is actually meshed. If this header is set by an
unmeshed peer, the header is ignored.
This change also modifies the outbound proxy to always _clear_ this
header so that it can't be sent to the application.
> outbound: Only honor the `l5d-proxy-connection` header when meshed

- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/test_util.rs
- linkerd/app/src/env.rs
The proxy may set error messages in the outbound proxy's response
headers; but sometimes this isn't desirable, especially on ingresses
where the repsonses may be sent to external clients.
This change introduces a new configuration,
`LINKERD2_PROXY_OUTBOUND_DISABLE_INFORMATIONAL_HEADERS` that can be set
to `false` to disable these headers from being included in responses
from the outbound proxy. These headers are also disabled by default when
ingress mode is enabled.
> outbound: Disable informational headers by config

- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/mod.rs
- linkerd/app/outbound/src/http/strip_proxy_error.rs
- linkerd/proxy/http/src/lib.rs
- linkerd/proxy/http/src/strip_header.rs
If the outbound proxy is not configured to emit headers, then we
shouldn't surface `l5d-proxy-error` headers sent by peer proxies.
This change adds a module to the outbound HTTP endpoint stack to strip
these headers when appropriate.
> outbound: Strip peer-sent `l5d-proxy-error` headers

- Cargo.lock
- linkerd/app/inbound/src/http/server.rs
- linkerd/stack/tracing/Cargo.toml
- linkerd/stack/tracing/src/lib.rs
This change modifies `stack-tracing`'s `Instrument` service type to log
a message as instances are dropped, which can be useful for diagnosing
stack retention issues.
This change also modifies this type to stop using `pin-project` (since
it wasn't actually using it).
> stack-tracing: Log when services are dropped

- linkerd/proxy/discover/src/from_resolve.rs
- linkerd/proxy/dns-resolve/src/lib.rs
- linkerd/proxy/resolve/src/map_endpoint.rs
- linkerd/proxy/resolve/src/recover.rs
It's helpful to have more insight into what's going on during endpoint
resolution. This change adds trace-level logging messages to various
resolver modules.
> Add trace-level logging around discovery updates

- linkerd/app/core/src/control.rs
- linkerd/app/src/dst.rs
It can be difficult to identify when log messages are emitted from
controller clients. This change adds tracing spans to identify the
client and its endpoints.
> Add tracing spans to controller clients

- linkerd/app/core/src/control.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/logical.rs
Load balanced clients can get stuck continually trying to reconnect to
defunct endpoints in situations like the following:
1. A balancer has an existing endpoint but it is pending;
2. A new ready endpoint is added to the balancer;
3. Requests are sent to the new endpoint and the balancer ends up with
the new endpoint being ready.
4. Service discovery issues an update indicating that we should no
longer use the old endpoint, which has now shutdown.
This discovery update won't be processed by the balancer until we
attempt to issue a request on the balancer. But, because each endpoint
uses `SpawnReady` to attempt reconnection on a background task, we
continually attempt to reconnect to the defunct endpoint even though
we'll never actually issue requests to it (because it will be removed as …
> Avoid attempting to reconnect to defunct endpoints

- linkerd/app/admin/src/server/mod.rs
Rust nightly catches a few unused types that are apparently not caught
on the most recent stable releases.
> admin: Remove unused types

- linkerd/app/gateway/src/lib.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/server.rs
In Linkerd stable-2.10.0, the proxy started using a specialized protocol
header for multicluster gateway connections (`transport.l5d.io`). Now
that stable-2.11.0 has been released, we can drop support for gateway
connections that do not use this protocol.
> Require ALPN on gateway connections

- linkerd/proxy/discover/src/from_resolve.rs
It seems that we no longer log specific discovery changes at DEBUG
anywhere. We probably ought to revisit the discovery pipeline more
holistically and ensure that we're logging in strategic places, but for
now this will help users diagnose discovery updates without subscribing
to the much noisier TRACE stream.
Relates to linkerd/linkerd2#6842
> Log discovery changes at DEBUG

- linkerd/http-retry/src/lib.rs
`ReplayBody::poll_data` includes some deeply nested logic that can be
avoided with early returns. This restructures `ReplayBody::poll_data` so
that the control flow is easier to follow.
> retry: Simplify ReplayBody::poll_data for readability

- linkerd/meshtls/rustls/src/creds.rs
2dd7bb8ff changed how rustls configurations are constructed; but it
didn't properly configure the default client configuration with the
proxy's trust root. This enables the identity client to establish TLS
connections with the identity controller during startup.
> rustls: Configure the initial TLS client with trust roots

- .github/workflows/check-release.yml
- .github/workflows/check.yml
- .github/workflows/deps.yml
- .github/workflows/fuzzers.yml
- .github/workflows/test.yml
It turns out that the github UI doesn't always scope a job's name to a
workflow (especially in the required checks UI). This change adds
prefixes to each job name so that jobs end up grouped by workflow in any
lexical ordering.
> ci: Make job names uniform

- Cargo.lock
- linkerd/app/integration/Cargo.toml
- linkerd/meshtls/Cargo.toml
- linkerd/meshtls/src/client.rs
- linkerd/meshtls/src/creds.rs
- linkerd/meshtls/src/lib.rs
- linkerd/meshtls/src/server.rs
- linkerd2-proxy/Cargo.toml
- linkerd2-proxy/src/main.rs
Currently, the `linkerd-meshtls` crate cannot be compiled when no TLS
implementation feature flags are enabled. This is an issue, since it
means the `rustls` implementation must be enabled by default, requiring
all crates that depend on `meshtls`, or on a crate that depends on it,
to expose feature flags for controlling what TLS implementation(s) are
enabled. This is not ideal.
This branch changes the `meshtls` so that it can compile even when no
TLS implementations are enabled. The crates which actually need TLS
implementations to be enabled (the `linkerd2-proxy` application crate,
and `linkerd-app-integration`) now depend on the `linkerd-meshtls` crate
for the purposes of enabling feature flags. Other crates that depend on
`meshtls` can do so without having to propagate its feature …
> meshtls: allow building without any TLS impls enabled

- linkerd/meshtls/rustls/src/lib.rs
- linkerd/meshtls/rustls/src/tests.rs
- linkerd/server-policy/src/lib.rs
- linkerd/tls/test-util/src/lib.rs
In a prior change, the rustls credential-loading tests were accidentally
disabled. This change restores these tests and updates them to use the
newer API.
> Restore rustls credential tests

- Cargo.lock
- linkerd/meshtls/Cargo.toml
- linkerd/meshtls/rustls/Cargo.toml
- linkerd/meshtls/tests/rustls.rs
- linkerd/meshtls/tests/util.rs
We'll want to run the same end-to-end tests against all meshtls
backends. This change moves the rustls `tls_accept` tests into meshtls
crate.
> meshtls: Move TLS e2e tests into the meshtls crate

- linkerd/meshtls/rustls/src/client.rs
- linkerd/meshtls/rustls/src/server.rs
We use needlessly verbose references to std::task types in the
`linkerd-meshtls-rustls` crate. This change simplifies these imports.
> rustls: Tidy std::task imports

- linkerd/app/integration/src/lib.rs
- linkerd/app/integration/src/tests/transparency.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/tcp/connect.rs
- linkerd/duplex/src/lib.rs
- linkerd/http-retry/src/lib.rs
- linkerd/proxy/api-resolve/src/lib.rs
- linkerd/proxy/transport/src/lib.rs
- linkerd/proxy/transport/src/orig_dst.rs
- linkerd/system/src/lib.rs
- linkerd/system/src/linux.rs
- linkerd2-proxy/src/main.rs
- opencensus-proto/src/lib.rs
We've accrued various compiler directives and clippy exceptions that are
no longer necesary. This change removes these unnecessary settings.
This change also addresses a lint in our integration tests.
> Eliminate needless compiler directives

- Cargo.lock
- linkerd/app/core/src/serve.rs
- linkerd/app/inbound/src/server.rs
- linkerd/app/integration/src/proxy.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/proxy/transport/Cargo.toml
- linkerd/proxy/transport/src/listen.rs
- linkerd/proxy/transport/src/orig_dst.rs
The TCP server can fail connections in a few situations:
* `accept(2)` can fail
* setting thte TCP keepalive can fail
* getting the client peer address can fail
It's not easy to differentiate these errors when inspecting proxy logs.
This change adds wrapper error types with custom error messages that
disambiguate the error cause.
Additionally, this change includes the client address when logging
information/warnings about connection errors in general. This is
redundant when logging is set at debug, but will be helpful when logging
is set at the normal level.
> transport: Improve TCP server error messages

- .github/workflows/coverage.yml
The coverage workflow has been failing since boring was added as a
dependency.
This change updates the coverage workflow to include the proper build
dependencies and splits the build and test running phases into distinct
steps.
The tests are now run daily instead of weekly so we can more readily
detect and recover from regressions.
> ci: Fix coverage workflow

- Cargo.lock
Updating anyhow v1.0.44 -> v1.0.45
Updating cc v1.0.71 -> v1.0.72
Updating proc-macro2 v1.0.30 -> v1.0.32
Updating rustls v0.20.0 -> v0.20.1
Updating syn v1.0.80 -> v1.0.81
Updating tinyvec v1.5.0 -> v1.5.1
Updating tokio-macros v1.5.0 -> v1.5.1
Updating tonic v0.6.0 -> v0.6.1
> build(deps): bump various dependencies

- .github/dependabot.yml
In order to prevent dependabot updates from consuming CI resources
during working hours, this change schedules dependabot updates to run at
10:00 UTC.
> ci: Run dependabot updates at 2AM PST

- .github/workflows/coverage.yml
The coverage workflow is misconfigured so that it fails to run:
`cargo-tarpaulin` has command line arguments that don't match other
cargo commands (`--packages` instead of `--package`, which cannot be
mixed with `--workspace`). Furthermore, it doesn't seem that we actually
benefit from running tarpaulin over our non-integration tests, since the
coverage reports are not merged.
> ci: Skip unit tests in coverage report

- linkerd/app/integration/src/tests/telemetry.rs
A few fixes to compile the integration tests on macOS. Unfortunately, [4 of the tests are failing](https://gist.github.com/tychedelia/301e82856d85c0f59d649e46c5d0c1ca) (2 intermittently so). I tried to dig in a bit, but wasn't able to figure out what was up. Happy to continue investigating with further direction.
This also includes an ugly Makefile hack to exclude the `linekerd-system` on macOS during tests. The conditional dependency inside `linkerd-app-core` works when running `cargo build`, but I guess `cargo test` wants to consume all workspace members (in order to run tests inside the crate, presumably).
(Also, for any future readers I had to increase the file descriptor limit in order to get these to run -- the default on macOS is randomly super low).
Signed-off-by: Jem McElwain …
> Fixes for compiling on macOS

- linkerd/app/inbound/src/direct.rs
Since the legacy gateway mode has been removed from the proxy, we no
longer need to support multiple I/O types for the gateway. This change
drops the unused I/O variant from the GatewayIo type.
> inbound: Simplify GatewayIo type

- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/server.rs
Closes https://github.com/linkerd/linkerd2/issues/6178
When an endpoint is marked as opaque, but its logical service does not have an opaque annotation, the `TransportHeader` will not an include an alternate name, but it will the connection protocol:
```
[    72.279002s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.24:55848}:server{port=4143}:direct: linkerd_transport_header::server: Read transport header header=TransportHeader { port: 80, name: None, protocol: Some(Http2) }
[    72.279029s]  INFO ThreadId(01) inbound:accept{client.addr=10.42.0.24:55848}: linkerd_app_core::serve: Connection closed error=a named target must be provided on gateway connections client.addr=10.42.0.24:55848
```
The connection will be closed with an error. Through this change, we can handle HTTP …
> Handle HTTP traffic over opaque transport connections

- linkerd/app/integration/src/proxy.rs
- linkerd/app/integration/src/tests/discovery.rs
- linkerd/app/integration/src/tests/identity.rs
- linkerd/app/integration/src/tests/profile_dst_overrides.rs
- linkerd/app/integration/src/tests/profiles.rs
- linkerd/app/integration/src/tests/tap.rs
- linkerd/app/integration/src/tests/telemetry.rs
- linkerd/app/integration/src/tests/telemetry/tcp_errors.rs
- linkerd/app/integration/src/tests/transparency.rs
While working on #1428, I was a bit confused reading through tests and noticed that it looked like at some point the admin server was just a metrics server, or referred to as such. This refactor just renames the address in integration tests to be consistent with the name used in the proxy.
Signed-off-by: Aaron Friel <mayreply@aaronfriel.com>
> refactor: rename 'metrics' addr to 'admin' in tests

- .github/dependabot.yml
- Cargo.lock
Dependabot seems to only create updates for direct dependencies. This
change ensures we receive updates for all dependencies.
> dependabot: Allow updates for transitive dependencies

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/devcontainer.yml
> devcontainer: Fix kubectl path

- deny.toml
When we skip-tree hyper, we miss out on all dupes that may impact tokio,
etc.
Thsi change narrowly exempts the use of iota v4.
> deny: Don't skip everything in hyper's tree

- .clippy.toml
- linkerd/app/integration/src/lib.rs
- linkerd/app/integration/src/metrics.rs
- linkerd/detect/src/lib.rs
- linkerd/http-access-log/src/lib.rs
- linkerd/http-metrics/src/requests/service.rs
- linkerd/proxy/tap/src/grpc/server.rs
- linkerd/stack/metrics/src/service.rs
- linkerd/tracing/src/uptime.rs
When comparing instances, we should use saturating varieties to help
ensure that we can't hit panics.
This change bans uses of `std::time::Instant::{duration_since, elapsed,
sub}` via clippy. Uses are ported to using
`Instant::saturating_duration_since`.
Related to linkerd/linkerd2#7748
> Ban uses of `Instant` operations that can panic

- .github/dependabot.yml
`futures`, `prost, and `tracing` release top level crates, so there's no
need to be notified of leaf crate updates.
> dependabot: Ignore leaf updates

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/devcontainer.yml
* Set a default locale (en_US.UTF-8)
* Use multi-stage docker builds and install tools into /usr/local/bin
* Drop needless extensions
* Use a `RUST_VERSION` build-arg instead of inline version strings
> Update the devcontainer

- Dockerfile
Recently a new `--timeout` flag was introduced to [linkerd-await](https://github.com/linkerd/linkerd-await/).
When building a custom image of the proxy and using that in an installation, the `--timeout` flag now used by the postStart hook is invalid because `--timeout` is an unrecognized flag. It's unrecognized because Docker is building the proxy image off a proxy that used a linkerd-await version that did _not_ have this flag.
Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>
> Bump runtime image so that linkerd-await 0.2.5 is used

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/actions/package/Dockerfile
- .github/workflows/devcontainer.yml
- .github/workflows/toolchain.yml
- Dockerfile
- update-rust-version.sh
The toolchain workflow validates that the same rust toolchain version is
used in all docker images, matching the value in the `rust-toolchain`
file.
This change also updates the devcontainer to include the `yq` utility.
> ci: Add a toolchain workflow

- .github/workflows/beta.yml
- .github/workflows/nightly.yml
We currently only really catch Rust regressions as they hit stable. This
change adds workflows to build the proxy daily against `nightly` and
weekly against `beta`.
These workflows are separated so that they can run on different
schedules and so that a failure on one toolchain does not interfere with
the other.
> ci: Add workflows to run beta, nightly builds

- .github/workflows/build.yml
- .github/workflows/check-each.yml
- .github/workflows/coverage.yml
- .github/workflows/deps.yml
- .github/workflows/integration.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
This change splits out our GitHub workflows to run conditionally,
depending on which files change in a pull request.
* `build`: builds the proxy in release mode wh
* `check-each`: checks that each Cargo.toml checks cleanly on its own.
This used to be a serial task, but has been converted to a matrix job.
* `deps`: Only runs on dependency changes to check cargo-deny
* `integration`: Runs integration tests on code & dependency changes.
* `lint`: Runs clippy, fmt, and doc on all source changes. Not run on
dependency changes.
* `test`: Runs unit tests on code and dependency changes
This prevents doing needless work on dependency changes (as these are
extremely common) and makes it easier to rerun narrower workflows, if
necessary. The best part of this, though, is that we've made
`check-each` …
> ci: Split out workflows

- Cargo.lock
- deny.toml
- linkerd/io/Cargo.toml
- linkerd/proxy/discover/Cargo.toml
- linkerd/proxy/discover/src/buffer.rs
This branch updates `tokio-util` to v0.7.0.
The dependabot-generated PR for this update doesn't work, because this
is a breaking API change. The only update that was necessary here was
changing the use of `tokio_util::sync::PollSender` in
`linkerd-proxy-discover` to use the updated method names.
Closes #240
`tokio-util` v0.6.9 is still in the dependency tree because `tower`
depends on it.
> build(deps): update tokio-util to v0.7

- .github/workflows/check-each.yml
The point of this job is to check that each crate can be built
independently (i.e., that it doesn't depend on features pulled in by
another crate).
This change also updates the workflow to check linkerd-meshtls-boring by
installing its build deps.
> ci: Only run checks on Cargo.toml changes

- linkerd/app/src/env.rs
As part of #7816, we want to be able to set the `LINKERD2_PROXY_INBOUND_PORTS` env var to `""` when an app does not specify its ports. This means that in the proxy environment, `LINKERD2_PROXY_INBOUND_PORTS = ""`.
In order to handle this case, we now need to handle `LINKERD2_PROXY_INBOUND_PORTS` being present or not; if it is present then we need to handle it being `""` or some other value.
With this change, we now parse `LINKERD2_PROXY_INBOUND_PORTS` and if it is empty, handle it the same way that we handle it being absent.
I've tested in this change in an install and the logs now report:
```
time="2022-02-09T22:59:34Z" level=info msg="running version edge-21.4.5"
[     0.000268s]  WARN ThreadId(01) linkerd_app::env: No inbound ports specified via LINKERD2_PROXY_INBOUND_PORTS
[ …
```
> Do not error when `LINKERD2_PROXY_INBOUND_PORTS` is empty

- .github/workflows/docker.yml
- Dockerfile
PR #1479 changed the docker base image to not include a shell, which
broke the dockerfile's logic for skipping the identity wrapper. It's no
longer possible to run the proxy without identity, so this functionality
isn't needed in any case.
This change fixes the Dockerfile and adds a CI workflow to test docker
builds on Dockerfile changes.
> Fix dockerfile

- Cargo.lock
- Cargo.toml
- Dockerfile
- deny.toml
tokio & tower have been patched to avoid issues described in
linkerd/linkerd2#7748, but they have not yet been released. This change
pins these dependencies to Git to pickup the workarounds.
> Pin git deps for dependencies that have `Instant` workarounds

- .github/workflows/check-each.yml
Currently we check all crates on all source and manifest changes. This
change updates the `check-each` workflow to use the
`tj-actions/changed-files` action to limit checks to modified crates.
All checks are run when the action itself chnages.
> ci: Only run checks on changed crates

- .github/workflows/fuzzers.yml
We previously always built fuzzers. This change updates the fuzzers
workflow as follows:
* the workflow is only invoked when a fuzz crate changes (or when the
workflow itself changes).
* fuzzer builds are only executed for changed crate directories
> ci: Run fuzzing only on related changes

- linkerd/app/inbound/src/test_util.rs
- linkerd/app/outbound/src/test_util.rs
- linkerd/app/src/env.rs
- linkerd/exp-backoff/src/lib.rs
Now that we can use const functions, we can update `ExponentialBackoff`
to expose a constructor instead of having public members.
> Add ExponentialBackoff::new_unchecked

- Cargo.lock
- Cargo.toml
- deny.toml
`h2` has a few important changes since its last official release:
* hyperium/h2@4dc2b4a Avoids time operations that can panic
* hyperium/h2@85549fc Fixes an issue with header parsing
* hyperium/h2@b8eab38 Removes noise from tracing spans
This change patches our `h2` dependency to use the laster commit on the
master branch.
> Update h2 to use unpublished changes

- linkerd/app/core/src/control.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/endpoint.rs
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/proxy/http/src/client.rs
- linkerd/proxy/http/src/glue.rs
- linkerd/proxy/http/src/h1.rs
- linkerd/proxy/http/src/h2.rs
- linkerd/proxy/http/src/orig_proto.rs
- linkerd/stack/src/map_target.rs
Currently, when the outbound proxy communicates with a meshed endpoint
that uses opaque transport (i.e. multi-cluster gateways), it *always*
sets the gateway header's session protocol to HTTP/2, since the meshed
endpoint supports HTTP/2 protocol upgrading. But the HTTP client may
choose not to use HTTP/2 if the request includes the `Upgrade` header,
as it does for WebSocket connections. In these cases, the transport
header should indicate that the connection is HTTP/1.
This change modifies the HTTP client to pass the used protocol version
when building a connection. This value is then used to set the session
protocol header when it is required..
> Use the connection's HTTP version in transport header

- Cargo.lock
- Cargo.toml
- deny.toml
Version v0.3.12 of `h2` has been published, so we no longer need the
patch added in #1536 to pick up unreleased changes.
> bump `h2` to v0.3.12 and remove patch

- linkerd/app/core/src/metrics.rs
- linkerd/app/core/src/transport/labels.rs
- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/http.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/authorize/http.rs
- linkerd/app/inbound/src/policy/authorize/tcp.rs
- linkerd/app/inbound/src/policy/defaults.rs
- linkerd/app/inbound/src/policy/discover.rs
- linkerd/app/inbound/src/policy/tests.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/app/integration/src/tests/telemetry.rs
- linkerd/app/integration/src/tests/transparency.rs
- linkerd/server-policy/src/lib.rs
The inbound policy module uses the label `saz_name` to indicate the
authorization resource being employed to allow/deny traffic. This
corresponds to the `ServerAuthorization` kubernetes resource (with the
`saz` shortname). This resource type is going to be deprecated in favor
of a new, more general, `AuthorizationPolicy` resource.
When this change is made in the control plane, the policy controller
will include a `kind` label on gRPC messages indicating whether the
resource type, or `default` if a default policy is in effect.
This change honors this new `kind` field and adds a dedicated label to
indicate the kind.
Server labels are changed from:
srv_name="default:foo"
srv_name="fah"
to:
srv_kind="default",srv_name="foo"
srv_kind="server",srv_name="fah"
Authorization labels are changed …
> inbound: Support multiple authorization types

- Cargo.lock
- linkerd/tracing/Cargo.toml
- linkerd/tracing/src/level.rs
- linkerd/tracing/src/lib.rs
[`tracing-subscriber` v0.3.10][1] introduces a new [builder API][2] for
configuring the `EnvFilter` type. One of the configurations that can now
be set using the builder is whether span field value filters for
`fmt::Debug` fields are interpreted as precise string matching or as
regular expressions.
Disabling regular expressions is strongly recommended in cases where
filter configurations can come from an untrusted source, as a malicious
regular expression is a potential denial-of-service vector. In the
proxy, we already implement a form of access control for setting the
filter --- the `/admin/log-level` endpoint denies requests that did not
originate from localhost, so it's only possible to set the log level
when SSHed into the pod. However, it's probably wise to disable regex
filters …
> tracing: disable regular expression matching in log filters

- .devcontainer/Dockerfile
- linkerd/app/inbound/src/http.rs
Nightly builds were broken when 279b301 landed, so we missed
the regression. This change fixes the inbound fuzzer build. It also
updates the devcontainer build to include a nightly toolchain with
cargo-fuzz.
> Fix inbound fuzzing build

- .github/workflows/release.yml
Currently we only exercise the release workflow on tagged releases, but
this makes it difficult to validate changes to the workflow itself.
This change updates the release workflow to run its build on pull
requests that change the workflow. The release-publishing step is only
run on tags, though.
> ci: Run the release workflow on changes

- .github/workflows/release.yml
> ci: Only run the release workflow on PRs that touch the workflow

- .github/actions/list-changed-crates/Dockerfile
- .github/actions/list-changed-crates/action.yml
- .github/actions/list-changed-crates/entrypoint.sh
- .github/workflows/check-each.yml
Our check-each workflow is subtly broken: we specify a YAML list of
paths to watch for changes, but the `changed-files` action expects a
newline-separated list. This change fixes this configuration.
This change also moves the complicated `list-changed-crates` script into
its own (local) action so that the script is easier to read/test/maintain.
> Split out list-changed-crates into an action

- .devcontainer/devcontainer.json
Devconatiner memory usage is currently unbounded. This allows runaway
processes (like rust-analyzer) to monopolize system resources, causing
memory exhaustion for the host OS.
This change adds a limit so that the oomkiller reaps devcontainer
processes when they exceed 8GB.
> dev: Limit devcontainer memory usage to 8GB

- Cargo.lock
- linkerd/app/admin/src/server.rs
- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/control.rs
- linkerd/app/core/src/errors/respond.rs
- linkerd/app/core/src/serve.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/integration/src/controller.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/app/src/dst.rs
- linkerd/proxy/discover/src/buffer.rs
- linkerd/proxy/identity-client/src/certify.rs
- linkerd/reconnect/src/lib.rs
- linkerd/service-profiles/src/default.rs
`tracing-core` v0.1.26 improved support for recording
`std::error::Error` trait objects as structured values rather than as
`fmt::Display` or `fmt::Debug`. This allows the `tracing` subscriber to
log these errors somewhat nicer, such as including the error's `cause`
as a separate field (if it has one).
This branch updates the `tracing-core` dependency to v0.1.26, and
changes `tracing` events that previously recorded `dyn Error`s using
`fmt::Display` to record them using the `Value` impl for `dyn Error`
instead. I didn't touch any errors that had not already been converted
to a `Box<dyn Error + ...>`.
> tracing: record errors as `&dyn Error`s when possible

- linkerd/app/outbound/src/http/detect.rs
- linkerd/app/outbound/src/switch_logical.rs
The outbound proxy's logging doesn't make it clear how targets decide
whether protocol detection is employed. This change adds debug logging
to make it easier to understand these decisions.
> outbound: Add logging for endpoint opaqueness

- linkerd/app/outbound/src/endpoint.rs
- linkerd/app/outbound/src/switch_logical.rs
- linkerd/service-profiles/src/client.rs
The outbound stack only honors opaqueness when the profile response
clearly indicates that the target is a known endpoint or logical
service. This ignores the case when the target is unknown but the target
port is in the default opaque ports list, in which case the profile
response has no metadata except for the opaqueness setting.
This change handles this case explicitly and adds a test for the
`switch_logical` stack to ensure that these profile responses are
honored.
Fixes linkerd/linkerd2#8273
> outbound: Preserve opaqueness on unknown endpoints

- linkerd/app/src/env.rs
- linkerd/exp-backoff/src/lib.rs
- linkerd/metrics/src/histogram.rs
- linkerd/metrics/src/latency.rs
- linkerd/proxy/api-resolve/src/pb.rs
- linkerd/proxy/tap/src/grpc/match_.rs
- linkerd/service-profiles/src/proto.rs
- linkerd/transport-header/src/lib.rs
Signed-off-by: Haining <haining.cao@daocloud.io>
`std::usize::MAX` is a deprecated way.
https://doc.rust-lang.org/core/usize/constant.MAX.html
> Update deprecated codes

- linkerd/app/core/src/svc.rs
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/switch_logical.rs
- linkerd/app/outbound/src/tcp.rs
Currently, ingress-mode proxies ONLY support HTTP traffic. This is an
unfortunate tradeoff, as ingress may make arbitrary outbound connections
(e.g., TLS calls to external services). To avoid requiring that these
connections be completely skipped from the proxy, we can fallback to
transporting these connections after HTTP detection fails.
Ingress-mode proxies DO NOT fully honor port opacity configurations:
HTTP detection is always performed before discovery is attempted.
Fixes linkerd/linkerd2#7238
> ingress: Fall back to normal TCP forwarding

- linkerd/app/core/src/metrics.rs
- linkerd/app/core/src/telemetry.rs
- linkerd/app/core/src/telemetry/process.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/app/integration/src/proxy.rs
- linkerd/app/outbound/src/test_util.rs
- linkerd/app/src/lib.rs
- linkerd/tracing/src/lib.rs
- linkerd/tracing/src/uptime.rs
- linkerd2-proxy/src/main.rs
The proxy exposes a `process_cpu_seconds_total` metric. It also exposes
a `process_start_time_seconds` metric. But given a random metrics
snapshot, we have no way of knowing the proxy's uptime unless we know
the current time at the time of the snapshot. linkerd/linkerd2#8443
proposed adding a `process_uptime_seconds_total` metric tracking the
(fractional) number of seconds since the process started, to make these
other process metrics easier to interpret.
This branch implements the `process_uptime_seconds_total` metric.
Actually adding the metric is rather simple.
However, it occurred to me that uptimes are also used as timestamps in
the proxy's `tracing` logs. Currently, the start time used to calculate
log timestamps is just recorded when constructing the logger. If
separate `Instant`s …
> metrics: add `process_uptime_seconds_total` metric

- linkerd/app/core/src/control.rs
- linkerd/app/core/src/errors.rs
- linkerd/dns/src/lib.rs
- linkerd/proxy/dns-resolve/src/lib.rs
The `dns` module uses boxed errors, which makes it difficult to reason
about the types of errors we may encounter.
This change adds error newtypes so that we can at least print more
detailed information about the type of resolution that failed.
> dns: Use typed errors

- Cargo.lock
- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/control.rs
- linkerd/app/core/src/errors.rs
- linkerd/app/core/src/lib.rs
- linkerd/app/core/src/serve.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/error/Cargo.toml
- linkerd/error/src/lib.rs
- linkerd/stack/src/fail_on_error.rs
We have similar/redundant code that handles inspecting (boxed) errors to
determine whether they are caused by a given error type. This change
replaces the other methods for expecting with utility functions
`is_caused_by` and `cause_ref`.
These helpers are now tested.
> Consolidate error chain inspection with `cause_ref`

- .github/workflows/beta.yml
- .github/workflows/build.yml
- .github/workflows/check-all.yml
- .github/workflows/check-each.yml
- .github/workflows/deps.yml
- .github/workflows/lint.yml
- .github/workflows/nightly.yml
This change replaces the manually installed the `cargo-action-fmt`
utility with a setup action. This reduces boilerplate and ensures that
we'll get updates via dependabot.
> ci: Use the cargo-action-fmt setup action

- Cargo.lock
socket2 v0.4.5 has been yanked (rust-lang/socket2#308).
This reverts commit 9004d9c6e1eaeb15d72a2dc36c9c7cc452047dc8.
> Revert "build(deps): bump socket2 from 0.4.4 to 0.4.5 (#1654)"

- linkerd/cache/src/lib.rs
- linkerd/cache/src/new_service.rs
In some cases--like inbound policy discovery--we have a set of permanent
values that should never be removed from the cache. This change updates
the cache to only hold a handle when eviction is scheduled. No handle is
held when the cache entry is permanent.
This change also fixes a possible race condition. Previously, the
eviction task could consume an entry's handle without locking the cache.
This made it possible for a `get_or_insert_with` call to race against
the eviction task, adding an entry that would be immediately evicted by
the eviction task.
> Store permanent values in the cache (for #1683)

- Cargo.lock
- linkerd/app/core/src/svc.rs
- linkerd/cache/src/lib.rs
- linkerd/cache/src/new_service.rs
Currently, the `linkerd-cache` crate contains an implementation of a
cache where entries are evicted if they have not been accessed for a
timeout duration. This type currently implements the `NewService` trait
and requires that cached values are `Service`s. It does not provide a
more general purpose key-value cache interface.
PR #1677 introduces dynamic discovery for inbound port policies. We
would like to implement a similar eviction strategy for these policy
watches. However, the policy watches are *not* used in a `NewService`
implementation, but in a `CheckPolicy` implementation.
Therefore, this branch rewrites the `Cache` type to serve as a
general-purpose key-value cache, and adds a new `NewCachedService` type
that implements `NewService` on top of `Cache`.
> cache: generalize `Cache` into a key-value cache

- linkerd/tracing/src/lib.rs
While reviewing #1642, I found myself wanting clearer documentation
about what is being initilalized. This change attempts to reorganize the
builder for clarity.
> tracing: Simplify trace initialization (for #1642)

- Cargo.lock
- linkerd/app/admin/src/stack.rs
- linkerd/app/inbound/Cargo.toml
- linkerd/app/inbound/fuzz/Cargo.toml
- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/metrics/error.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/api.rs
- linkerd/app/inbound/src/policy/config.rs
- linkerd/app/inbound/src/policy/store.rs
- linkerd/app/inbound/src/policy/tests.rs
- linkerd/app/inbound/src/server.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/app/src/env.rs
- linkerd/cache/Cargo.toml
- linkerd/cache/src/lib.rs
- linkerd/stack/src/filter.rs
During process startup, proxies discover policies for all documented
inbound ports. Undocumented ports use the default policy and cannot be
configured by the policy controller.
This is an annoying limitation, as Kubernetes does not otherwise require
a pod's ports to be explicitly documented.
This change lifts this limitation. We continue to eagerly
discover policies for documented ports during startup, but we now fall
back to dynamically discovering policies for undocumented ports. This
discovery does not block processing a connection. The default policy is
honored until a policy is provided by the control plane.
Fixes https://github.com/linkerd/linkerd2/issues/7640
> Dynamically discover policies for undocumented ports

- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/policy.rs
> Don't allow a policy to be used if `check_port_allowed` fails

- linkerd/app/integration/src/tests/transparency.rs
- linkerd/proxy/http/src/h1.rs
When the proxy transports `CONNECT` requests, the client silently
ignores `content-length` and `transport-encoding` response headers, as
it should. When the proxy passees these headers to the hyper server, it
errors (as is dictated by the RFC).
This change updates the HTTP client to remove these headers from
responses so that the proxy no longer propagates these illegal headers.
Fixes linkerd/linkerd2#8539
> http: Strip illegal headers from CONNECT responses

- .github/actions/list-changed-crates/entrypoint.sh
- checksec.sh
- linkerd/app/integration/src/data/gen-certs.sh
- linkerd/tls/test-util/src/testdata/gen-certs.sh
- Single quotes instead of double quotes for static strings
- No quotes are needed for variable assignments
- Use shellscript built-in functionality instead of dirname
Signed-off-by: Joakim Roubert <joakim.roubert@axis.com>
> Shellscript housekeeping

- linkerd/app/integration/src/controller.rs
- linkerd/app/integration/src/proxy.rs
- linkerd/app/integration/src/server.rs
- linkerd/app/integration/src/tcp.rs
- linkerd/app/integration/src/tests/profiles.rs
Currently, the service profiles integration test uses a very complex
declarative macro to generate test bodies. This approach has some
downsides:
1. All of the test code is contained inside a macro. This means that
`rustfmt` will not reformat it, and (in some cases) compilation
errors can be unclear.
2. The macro-generated code is relatively inflexible. This makes it
difficult to add new tests that need to do slightly different things.
3. Adding new configurations to the macro is complex. If we want to add
some new thing that can also be passed in to change the generated
code, we have to modify a bunch of macro match arms, which is
annoying and time-consuming.
This branch rewrites the profiles integration tests to use a
builder-style design instead of a macro. This way, the repetitive …
> test: replace `profile_test!` macro with builder

- justfile
Currently, when running `just docker`, the image is not given a
meaningful tag name by default. This commit changes the `justfile` so
that the default tag is something useful, rather than `''`. If no tag
name is provided from the command line, the Docker image will be given
the tag `gchr.io/linkerd-io/proxy:$USER-$GIT_SHA`. The image name of the
actual Linkerd repository is used so that dev images can be selected
using only the `--proxy-version` flag of `linkerd inject`, and
`--proxy-image` is not needed.
If we'd prefer not to output the same image name as release images by
default, I could that part to something different.
> justfile: generate a default docker tag name

- linkerd/http-box/src/erase_response.rs
- linkerd/http-box/src/lib.rs
- linkerd/http-box/src/response.rs
The `linkerd-http-box` crate currently contains `BoxRequest` and
`BoxResponse` middleware for boxing request/response bodies, and an
`EraseRequest` middleware for erasing the type of request bodies, for
use in a stack which must be able to serve *multiple* request body
types. However, there is no corresponding `EraseResponse` middleware.
This branch adds an `EraseResponse` middleware in `linkerd-http-box`.
This is necessary for PR #1706, but I factored this out into its own
branch as it's a fairly self-contained change.
> http-box: add `EraseResponse` middleware

- linkerd/stack/src/proxy.rs
This branch adds a `Proxy::into_service` method that composes a `Proxy`
with a `Service`, returning a new `Service` that calls the inner
`Service` through that `Proxy`.
This negates the need for `Proxy::proxy_oneshot`, so this also
closes #1725.
Currently, this is unused, but it will be used in PR #1706 (from which
this change was factored out).
> stack: add `ProxyService` for composing a `Proxy` with a `Service`

- Cargo.lock
- linkerd/app/admin/src/stack.rs
- linkerd/app/core/Cargo.toml
- linkerd/app/core/src/metrics.rs
- linkerd/app/core/src/transport/labels.rs
- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/http.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/metrics/authz.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/api.rs
- linkerd/app/inbound/src/policy/authorize/http.rs
- linkerd/app/inbound/src/policy/authorize/tcp.rs
- linkerd/app/inbound/src/policy/defaults.rs
- linkerd/app/inbound/src/policy/tests.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/server-policy/src/lib.rs
In preparation to introduce new route types to the policy API, this
change introduces a new `server_policy::Meta` type that includes a
`group` field so that we can explicitly differentiate between multiple
types of resources).
This change renames some types in anticipation of new types being
introduced:
* `Permit` is now `ServerPermit`
* `AuthzLabels` is now `ServerAuthzLabels`
> Add 'group' labels to describe policy resources

- linkerd/app/inbound/src/http/router.rs
- linkerd/app/outbound/src/switch_logical.rs
- linkerd/app/outbound/src/tcp/logical.rs
- linkerd/app/src/env.rs
- linkerd/proxy/transport/src/addrs.rs
We have several address-related newtypes that wrap `SocketAddr` types.
They currently implement `AsRef<SocketAddr>`, but this is a little
cumbersome in practice. This change replaces these `AsRef`
implementations with `Deref` so that we can, for instance, call `.ip()`
and `.port()` on these types directly without special handling.
> Implement `Deref` for address newtypes

- linkerd/app/inbound/src/http/router.rs
- linkerd/app/integration/src/server.rs
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/retry.rs
In anticipation of introducing new route types, this change renames
inbound and outbound `Route` target types to `ProfileRoute`.
> Rename target types from Route to ProfileRoute

- Cargo.lock
- linkerd/app/outbound/src/endpoint.rs
- linkerd/proxy/api-resolve/src/metadata.rs
- linkerd/proxy/discover/Cargo.toml
- linkerd/proxy/discover/src/from_resolve.rs
The proxy can receive redundant discovery updates. When this occurs, it
causes the balancer to churn, replacing an endpoint stack (and
therefore needlessly dropping a connection).
This change updates the discovery module to keep clones of the
discovered endpoint metadata, so that updated values can be compared to
eliminate duplicate updates.
Relates to linkerd/linkerd2#8677
> Dedupe discovery updates

- .github/workflows/deps.yml
- deny.toml
The tokio-util exception is no longer needed, as all dependencies have
been updated to use v0.7.
> deny: Remove tokio-util from exceptions

- .devcontainer/devcontainer.json
I see OOM kills when trying to build/test the proxy (my guess is
rust-analyzer has gotten more memory-hungry). This change updates the
devcontainer memory constraint to 12GB, which seems to work.
> dev: Update memory contraints

- linkerd/app/admin/src/stack.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/authorize.rs
- linkerd/app/inbound/src/policy/http.rs
- linkerd/app/inbound/src/policy/tcp.rs
The `AuthorizeHttp` and `AuthorizeTcp` layers don't necessarily only
enforce authorization. This change renames to, for instance,
`HttpPolicy` and `TcpPolicy` and eliminates the `authorize` submodule
structure.
> inbound: Rename policy-enforcement layers

- .github/fuzzers-list.sh
- .github/workflows/fuzzers.yml
The fuzzer CI embeds a somewhat complicated script. This change splits
it into a distinct file so that it can be shellchecked, etc.
> ci: Split fuzzer logic into a script

- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/metrics.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/inbound/src/metrics/authz.rs
- linkerd/app/inbound/src/metrics/error.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/http.rs
- linkerd/app/inbound/src/policy/tcp.rs
This change adds `route_{kind,group,name}` labels for inbound HTTP
authorization metrics. In this first implementation, a default route is
used for all metrics. In followup changes these labels will vary based
on control plane responses; and they will be wired into additional
inbound HTTP metrics.
Distinct error and permit types are introduced so that TCP-only
types are differentiated.
> inbound: Add route authorization labels

- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/tcp.rs
- linkerd/app/inbound/src/policy/tcp/tests.rs
When the inbound receives a "direct" inbound connection--a connection
that targets the proxy's inbound port--it uses the "opaque transport"
wrapper to discover the actual destination port for the connection. In
this case, the direct stack does a one-off authorization check instead
of using the proper TCP policy layer, which means that these connections
don't get the proper authorization metrics.
This change updates the direct TCP stack to use the TcpPolicy middleware
to enforce authorization. It also removes the authorization checking
utilities from the public `AllowPolicy` type so that all authorizations
must go through the metrics-tracking middlewares. The `policy` tests are
moved under the `policy::tcp` module so they have access to these
functions.
The TCP accept stack no longer …
> inbound: Record policy metrics for opaque-transport connections

- linkerd/app/inbound/src/detect.rs
The inbound TLS detection stack may forward non-mesh-TLS connections to
the application without recording TCP metrics. This change adds metrics
for these connections. This change also includes other non-functional
changes to setup for #1781.
> inbound: Record TCP metrics for forwarded TLS connections

- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/detect/tests.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/store.rs
Before making changes that support inbound HTTP route authorization
policies, this change makes some cosmetic changes that will help
minimize the changes needed for new funcationality.
No funtional changes.
> inbound: Cleanup in preparation for route policies #1781

- Cargo.lock
- Cargo.toml
- linkerd/http-route/Cargo.toml
- linkerd/http-route/src/grpc.rs
- linkerd/http-route/src/grpc/match.rs
- linkerd/http-route/src/grpc/match/tests.rs
- linkerd/http-route/src/grpc/tests.rs
- linkerd/http-route/src/http.rs
- linkerd/http-route/src/http/match.rs
- linkerd/http-route/src/http/match/header.rs
- linkerd/http-route/src/http/match/host.rs
- linkerd/http-route/src/http/match/path.rs
- linkerd/http-route/src/http/match/query_param.rs
- linkerd/http-route/src/http/match/tests.rs
- linkerd/http-route/src/http/tests.rs
- linkerd/http-route/src/lib.rs
This change adds a standalone utility crate that will support matching
routes for the Gateway API's HTTP route types. This crate is not yet
used. In followup changes:
* filter types will be added to support header-rewriting, HTTP
redirection, and error injection filters;
* the inbound proxy will be updated to supcort route-oriented
authorization policies; and
* the inbound policy API client will be updated to configure inbound
server routes.
> Add HTTP route matchers to support the Gateway API

- Cargo.lock
- linkerd/proxy/http/Cargo.toml
- linkerd/proxy/tcp/Cargo.toml
- linkerd/service-profiles/Cargo.toml
Tower [v0.4.13] includes a fix for a bug in the `tower::ready_cache`
module, tower-rs/tower#415. The `ready_cache` module is used internally
in Tower's load balancer. This bug resulted in panics in the proxy
(linkerd/linkerd2#8666, linkerd/linkerd2#6086) in cases where the
Destination service sends a very large number of service discovery
updates (see linkerd/linkerd2#8677).
This commit updates the proxy's dependency on `tower` to 0.4.13, to
ensure that this bugfix is picked up.
Fixes linkerd/linkerd2#8666
Fixes linkerd/linkerd2#6086
[v0.4.13]: https://github.com/tower-rs/tower/releases/tag/tower-0.4.13
> 2.161.3: cherry-pick #1758

- linkerd/app/core/src/control.rs
- linkerd/app/core/src/errors.rs
- linkerd/dns/src/lib.rs
- linkerd/proxy/dns-resolve/src/lib.rs
When resolving control plane components, we first resolve a SRV
record. If we're unable to parse IPv4 addresses from the record,
then we fall back to an A record lookup. But if the initial resolution
fails completely (i.e. doesn't produce any record data), then we don't
fall back to an A record.
This change fixes this fallback behavior so that we attempt A record
lookups whenever a SRV lookup fails. In doing so, we change the dns
module to use typed errors (avoiding boxing) so that we can print
better error messages and have static guarantees about the error
types being handled.
Fixes linkerd/linkerd2#8296
Co-authored-by: Alex Leong <alex@buoyant.io>
> 2.161.3: cherry-pick #1670

- linkerd/app/integration/src/tests/transparency.rs
- linkerd/proxy/http/src/h1.rs
When the proxy transports `CONNECT` requests, the client silently
ignores `content-length` and `transport-encoding` response headers, as
it should. When the proxy passees these headers to the hyper server, it
errors (as is dictated by the RFC).
This change updates the HTTP client to remove these headers from
responses so that the proxy no longer propagates these illegal headers.
Fixes linkerd/linkerd2#8539
> 2.161.3: cherry-pick #1699

- Cargo.lock
- linkerd/app/outbound/src/endpoint.rs
- linkerd/proxy/api-resolve/src/metadata.rs
- linkerd/proxy/discover/Cargo.toml
- linkerd/proxy/discover/src/from_resolve.rs
The proxy can receive redundant discovery updates. When this occurs, it
causes the balancer to churn, replacing an endpoint stack (and
therefore needlessly dropping a connection).
This change updates the discovery module to keep clones of the
discovered endpoint metadata, so that updated values can be compared to
eliminate duplicate updates.
Relates to linkerd/linkerd2#8677
> 2.161.3: cherry-pick #1759

- linkerd/app/core/src/errors/respond.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/http.rs
- linkerd/http-route/src/http/filter.rs
- linkerd/http-route/src/http/filter/redirect.rs
- linkerd/http-route/src/http/match.rs
- linkerd/http-route/src/http/match/path.rs
- linkerd/server-policy/src/http.rs
The Gateway API requires that `HTTPRoute` implementations support a
[redirection filter][gwapi].
This change adds a filter implementation to the `http-route` crate.
Inbound server policies are updated to apply this filter on HTTP routes.
When a request is redirected, the policy layer returns an error and the
error crate is responsible for turning that error into an HTTP response.
This change fixes path matching so that trailing slashes do not impact
prefix matching.
[gwapi]: https://github.com/kubernetes-sigs/gateway-api/blob/541e9fc2b3c2f62915cb58dc0ee5e43e4096b3e2/apis/v1beta1/httproute_types.go#L772-L821
> Add an HTTP route redirect filter

- Cargo.lock
- linkerd/app/inbound/src/policy/http.rs
- linkerd/app/inbound/src/policy/http/tests.rs
- linkerd/http-route/Cargo.toml
- linkerd/http-route/src/grpc.rs
- linkerd/http-route/src/grpc/filter.rs
- linkerd/http-route/src/grpc/filter/inject_failure.rs
- linkerd/http-route/src/http/filter.rs
- linkerd/http-route/src/http/filter/inject_failure.rs
- linkerd/server-policy/src/grpc.rs
- linkerd/server-policy/src/http.rs
The control plane may choose to inject failures for a route. It may
cause all requests to fail, or only a random subset of requests to fail.
This change adds HTTP and gRPC route filters that can cause error
responses for inbound requests.
> Add HTTP and gRPC route failure-injection filters

- Cargo.lock
- linkerd/tracing/Cargo.toml
This reverts commit 7ecdd7840fb2a4b2a26f8195585a54621d4b1f07.
Upgrading tracing-subscriber breaks logging in the proxy.
`cargo run` on main:
```
Finished dev [unoptimized] target(s) in 43.90s
Running `target/debug/linkerd2-proxy`
Invalid configuration: no destination service configured
```
Versus `cargo run` with this change reverted:
```
Finished dev [unoptimized] target(s) in 52.61s
Running `target/debug/linkerd2-proxy`
[     0.007639s] ERROR ThreadId(01) linkerd_app::env: LINKERD2_PROXY_IDENTITY_SVC_ADDR and LINKERD2_PROXY_IDENTITY_SVC_NAME must be set.
[     0.007680s] ERROR ThreadId(01) linkerd_app::env: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS must be set.
[     0.007687s] ERROR ThreadId(01) linkerd_app::env: LINKERD2_PROXY_IDENTITY_DIR must be set.
[     0.007692s] ERROR ThreadId(01) …
```
> Revert "build(deps): bump tracing-subscriber from 0.3.11 to 0.3.14 (#1806)"

- linkerd/proxy/http/src/h1.rs
The issue linkerd/linkerd2#6035 describes a situation where Linkerd
rejects HTTP/1.1 CONNECT requests because the remote (non-Linkerd)
forward proxy returns a successful response that erroneously has the
wrong HTTP version (HTTP/1.0). Since the CONNECT method does not exist
in the HTTP/1.0 protocol, Linkerd does not treat this response as a
CONNECT.
It turns out that in the accursed Real World, some HTTP forward proxies
actually do return the wrong protocol version when successfully handling
CONNECT requests. We don't want to remove the check that the protocol
version is correct, because it could lead to us incorrectly treating
responses to CONNECTs as establishing a tunnel when they don't actually
do that. However, in order to make it easier for future users who
encounter issues where …
> http: log a warning when a CONNECT response has the wrong version

- .devcontainer/devcontainer.json
`skellock.just` is unmaintained and has syntax highlighting bugs.
`kokakiwi.vscode-just` fixes those bugs!
> dev: Use the kokakiwi.vscode-just

- .devcontainer/devcontainer.json
- .devcontainer/on-create.sh
- .github/fuzzers-list.sh
- .github/workflows/actions.yml
- .github/workflows/beta.yml
- .github/workflows/check-all.yml
- .github/workflows/check-each.yml
- .github/workflows/coverage.yml
- .github/workflows/deps.yml
- .github/workflows/integration.yml
- .github/workflows/lint.yml
- .github/workflows/nightly.yml
- .github/workflows/shellcheck.yml
- .github/workflows/test.yml
- .github/workflows/toolchain.yml
- CONTRIBUTING.md
- README.md
- justfile
* Update devcontainer to v26
* Add a `just markdownlint` recipe
* Add a `shellcheck` workflow
* Address lints
> dev: Update markdowlint-cli2 to 5.0.1

- .github/actions/list-changed-crates/Dockerfile
- .github/actions/list-changed-crates/action.yml
- .github/workflows/actions.yml
- .github/workflows/toolchain.yml
- justfile
Add a job to the `rust-toolchain` workflow that compares the
`rust-toolchain` file to the output of `cargo --version` in the
devcontainer.
> ci: Validate that rust-toolchain matches devcontainer

- .devcontainer/devcontainer.json
- .github/actions/list-changed-crates/Dockerfile
- .github/workflows/actions.yml
- .github/workflows/beta.yml
- .github/workflows/check-all.yml
- .github/workflows/check-each.yml
- .github/workflows/coverage.yml
- .github/workflows/deps.yml
- .github/workflows/integration.yml
- .github/workflows/lint.yml
- .github/workflows/nightly.yml
- .github/workflows/shellcheck.yml
- .github/workflows/test.yml
- .github/workflows/toolchain.yml
- justfile
This change updates to the v28 devcontainer, which includes an extracted
`action-dev-check` script that replaces the inlined just recipe. This
change also renames some recipes (like action-lint, md-lint, and
sh-lint) to be uniform with the recipes in other repos.
> dev: Use a common action-dev-check

- Cargo.lock
- linkerd/server-policy/Cargo.toml
- linkerd/server-policy/src/meta.rs
As the proxy discovers policies, it refers to the source of the policy configuration. This comes in two flavors: "default" (synthetic) resources and resources that actually exist in the cluster.
When the proxy reads routes and authorization, the control plane uses protobuf types to differentiate these states; but server resources are described by a generic label map. When the proxy reads this label map, it doesn't properly detect when default/synthetic resources are used and it _always_ indicates that the resource is real.
This can lead to duplicate metrics when, for instance, the proxy initially uses a default server and then obtains a default configuration by discovery.
This change fixes this situation in two ways:
1. We now properly detect and differentiate default server …
> Fix inbound server label ambiguity

- Cargo.lock
Hyper v0.3.15 fixes a potential deadlock in HTTP/2 clients. For some reason this wasn't automatically picked up by depenabot.
> Bump hyper & h2

- deny.toml
The other unicode packages don't use this license, so an exception should be
okay. This could also just be moved to licenses.allow.
Fixes #1964 checks.
Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>
> Allow Unicode-dfs-2016 for unicode-ident

- linkerd/meshtls/rustls/src/creds/receiver.rs
This fixes a new Clippy lint for uses of `.ok().expect("...")` on `Result`s that could just be replaced with `.expect("...")`. This pattern shows up in a couple of the meshtls-rustls tests, and the Clippy lint was causing CI to fail.
> meshtls-rustls: fix clippy `.ok().expect()` lints in tests

- linkerd/app/gateway/src/gateway.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/logical.rs
- linkerd/app/outbound/src/policy.rs
- linkerd/app/outbound/src/policy/config.rs
- linkerd/app/outbound/src/policy/discover.rs
- linkerd/app/outbound/src/policy/http/router.rs
- linkerd/app/outbound/src/switch_logical.rs
- linkerd/app/outbound/src/tcp/logical.rs
- linkerd/app/src/lib.rs
- linkerd/client-policy/src/http.rs
- linkerd/client-policy/src/http/router.rs
- linkerd/client-policy/src/lib.rs
This branch refactors the prototype client policy code to move the
discovery of client policies to still occur after profile discovery, but
before the HTTP logical stack. This means that SO_ORIGINAL_DST addresses
need not be stored in the `Logical` target type any longer, which I
think is significantly nicer, as we no longer have a `Logical` field
that's ignored by hashing and equality.
Instead, the client policy discovery now occurs in the stack produced by
`push_discover`. This is conceptually much more correct. In addition, it
allows us to remove the separate caching logic for client policy
lookups, and just use the same per-original-destination-address cache
that's used for service profile lookups. This simplifies the policy code
significantly, and allows moving stuff back out of …
> move client policy discovery out of HTTP logical stack

- .github/actions/list-changed-crates/entrypoint.sh
- .github/workflows/fuzzers.yml
- justfile
`@-` suppresses logging and ignores the command's exit code. We only want to
use `@` so that logging is suppressed but exit codes are fatal.
> just: Fix justfile command silencing

- .checksec/amd64-gnu.json
- .checksec/amd64-musl.json
- .checksec/arm-gnu.json
- .checksec/arm-musl.json
- .checksec/arm64-gnu.json
- .checksec/arm64-musl.json
- .devcontainer/devcontainer.json
- .github/actions/list-changed-crates/Dockerfile
- .github/workflows/actions.yml
- .github/workflows/beta.yml
- .github/workflows/check-all.yml
- .github/workflows/check-each.yml
- .github/workflows/coverage.yml
- .github/workflows/deps.yml
- .github/workflows/docker.yml
- .github/workflows/integration.yml
- .github/workflows/lint.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/shellcheck.yml
- .github/workflows/test.yml
- .github/workflows/toolchain.yml
- Cargo.toml
- Dockerfile
- justfile
This change adds release targets for static binaries (using musl).
With this change, we retain debug symbols in an alternate file.
This change bumps the devcontainer to v38 to include just-cargo fixes.
> release: Produce static binaries

- linkerd/app/gateway/src/lib.rs
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/logical.rs
Currently the `push_http_logical` commingles the concrete stack (load balancers, etc) and the logical stack (routing). This change splits these builders into separate functions.
> outbound: Split the concrete and logical stack builders

- linkerd/app/core/src/config.rs
- linkerd/app/core/src/control.rs
- linkerd/app/core/src/svc.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/endpoint.rs
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/detect.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/retry.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/logical.rs
- linkerd/app/outbound/src/tcp/logical.rs
- linkerd/app/outbound/src/test_util.rs
- linkerd/app/src/env.rs
- linkerd/proxy/http/src/server.rs
- linkerd/service-profiles/src/http/service.rs
- linkerd/stack/Cargo.toml
- linkerd/stack/src/switch_ready.rs
Proxies may buffer TCP connections while waiting for policy discovery
and may buffer HTTP requests while waiting for a shared resource (like a
load balancer).
Previously, a single configuration was used to configure both TCP and
HTTP buffers. This change decouples these configurations in preparation
for allowing balancer configuration to be configured by the control
plane.
Furthermore, this change updates the stack builder to always construct
buffers with failfast and spawnready to (1) ensure that all buffers
enforce the proper backpressure and load shedding semantics and (2) to
reduce boilerplate.
This change updates the proxy's environment configuration as follows:
* Removed `LINKERD2_PROXY_INBOUND_DISPATCH_TIMEOUT`
* Removed `LINKERD2_PROXY_OUTBOUND_DISPATCH_TIMEOUT`
* Added …
> config: Decouple HTTP and TCP buffering config

- linkerd/stack/src/failfast.rs
- linkerd/stack/src/failfast/gate.rs
- linkerd/stack/src/failfast/test.rs
* Moved `Gate` into its own module.
* Moved `test` into their own file.
* Reorganized `Gate:poll_ready` slightly for clarity.
* Added comments to `FailFast::poll_ready` state changes.
* Renamed `max_unavailable` to `timeout`.
> Split out failfast into smaller modules

- linkerd/stack/src/lib.rs
- linkerd/stack/src/watch.rs
This branch adds an implementation of a middleware that watches a `watch::Receiver` of targets and builds a new service when the watch is updated. The current state of the inner service is broadcast over a second watch to any clones of the `SpawnWatch` service.
This is the same code added in PR #2100, but rebased onto `main`, with documentation and tests added.
> stack: add `SpawnWatch` middleware

- Cargo.lock
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/logical/router.rs
- linkerd/app/outbound/src/tcp/logical/router.rs
- linkerd/service-profiles/Cargo.toml
- linkerd/service-profiles/src/http.rs
- linkerd/service-profiles/src/lib.rs
- linkerd/service-profiles/src/proto.rs
Currently, the logical router will generate a single traffic
distribution that's used for every HTTP route. This is fine when working
with ServiceProfiles, where a single traffic split applies to the entire
profile, but won't work with the new client policy implementation based
on HTTPRoutes, where each route may have its own separate list of
backends.
This branch changes the profile router so that a separate distribution
is built per route. The `Profile` and `profiles::http::Route` types are
changed so that each route has its own list of targets. In the case of
`Profile`s constructed from a ServiceProfile, these lists are all the
same. However, when adding support for the new client policy API, the
same structures can be generated with separate lists of backends per
route.
In a follow-up …
> generate distributions per-route

- linkerd/stack/src/watch.rs
I added this while trying to debug the tests, and forgot to remove it. We should get rid of it before merging #2095.
> remove stray `dbg!` in `watch`

- linkerd/stack/src/lazy.rs
- linkerd/stack/src/lib.rs
This branch adds a `Lazy` service in `linkerd-stack`, which calls a
`NewService` to create an inner `Service` the first time it's polled to
readiness. The `Lazy` service can be cloned, sharing the inner service
with an `Arc<Mutex<...>>`, and the first clone to be polled will create
the inner service.
This was factored out from PR #2095, with tests added.
> stack: add `Lazy` middleware

- Cargo.lock
- linkerd/distribute/Cargo.toml
- linkerd/distribute/src/cache.rs
- linkerd/distribute/src/lib.rs
- linkerd/distribute/src/params.rs
- linkerd/distribute/src/service.rs
- linkerd/distribute/src/stack.rs
`NewDistribute` will be used to implement per-route traffic distribution policies so that, for instance, each request route may use a different traffic split. In this setup, we want each instance--re-constructed as configuration changes--to reuse a common set of concrete services so that load balancer state need not be lost when a policy changes.
This change adds a `distribute::BackendCache` module that produces a `NewDistribute` for an updated, cached set of backends.
> distribute: Add a backend cache

- Cargo.lock
- linkerd/service-profiles/Cargo.toml
- linkerd/service-profiles/src/http/proxy.rs
- linkerd/service-profiles/src/http/service.rs
- linkerd/service-profiles/src/lib.rs
- linkerd/service-profiles/src/split.rs
We may clone `Profile` structures when processing a watch. Currently, the profile includes vectors that we need not copy every time we clone a profile.
This change replaces these heap-allocated vectors (`Vec`) instances with reference-counted slices (`Arc<[_]>`) so that `Profile::clone` calls need not allocate.
> Make `Profile::clone` cheaper

- linkerd/stack/Cargo.toml
- linkerd/stack/src/watch.rs
The spawn watch layer helper wasn't actually usable. This has been fixed.
This change also fixes stack's tokio feature flags (needed for watch).
> stack: Fix `NewSpawnWatch::layer` type signature

- linkerd/distribute/src/params.rs
- linkerd/distribute/src/service.rs
- linkerd/proxy/api-resolve/src/lib.rs
- linkerd/service-profiles/src/http.rs
- linkerd/service-profiles/src/proto.rs
We want to use our configuration types as hash keys in some places. To do so, we need to implement `Hash`.
> Implement `Hash` for configuration types

- linkerd/app/gateway/src/lib.rs
- linkerd/app/outbound/src/logical.rs
- linkerd/app/outbound/src/tcp.rs
- linkerd/app/outbound/src/tcp/concrete.rs
- linkerd/app/outbound/src/tcp/logical.rs
- linkerd/app/outbound/src/tcp/logical/tests.rs
This branch refactors the outbound proxy to have separate `push_tcp_logical` and `push_tcp_concrete` methods, rather than building both stacks in `push_tcp_logical`. This makes the TCP outbound proxy more consistent with how the HTTP outbound proxy is built (as it has separate methods for building the logical and concrete stacks).
No functional changes, just moving code around.
> outbound: separate TCP logical and concrete stacks

- .github/workflows/release.yml
- linkerd2-proxy/src/main.rs
Our cross-compiled musl builds do not currently compile (OOM). To unblock releases, this change disables these builds for now.
> Disable musl in release build

- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/detect/tests.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/api.rs
- linkerd/app/inbound/src/policy/config.rs
- linkerd/app/inbound/src/policy/defaults.rs
- linkerd/app/inbound/src/policy/http.rs
- linkerd/app/inbound/src/policy/http/tests.rs
- linkerd/app/inbound/src/policy/store.rs
- linkerd/app/inbound/src/policy/tcp.rs
- linkerd/app/inbound/src/policy/tcp/tests.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/app/src/env.rs
- linkerd/proxy/policy/src/grpc.rs
- linkerd/proxy/policy/src/http.rs
- linkerd/proxy/policy/src/lib.rs
- linkerd/proxy/policy/src/opaque.rs
This branch just does most of the remaining busywork to update existing code with the changes from `ver/client-policy-sketch`, and fix the remaining compiler errors.
> fill in the blanks for `ver/client-policy-sketch`

- linkerd/stack/src/annotate_error.rs
- linkerd/stack/src/lib.rs
This branch introduces a new `AnnotateError` middleware in `linkerd-stack`, for adding context to errors returned by a wrapped `Service`.
The `annotate_error` module contains a new trait, `ErrorContext`, which is implemented by types that provide context to `Error`s by wrapping them with a new `Error` type, and the `AnnotateError` middleware itself. The middleware consists of a `NewService` which extracts a `Param` implementing `ErrorContext` and produces a `Service`, which wraps any errors returned by the inner `Service` using that `ErrorContext`.
Additionally, `NewAnnotateError` may be constructed with an `ExtractParam` implementation that configures how an `ErrorContext` implementation is produced from a target type, when the `Param`s themselves do not implement `ErrorContext`. …
> stack: add `AnnotateError` middleware

- linkerd/app/core/src/errors/respond.rs
- linkerd/app/integration/src/tests/transparency.rs
- linkerd/proxy/http/src/orig_proto.rs
When the inbound proxy's `ClientRescue` layer sees a client connection
error for a connection initiated for an HTTP/1 request, it will add a
`connection: close` header to the synthesized error response. The
`ClientRescue` layer is not currently aware of whether an HTTP/1 request
was recieved from an upstream proxy as part of an orig-proto upgrade or
not. If the request _is_ part of an orig-proto upgrade, the server side
of the inbound proxy is an HTTP/2 server. When Hyper's HTTP/2 server
sees a response with a `connection: close` header, it emits a warning,
because `connection` headers are illegal in HTTP/2.
The inbound proxy *does* strip any headers set by the server that are
illegal in HTTP/2 when performing an orig-proto downgrade. However, this
stripping occurs only when handling a …
> orig_proto: don't set `connection: close` on errors

- linkerd/app/core/Cargo.toml
- linkerd/app/core/src/config.rs
- linkerd/app/core/src/control.rs
- linkerd/app/core/src/svc.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/endpoint.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/tcp/concrete.rs
- linkerd/app/outbound/src/test_util.rs
- linkerd/app/src/env.rs
- linkerd/stack/Cargo.toml
- linkerd/stack/src/lib.rs
- linkerd/stack/src/queue.rs
Buffer services in the proxy are constructed with a queue capacity and a
failfast timeout. Currently, these parameters are configured based on
the proxy's config structs (parsed from environment variables), and each
buffer `Layer` is created with a fixed buffer configuration depending on
which stack it is used in, so all buffers constructed by that stack will
have the same configuration. In the future, we would like to allow these
parameters to be configured per-target by the control plane.
In order to support configuring buffer parameters dynamically, this
branch introduces a `NewQueue` type, which implements `NewService` and
produces `Buffer` + `FailFast` services configured using a `QueueConfig`
`Param` extracted from the target. This will allow target types to
implement …
> configure buffers from target `Param`s

- linkerd/app/core/src/control.rs
- linkerd/app/core/src/svc.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/server.rs
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/tcp.rs
- linkerd/app/outbound/src/tcp/concrete.rs
- linkerd/app/outbound/src/tcp/logical.rs
- linkerd/service-profiles/src/default.rs
- linkerd/service-profiles/src/discover.rs
- linkerd/service-profiles/src/lib.rs
- linkerd/stack/src/lib.rs
- linkerd/stack/src/new_service.rs
- linkerd/stack/src/watch.rs
The profile discovery module--especially on the outbound side--requires some structural changes to begin adding more logic to it.
1. The outbound::discover module is simplified. It is no longer specific to sockets in the accept stack and may be used for other request types. Its cache, buffer, and stack metrics are no longer coupled to the discovery stack.
2. The `profiles::Discovery` module determines whether discovery is allowed (via a predicate). This has logic has been moved into the calling stack explicitly so that the discovery module always performs discovery as requested.
3. The `profiles::Discovery` module now wraps a two-tiered `NewService`, the first of which takes the original target value and the second of which takes the profile resolution.
* Stack manipulation layers are …
> Simplify profile discovery

- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/errors/respond.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/outbound/src/http/detect.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/proxy/http/src/version.rs
The HTTP error responder already knows whether a request is considered HTTP/1, HTTP/2, or gRPC.
This change updates these log messages to include the relevant protocol information for each failed request.
Furthermore, this change updates the `http::Version` enum to implement `Debug` with full HTTP version strings like "HTTP/1" and "HTTP/2". We then remove the version for debug spans, as it's needlessly verbose for most uses. When debugging, we can identify the version based on specific events in a span. It need not exist on every event on the span.
> Update HTTP error responder to log version info

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- deny.toml
- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/control.rs
- linkerd/app/core/src/errors/respond.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/outbound/src/endpoint.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/detect.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/logical.rs
- linkerd/app/outbound/src/tcp/concrete.rs
- linkerd/app/outbound/src/tcp/connect.rs
- linkerd/app/outbound/src/tcp/logical.rs
- linkerd/meshtls/Cargo.toml
- linkerd/meshtls/boring/Cargo.toml
- linkerd/proxy/http/src/version.rs
- linkerd2-proxy/Cargo.toml
* Move HTTP version logging into the `Respond` handler (since it already includes all of this information). This also let's us be explicit about gRPC. This removes needing to wire it through elsewhere.
* All error types are defined in the module in which they are used, even when they exactly match error types elsewhere. As we move forward with the upcoming changes, we want each stack to be as independent as possible.
* `http::Version` now implements `Debug` with full "HTTP/1" or "HTTP/2" strings. We change uses of `Display` to `Debug`.
* Remove `RouteError` types for now. They're not really critical for debugging. We may restore them later as those stacks evolve.
> Error type suggestions for #2162

- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/svc.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/logical.rs
- linkerd/app/outbound/src/tcp.rs
`Stack::push_request_filter` may apply to either `Service` or `NewService` stacks. The use of "request" makes it sound like it only applies to services. This change renames it to `Stack::push_filter`.
`Stack::push_idle_cache` is renamed to `Stack::push_new_idle_cached` to reflect that the stack is a `NewService`.
> core: Rename Stack utilities for clarity

- linkerd/app/integration/src/tests/telemetry.rs
We have a previously-flakey test that now fails consistently. Disable it.
> Disable broken tests

- linkerd/trace-context/src/lib.rs
- linkerd/trace-context/src/propagation.rs
- linkerd/trace-context/src/propagation/b3.rs
- linkerd/trace-context/src/propagation/w3c.rs
This is a proof of concept PR to show what changes would be necessary to support `tracecontext`, the OpenTelemetry "standardised" way of propagating distributed tracing context (aka `w3c` format).
A copy of the RFC [can be found here](https://www.w3.org/TR/trace-context-1/#processing-model-for-working-with-trace-context). The RFC/specification has a processing model for how the header(s) should be parsed. This proof of concept contains _most_ cases, some which are a bit more trivial to implement have been left out and will be done when (or if) this moves forward. The parsing logic is also a bit rushed and I will want to revisit it if conceptually this all looks sound.
Also, most notably, `tracestate` is not being handled at all, since it's optional:
> Vendors receiving a tracestate …
> Add traceparent header parsing for w3c tracecontext

- linkerd/app/gateway/src/lib.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/logical.rs
- linkerd/app/outbound/src/tcp/concrete.rs
- linkerd/proxy/balance/src/discover.rs
- linkerd/proxy/balance/src/lib.rs
- linkerd/proxy/core/src/resolve.rs
`Resolve` trait references typically include many additional type constraints. This change moves this boilerplate into the trait alias so it need not be repeated.
> Simplify the `Resolve` trait alias

- Cargo.lock
Versions 0.6.4 and 0.6.3 of the `miniz_oxide` crate have been yanked from crates.io, due to an accidental MSRV violation (see Frommi/miniz_oxide#135). `miniz_oxide` is a dependency of `flate2`, which is used by `linkerd-app-integration` for testing gzip metrics compression.
Because the lockfile currently contains a yanked version of `miniz_oxide`, our `cargo deny` checks are failing on CI. This PR downgrades the `miniz_oxide` dependency to 0.6.2, which is not yanked. This should fix CI.
> downgrade `miniz_oxide` from yanked 0.6.4 to 0.6.2

- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/svc.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/outbound/src/http/detect.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/detect/src/lib.rs
- linkerd/proxy/http/src/lib.rs
- linkerd/proxy/http/src/server.rs
The protocol detection stack does not easily allow for its inner stack to hold any per-target state because it commingles the (async) detection result with the original target.
This change updates the detection module to use a cascading inner stack so that the caller may determine how to use these targets. All implementations lift the original targets to preserve the prior behavior.
> Use a cascading stack with protocol detection

- linkerd/app/gateway/src/lib.rs
- linkerd/app/outbound/src/endpoint.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/logical.rs
- linkerd/app/outbound/src/opaq.rs
- linkerd/app/outbound/src/opaq/concrete.rs
- linkerd/app/outbound/src/opaq/forward.rs
- linkerd/app/outbound/src/opaq/logical.rs
- linkerd/app/outbound/src/opaq/logical/tests.rs
- linkerd/app/outbound/src/tcp.rs
- linkerd/app/outbound/src/tcp/connect.rs
- linkerd/app/outbound/src/tcp/endpoint.rs
- linkerd/app/outbound/src/tcp/tagged_transport.rs
- linkerd/proxy/api-resolve/src/metadata.rs
- linkerd/proxy/api-resolve/src/pb.rs
We differentiate "opaque" and "tcp" stacks because some TCP stacks may
also apply for HTTP traffic. We shorten this in code as "opaq" because
it's unambiguous and the same length as "http"
* Add an `outbound::opaq` module for opaque stacks. ("opaq").
* Rename `push_tcp_{logical,concrete,forward}` to `push_opaq_*`
* Rename `OpaqueTransport` to `TaggedTransport` (Closes #2212).
> outbound: Split out separate 'opaq' modules

- Cargo.lock
- linkerd/app/inbound/Cargo.toml
- linkerd/app/integration/Cargo.toml
- linkerd/http-route/Cargo.toml
- linkerd/proxy/api-resolve/Cargo.toml
- linkerd/proxy/api-resolve/src/pb.rs
- linkerd/proxy/identity-client/Cargo.toml
- linkerd/proxy/tap/Cargo.toml
- linkerd/server-policy/Cargo.toml
- linkerd/service-profiles/Cargo.toml
v0.8.0 of `linkerd2-proxy-api` adds a `ProtocolHint::Opaque` variant to
the Destination API to indicate that an endpoint will not perform
application-level processing. This branch updates the proxy to depend on
v0.8.0. Currently, the `Opaque` hint does not change the proxy's
behavior; this will be added in a follow-up branch.
> update `linkerd2-proxy-api` to v0.8.0

- linkerd/app/core/src/svc.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/metrics/error/http.rs
- linkerd/app/inbound/src/policy/http.rs
- linkerd/app/integration/src/tests/discovery.rs
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/endpoint/tests.rs
- linkerd/app/outbound/src/tcp/connect.rs
- linkerd/app/outbound/src/tcp/tagged_transport.rs
- linkerd/http-box/src/request.rs
- linkerd/proxy/api-resolve/src/metadata.rs
- linkerd/proxy/balance/src/lib.rs
- linkerd/stack/metrics/src/service.rs
To support new discovery types, we want to changing how stacks are composed so that target types are domain-specific and configuration is instrumented via target wrappers.
This change sets up stack changes as follows:
* `Layers::push_flatten_new` is a utility for flatten "cascaded" `NewService` types by providing a target for child `NewService` impls.
* Target/Param constraints and impls are made uniform.
* In tests, we provide new test-specific target types.
* Configuration types are made ready to be stored in a cache.
> outbound: Lint stack target types

- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/sidecar.rs
In preparation for new target types, this change splits the ingress and proxy stack builders into ingress and sidecar modules, respectively.
> outbound: Split sidecar and ingress stack modules

- .devcontainer/devcontainer.json
- linkerd/app/integration/src/tests/tap.rs
The `tap::rejects_incorrect_identity_when_identity_is_expected` test passes incorrectly. This change updates the test to assert the expected condition; and then the test is skipped (like the other tap integration tests). These tests all need discovery configuration to operate as intended.
This change also updates the devcontainer.json spec with an increased memory limit. This is necessary to run tests.
> test: Disable tap::rejects_incorrect_identity_when_identity_is_expected

- linkerd/app/outbound/src/discover/tests.rs
The discovery stack no longer caches its inner stacks. Instead, it caches discovery resolutions. The modules tests were not updated to reflect this difference.
This change updates the cache test to measure discovery lookups and not service creation.
> outbound: Improve discovery cache test

- linkerd/app/integration/src/controller.rs
- linkerd/app/integration/src/tests/identity.rs
- linkerd/app/integration/src/tests/telemetry.rs
- linkerd/app/integration/src/tests/telemetry/tcp_errors.rs
Currently, updates sent by the mock destination controller used in integration tests are constructed by a number of free functions with names like `destination_add_tls` and `destination_add_h2_hinted` and so on. These functions determine different aspects of the generated destination updates, such as protocol hints, labels, and TLS identity. This works acceptably for the current integration tests. However, in order to add new tests, it may be desirable to add additional destination configurations. For example, for testing the handling of various protocol hints on direct connections, it's necessary to set both a protocol hint *and* a TLS identity (direct connections require TLS). The current approach has separate functions for constructing updates with a protocol hint and updates with TLS. …
> integration: add destination update builders

- linkerd/app/integration/src/controller.rs
- linkerd/app/integration/src/tests/direct.rs
- linkerd/app/integration/src/tests/identity.rs
- linkerd/app/integration/src/tests/telemetry.rs
- linkerd/app/integration/src/tests/telemetry/tcp_errors.rs
Depends on #2232
This branch adds a new integration test for direct connections transporting hinted HTTP/2. This was factored out from #2209. I did *not* add the test that actually reproduces linkerd/linkerd2#9888 in this PR, as it would fail.
> integration: add test for direct HTTP connections

- Cargo.lock
- Cargo.toml
- linkerd/proxy/client-policy/Cargo.toml
- linkerd/proxy/client-policy/src/grpc.rs
- linkerd/proxy/client-policy/src/http.rs
- linkerd/proxy/client-policy/src/lib.rs
- linkerd/proxy/client-policy/src/opaq.rs
This change introduces the client policy types that will be used to configure outbound proxies. These types are analogous to those used for server policy in inbound proxies. They support integration with the Kubernetes Gateway API.
These types are relatively sketchy at the moment. They will change as they are integrated into the outbound proxy.
> Add client-policy types

- Cargo.lock
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/ingress.rs
In 91bbbd4, we added a `LoadShed` onto the ingress proxy. This causes errors while discovery is pending.
This change removes the ingress `LoadShed` layer and documents the backpressure and error handling semantics of the ingress stack. This change also adds a descriptive error wrapper onto the inbound server stack.
> outbound: Fix ingress-mode proxy

- Cargo.lock
- linkerd/app/gateway/Cargo.toml
- linkerd/app/gateway/src/http.rs
- linkerd/app/gateway/src/http/tests.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/gateway/src/server.rs
- linkerd/app/inbound/Cargo.toml
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/http.rs
- linkerd/app/inbound/src/server.rs
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/endpoint/tests.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/protocol.rs
- linkerd/app/outbound/src/sidecar.rs
- linkerd/app/outbound/src/tcp/endpoint.rs
- linkerd/proxy/core/src/resolve.rs
A recent change broke how gateways handle the URI of upgraded HTTP/1.1 requests. This problem was caused by normaling the URI twice (once in the inbound HTTP server and once in the outbound HTTP server).
To fix this, the outbound HTTP server has been removed from the cached stack so that it is not included in gatewayed services.
Furthermore, to test this, this change splits `push_http_client` from the `Outbound::push_http_endpoint` stack and `push_http_tcp_server` from the `Inbound::push_http_server` stack. This allows us to write tests that mock HTTP-level services.
> gateway: Fix URI form for gatewayed HTTP/1 requests

- linkerd/tracing/src/level.rs
- linkerd/tracing/src/lib.rs
Currently, `tracing` spans are used to record HTTP access log entries. These spans are recorded at the `INFO` level, in order to allow the use of fast-path filtering for the more verbose `DEBUG` and `TRACE` levels when running with the default tracing filter configuration (`linkerd=info`) --- if no events will ever be enabled at a given level, `tracing` can skip them more efficiently than when events with some targets are enabled at that level. The access log spans are recorded with a separate `_access_log` target, so that the default `linkerd=info` filter does not enable them.
However, when running with a custom filter configuration that enables `info` for all targets, the access log spans will be enabled even if access logging is disabled. This means that these spans will be recorded …
> trace: never log access log spans to stdout

- linkerd/app/outbound/src/http/server.rs
- linkerd/proxy/http/src/normalize_uri.rs
This branch refactors `http::NormalizeUri` to take an `ExtractParam` for
extracting the default authority, rather than requiring `T:
Param<DefaultAuthority>`. This way, we can remove the wrapper target
type that's used only to temporarily add this `Param` impl.
I wanted to do similar refactors elsewhere but couldn't actually find
any other obvious places where we were using a target type to do the
work of `ExtractParam`.
> http: use `ExtractParam` in `NewNormalizeUri`

- linkerd/app/core/src/classify.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/http-classify/src/lib.rs
- linkerd/http-classify/src/service.rs
We have no need for a one-off trait for the response classificatino module. This change removes the `CanClassify` trait and updates the `NewClassify` module to take an `ExtractParam` for greater flexibility. `app::core` is updated with type aliases for our current uses.
> http: Replace `classify::CanClassify` with `Param`

- linkerd/proxy/http/src/timeout.rs
* Add comparison impls for `ResponseTimeout`;
* Use `ExtractParam` to build `ResponseTimeout` values.
> http: Improve timeout module

- linkerd/app/outbound/src/http/logical.rs
- linkerd/proxy/http/src/header_from_target.rs
To allow callers of `NewHeaderFromTarget` to provide bespoke param implementations, this change updates the module to use `ExtractParam` instead of `Param`.
> Use `ExtractParam` in `http::NewHeaderFromTarget`

- linkerd/app/admin/src/stack.rs
- linkerd/app/gateway/src/http/tests.rs
- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/detect/tests.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/metrics/authz.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/discover.rs
- linkerd/app/inbound/src/policy/http.rs
- linkerd/app/inbound/src/policy/http/tests.rs
- linkerd/app/inbound/src/policy/store.rs
- linkerd/app/inbound/src/policy/tcp.rs
- linkerd/app/inbound/src/policy/tcp/tests.rs
Depends on #2186.
Currently, the `linkerd-app-inbound` crate's `GetPolicy` trait performs lookups for `OrigDstAddr`s. This is not strictly correct: the `OrigDstAddr` newtype should specifically represent an address that was returned by a `getsockopt(..., SO_ORIGINAL_DST, ...)` call, and in the case of the inbound direct stack, the "original dst address" passed to `GetPolicy` may actually be synthesized from a port override in the `TransportHeader`. Therefore, it would be nicer if we had a `LookupAddr` type specifically representing an address used as an argument for policy lookups, analogous to the `profiles::LookupAddr` newtype used on the outbound side. See [this comment][1] for details.
Therefore, this branch makes the following changes:
- Policy types (e.g. `ServerPolicy`, …
> inbound: refactor newtypes for policy addresses

- .github/workflows/fuzzers.yml
- .github/workflows/nightly.yml
Currently, our nightly builds are failing due to the new warning `opaque_hidden_inferred_bound`, which triggers when an opaque type (`impl Trait`) in an associated type position does not explicitly include the associated type's trait bounds (e.g. returning a `Service<Future = impl Send, ...>`) or similar.
Unfortunately, we cannot simply change our code to make the trait bound's type explicit, as changing `impl Send` to
`impl Future<...> + Send` in this position results in a surprising error which I don't think is correct:
```
error[E0277]: `impl std::marker::Send` is not a future
--> linkerd/app/outbound/src/http/logical.rs:97:30
|
97 |                     Future = impl Future<Output = Result<http::Response<http::BoxBody>, Error>> + Send,
| …
```
> allow `opaque_hidden_inferred_bound` warning on nightly

- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/logical/policy.rs
- linkerd/app/outbound/src/http/logical/profile.rs
- linkerd/app/outbound/src/opaq/logical.rs
- linkerd/distribute/src/cache.rs
- linkerd/distribute/src/lib.rs
- linkerd/distribute/src/stack.rs
- linkerd/proxy/api-resolve/src/resolve.rs
The `BackendCache` module currently produces `NewDistribute` instances. This does not allow any other layers to be insertedb between the distribution decision and the caching decision.
To support per-route-backend filters, we need to separate these modules.
This change updates `BackendCache` as `NewBackendCache` and adds a basic service to extract targets from the cache.
`NewDistribute` is updated so that it builds new inner services instead of using the cache directly. The distribution layers are moved up into the route stack to prepare for additional filters being applied.
> outbound: Decouple backend caching from request distribution

- Cargo.lock
- linkerd/proxy/client-policy/Cargo.toml
- linkerd/proxy/client-policy/src/grpc.rs
- linkerd/proxy/client-policy/src/http.rs
- linkerd/proxy/client-policy/src/lib.rs
- linkerd/proxy/client-policy/src/opaq.rs
There's some pretty obtuse code to render route iterators. This change avoids this by passing around a hash set to collect backends into. This is sufficient, especially, as this is all handled internally to the crate.
> client-policy: Simplify route backend collection.

- Cargo.lock
- Cargo.toml
- linkerd/proxy/client-policy/Cargo.toml
- linkerd/proxy/client-policy/src/grpc.rs
- linkerd/proxy/client-policy/src/http.rs
- linkerd/proxy/client-policy/src/lib.rs
- linkerd/proxy/client-policy/src/opaq.rs
This branch adds functions to the `linkerd-proxy-client-policy` crate for converting the `linkerd2-proxy-api` outbound policy protobuf types into the proxy's internal representations. These are not used in this branch, but will be used in subsequent changes that actually wire up outbound policy discovery.
This change was factored out from #2265, so that it can be reviewed independently of the rest of the client policy discovery plumbing.
Note that this branch changes the `linkerd2-proxy-api` dependency to a Git dep on the outbound policy branch (linkerd/linkerd2-proxy-api#165), as the new APIs have not yet been published.
> client-policy: add protobuf conversion

- linkerd/app/inbound/src/policy/api.rs
- linkerd/app/inbound/src/policy/config.rs
- linkerd/app/inbound/src/server.rs
- linkerd/app/src/env.rs
- linkerd/app/src/lib.rs
- linkerd/app/src/policy.rs
Currently, configuration for the policy controller client is part of the `linkerd_app_inbound` crate's `Config` struct. This is because only the inbound proxy currently communicates with the policy controller.
In order to change the outbound side of the proxy to resolve client policies from the new `OutboundPolicy` API, the outbound proxy will now also need a policy controller client. Preferrably, both the client configuration and the actual client connection(s) should be shared between both halves of the proxy, similar to how the destination controller client is shared by both the inbound and outbound proxies.
Therefore, this branch pulls the shared policy client configuration out of the inbound config and onto the top-level `linkerd_app` crate's `Config` struct. The shape of the …
> separate policy client config from `inbound::Config`

- linkerd/app/gateway/src/lib.rs
- linkerd/app/gateway/src/server.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/discover/tests.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/policy.rs
- linkerd/app/outbound/src/policy/api.rs
- linkerd/app/outbound/src/sidecar.rs
- linkerd/app/outbound/src/tcp.rs
By avoiding a dedicated param value type, we can more flexibly instrument discovery!
> Simplify outbound discovery target types

- justfile
The justfile does not properly escape tags with multiple slashes.
This change updates the sed command to use a global replace.
> just: Fix docker tag formatting

- linkerd/app/outbound/src/http/logical/policy.rs
- linkerd/app/outbound/src/sidecar.rs
The new policy router currently reports a numeric authority when using policy routes. In some cases, we have a named concrete address for the load balancer. In the vast majority of cases, this address is the same as the logical service's.
For now, let's use concrete addresses for telemetry. This will help minimize regressions while we figure how to move telemetry forward.
> outbound: Report concrete authorities for policies

- Cargo.lock
- linkerd/app/gateway/Cargo.toml
- linkerd/app/gateway/src/lib.rs
- linkerd/app/gateway/src/server.rs
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/sidecar.rs
- linkerd/app/src/lib.rs
Depends on #2314.
Currently, the gateway stack does not resolve client policies, and only
uses service profiles for client-side policy discovery. This branch
updates the gateway proxy to also perform client policy discovery,
similarly to the outbound proxy.
Because all outbound stacks, including the one constructed by the
gateway, will now discover client policies, the client policy `Receiver`
in the `Discovery` type, which is currently an `Option`, can now be made
non-optional. This simplifies some code a little bit and removes some
`expect`s.
> gateway: discover client policies from the policy controller

- linkerd/app/outbound/src/http/logical/policy/router.rs
PR #2313 changed client policies with the load balancer dispatch type to report the load balancer's destination address as the "authority" label, rather than the numeric authority the policy was discovered for. However, this change was accidentally undone when merging PR #2260, which moved the code where the authority label is generated to a different file.
This PR changes it back, so that the discovered concrete destination address should still be reported as the "authority" metrics label.
> outbound: fix `Balance::Dispatch` "authority" labels

- linkerd/app/gateway/src/discover.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/gateway/src/server.rs
This branch moves the `Gateway::discover` method from `gateway/src/server.rs` into its own file. This is to prepare for future changes that will add more discovery-related logic to the gateway proxy, which made sense to put in its own module (see #2333 for details). In addition, I renamed the `Gateway::discover` method to `Gateway::resolver`, for consistency with the similar method on `Outbound`.
> gateway: move discovery resolver into its own file

- linkerd/stack/src/failfast.rs
- linkerd/stack/src/gate.rs
To implement circuit breakers, we want to use the gate to control whether or not a service is available to callers. When a service is coming out of a failed state, we may want to admit a limited number of requests through before going back to an unfettered state.
To support this, this change updates the `Gate` service to be backed by a `tokio::sync::watch` channel so that each side of the gate channel can communicate state updates.
`gate::Tx::closed` is renamed to `gate::Tx::lost` to avoid ambiguity.
> gate: Support admitting a limited number of requests

- Cargo.lock
- linkerd/app/core/Cargo.toml
- linkerd/app/core/src/classify.rs
- linkerd/app/core/src/metrics.rs
- linkerd/app/integration/src/tests/profiles.rs
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend.rs
- linkerd/app/outbound/src/http/logical/policy/router.rs
- linkerd/app/outbound/src/http/logical/policy/tests.rs
- linkerd/app/test/src/resolver/client_policy.rs
- linkerd/proxy/client-policy/Cargo.toml
- linkerd/proxy/client-policy/src/grpc.rs
- linkerd/proxy/client-policy/src/http.rs
- linkerd/proxy/client-policy/src/lib.rs
- linkerd/proxy/client-policy/src/opaq.rs
* 408457ad Carve out space in the policy API for a "failure policy"
* 2e165e05 classify: Replace SuccessOrFailure with Result
* 6af16e29 Update classifier to reuse clientpolicy response status/code types
* 60a61d96 Configure request classification from client policy routes
> Configure response classifiers from ClientPolicy routes

- linkerd/proxy/client-policy/src/grpc.rs
- linkerd/proxy/client-policy/src/http.rs
- linkerd/proxy/client-policy/src/lib.rs
- linkerd/proxy/client-policy/src/opaq.rs
Due to an oversight in the code for converting the proxy API `OutboundPolicy` protobuf types into the proxy's internal representations, `RouteBackend`s are currently constructed with the _route_'s metadata, rather than the metadata for that individual backend. This is incorrect, so this branch fixes that.
Because the functions for converting the protobuf types to `RouteBackend`s and `RouteDistribution`s no longer need to have the route's `Arc<Meta>` passed in, some of these functions have been changed to `TryFrom` implementations.
> client-policy: `RouteBackend`s use the backend's metadata

- Cargo.lock
- linkerd/app/core/Cargo.toml
- linkerd/app/core/src/classify.rs
- linkerd/http-classify/Cargo.toml
- linkerd/http-classify/src/lib.rs
- linkerd/proxy/http/Cargo.toml
- linkerd/proxy/http/src/classify.rs
- linkerd/proxy/http/src/classify/channel.rs
- linkerd/proxy/http/src/classify/gate.rs
- linkerd/proxy/http/src/classify/insert.rs
- linkerd/proxy/http/src/lib.rs
This branch introduces middleware for opening and closing a `Gate` middleware based on HTTP response classification. The `BroadcastClassification` service applies an HTTP response classifier to each request, and sends the classification over a channel. The `NewClassifyGate` middleware constructs stacks containing `BroadcastClassification` and `Gate` middleware. In conjunction with a _failure accrual policy_, these middleware allow response classification results to determine whether a service stack is available, implementing _request-level HTTP circuit breaking_.
Failure accrual policies are determined by the `ExtractParam` implementation provided to the `NewClassifyGate` layer. This type must provide a `classify::gate::Params` type containing a `mpsc::Sender` for the response …
> add `NewClassifyGate` and `BroadcastClassification` middleware

- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/logical/policy/router.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/proxy/client-policy/src/lib.rs
When a `backendRef` in an HTTPRoute references a valid Service name
which doesn't currently exist in the cluster, the policy controller
constructs a synthesized backend with a `failureInjector` filter, so
that traffic sent to the invalid backend will fail with a descriptive
error message, and any other backends in the route will still work
normally. Because the backend doesn't exist, there is no reasonable
value for the policy controller to set as the backend's `dispatcher`
field in the OutboundPolicy proto.
Unfortunately, however, the proxy currently rejects any OutboundPolicy
which has a backend without a populated `dispatcher` field. This means
that when an OutboundPolicy has one backend that has no `dispatcher`,
the proxy will synthesize an invalid policy that fails all traffic, …
> client-policy: accept backends with empty `dispatcher` fields

- Cargo.lock
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/breaker.rs
- linkerd/app/outbound/src/http/breaker/consecutive_failures.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/exp-backoff/src/lib.rs
- linkerd/proxy/client-policy/Cargo.toml
- linkerd/proxy/client-policy/src/lib.rs
- linkerd/stack/Cargo.toml
- linkerd/stack/src/gate.rs
Depends on https://github.com/linkerd/linkerd2-proxy/pull/2354.
This branch introduces a `ConsecutiveFailures` failure accrual policy
which marks an endpoint as unavailable if a given number of failures
occur in a row without any successes. Once the endpoint is marked as
failing, it is issued a single probe request after a delay. If the probe
succeeds, the endpoint transitions back to the available state.
Otherwise, it remains unavailable, with subsequent probe requests being
issued with an exponential backoff. The consecutive failures failure
accrual policy was initially implemented in PR #2334 by @olix0r.
A new `FailureAccrual::ConsecutiveFailures` variant is added in
`linkerd2-proxy-client-policy` for configuring the consecutive failures
failure accrual policy. The construction of …
> add `ConsecutiveFailures` failure accrual policy

- Cargo.lock
- linkerd/app/integration/src/policy.rs
- linkerd/app/integration/src/tests/client_policy.rs
- linkerd/proxy/client-policy/src/grpc.rs
- linkerd/proxy/client-policy/src/http.rs
- linkerd/proxy/client-policy/src/lib.rs
This branch updates the proxy to configure failure accrual policies from
the OutboundPolicy API. It updates the dependency on
`linkerd2-proxy-api` to include changes from
linkerd/linkerd2-proxy-api#223, which adds failure accrual configuration
to the `Protocol::Http1`, `Protocol::Http2`, and `Protocol::Grpc`
variants.
Currently, `ConsecutiveFailures` (added in #2357) is the only supported
failure accrual policy. If the proxy API does not configure a failure
accrual policy, failures are not accrued, and endpoints do not become
unavailable due to failure accrual.
> configure failure accrual from the `OutboundPolicy` API

- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/logical/tests.rs
- linkerd/stack/src/gate.rs
This branch adds a stack test in `linkerd_app_outbound` for the
consecutive-failures failure accrual policy. This test builds the HTTP
logical and concrete stacks and tests their behavior using a mocked
`tower::Service` as the endpoint stack, and a mock stack target type and
destination resolver. Because these stack tests do not perform IO,
execute in a single thread, and use the paused Tokio timer, they should
be fully deterministic, minimizing potential flaky failures. However, we
are still testing enough of the stack to exercize the circuit-breaking
functionality integrated with other components of the proxy.
The test added in this branch exercises only the behavior of a single
concrete stack (one backend). It tests that the backend's circuit
breaker trips when the configured number of …
> outbound: add failure accrual test, fix `Gate`s not becoming ready

- linkerd/app/outbound/src/http/breaker/consecutive_failures.rs
- linkerd/app/outbound/src/http/concrete.rs
There are no explicit indications of failure accrual related behavior.
This change adds INFO-level logs when a failure accrual breaker is
tripped or reeopened. These log messages are scoped within the
'endpoint' log context so that log lines include endpoint and balancer
addresses.
INFO balance{addr=logical.test.svc.cluster.local:666}:endpoint{addr=192.0.2.41:666}:consecutive_failures: linkerd_app_outbound::http::breaker::consecutive_failures: Consecutive failure-accrual breaker closed
INFO balance{addr=logical.test.svc.cluster.local:666}:endpoint{addr=192.0.2.41:666}:consecutive_failures: linkerd_app_outbound::http::breaker::consecutive_failures: Consecutive failure-accrual breaker reopened
> outbound: Emit INFO-level logs on failure accrual changes

- linkerd/app/admin/src/stack.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/inbound/src/metrics.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/metrics.rs
This helps avoid a bug with rust-analyzer and is generally clearer.
> app: Rename Metrics types as InboundMetrics and OutboundMetrics

- Cargo.lock
- linkerd/app/admin/src/stack.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/inbound/src/metrics.rs
- linkerd/app/integration/src/policy.rs
- linkerd/app/integration/src/tests/client_policy.rs
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/logical/policy.rs
- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend/count_reqs.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend/metrics.rs
- linkerd/app/outbound/src/http/logical/policy/router.rs
- linkerd/app/outbound/src/http/logical/policy/tests.rs
- linkerd/app/outbound/src/http/logical/tests.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/metrics.rs
- linkerd/app/outbound/src/sidecar.rs
- linkerd/app/test/src/resolver/client_policy.rs
- linkerd/proxy/client-policy/src/lib.rs
When performing policy-based routing, proxies may dispatch requests through per-route backend configurations. In order to illustrate how routing rules apply and how backend distributions are being honored, this change adds two new metrics:
* `outbound_http_route_backend_requests_total`; and
* `outbound_grpc_route_backend_requests_total`
Each of these metrics includes labels that identify a routes parent (i.e. a Service), the route resource being used, and the backend resource being used.
This implementation does NOT implement any form of metrics eviction for these new metrics. This is tolerable for the short term as the cardinality of services and routes is generally much less than the cardinality of individual endpoints (where we do require timeout/eviction for metrics).
> outbound: Report per-route-backend request count metrics

- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/logical/profile.rs
PR #2250 removed the `l5d-dst-canonical` header from ServiceProfile requests. This header is used by the inbound proxy for telemetry purposes, so removing it and not putting it back broke ServiceProfile route metrics. This commit adds a layer for setting this header to the service profile route stack.
We can also add the header for non-ServiceProfile requests if that's desirable...I'll have to look into whether it is. This commit should, at least, fix the existing ServiceProfile route metrics.
> outbound: add `l5d-dst-canonical` to requests with ServiceProfiles

- Cargo.lock
- linkerd/app/outbound/src/http/breaker.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/concrete/metrics.rs
- linkerd/app/outbound/src/http/concrete/tests.rs
- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend/metrics.rs
- linkerd/app/outbound/src/metrics.rs
- linkerd/proxy/balance/Cargo.toml
- linkerd/proxy/balance/src/gauge_endpoints.rs
- linkerd/proxy/balance/src/lib.rs
- linkerd/proxy/http/src/balance.rs
It's not currently possible to know how many endpoints are in a balancer. This change adds an `outbound_http_balancer_endpoints` gauge that exposes the number of endpoints a balancer has by their current readiness status.
Note that in the concrete stack we do not currently differentiate between gRPC and HTTP backends, so all balancers are exposed under this single metric.
> outbound: Report HTTP balancer endpoint gauges

- Cargo.lock
- Cargo.toml
- linkerd/app/inbound/Cargo.toml
- linkerd/app/integration/Cargo.toml
- linkerd/app/outbound/Cargo.toml
- linkerd/http-route/Cargo.toml
- linkerd/proxy/api-resolve/Cargo.toml
- linkerd/proxy/client-policy/Cargo.toml
- linkerd/proxy/identity-client/Cargo.toml
- linkerd/proxy/server-policy/Cargo.toml
- linkerd/proxy/tap/Cargo.toml
- linkerd/service-profiles/Cargo.toml
This branch updates the dependency on `linkerd2-proxy-api` to use v0.9.0 from `crates.io` rather than via a Git dependency.
> update `linkerd2-proxy-api` to v0.9.0 from crates.io

- linkerd/app/outbound/src/metrics.rs
d6f20a6 added a new `outbound_http_balancer_endpoints` gauge, but omitted it from metrics export. This change fixes this deficiency to ensure that this metric is rendered.
> outbound: Export balancer endpoints gauges

- Cargo.lock
The DOS mitigation changes in `h2` v0.3.17 inadvertantly introduced a potential panic (hyperium/h2#674). Version 0.3.18 fixes this, so we should bump the proxy's dependency to avoid panics.
> build(deps): bump `h2` to v0.3.18

- linkerd/app/integration/src/controller.rs
- linkerd/app/integration/src/tests/transparency.rs
- linkerd/app/outbound/src/sidecar.rs
Currently, the outbound proxy determines whether or not to perform
protocol detection based on the presence of the `opaque_protocol` field
on the resolved `ServiceProfile` from the Destination controller.
However, the `OutboundPolicy` resolved from the policy controller also
contains a `proxy_protocol` field that indicates what protocol should be
used for this destination. While the proxy uses the HTTPRoutes from the
`OutboundPolicy`'s `proxy_protocol`, it does _not_ take into account the
`proxy_protocol` when determining whether or not to perform protocol
detection. This can result in the outbound proxy performing protocol
detection on connections to destinations that have been marked as
opaque.
This branch modifies the outbound proxy to use the `proxy_protocol` from
the …
> outbound: determine protocol based on `OutboundPolicy`

- Dockerfile
- linkerd/tracing/src/lib.rs
Since upstream has yet to release a version with PR bluejekyll/trust-dns#1881, this commit changes the proxy's default log level to silence warnings from `trust_dns_proto` that are generally spurious.
See linkerd/linkerd2#10123 for details.
> set default `trust_dns` log level to `ERROR`

- linkerd/app/outbound/src/http/logical/tests.rs
Looks like we accidentally merged PR #2375 without a CI build against the latest state of `main`. In the meantime since #2375 was last built on CI, PR #2374 added an additional metadata field to `policy::HttpParams`, which the `HttpParams` constructed in the test added from #2375 doesn't populate. Therefore, merging this PR broke the build. Whoops!
This commit populates the `meta` field, fixing it.
> outbound: add missing `meta` field in test policy

- Cargo.lock
- linkerd/app/Cargo.toml
- linkerd/app/inbound/Cargo.toml
- linkerd/app/inbound/src/policy/config.rs
- linkerd/app/inbound/src/policy/store.rs
- linkerd/app/inbound/src/policy/tcp/tests.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/app/integration/src/tests/transparency.rs
- linkerd/app/src/env.rs
The proxy injector populates an environment variable,
`LINKERD2_PROXY_INBOUND_PORTS_DISABLE_PROTOCOL_DETECTION`, with a list
of all ports marked as opaque. Currently, however, _the proxy _does not
actually use this environment variable_. Instead, opaque ports are
discovered from the policy controller. The opaque ports environment
variable was used only when running in the "fixed" inbound policy mode,
where all inbound policies are determined from environment variables,
and no policy controller address is provided. This mode is no longer
supported, and the policy controller address is now required, so the
`LINKERD2_PROXY_INBOUND_PORTS_DISABLE_PROTOCOL_DETECTION` environment
variable is not currently used to discover inbound opaque ports.
There are two issues with the current state of …
> inbound: determine default policies using the opaque ports env var

- deny.toml
The proc-macro ecosystem is in the middle of a migration from `syn` v1 to `syn` v2. Some crates (such as `tokio-macros`, `async-trait`, `tracing-attributes`, etc) have been updated to v2, while others haven't yet. This means that `cargo deny` will not currently permit us to update some of those crates to versions that depend on `syn` v2, because they will create a duplicate dependency.
Since `syn` is used by proc-macros (executed at compile time), duplicate versions won't have an impact on the final binary size. Therefore, it's fine to allow both v1 and v2 to coexist while the ecosystem is still being gradually migrated to the new version.
> chore: allow `syn` v1 and v2 to coexist peacefully

- linkerd/proxy/resolve/src/recover.rs
This emits an `unused_mut` warning on the latest nigthly, fixing the fuzzing and codecov CI builds. This commit removes it.
> recover: remove unused `mut`

- Cargo.lock
- linkerd/app/inbound/Cargo.toml
- linkerd/app/integration/Cargo.toml
- linkerd/app/integration/src/policy.rs
- linkerd/app/integration/src/tests/client_policy.rs
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/router.rs
- linkerd/app/outbound/src/http/logical/policy/tests.rs
- linkerd/app/outbound/src/http/logical/tests.rs
- linkerd/app/test/src/resolver/client_policy.rs
- linkerd/http-route/Cargo.toml
- linkerd/proxy/api-resolve/Cargo.toml
- linkerd/proxy/client-policy/Cargo.toml
- linkerd/proxy/client-policy/src/grpc.rs
- linkerd/proxy/client-policy/src/http.rs
- linkerd/proxy/client-policy/src/lib.rs
- linkerd/proxy/client-policy/src/opaq.rs
- linkerd/proxy/identity-client/Cargo.toml
- linkerd/proxy/server-policy/Cargo.toml
- linkerd/proxy/tap/Cargo.toml
- linkerd/service-profiles/Cargo.toml
The latest proxy-api release, v0.10.0, adds fields to the
`OutboundPolicies` API for configuring HTTP request timeouts, based on
the proposed changes to HTTPRoute in kubernetes-sigs/gateway-api#1997.
This branch updates the proxy-api dependency to v0.10.0 and adds the new
timeout configuration fields to the proxy's internal client policy
types. In addition, this branch adds a timeout middleware to the HTTP
client policy stack, so that the timeout described by the
`Rule.request_timeout` field is now applied.
Implementing the `RouteBackend.request_timeout` field with semantics as
close as possible to those described in GEP-1742 will be somewhat more
complex, and will be added in a separate PR. The reason for this
complexity is that, as described in GEP-1742, the
`timeouts.backendRequest` …
> outbound: implement `OutboundPolicies` route request timeouts

- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend.rs
- linkerd/proxy/client-policy/src/lib.rs
PRs #2418 and #2419 add per-route and per-backend request timeouts
configured by the `OutboundPolicies` API to the `MatchedRoute` and
`MatchedBackend` layers in the outbound `ClientPolicy` stack,
respectively. This means that — unlike in the `ServiceProfile` stack —
two separate request timeouts can be configured in `ClientPolicy`
stacks. However, because both the `MatchedRoute` and `MatchedBackend`
layers are in the HTTP logical stack, the errors emitted by both
timeouts will have a `LogicalError` as their most specific error
metadata, meaning that the log messages and `l5d-proxy-error` headers
recorded for these timeouts do not indicate whether the timeout that
failed the request was the route request timeout or the backend request
timeout.
In order to ensure this information is …
> outbound: add backend and route metadata to errors

- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/proxy/client-policy/src/lib.rs
When the outbound proxy resolves an outbound policy from the policy
controller's `OutboundPolicies` API, the policy controller may return an
error with the `grpc-status` code `NotFound` in order to indicate that
the destination is not a ClusterIP service. When this occurs, the proxy
will fall back to either using a ServiceProfile, if the ServiceProfile
contains non-trivial configuration, or synthesizing a default client
policy from the ServiceProfile.
However, when the outbound proxy is configured to run in ingress mode,
the fallback behavior does not occur. Instead, the ingress mode proxy
treats any error returned by the policy controller's `OutboundPolicies`
API as fatal. This means that when an ingress controller performs its
own load-balancing and opens a connection to a pod IP …
> outbound: handle `NotFound` client policies in ingress mode

- linkerd/app/outbound/src/discover.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/proxy/client-policy/src/lib.rs
When the outbound proxy resolves an outbound policy from the policy controller's `OutboundPolicies` API, the policy controller may return an error with the `grpc-status` code `NotFound` in order to indicate that the destination is not a ClusterIP service. When this occurs, the proxy will fall back to either using a ServiceProfile, if the ServiceProfile contains non-trivial configuration, or synthesizing a default client policy from the ServiceProfile.
However, when the outbound proxy is configured to run in ingress mode, the fallback behavior does not occur. Instead, the ingress mode proxy treats any error returned by the policy controller's `OutboundPolicies` API as fatal. This means that when an ingress controller performs its own load-balancing and opens a connection to a pod IP …
> outbound: handle `NotFound` client policies in ingress mode (#2431)

- .github/workflows/release.yml
- Cargo.lock
- Dockerfile
- justfile
- linkerd/app/core/Cargo.toml
- linkerd/app/core/build.rs
- linkerd/app/core/src/metrics.rs
- linkerd/app/core/src/telemetry/build_info.rs
- linkerd2-proxy/src/main.rs
The proxy currently emits very little useful version information.
This change updates the proxy to support new build-time environment variables that are used to report version information:
* LINKERD2_PROXY_BUILD_TIME
* LINKERD2_PROXY_VENDOR
* LINKERD2_PROXY_VERSION
Additionally, several pre-existing Git-oriented metadata have been removed, as they were generally redundant or uninformative. The Rustc version has also been removed (since it has no real user-facing value and can be easily determined by the version/tag).
> Emit distinguishable version info

- Cargo.lock
- Cargo.toml
- linkerd/app/inbound/Cargo.toml
- linkerd/app/integration/Cargo.toml
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend.rs
- linkerd/app/outbound/src/http/logical/policy/route/filters.rs
- linkerd/http-route/Cargo.toml
- linkerd/http-route/src/http/filter/modify_header.rs
- linkerd/proxy/api-resolve/Cargo.toml
- linkerd/proxy/client-policy/Cargo.toml
- linkerd/proxy/client-policy/src/http.rs
- linkerd/proxy/identity-client/Cargo.toml
- linkerd/proxy/server-policy/Cargo.toml
- linkerd/proxy/tap/Cargo.toml
- linkerd/service-profiles/Cargo.toml
Add support for the response header modifier, which was added to the proxy API in https://github.com/linkerd/linkerd2-proxy-api/pull/251
> Add suport for response header filter

- linkerd/app/src/env.rs
In 2.13, the default inbound and outbound HTTP request queue capacity decreased from 10,000 requests to 100 requests (in PR #2078). This change results in proxies shedding load much more aggressively while under high load to a single destination service, resulting in increased error rates in comparison to 2.12 (see linkerd/linkerd2#11055 for details).
This commit changes the default HTTP request queue capacities for the inbound and outbound proxies back to 10,000 requests, the way they were in 2.12 and earlier. In manual load testing I've verified that increasing the queue capacity results in a substantial decrease in 503 Service Unavailable errors emitted by the proxy: with a queue capacity of 100 requests, the load test described [here] observed a failure rate of 51.51% of requests, …
> Increase HTTP request queue capacity

- linkerd/app/src/env.rs
This backports #2449 to the v2.203.x branch.
In 2.13, the default inbound and outbound HTTP request queue capacity decreased from 10,000 requests to 100 requests (in PR #2078). This change results in proxies shedding load much more aggressively while under high load to a single destination service, resulting in increased error rates in comparison to 2.12 (see linkerd/linkerd2#11055 for details).
This commit changes the default HTTP request queue capacities for the inbound and outbound proxies back to 10,000 requests, the way they were in 2.12 and earlier. In manual load testing I've verified that increasing the queue capacity results in a substantial decrease in 503 Service Unavailable errors emitted by the proxy: with a queue capacity of 100 requests, the load test described [here] …
> [backport] Increase HTTP request queue capacity (#2449)

- Cargo.lock
- Cargo.toml
- deny.toml
- linkerd/meshtls/boring/Cargo.toml
The `linkerd-meshtls-boring` crate currently uses a Git dependency on `boring` and `tokio-boring`. This is because, when this crate was initially introduced, the proxy required unreleased changes to these crates. Now, however, upstream has published all the changes we depended on (this happened ages ago), and we can depend on these libraries from crates.io.
This branch removes the Git deps and updates to v3.0.0 of `boring`/`tokio-boring`. I've also changed the `cargo-deny` settings to no longer allow Git deps on these crates, as we no longer depend on them from Git.
> build(deps): use published version of `boring`

- Cargo.lock
- Cargo.toml
- deny.toml
- linkerd/meshtls/rustls/Cargo.toml
- linkerd/meshtls/rustls/src/creds/store.rs
- linkerd/meshtls/rustls/src/server.rs
This commit changes the `linkerd-meshtls-rustls` crate to use the upstream `rustls-webpki` crate, maintained by Rustls, rather than our fork of `briansmith/webpki` from GitHub. Since `rustls-webpki` includes the change which was the initial motivation for the `linkerd/webpki` fork (rustls/webpki#42), we can now depend on upstream.
> use `rustls-webpki` instead of `linkerd/webpki`

- Cargo.lock
- Cargo.toml
- deny.toml
Now that [v0.101.5 of `rustls-webpki`][1] has been [published][2], we can now depend on the crate from crates.io. This allows us to remove the Git dependency on the branch preparing that release to be published, which allows us to remove the allowance for Git dependencies in the `cargo-deny` config.
[1]: https://github.com/rustls/webpki/releases/tag/v%2F0.101.5
[2]: https://crates.io/crates/rustls-webpki/0.101.5
> meshtls: use published `rustls-webpki` v0.101.5

- Cargo.lock
- Cargo.toml
- deny.toml
- linkerd/meshtls/rustls/Cargo.toml
- linkerd/meshtls/rustls/src/creds/store.rs
- linkerd/meshtls/rustls/src/server.rs
This branch backports PRs #2465 and #2470 to the `release/v2.203` branch.
> backport #2465 and #2470 to v2.203

- Cargo.lock
- deny.toml
- linkerd/app/integration/Cargo.toml
- linkerd/app/integration/src/identity.rs
- linkerd/meshtls/rustls/Cargo.toml
- linkerd/meshtls/rustls/src/creds.rs
- linkerd/meshtls/rustls/src/creds/receiver.rs
- linkerd/meshtls/rustls/src/creds/store.rs
Currently, the proxy [depends on an outdated version of `rustls`][1], v0.20.8. The `rustls` dependency is via our dependency on `tokio-rustls` v0.23.4; we don't have a direct `rustls` dependency, in order to ensure that the version of `rustls` is always the same version as used by `tokio-rustls`. `rustls` also has a dependency on `webpki`, and v0.20.x of `rustls` uses the original `webpki` crate, rather than the `rustls-webpki` crate. So, unfortunately, because we have a transitive dep on `webpki` via `rustls`, PR linkerd/linkerd2-proxy#2465 did not remove _all_ `webpki` deps from our dependency tree, only the direct dependency.
This branch updates to `rustls` v0.21.x, which depends on `rustls-webpki` rather than `webpki`, removing the `webpki` dependency. This is accomplished by updating …
> meshtls: update to `rustls` v0.21.7

- Cargo.lock
- deny.toml
- linkerd/app/integration/Cargo.toml
- linkerd/app/integration/src/identity.rs
- linkerd/meshtls/rustls/Cargo.toml
- linkerd/meshtls/rustls/src/creds.rs
- linkerd/meshtls/rustls/src/creds/receiver.rs
- linkerd/meshtls/rustls/src/creds/store.rs
This branch cherry-picks #2472 onto `release/v2.203`.
Currently, the proxy [depends on an outdated version of `rustls`][1], v0.20.8. The `rustls` dependency is via our dependency on `tokio-rustls` v0.23.4; we don't have a direct `rustls` dependency, in order to ensure that the version of `rustls` is always the same version as used by `tokio-rustls`. `rustls` also has a dependency on `webpki`, and v0.20.x of `rustls` uses the original `webpki` crate, rather than the `rustls-webpki` crate. So, unfortunately, because we have a transitive dep on `webpki` via `rustls`, PR linkerd/linkerd2-proxy#2465 did not remove _all_ `webpki` deps from our dependency tree, only the direct dependency.
This branch updates to `rustls` v0.21.x, which depends on `rustls-webpki` rather than `webpki`, removing the …
> meshtls: update to `rustls` v0.21.7 (#2472)

- linkerd/app/core/src/metrics.rs
Fixes https://github.com/linkerd/linkerd2/issues/11449
The `grpc_status` metric label is rendered as a long form, human readable string value in the proxy metrics.  For example:
```
response_total{direction="outbound", [...], classification="failure",grpc_status="Unknown error",error=""} 1
```
This is because of the Display impl for Code.  We explicitly convert to an i32 so this renders as a number instead:
```
response_total{direction="outbound", [...] ,classification="failure",grpc_status="2",error=""} 1
```
> Render grpc_status metric label as number

- linkerd/proxy/balance/src/discover/buffer.rs
In 6d2abbc, we changed how outbound proxies process discovery updates. The prior implementation used a watchdog timeout to bound the amount of time an update stream could be full. With that change, when an update channel fills, the backpressure can extend to the destination controller's gRPC response stream.
To detect and avoid this harmful (and useless) backpressure, this change modifies the balancer's discovery processing stream to exit when the balancer has 1000 unprocessed discovery updates. A sufficiently scary warning is logged.
> balance: Log and fail stuck discovery streams.

- Cargo.lock
This commit updates the proxy's dependency on `rustix` in order to resolve a potential memory exhaustion issue when using the `rustix::fs::Dir` iterator with the `linux-raw` backend. This issue is described in GHSA-c827-hfw6-qwvm.
We currently depend on both `rustix` v0.36 and v0.37 as transitive deps, so this branch updates the v0.36 dep from v0.36.14 to v0.36.16, and the v0.37 dependency from v0.37.4 to v0.37.7.
Unfortunately, we weren't able to get Dependabot to bump these deps for us, because it no longer supports the legacy (non-TOML) `rust-toolchain` file (see #2487 for details). Therefore, we have to do this bump manually.
> build(deps): update `rustix` to v0.36.16/v0.37.7

- linkerd/stack/src/gate.rs
If `Gate` becomes ready, it assumes the inner service remains ready indefinitely.
Load balancers rely on lazy and redudant readiness checking to avoid disconnected endpoints.
This change fixes the Gate to ensure that the inner service is always polled whenever the gate is polled.
> gate: Detect disconnected inner services in readiness

- linkerd/app/core/src/metrics.rs
- linkerd/proxy/balance/src/discover/buffer.rs
`stable-2.14` is currently on proxy version v2.210.0. This branch backports #2484 and #2480 to v2.210.x.
> backports for stable release v2.210.1

- linkerd/app/outbound/src/http/breaker/consecutive_failures.rs
- linkerd/stack/src/failfast.rs
- linkerd/stack/src/gate.rs
The gate middleware controls a service's readiness so that it can exert backpressure. This is used, for instance, by the circuit breaker module so that an endpoint can go into an unavailable state after the breaker has been tripped and be marked available again as it recovers.
This change fixes a bug in that recovery scenario: when the gate is in a Limited state (i.e. when the circuit breaker puts an endpoint into Probation to test its availability), and caller (i.e. the balancer) is waiting for the endpoint to leave probation, the balancer may never be notified that the endpoint has left its probation state.
To fix this, we update the gate controller to definitively close its inner Semaphore when transitioning out of a limited state -- dropping the semaphore in the sender doesn't close …
> gate: Fix readiness deadlock

- linkerd/app/inbound/src/policy/api.rs
- linkerd/app/outbound/src/policy/api.rs
- linkerd/app/src/dst.rs
The controller client includes a recovery/backoff module that causes resolutions to be retried when an unexpected error is encountered. These events are only logged at debugging and trace log levels.
This change updates the destination controller recovery module to log unexpected errors. This will benefit both profile and endpoint resolution.
> dst: Log a warning when the controller clients receive an error

- Cargo.lock
- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/control.rs
- linkerd/app/inbound/Cargo.toml
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/outbound/src/http/endpoint/tests.rs
- linkerd/app/outbound/src/http/retry.rs
- linkerd/http-metrics/Cargo.toml
- linkerd/http-metrics/src/lib.rs
- linkerd/http-metrics/src/requests.rs
- linkerd/http-metrics/src/requests/service.rs
- linkerd/proxy/http/src/classify/insert.rs
ecaaf39 changed the proxy's behavior with regard to creating [default response classifiers][default]: the defaults used to support detecting gRPC response (regardless of the request properties).
To fix this, we modify the metrics module that uses responses classifiers to *require* them without inferring defaults. This enforces the intended usage pattern so that we do not silently and implicitly fall back to the default behavior. This requirement is only strictly enforced in development builds. In release builds, the prior defaulting behavior remains in place. This minimizes the difference from the existing behavior, especially if we hit untested cases where a hard failure would be untenable (especially in metrics code).
This change also updates the `NewClassify` module that inserts the …
> inbound: Fix gRPC response classification

- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/serve.rs
- linkerd/app/inbound/src/server.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/src/lib.rs
- linkerd/app/src/tap.rs
- linkerd/proxy/transport/src/addrs.rs
- linkerd/proxy/transport/src/lib.rs
- linkerd/proxy/transport/src/listen.rs
- linkerd/proxy/transport/src/orig_dst.rs
When the proxy's TCP server encounters an error (usually due to one of the connections failing, we log the error and the client's address. The server's address was omitted because it varies based on context that is not known in this module: in some cases it's the actual server address on the socket, but when proxying a connection it may be determined by the value retrieved from the SO_ORIGINAL_DST socket option.
To fix this, the server now requires that connection metadata be able to materialize an 'AddrPair' parameter that describes a client-server connection. The TCP listener impls are updated to satisfy this based on the appropriate metadata; and the TCP server consumes this type to include both client and server addresses in the relevant logs/contexts.
> Include server address in server error logs

- linkerd/app/inbound/src/policy/api.rs
- linkerd/app/outbound/src/policy/api.rs
- linkerd/app/src/dst.rs
This cherry-picks 920b2ddfbaa31541877801d181f546a0e27faaaf into `release/v2.210`, to be tagged as `release/2.210.2`, to be included in linkerd `stable-2.14.3`.
> Log a warning when the controller clients receive an error (#2499)

- linkerd/dns/name/src/name.rs
Before b4ff7d23e, our identity::Name type used a reference-counted dns::Name. This change restores this reference-counting behavior, moving it into the lower-level `dns::Name` type.
This generally helps to minimize allocation overhead for proxied traffic.
> Use reference-counted strings in dns::Name

- .github/list-crates.sh
- .github/workflows/check-each.yml
At some point, the check-each workflow broke (likely due to change in the action dependency we use to enumerate changed files).
This change fixes the script used to convert changed files to crate names so that the check-each workflows runs properly.
> ci: Fix check-each workflow

- .github/workflows/check-all.yml
- .github/workflows/check-each.yml
- .github/workflows/coverage.yml
- .github/workflows/deps.yml
- .github/workflows/fuzzers.yml
- .github/workflows/integration.yml
- .github/workflows/lint.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
We don't consume debuginfo from CI builds, so we can disable debug symbols in these builds.
The coverage test is also fixed to address a linking issue with the version of cargo-tarpaulin we have cached. The coverage workflow has all debuginfo enabled since it's used for coverage generation.
> ci: Turn off debuginfo in ci test builds

- .github/fuzzers-list.sh
- .github/list-crates.sh
- justfile
The fuzzer tests in CI were broken in CI by a change to the file-listing
action. This change fixes CI for fuzzer changes.
It does not actually fix the fuzzer suites.
> ci: Fix fuzzer listing

- .devcontainer/Dockerfile
The devcontainer nightly install leaves cargo in a bad state due to permissions issues in the docker setup. Let's just disable nightly for now (it can always be added at runtime).
> dev: Disable nightly install for now

- linkerd/app/src/env.rs
DEFAULT_OUTBOUND_TCP_QUEUE_CAPACITY was incorrectly set to 10 so that bursts of TCP connections could see EOF errors.
This change increases the value to match the HTTP queue capacity.
> Update DEFAULT_OUTBOUND_TCP_QUEUE_CAPACITY to 10K

- .github/workflows/check-all.yml
- .vscode/settings.json
- Cargo.lock
- Dockerfile
- deny.toml
- justfile
- linkerd/app/Cargo.toml
- linkerd/app/admin/Cargo.toml
- linkerd/app/admin/src/lib.rs
- linkerd/app/admin/src/pprof.rs
- linkerd/app/admin/src/server.rs
- linkerd/app/admin/src/stack.rs
- linkerd/app/src/env.rs
- linkerd/tracing/Cargo.toml
- linkerd2-proxy/Cargo.toml
This change introduces a new, optional /debug/pprof/profile endpoint to
the proxy's admin server. This endpoint is feature-gated and, initially,
it will not be included in release builds.
When the feature is enabled, profiling requests are only permitted over
the loopback interface.
The development Dockerfile is updated to prevent stripping debug
symbols so the pprof data is hydrated with debug symbols.
> admin: Add optional /debug/pprof/profile endpoint

- linkerd/app/core/src/control.rs
- linkerd/app/core/src/svc.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/logical/policy.rs
- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend.rs
- linkerd/app/outbound/src/http/logical/policy/router.rs
- linkerd/app/outbound/src/http/logical/profile.rs
- linkerd/app/outbound/src/opaq.rs
- linkerd/app/outbound/src/opaq/logical.rs
- linkerd/stack/src/box_future.rs
- linkerd/stack/src/box_service.rs
- linkerd/stack/src/lib.rs
tower::util::BoxCloneService doesn't implement Sync, which is necessary when we may want to share these services across threads (which is entirely the point of making a service cloneable, really).
This change replicates BoxCloneService as BoxCloneSyncService and updates many of Linkerd's stacks to return this new type.
This continues on the work begun in #2510 and #2514.
---
Building proxy with full debug symbols:
```
:; RUSTFLAGS='-C debuginfo=2' just profile=release build              
```
Before:
```
:; du -h target/x86_64-unknown-linux-gnu/release/linkerd2-proxy{,.dbg}
20M     target/x86_64-unknown-linux-gnu/release/linkerd2-proxy
1.5G    target/x86_64-unknown-linux-gnu/release/linkerd2-proxy.dbg
```
After:
```
:; du -h target/x86_64-unknown-linux-gnu/release/linkerd2-proxy{,.dbg}
20M …
```
> stack: Add BoxCloneSyncService

- .github/workflows/coverage.yml
- .github/workflows/integration.yml
- linkerd/app/integration/Cargo.toml
- linkerd/app/integration/src/tests/telemetry.rs
- linkerd/app/integration/src/tests/telemetry/tcp_errors.rs
Our coverage workflow only measures the coverage of integration tests, ignoring all of our unit tests and component tests. This is caused by our inclusion of tests that don't run in CI in the default integration test configuration.
In order to run coverage over all tests, we disable two flakey tests from the default integration test configuration. The tests that are flakey only in coverage are simply enabled. Instead, we'll tolerate test failures in our coverage reports. We'll trust that our tests are actually executed successfully outside of the coverage run.
> ci: Compute coverage over all tests

- Cargo.lock
- linkerd/stack/metrics/Cargo.toml
- linkerd/stack/metrics/src/service.rs
The stack metrics module cannot currently wrap services that need to implement Clone.
To fix this, we introduce an extra Arc that ensures we only count drops when all clones have been dropped.
> stack-metrics: Implement Clone for TrackService

- .github/workflows/coverage.yml
This should shave 2+ minutes off of coverage tests.
> ci: Fetch tarpaulin binary instead of compiling

- .codecov.yml
- .github/workflows/coverage.yml
In preparation for some larger changes to the proxy, this change enables codecov on main and on PRs that change code. We need to run coverage on main so that PRs have a meaningful comparison point.
We use the styfle/cancel-workflow-action to prevent multiple runs from clogging up Actions Runners.
We can adapt this configuration if it's too annoying, but it seems low risk to add for now.
> ci: Enable coverage on main and all PRs

- linkerd/app/outbound/src/http/logical/tests.rs
This change improves error handling and logging for hte outbound consecutive_failures_accrue test, especially imposing timeouts on requests that can hang when the functionality is broken.
> test: Cleanup consecutive_failures_accrue

- linkerd/app/integration/src/tests/discovery.rs
The outbound_balancer_waits_for_ready_endpoint test doesn't reliably demonstrate the behavior it is trying to test: we setup two identical endpoints, so our tests can't be sure that the response is coming from the correct endpoint.
This change updates this test to provide backends that return varied responses so we can ensure the desired behavior.
This change also improves the test's logging. The discovery test infrastructure is updated to allow overriding the logical service address. This aids disambiguating addresses in logs.
> test: Cleanup outbound_balancer_waits_for_ready_endpoint

- .codecov.yml
- Cargo.lock
- Cargo.toml
- deny.toml
- linkerd/app/Cargo.toml
- linkerd/app/core/Cargo.toml
- linkerd/app/gateway/Cargo.toml
- linkerd/app/inbound/Cargo.toml
- linkerd/app/inbound/fuzz/Cargo.toml
- linkerd/app/integration/Cargo.toml
- linkerd/app/outbound/Cargo.toml
- linkerd/app/test/Cargo.toml
- linkerd/exp-backoff/Cargo.toml
- linkerd/http-route/Cargo.toml
- linkerd/opencensus/Cargo.toml
- linkerd/proxy/api-resolve/Cargo.toml
- linkerd/proxy/client-policy/Cargo.toml
- linkerd/proxy/identity-client/Cargo.toml
- linkerd/proxy/server-policy/Cargo.toml
- linkerd/proxy/tap/Cargo.toml
- linkerd/service-profiles/Cargo.toml
- linkerd/tonic-watch/Cargo.toml
- linkerd/transport-header/Cargo.toml
- opencensus-proto/Cargo.toml
- opencensus-proto/src/gen/opencensus.proto.agent.trace.v1.rs
- opencensus-proto/src/gen/opencensus.proto.trace.v1.rs
- tools/Cargo.toml
* tokio 1.34
* tonic 0.10
* prost 0.12
* linkerd2-proxy-api 0.12 (linkerd/linkerd2-proxy-api#269)
> deps: Update tokio, tonic, and prost

- linkerd/proxy/balance/src/pool/p2c.rs
8222d6e86 removed the discovery module that logged changes.
The balancer's logging is changed to increase endpoint updates to INFO.
> balance: Restore INFO logging of balancer changes

- Cargo.lock
- Cargo.toml
- linkerd/app/Cargo.toml
- linkerd/app/inbound/Cargo.toml
- linkerd/app/inbound/src/policy/api.rs
- linkerd/app/inbound/src/policy/config.rs
- linkerd/app/inbound/src/server.rs
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/policy/api.rs
- linkerd/app/src/dst.rs
- linkerd/app/src/env.rs
- linkerd/app/src/lib.rs
- linkerd/app/src/policy.rs
- linkerd/proxy/api-resolve/Cargo.toml
- linkerd/proxy/api-resolve/src/resolve.rs
- linkerd/service-profiles/Cargo.toml
- linkerd/service-profiles/src/client.rs
- linkerd/tonic-stream/Cargo.toml
- linkerd/tonic-stream/src/lib.rs
When connecting to a control plane API, the API server can return an
HTTP response long before it returns the first stream response. To bound
this time, we now enforce timeouts so that failures may result in attempting
to use an alternate controller instances.
All controller response streams now use a generic gRPC middlware with
initial, idle, and lifetime timeouts. When an initial timeout is
encounterd, a DeadlineExceeded grpc status is synthesized. When the
other timeouts are encountered, the stream terminates gracefully.
These timeouts are configurable by the proxy injector. Timeouts are not
enabled without configuration:
* LINKERD2_PROXY_CONTROL_STREAM_INITIAL_TIMEOUT
* LINKERD2_PROXY_CONTROL_STREAM_IDLE_TIMEOUT
* LINKERD2_PROXY_CONTROL_STREAM_LIFETIME
Each of these parameters is …
> control: Enforce timeouts on response stream

- linkerd/app/inbound/src/policy/api.rs
- linkerd/app/outbound/src/policy/api.rs
- linkerd/app/src/dst.rs
When stream limits cause a graceful stream end, we should not log a warning.
> control: Avoid logging warnings on reconnect

- Cargo.lock
- linkerd/meshtls/rustls/Cargo.toml
The meshtls-rustls crate has an unneeded cyclic dependency onto meshtls. This change removes this unused dependency.
> cargo: Remove cyclic meshtls dependency

- linkerd/app/gateway/src/http.rs
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/concrete/balance.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/logical/policy.rs
- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend/count_reqs.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend/metrics.rs
- linkerd/app/outbound/src/http/logical/policy/router.rs
- linkerd/app/outbound/src/http/logical/policy/tests.rs
- linkerd/app/outbound/src/http/logical/tests.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/metrics.rs
- linkerd/app/outbound/src/sidecar.rs
- linkerd/pool/p2c/src/lib.rs
- linkerd/proxy/balance/gauge-endpoints/src/lib.rs
- linkerd/proxy/balance/queue/src/failfast.rs
- linkerd/proxy/balance/queue/src/lib.rs
- linkerd/proxy/balance/src/lib.rs
To help setup for adding neew route metrics to the outbound proxy, this change wires up route metrics registry infrastructure, porting the route backend metrics implementation to use prometheus-client instead of Linkerd's legacy metrics.
> outbound: Update route backend metrics implementation

- linkerd/app/src/env.rs
This change allows the proxy to be configured to use SPIRE
as it is credentials provider. There are three additional ENV
vars introduced: 
- `LINKERD2_PROXY_IDENTITY_SERVER_ID` - Configures the TLS Id of the proxy inbound server.
- `LINKERD2_PROXY_IDENTITY_SERVER_NAME` - Configures the server name of this proxy.
- `ENV_IDENTITY_SPIRE_SOCKET` - If this config is set, then the proxy will use Spire as the identity provider
For backward compatibility reasons if `ENV_IDENTITY_IDENTITY_LOCAL_NAME` is set both
tls id and server_name will be sourced from its value. If however it is not set, both `LINKERD2_PROXY_IDENTITY_SERVER_ID` and `LINKERD2_PROXY_IDENTITY_SERVER_NAME` are required. 
> config:add spire client config

- linkerd/app/outbound/src/http/handle_proxy_error_headers.rs
When an outbound client reads a response from a remote peer that includes the l5d-proxy-error header, it doesn't communicate this error state in logs, and it (incorrectly, according to the comments) leaves the l5d-proxy-error header on the response.
Furthermore, we currently _always_ emit a DEBUG log message "Remote proxy error", even when no error header is present.
This change updates the error handler to:
1. Emit 'Remote proxy error' messages at INFO level when the header is validly set;
2. Strip these headers when they are logged (i.e. to eliminate ambiguity and potential for double-logging).
Tests are updated to exercise the header removal logic.
> outbound: Log and remove l5d-proxy-error from responses

- linkerd/app/admin/src/stack.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/outbound/src/http/server.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/protocol.rs
- linkerd/proxy/http/src/lib.rs
- linkerd/proxy/http/src/server.rs
We plan to add defensive timeouts to the HTTP server to limit idle streams and connections. In preparation for this, we need to parameterize the server to accept these additonal configurations.
This change updates NewServeHttp to use an ExtractParam to build a Params struct for each server. In follow-up changes, the timeout configuration will be instrumented through this Params struct.
There are no functional changes in this commit.
> http: Parameterize NewServeHttp

- .checksec/amd64-gnu.json
- .checksec/amd64-musl.json
- .checksec/arm-gnu.json
- .checksec/arm-musl.json
- .checksec/arm64-gnu.json
- .checksec/arm64-musl.json
- Cargo.lock
- linkerd/dns/name/Cargo.toml
- linkerd/meshtls/rustls/Cargo.toml
- linkerd/meshtls/rustls/src/creds/store.rs
- linkerd/tls/Cargo.toml
This change updates the repo to uses the latest TLS dependencies.
> build(deps): Update rustls and ring

- Cargo.lock
:; cargo update
Updating crates.io index
Updating anyhow v1.0.79 -> v1.0.80
Updating base64 v0.21.5 -> v0.21.7
Updating bitflags v2.4.0 -> v2.4.2
Updating cc v1.0.83 -> v1.0.86
Updating cpufeatures v0.2.11 -> v0.2.12
Updating either v1.9.0 -> v1.10.0
Updating indexmap v2.1.0 -> v2.2.3
Updating ipnet v2.7.2 -> v2.9.0
Updating jemalloc-sys v0.5.3+5.3.0-patched -> v0.5.4+5.3.0-patched
Removing jobserver v0.1.28
Updating memmap2 v0.9.3 -> v0.9.4
Updating miniz_oxide v0.7.1 -> v0.7.2
Updating num-bigint v0.4.3 -> v0.4.4
Updating num-integer v0.1.45 -> v0.1.46
Updating num-traits v0.2.15 -> v0.2.18
Updating object v0.32.1 -> v0.32.2
Updating rcgen v0.12.0 -> v0.12.1
Updating rustix v0.38.28 -> v0.38.31
Updating semver v1.0.21 -> v1.0.22
Updating serde v1.0.195 -> v1.0.197
Updating serde_derive …
> build(deps): Bump all remaining deps

- linkerd/proxy/transport/src/orig_dst.rs
We first retrieve the socket option `SO_DOMAIN` to figure the socket's family, to then use the appropriate level and optname args when retrieving the original destination.
> Add IPv6 support when retrieving original destination

- .github/workflows/release.yml
This job can be required on all changes.
> ci: Add a confirmation job to the release workflow

- .github/workflows/release.yml
There's no need to check for file changes on release tags. Furthermore, avoid rebuilding packages on workflow changes (for now).
> ci: Skip checking changed files on releases

- .github/workflows/beta.yml
- .github/workflows/nightly.yml
- hyper-balance/src/lib.rs
- linkerd/app/admin/src/server.rs
- linkerd/app/gateway/src/http/tests.rs
- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/detect/tests.rs
- linkerd/app/inbound/src/policy/http/tests.rs
- linkerd/app/inbound/src/policy/tcp/tests.rs
- linkerd/app/integration/src/tests/identity.rs
- linkerd/app/integration/src/tests/profiles.rs
- linkerd/app/integration/src/tests/transparency.rs
- linkerd/app/outbound/src/discover/tests.rs
- linkerd/app/outbound/src/http/handle_proxy_error_headers.rs
- linkerd/app/outbound/src/http/logical/tests.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/opaq/logical/tests.rs
- linkerd/app/outbound/src/tcp/tagged_transport.rs
- linkerd/app/src/identity.rs
- linkerd/http-retry/src/replay.rs
- linkerd/idle-cache/src/lib.rs
- linkerd/meshtls/rustls/src/server.rs
- linkerd/meshtls/tests/util.rs
- linkerd/proxy/api-resolve/src/pb.rs
- linkerd/proxy/http/src/classify/channel.rs
- linkerd/proxy/spire-client/src/lib.rs
- linkerd/proxy/tap/src/grpc/match_.rs
- linkerd/stack/src/failfast/test.rs
- linkerd/stack/src/lazy.rs
- linkerd/stack/src/watch.rs
Our nightly build is failing due to some dead code warnings that aren't being
triggered on stable.
This change runs `cargo +nightly clippy --fix` and then manually fixes the
remaining issues.
> Fix Clippy warnings on nightly

- .github/workflows/coverage.yml
- .github/workflows/pr.yml
The Swatinem/rust-cache action attempts to cache dependencies for rust builds.
This PR adds it to the PR and Coverage workflows.
> ci: Use rust-cache in PR workflow

- .github/workflows/release.yml
- justfile
Previously, we have triggered release workflows by pushing a tag to the repo. While this isn't a huge problem, it's sub-optimal for automation workflows, where can rely on the `gh` CLI, and it's a sub-optimal user interface compared to the GitHub Actions UI.
This change updates the release workflow to be triggered by a workflow_dispatch event with a set of metadata that is used to drive the release process. These inputs can be specified when triggering the workflow. For example:
:; gh workflow run release.yml -f version=v2.220.0 -f publish=true
> ci: Update release workflow to be triggered via API

- linkerd/proxy/api-resolve/src/metadata.rs
- linkerd/proxy/api-resolve/src/pb.rs
The proxy API endpoint types include a 'weight' field that is not currently exposed by the endpoint Metadata type. This change updates the Metadata type to include the weight field as specified in the API.
> api-resolve: Expose endpoint weights

- deny.toml
There's no point in having to specify the license value on all our unpublished crates. This commit relaxes the license check for private crates.
> cargo-deny: Ignore private crates

- Cargo.lock
- Cargo.toml
- linkerd/pool/mock/Cargo.toml
- linkerd/pool/mock/src/lib.rs
- linkerd/proxy/balance/queue/Cargo.toml
- linkerd/proxy/balance/queue/src/tests.rs
This enables this to be reused in other crates.
> pool: Extract MockPool into a standalone crate

- .github/workflows/release.yml
This allows unnamed references to be released, which is necessary now that the release workflow produces tag references.
> ci: Update release workflow to use arbitrary references

- .github/workflows/release.yml
The release workflow needs to be able to write actions.
> ci: Fix release workflow permissions

- .github/workflows/pr.yml
Some integration tests can fail in CI due to resource volatility.
This commit configures the PR workflow to use NEXTEST_RETRIES=3 to automatically retry flakey tests.
> ci: Configure integration test retries

- .github/workflows/release-weekly.yml
- .github/workflows/release.yml
This commit adds a release-weekly workflow that runs on Wednesday nights. If there hasn't been a proxy release earlier in the week and there are new commits on main, then a new release is triggered.
> ci: Automate weekly proxy releases

- linkerd/app/admin/src/server.rs
- linkerd/app/inbound/src/http/server.rs
- linkerd/app/outbound/src/protocol.rs
- linkerd/proxy/http/src/glue.rs
- linkerd/proxy/http/src/lib.rs
- linkerd/proxy/http/src/server.rs
- linkerd/proxy/tap/src/accept.rs
The proxy HTTP server emits requests with an UpgradeBody type (as required by the server module that sets up HTTP CONNECT handling). We also wrap HTTP/2 requests in this body even though we do not currently support CONNECT over HTTP/2. The inbound and outbound server stacks then Box the request body so that the UpgradeBody type is hidden.
This commit moves the Box-ing of the request body into the HTTP server to reduce boilerplate.
This change sets up for additional HTTP server changes. There are no functional changes.
> proxy-http: Box request bodies

- linkerd/app/integration/src/client.rs
- linkerd/app/integration/src/controller.rs
- linkerd/app/integration/src/server.rs
- linkerd/proxy/http/src/executor.rs
- linkerd/proxy/http/src/h2.rs
- linkerd/proxy/http/src/lib.rs
- linkerd/proxy/http/src/server.rs
- linkerd/proxy/tap/src/accept.rs
The proxy::http::trace module was a bit of a misnomer, as it has nothing to do with "tracing" per-se, and much more to do with being a hyper executor.
This change renames the module and hides it form public export for clarity. It also simplifies instantiation of the executor.
> proxy-http: Simplify TracingExecutor

- linkerd/app/core/src/control.rs
The controller client is supposed to be configured with H2 settings derived from the environment, but it incorrectly uses defaults.
This change updates the controller client to be configured with the proper H2 client settings.
> control: Configure controller client H2 settings

- linkerd/app/core/src/lib.rs
- linkerd/proxy/http/src/glue.rs
- linkerd/proxy/http/src/h1.rs
- linkerd/proxy/http/src/lib.rs
- linkerd/proxy/http/src/normalize_uri.rs
- linkerd/proxy/http/src/override_authority.rs
- linkerd/proxy/http/src/upgrade.rs
Various utility functions are defined in the h1 module that are not strictly HTTP/1-specific.
In preparation for additional reorganization of the http module, this change moves utility functions:
> chore(proxy-http): Move utilities out of h1 module

- linkerd/proxy/transport/src/orig_dst.rs
In 9ee109a954cf5e267d19e52bb7dd73b0a26d79ae we generalized the `so_original_dst` function to first retrieve the socket's `SO_DOMAIN` in order to determine what constants to use to retrieve the original destination, that would work for both IP families.
This works fine when the socket is bound to `0.0.0.0` and receives a connection to the pod's IPv4 address, or when bound to `::` and receives a connection to the pod's IPv6 address. When the cluster is in dual-stack mode and we bind the socket to `::`, it properly receives connections targeted at both the pod's IPv4 and IPv6 addresses, but in the former case the `getsockopt` call to retrieve the original destination fails with:
```
WARN ThreadId(01) inbound: linkerd_app_core::serve: Server failed to accept connection error=No such file or …
```
> Fix so_original_dst retrieval in dual-stack mode

- Cargo.lock
- linkerd/dns/Cargo.toml
- linkerd/dns/src/lib.rs
The trust-dns-resolver library has been rebranded as hickory-resolver as per this [post](https://bluejekyll.github.io/blog/posts/announcing-hickory-dns/).
In order to continue receiving updates, we swap the dependency and upgrade to v0.24.0
> Swap trust-dns-resolver dependency with hickory-resolver

- Cargo.lock
- linkerd/app/core/src/control.rs
- linkerd/app/gateway/src/http.rs
- linkerd/app/gateway/src/http/tests.rs
- linkerd/app/gateway/src/lib.rs
- linkerd/app/integration/src/proxy.rs
- linkerd/app/outbound/src/discover/tests.rs
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/concrete/balance.rs
- linkerd/app/outbound/src/http/endpoint/tests.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/logical/tests.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/metrics.rs
- linkerd/app/outbound/src/opaq.rs
- linkerd/app/outbound/src/opaq/concrete.rs
- linkerd/app/outbound/src/opaq/logical/tests.rs
- linkerd/app/outbound/src/sidecar.rs
- linkerd/app/src/dst.rs
- linkerd/app/src/identity.rs
- linkerd/app/src/lib.rs
- linkerd/app/src/oc_collector.rs
- linkerd/app/src/policy.rs
- linkerd2-proxy/Cargo.toml
- linkerd2-proxy/src/main.rs
As we introduced the newer prometheus-client metrics registry, we did so by allowing stacks to register metrics directly. This is incongruent with the existing legacy metrics registries, which are known by the Inbound and Outbound stack builders.
This leads to two problems:
1. We cannot build the admin server until all of the proxy stacks are built. This ordering dependency is unnecessary and cumbersome if we want to insert additional discovery work into the initialization process.
2. It is cumbersome to add new metrics to stacks, as the registry must be passed through the stack building process.
To fix this, this change introduces additional Metrics types so that these metrics may be registered along with the other stack metrics.
BREAKING CHANGE: Gateway-mode proxies now report Balancer …
> chore(app,outbound)!: Decouple metrics registry from stack building

- linkerd/proxy/http/src/server.rs
- linkerd/proxy/http/src/server/tests.rs
This change adds tests that exercises the server's behavior when clients exhaust their HTTP/2 receive windows, i.e. so that the server is unable to send additional data to a client.
These tests currently only document the existing behavior, but they will be extended to validate mitigation strategies as they are implemented.
> chore(http): test HTTP/2 flow control exhaustion

- linkerd/app/outbound/src/metrics.rs
31d7464ef introduced a naming regression, so that metrics that 'outbound_http_' became 'outbound_http_http_'. This change fixes this regression.
> fix(http): fix outbound HTTP metrics naming

- linkerd/app/src/spire.rs
Makes the fields of the spire::Config struct pub so we can construct client configs from other crates.
> identity: make spire client config fields pub

- linkerd/app/src/env.rs
- linkerd/app/src/env/control.rs
- linkerd/app/src/env/http2.rs
- linkerd/proxy/http/src/h2.rs
- linkerd/proxy/http/src/server.rs
59ea792b3 expanded the proxy's HTTP/2 server parameters so that a variety of Hyper server settings may be controlled at runtime. There is currently no way for the control plane to influence these settings.
This commit adds environment-based configuration for the inbound and outbound proxy servers. All server parameters made configurable in 59ea792b3 are now configurable via environment variables. Variables take the form:
LINKERD2_PROXY_<PROXY>_SERVER_HTTP2_<PARAM>
Where `<PROXY>` is either `INBOUND` or `OUTBOUND`, and `<PARAM>` is the capitalized snake-case name of the parameter.
> feat(app): configure HTTP/2 server parameters

- linkerd/pool/p2c/src/lib.rs
The p2c pool tracks an endpoints gauge that is incremented and decremented as endpoints are added and removed from the balancer. When a balancer is dropped, the proxy does not reset this gauge to 0. If the balancer is recreated later, this causes endpoints to appear to be double-counted.
This commit fixes this in two ways:
1. When the balancer is dropped, the endpoints gauge is reset to 0.
2. When the pool is reset (i.e., during initialization), we always reset the endpoints value rather than use individual inc/dec calls.
> fix(pool): Reset endpoints gauge on drop

- linkerd/proxy/transport/src/listen.rs
- linkerd/proxy/transport/src/orig_dst.rs
The policy logic doesn't account for IPv4-mapped IPv6 addresses when matching allowed IPs with client IPs, so this change "unwraps" these types of IPs, converting those sockets into `SocketAddr::V4` at the lowest level in `BindTcp`. This also allows us to simplify the logic introduced by 7338f6b2b27c40ef8748551bed3e89905322f151 into `BindWithOrigDst` as it no longer has to account for IPv4-mapped IPv6 addresses (it was detecting them but wasn't unwrapping them).
As an example, this is the error we were getting, when prometheus (at 10.42.0.11) attempted to scrape a pod, even when that IP was authorized:
```
[    69.592605s]  INFO ThreadId(02) daemon:admin{listen.addr=[::]:4191}: linkerd_app_inbound::policy::http: Request denied server.group=policy.linkerd.io server.kind=server …
```
> Unwrap IPv4-mapped IPv6 addresses

- Cargo.lock
- Cargo.toml
- linkerd/http/h2/Cargo.toml
- linkerd/http/h2/src/lib.rs
- linkerd/proxy/http/Cargo.toml
- linkerd/proxy/http/src/h2.rs
This sets up configuring ClientParams from the proxy-api-resolve crate, i.e. so that the proxy-api-resolve crate does not need to depend on the proxy-http crate.
> chore(http): split params types into a dedicated http-h2 crate

- linkerd/app/inbound/src/http/router.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/concrete/balance.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/endpoint/tests.rs
- linkerd/proxy/http/src/client.rs
- linkerd/proxy/http/src/h1.rs
Currently all HTTP client configuration is derived from the configuration loaded at startup.
We'd like to allow this configuration to vary by endpoint so that, for example, we can enable keepalives when communicating with other proxies. These keepalives allow load balancers to eagerly detect connections that are in a bad state (i.e. before attempting to write a request to that connection).
To setup this kind of per-endpoint configuration, this change modifies the HTTP client to extract its configuration from the per-endpoint target so that calling stacks can provide this configuration.
The inbound and outbound stacks continue to set these configurations based on process-wide defaults, but we now have obvious places where we can set these parameters based on discovery results.
There are no …
> chore(http): allow http client configuration to vary by endpoint

- Cargo.lock
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/concrete/balance.rs
- linkerd/http/h2/src/lib.rs
- linkerd/proxy/api-resolve/Cargo.toml
- linkerd/proxy/api-resolve/src/metadata.rs
- linkerd/proxy/api-resolve/src/pb.rs
This commit updates the outbound proxy to read HTTP/2 client parameters from
Destination responses and to use these values to override the process-wide
defaults.
> feat(outbound): Configure HTTP/2 client overrides from discovery

- .github/workflows/release.yml
It is sometimes necessary for multiple release workflows to run in parallel. The current configuration does not allow this. This commit changes the configuration so that the concurrency group varies by the target ref.
> ci(release): Allow concurrent releases

- justfile
This ensures that the proxy-init image is compatible with recent edge releases.
> fix(ci): Update proxy-init to v2.4.0

- linkerd/app/admin/src/server.rs
The `IpAddr::is_loopback` function does not account for ipv4 mapped ipv6 addresses and returns false if the address is an ipv4 localhost mapped to ipv6.  This causes localhost-only admin endpoints to be unaccessible from localhost when ipv4 mapped ipv6 addresses are used.
We update the logic to check if the ipv6 address is ipv4 mapped and, if so, if the mapped ipv4 address is loopback.
> Handle ipv6 wrapped ipv4 addresses in loopback check

- linkerd/app/admin/src/server.rs
- linkerd/app/admin/src/stack.rs
- linkerd/app/src/env.rs
The `/shutdown` admin endpoint of the proxy can potentially be a DOS vector, for example, in the case of a SSRF attack.
We add a LINKERD2_PROXY_SHUTDOWN_ENDPOINT_ENABLED environment variable to control if the `/shutdown` endpoint is enabled.  Disabling this endpoint removes this DOS vector.
> Add env var to disable admin shutdown endpoint

- deny.toml
- linkerd/app/core/src/dns.rs
- linkerd/dns/src/lib.rs
- linkerd/tracing/src/lib.rs
Followup to #2872 , where we swapped the trust-dns-resolver with the hickory-resolver dependency. We had mistakingly changed the default log level to `hickory_dns=error` when it should have been `hickory_resolver=error`.
> Properly set log level for hickory_resolver in proxy

- Cargo.lock
- Cargo.toml
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/http.rs
- linkerd/app/outbound/src/http/logical/policy.rs
- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend/metrics.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend/metrics/tests.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/labels.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/test_util.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/tests.rs
- linkerd/app/outbound/src/http/logical/policy/router.rs
- linkerd/app/outbound/src/http/logical/policy/tests.rs
- linkerd/http/prom/Cargo.toml
- linkerd/http/prom/src/count_reqs.rs
- linkerd/http/prom/src/lib.rs
- linkerd/http/prom/src/record_response.rs
- linkerd/http/prom/src/record_response/request.rs
- linkerd/http/prom/src/record_response/response.rs
- linkerd/http/route/src/grpc/tests.rs
The outbound policy router includes a requests counter that measures the number of requests dispatched to each route-backend; but this does not provide visibility into success rate or response time. Before introducing timeouts and retires on outbound routes, this change introduces visibility into per-route response metrics.
The route_request_statuses counters measure responses from the application's point of view. Once retries are introduced, this will provide visibility into the _effective_ success rate of each route.
outbound_http_route_request_statuses_total{parent...,route...,http_status="200",error="TIMEOUT"} 0
outbound_grpc_route_request_statuses_total{parent...,route...,grpc_status="NOT_FOUND",error="TIMEOUT"} 0
A coarse histogram is introduced at this scope to track the total …
> feat(outbound): Add response metrics to policy router

- Cargo.lock
- linkerd/app/outbound/src/http/retry.rs
- linkerd/http/retry/Cargo.toml
- linkerd/http/retry/src/lib.rs
- linkerd/http/retry/src/peek_trailers.rs
- linkerd/http/retry/src/replay.rs
- linkerd/retry/src/lib.rs
Before introducing a new retry middleware for policy-driven retries, this change updates the existing linkerd-http-retry crate (1) to use boxed Error types and (2) to default to use BoxBody types with ReplayBody and (the newly renamed) PeekTrailersBody.
> chore(retry): Simplify retry types

- Cargo.lock
- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/extensions.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics.rs
- linkerd/app/outbound/src/http/logical/policy/route/retry.rs
- linkerd/app/outbound/src/http/logical/tests.rs
- linkerd/app/outbound/src/http/logical/tests/retries.rs
- linkerd/app/outbound/src/http/logical/tests/timeouts.rs
- linkerd/app/outbound/src/http/retry.rs
- linkerd/http/box/src/response.rs
- linkerd/http/retry/Cargo.toml
- linkerd/http/retry/src/lib.rs
- linkerd/http/retry/src/peek_trailers.rs
- linkerd/proxy/client-policy/src/grpc.rs
- linkerd/proxy/client-policy/src/http.rs
This change updates the HTTP router to support retry policies that interact with the recently introduced timeout policies.
Retry policies can match responses by HTTP status code ranges or by individual GRPC response codes. Retry policies also include a max-retries limit and an optional retry timeout. When a retry timeout is configured, the router configures the endpoint-level stream timeout with a response header timeout that ensures initial response headers are received so that a retry decision may be made before returning the response to the server.
Routes are updated to include several retry-related metrics:
outbound_http_route_retry_limit_exceeded_total{parent...,route...} 0
outbound_http_route_retry_overflow_total{parent...,route...} 0 …
> feat(outbound): Add HTTP and gRPC route retries

- Cargo.lock
- Cargo.toml
- linkerd/app/inbound/Cargo.toml
- linkerd/app/integration/Cargo.toml
- linkerd/app/outbound/Cargo.toml
- linkerd/http/route/Cargo.toml
- linkerd/proxy/api-resolve/Cargo.toml
- linkerd/proxy/client-policy/Cargo.toml
- linkerd/proxy/client-policy/src/grpc.rs
- linkerd/proxy/client-policy/src/http.rs
- linkerd/proxy/client-policy/src/lib.rs
- linkerd/proxy/identity-client/Cargo.toml
- linkerd/proxy/server-policy/Cargo.toml
- linkerd/proxy/tap/Cargo.toml
- linkerd/service-profiles/Cargo.toml
This change updates linkerd2-proxy-api to v0.14.0, which introduces per-route timeout and retry policies. These API responses are bound to the recently introduced outbound retry policies.
Support for the legacy request_timeout configuration (which in rare situations may be set by older control planes) is maintained, but is now deprecated in favor of the newer timeout policies.
> feat(outbound): Discover timeouts and retries

- linkerd/app/outbound/src/http/logical/tests.rs
- linkerd/app/outbound/src/http/logical/tests/basic.rs
- linkerd/app/outbound/src/http/logical/tests/failure_accrual.rs
- linkerd/app/outbound/src/http/logical/tests/retries.rs
- linkerd/app/outbound/src/http/logical/tests/timeouts.rs
In preparation for adding more tests, this commit simplifies the test setup utilities so that they can be shared and reused across test modules.
> chore(outbound): Simplify router test utilities

- linkerd/app/inbound/src/policy/defaults.rs
- linkerd/app/inbound/src/policy/http.rs
- linkerd/app/inbound/src/policy/tcp.rs
- linkerd/app/src/env.rs
- linkerd/proxy/server-policy/src/meta.rs
Audit mode is triggered by the policy controller, which will create an authorization named "audit" allowing traffic for the given target. When the proxy processes an authorization with such name it will log it at INFO.
Also, add "audit" to the possible values for
`LINKERD2_PROXY_INBOUND_DEFAULT_POLICY`, whose effect is the same as "all-unauthenticated".
Please check linkerd/website#1805 for how this is supposed to work from the user's perspective.
> feat(inbound): Log traffic with the 'audit' policy

- linkerd/proxy/http/src/h1.rs
HTTP/1 clients do not preserve the calling trace context, so Hyper client debug logs are emitted without context metadata.
This change updates the HTTP/1 client to use an executor that preserves the tracing context.
> fix(http): Set logging contexts on HTTP/1 clients

- linkerd/identity/src/metrics.rs
- linkerd/metrics/src/lib.rs
- linkerd/metrics/src/process.rs
Currently, it's not possible to accurately calculate the time remaining before the proxy certificate expires, since the proxy didn't expose its view of what the time is. This exposes the wall clock time (rounded to the nearest second) as a gauge so downstream consumers can calculate the offsets for cert expiry, as well as any other offsets for timestamps we provide.
Example metrics output:
```
$ curl http://whoami.default:4191/metrics | grep process_clock_time
...
process_clock_time_seconds 1725565062.0
```
Fixes [#12413](https://github.com/linkerd/linkerd2/issues/12413)
> Add wall clock gauge to proxy metrics

- .devcontainer/devcontainer.json
- .github/workflows/beta.yml
- .github/workflows/coverage.yml
- .github/workflows/fuzzers.yml
- .github/workflows/nightly.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- Cargo.lock
- Dockerfile
- linkerd2-proxy/Cargo.toml
- linkerd2-proxy/src/main.rs
- linkerd2-proxy/src/rt.rs
Tokio has an unstable feature supporting runtime metrics.
This allows service operators to export metrics to systems like
Prometheus, so that they can observe how their workloads are performing
on the tokio runtime. This exposes information like the number of worker
threads, queue depth, the number of tasks polled, and so on.
`linkerd2-proxy` should expose these metrics.
This uses the `kubert-prometheus-tokio` crate to register a `Runtime`
metrics worker, and spawn a task to probe these metrics at a fixed,
regular interval.
see: <https://github.com/olix0r/kubert/tree/main/kubert-prometheus-tokio>
if the `tokio_unstable` feature is not enabled, this will emit a debug
event and do nothing.
> 📈 feat(rt): expose tokio runtime metrics

- linkerd/app/core/src/config.rs
- linkerd/app/core/src/control.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/inbound/src/test_util.rs
- linkerd/app/integration/src/proxy.rs
- linkerd/app/outbound/src/tcp/connect.rs
- linkerd/app/outbound/src/test_util.rs
- linkerd/app/src/env.rs
- linkerd/meshtls/tests/util.rs
- linkerd/proxy/transport/src/connect.rs
- linkerd/proxy/transport/src/lib.rs
- linkerd/proxy/transport/src/listen.rs
- linkerd/proxy/transport/src/listen/dual_bind.rs
Implement setting TCP_USER_TIMEOUT option for TCP sockets
To ensure stable connection and exclude dangling connections set TCP_USER_TIMEOUT for each TCP socket for inbound, outbound and to control-plane traffic. UserTimeout configured in same way as Keepalive for ServerConfig and ConnectConfig. if setting UserTimeout failed - there will be warning to console
Fixes [#13023](https://github.com/linkerd/linkerd2/issues/13023)
> Implement setting TCP_USER_TIMEOUT option for TCP sockets

- Cargo.lock
- Cargo.toml
- linkerd/tls/route/Cargo.toml
- linkerd/tls/route/src/lib.rs
- linkerd/tls/route/src/match.rs
- linkerd/tls/route/src/sni.rs
- linkerd/tls/route/src/tests.rs
This PR includes a nonfunctional change that adds a TLS route-matching library.
The library works similarly to the http-route one but instead of relying on HTTP concepts
such as paths, headers, etc is specific to TLS ones (i.e. SNI).
At the moment the library is capable of matching routes based on SNIs.
> feat(tls-route): add TLS route matching crate

- Cargo.lock
- linkerd/proxy/client-policy/Cargo.toml
- linkerd/proxy/client-policy/src/lib.rs
- linkerd/proxy/client-policy/src/tls.rs
In preparation for adding Tls routing, this change updates our `client-policy` crate with a `Protocol::Tls` variant.
> policy: add TLS protocol type to client-policy crate

- Cargo.lock
- Cargo.toml
- linkerd/opentelemetry/Cargo.toml
- linkerd/opentelemetry/src/lib.rs
- linkerd/opentelemetry/src/metrics.rs
This mirrors and duplicates most of the logic from the existing OpenCensus exporter to keep the functionality as similar as possible. Setting up the proxy to use this exporter will come in a follow-up.
[#10111](linkerd/linkerd2#10111)
> Add OpenTelemetry exporter implementation

- linkerd/app/outbound/src/http/retry.rs
- linkerd/http/retry/src/lib.rs
- linkerd/http/retry/src/replay.rs
`linkerd-http-retry` and `linkerd-retry` provide generic `tower`
middleware to allow services to retry requests that fail.
part of this middleware hinges on a `ReplayBody<B>` that will lazily
buffer request bodies' data for use in subsequent attempts. if a request
fails, the retry middleware will attempt to send another request,
assuming the original body was able to completely fit into this buffer.
`ReplayBody<B>` makes a subtle assummption, most succinctly stated in
this excerpt of an internal method's documentation:
```rust
// linkerd/http/retry/src/replay.rs
impl<B: Body> ReplayBody<B> {
/// This panics if another clone has currently acquired the state, based on
/// the assumption that a retry body will not be polled until the previous
/// request has been dropped.
fn …
```
> fix(retry): Avoid panicking if responses come early

- .github/dependabot.yml
OpenTelemetry packages should always be updated in lockstep with each other. This tells dependabot to group dependency updates into a single PR: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> Group opentelemetry dependency updates

- linkerd/app/outbound/src/http/logical/policy/route/backend/metrics.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend/metrics/tests.rs
a stray `#![allow(warnings)]` directive seems to have slipped in from an initial prototyping phase.
this commit removes this directive from
`/linkerd/app/outbound/src/http/logical/policy/route/backend/metrics.rs`, and addresses the newly unearthed warnings, related to unused imports.
> chore(app): Disallow warnings in policy router's backend metrics

- linkerd/app/outbound/src/http/logical/policy/route/backend.rs
the equivalent blocks in the parent `route.rs` file have the same `// === impl T ===` blocks that are added here. these are introduced, because they help visually group impl blocks when code in these files is folded.
> chore(app): add `impl` banner comments

- linkerd/http/prom/Cargo.toml
this commit introduces a description and adds the authors.
> docs(http/prom): Add metadata to Cargo.toml manifest

- linkerd/app/integration/src/test_env.rs
this is a documentation pass, fleshing out information about how the `TestEnv` interfaces work.
> docs(integration): Document test environment interfaces

- linkerd/http/prom/src/count_reqs.rs
<https://github.com/linkerd/linkerd2-proxy/pull/3228/files>
this fixes some links, added in #3228, because i observed github actions warning about these in a different pr. pardon me! 😅
> docs(http/prom): Fix broken doc links

- linkerd/app/src/env.rs
- linkerd/app/src/trace_collector.rs
- linkerd/app/src/trace_collector/oc_collector.rs
- linkerd/app/src/trace_collector/otel_collector.rs
Currently, we hard-code the trace service name to "linkerd-proxy". This allows this name to be configured through an env that can be set by the injector, annotations, etc.
linkerd/linkerd2#11157
> Allow configuring proxy trace exporter service name

- linkerd/app/core/src/metrics.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/endpoint.rs
- linkerd/app/outbound/src/http/endpoint/tests.rs
- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/metrics.rs
- linkerd/app/outbound/src/opaq/concrete.rs
- linkerd/app/outbound/src/tcp.rs
- linkerd/app/outbound/src/tcp/endpoint.rs
- linkerd/app/outbound/src/zone.rs
- linkerd/proxy/api-resolve/src/metadata.rs
- linkerd/proxy/api-resolve/src/pb.rs
- linkerd/transport-metrics/src/lib.rs
- linkerd/transport-metrics/src/zone.rs
- linkerd/transport-metrics/src/zone/client.rs
- linkerd/transport-metrics/src/zone/sensor.rs
Currently, the destination controller populates a zone locality field in the metric labels for an endpoint. This works fine, but can be expensive to query against in prometheus due to the high cardinality of the metrics it is attached to.
This introduces a separate `outbound_tcp_bytes_total` metric with only the zone locality as a label, which is the most common use of this label.
This includes some extra infrastructure to wire the new metric through as we currently don't use prometheus-client for transport metrics. Eventually, the existing metrics could and/or should be migrated, but that is saved for a future change.
> Extract zone locality into separate TCP metric

- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/labels.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/tests.rs
- linkerd/app/outbound/src/http/logical/policy/route/retry.rs
- linkerd/http/prom/src/record_response/request.rs
- linkerd/http/retry/src/lib.rs
this commit introduces an additional label to HTTP and gRPC route
metrics, containing the DNS host of requests. requests destined for an
ip address of some kind are not recorded with a hostname metric, as a
way to help minimize the impact of time series cardinality.
the core of this change is in this field addition:
```diff
// /linkerd/app/outbound/src/http/logical/policy/route/metrics/labels.rs
-pub struct Route(pub ParentRef, pub RouteRef);
+pub struct Route {
+    parent: ParentRef,
+    route: RouteRef,
+    hostname: Option<dns::Name>,
+}
```
see this part of the change to our `MkStreamLabel` implementation, used
in our metrics tracking request durtion, and counting response status
codes:
```diff
-    fn mk_stream_labeler<B>(&self, _: &::http::Request<B>) -> Option<Self::StreamLabel> …
```
> feat(app): Add hostname label to http metrics

- linkerd/app/gateway/src/opaq.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/opaq.rs
- linkerd/app/outbound/src/opaq/concrete.rs
- linkerd/app/outbound/src/opaq/logical.rs
- linkerd/app/outbound/src/opaq/logical/router.rs
- linkerd/app/outbound/src/opaq/logical/tests.rs
- linkerd/app/outbound/src/sidecar.rs
This change has the following effects: 
- we remove opaq::LogicalAddr
- we try to preserve the behavior of the endpoint metrics by using the profiles logical addr if we have used profiles for resolution.
> remove opaq logical addr

- Cargo.lock
- Cargo.toml
- linkerd/app/integration/src/controller.rs
- linkerd/app/integration/src/policy.rs
- linkerd/proxy/api-resolve/src/pb.rs
- linkerd/proxy/client-policy/src/lib.rs
- linkerd/proxy/client-policy/src/opaq.rs
- linkerd/proxy/server-policy/src/lib.rs
While finalizing API changes for an upcoming release, we need to pin the `linkerd2-proxy-api` dependency to a specific commit in the `main` branch. This will allow us to completely validate end-to-end functionality before releasing the new version of the API crate.
> build(deps): pin proxy-api to git

- linkerd/app/inbound/Cargo.toml
- linkerd/app/inbound/src/policy/http/tests.rs
- linkerd/proxy/server-policy/Cargo.toml
- linkerd/proxy/server-policy/src/local_rate_limit.rs
- linkerd/proxy/server-policy/src/local_rate_limit/tests.rs
We only expect to use `LocalRateLimit::new_no_overrides` for tests.
This change adds a test-util featuer to the server-policy crate so that we can assert that this constructor doesn't sneak into release code.
> chore(server-policy)!: feature-gate LocalRateLimit constructor

- linkerd/app/outbound/src/opaq/concrete.rs
- linkerd/app/outbound/src/opaq/logical.rs
This change adds resource coordinate labels for `Parent` and `Backend` to the `outbound_tcp_balancer_*` metrics.
> metrics: Add ParentRef and BackendRef to opaq balancer metrics

- Cargo.lock
This fixes a compilation error caused by a missing feature flag.
> build(deps): bump linkerd2-proxy-api

- Cargo.lock
- linkerd/distribute/Cargo.toml
- linkerd/distribute/src/keys.rs
- linkerd/distribute/src/lib.rs
- linkerd/distribute/src/params.rs
- linkerd/distribute/src/service.rs
- linkerd/distribute/src/service/first.rs
- linkerd/distribute/src/service/random.rs
- linkerd/distribute/src/stack.rs
Currently, if the proxy receives two backends with the same metadata, one of the backends will get dropped because the backend metadata is used as the key in a hash map. Attempting to then randomly distribute requests to the backends can panic when selecting the now non-existent backend.
This is fixed by no longer using backend metadata as a hash map key, instead generating separate IDs that are stored in a vec to retain the declared order of backends while also being used to look up the backend and associated weight independetly.
Validated with new unit tests excercising duplicate backend keys, as well as a few around the invariants use to store the backends.
> Allow duplicate weighted backend keys

- linkerd/app/outbound/src/opaq/logical/route.rs
- linkerd/app/outbound/src/opaq/logical/route/filters.rs
- linkerd/app/outbound/src/opaq/logical/router.rs
- linkerd/app/outbound/src/tls/logical/route.rs
- linkerd/app/outbound/src/tls/logical/route/filters.rs
- linkerd/app/outbound/src/tls/logical/router.rs
- linkerd/proxy/client-policy/src/lib.rs
- linkerd/proxy/client-policy/src/opaq.rs
- linkerd/proxy/client-policy/src/tls.rs
This PR wires the route and backend errors for TCP and TLS protocol and models them as Filters for the respective routing stacks.
> policy: add filters for TCP and TLS policy

- linkerd/app/outbound/src/http/logical/policy/route/backend/metrics.rs
- linkerd/http/prom/src/body_data/response.rs
**nb:** this is based on #3308. this is a refactor branch aimed at finding a way to simplify the somewhat burdensome types in the metrics middleware's `layer(..)` function.
this isn't a "simplification" so much as an outlining of the chunky types in this function signature.
that said... it's subjectively nice to outline the definition of our layers into a `MetricsLayer<T, N>`
that we can use as shorthand in the function signature of `layer(..)`.
this commit changes the backend-level metrics layer function, so that it invokes
`linkerd_app_core::svc::layers()` rather than `linkerd_app_core::svc::layer::mk()`.
this has a nice effect in that it simplifies the bounds of the `layer` function.
> refactor(app): Simplify backend metrics tower layer

- Cargo.lock
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/http/logical/policy/route/backend/metrics.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend/metrics/tests.rs
- linkerd/http/prom/Cargo.toml
- linkerd/http/prom/src/body_data.rs
- linkerd/http/prom/src/body_data/body.rs
- linkerd/http/prom/src/body_data/metrics.rs
- linkerd/http/prom/src/body_data/request.rs
- linkerd/http/prom/src/body_data/response.rs
- linkerd/http/prom/src/lib.rs
- linkerd/metrics/src/lib.rs
this introduces a new tower middleware for Prometheus metrics, used for instrumenting HTTP and gRPC
response bodies, and observing (a) the number of frames yielded by a body, and (b) the number of bytes
included in body frames.
this middleware allows operators to reason about how large or small the packets being served in a backend's
response bodies are.
a route-level middleware that instruments request bodies will be added in a follow-on PR.
an overview of changes made here:
* the `linkerd-http-prom` has a new `body_data` submodule. it exposes `request` and `response` halves, to
be explicit about which body is being instrumented on a `tower::Service`.
* the `linkerd-http-prom` crate now has a collection of new dependencies: `bytes` is added as a dependency
in order to inspect the data …
> feat(app): Backend frame count metrics

- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/labels.rs
- linkerd/app/outbound/src/http/logical/policy/route/retry.rs
this PR, based upon #3308, generalizes the `ExtractParam<P, T>` type used to retrieve Prometheus labels for the route-level retry middleware. this is a helpful component we'll want in order to build route-level frame counting middleware.
this commit promotes the `RetryLabelExtract` type out of the route retry middleware, and into the metrics
submodule.
in preparation for generalizing this component, we rename it to `RouteLabelExtract`.
this addresses the `TODO` comment, moving the `RouteLabelExtract` type out of the policy route layer
function.
this defines a method on `MatchedRoute` which may be called to retrieve a `RouteLabelExtract`. that type
holds references to the contruction-time information about the route, and can be used to later inspect an
outbound request at call-time, …
> refactor(app): Outline route label extractor

- Cargo.lock
- Cargo.toml
- linkerd/app/integration/src/policy.rs
- linkerd/app/outbound/src/opaq/logical/route/filters.rs
- linkerd/app/outbound/src/tls/logical/route/filters.rs
- linkerd/proxy/client-policy/src/opaq.rs
- linkerd/proxy/client-policy/src/tls.rs
This PR updates the proxy API dependency to a new version that uses filters to express errors for TLS and TCP routes. 
This PR depends on https://github.com/linkerd/linkerd2-proxy-api/pull/405
> policy: use TLS/TCP filters from proxy API response

- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/tests.rs
- linkerd/http/prom/src/body_data/metrics.rs
- linkerd/http/prom/src/body_data/request.rs
feat(app): Route frame count metrics
this introduces a new tower middleware for Prometheus metrics, used for
instrumenting HTTP and gRPC request bodies, and observing (a) the
number of frames yielded by a body, (b) the number of bytes included
in body frames, and (c) a distribution of the size of frames yielded.
this builds upon the backend-level metrics added in #3308. this
additionally uses the route label extractor, hoisted out of the retry
middleware's Prometheus telemetry in #3337.
* a `linkerd_http_prom::body_data::request::NewRecordBodyData::NewRecordBodyData`
middleware is added, which complements the equivalent
`linkerd_http_prom::body_data::response` middleware.
* this is added to policy routes' metrics layer.
see prometheus/client_rust#241 and prometheus/client_rust#242, which …
> feat(app): Route frame count metrics

- linkerd/app/outbound/src/metrics/transport.rs
- linkerd/app/outbound/src/opaq/logical/route.rs
- linkerd/app/outbound/src/opaq/logical/route/filters.rs
- linkerd/app/outbound/src/tls/logical/route.rs
- linkerd/app/outbound/src/tls/logical/route/filters.rs
This PR fixes a problem that was introduced in the following commit: https://github.com/linkerd/linkerd2-proxy/pull/3355/commits/5ac135212f1a7f51d083d99bf7e7d7231d5d972d
The problem is that if a particular route is configured to fail a connection, the `poll_ready` call on the inner service will return the error and the service will never get called. Therefore in order to capture that in metrics, we need to increment the metrics counter if we encounter errors while calling` poll_ready` on the inner service.
> metrics: correctly reflect closed connections in route metrics

- Cargo.lock
- linkerd/app/admin/Cargo.toml
- linkerd/app/admin/src/server/log/level.rs
- linkerd/app/admin/src/server/log/stream.rs
- linkerd/app/integration/src/tap.rs
- linkerd/app/integration/src/tests/discovery.rs
- linkerd/app/integration/src/tests/profiles.rs
- linkerd/app/integration/src/tests/shutdown.rs
- linkerd/app/integration/src/tests/tap.rs
- linkerd/app/integration/src/tests/telemetry.rs
- linkerd/app/outbound/src/http/logical/tests.rs
- linkerd/app/test/src/http_util.rs
hyper 0.14.x provided a collection of interfaces related to collecting
and aggregating request and response bodies, which were deprecated and
removed in the 1.x major release.
this commit updates calls to `hyper::body::to_bytes(..)` and
`hyper::body::aggregate(..)`. for now, `http_body::Body` is used, but we
can use `http_body_util::BodyExt` once we've bumped our hyper dependency
to the 1.x major release.
for more information, see:
* https://github.com/linkerd/linkerd2/issues/8733
* https://github.com/hyperium/hyper/issues/2840
* https://github.com/hyperium/hyper/pull/3020
> refactor(app): update deprecated hyper body calls

- .github/workflows/pr.yml
- justfile
CI runs frequently timeout waiting for pod readiness. There is a hardcoded 1m timeout.
This change makes this timeout configurable, specifying a 2m timeout in the CI configuration.
> ci: increase linkerd-install readiness timeout

- linkerd/app/test/src/http_util.rs
this `Server` type is not used by any tests.
this commit removes it, to help facilitate the upgrade to the hyper 1.0 major release. see <https://github.com/linkerd/linkerd2/issues/8733>.
> refactor(app/test): remove unused test `Server` interfaces

- Cargo.lock
Silences an advisory that doesn't impact us.
> build(deps): update hashbrown from 0.15.0 to 0.15.2

- linkerd/proxy/http/Cargo.toml
- linkerd/proxy/http/src/h2.rs
- linkerd/proxy/http/src/server/tests.rs
this branch contains a sequence of commits that focus on addressing deprecation warnings related to `hyper::client::conn::Builder`. this branch enables the `backports` feature, and then replaces some of these builders with the backported, http/2 specific, `hyper::client::conn::http2::Builder` type.
relates to https://github.com/linkerd/linkerd2/issues/8733.
> chore(proxy/http): address `hyper::client::conn::Builder` deprecations

- linkerd/app/inbound/src/http/tests.rs
this addresses hyper 1.0 deprecations in the server side of the inbound
proxy's http unit test suite logic.
see <https://github.com/linkerd/linkerd2/issues/8733> for more
information.
the client end of this change ends up being slightly involved, due to
changes that will need to be made in `linkerd_app_test::http_util`.
accordingly, those deprecations will be addressed in a subsequent
commit.
> chore(app/inbound): address `server::conn::Http` deprecations

- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/test/src/http_util.rs
this commit changes the `connect_and_accept(..)` helper function used in
the proxy's unit tests, altering its logic such that it now runs
background tasks inside of a `JoinSet`.
then, subsequent commits hoist code out of `run_proxy()` and `connect_client()`, and consolidate our `async move {}` blocks. this both simplifies the control flow of this test infrastructure, but also addresses some more hyper deprecations.
for more information about our progressing upgrade to hyper 1.0, see https://github.com/linkerd/linkerd2/issues/8733.
NB: this branch is based upon #3432.
> refactor(app/test): address hyper deprecations in test helpers

- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/integration/Cargo.toml
- linkerd/app/integration/src/controller.rs
- linkerd/app/integration/src/server.rs
- linkerd/app/integration/src/tests/transparency.rs
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/http/endpoint/tests.rs
- linkerd/proxy/tap/Cargo.toml
- linkerd/proxy/tap/src/accept.rs
this branch addresses a small assortment of calls to deprecated hyper interfaces.
see <https://github.com/linkerd/linkerd2/issues/8733>.
> chore(hyper): address miscellaneous deprecations

- deny.toml
if one runs `cargo deny check` on the current state of main, or checks deny logs in ci, one observes this waning:
```sh
$ cargo deny check
warning[unnecessary-skip]: skip 'idna' applied to a crate with only one version
┌─ /path/to/linkerd/linkerd2-proxy/deny.toml:63:15
│
63 │     { name = "idna" },
│               ━━━━ unnecessary skip configuration
advisories ok, bans ok, licenses ok, sources ok
```
today, our dependency graph only contains one version of `idna`, which has since release a 1.0 version:
```sh
$ cargo tree -i -p idna
idna v1.0.3
├── hickory-proto v0.24.2
└── url v2.5.4
```
this commit updates the `deny.toml` file, removing this directive to permit duplicate versions, now that this is no longer the case.
> chore(deny.toml): remove stale `idna` directive

- linkerd/app/inbound/Cargo.toml
- linkerd/app/inbound/fuzz/Cargo.toml
- linkerd/app/inbound/src/http.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/test/src/http_util.rs
**nb:** this branch is based upon #3454.
see https://github.com/linkerd/linkerd2/issues/8733 for more information on upgrading to hyper 1.0.
this removes `connect_and_accept(..)`. this will break fuzzing builds,
but it is not used elsewhere.
this commit addresses hyper deprecations in the inbound proxy's fuzz tests.
note that this commit does not compile. it was observed that some breakage had
accrued, because ci does not seem to be properly checking the fuzz tests.
this commit addresses breakage found in the fuzz tests, tied to
other previous work.
after these changes, one can observe that the fuzz tests build and run
once more by running the following:
```sh
cargo +nightly fuzz run --fuzz-dir=linkerd/app/inbound/fuzz/ fuzz_target_1
```
> chore(fuzz): address hyper deprecations in fuzz tests

- Cargo.toml
- hyper-balance/Cargo.toml
- linkerd/app/admin/Cargo.toml
- linkerd/app/core/Cargo.toml
- linkerd/app/inbound/Cargo.toml
- linkerd/app/integration/Cargo.toml
- linkerd/app/outbound/Cargo.toml
- linkerd/app/test/Cargo.toml
- linkerd/http/executor/Cargo.toml
- linkerd/http/metrics/Cargo.toml
- linkerd/http/retry/Cargo.toml
- linkerd/http/upgrade/Cargo.toml
- linkerd/metrics/Cargo.toml
- linkerd/proxy/http/Cargo.toml
- linkerd/proxy/tap/Cargo.toml
this commit alters various crates' manifests, pointing to a common workspace-level hyper dependency.
note that the lockfile is not altered; this commit does *not* affect the version of hyper
used, or have any other affect on the dependency graph. this will make future maintenance
of our hyper dependency marginally easier.
see linkerd/linkerd2#8733 for more information on upgrading to hyper 1.0.
> chore(hyper): define hyper as a workspace dependency

- linkerd/app/test/src/http_util.rs
this commit removes a duplicate function that was errantly defined, due to some issues when merging previous (interdependent) pr's.
see
- #3455
- #3454
- linkerd/linkerd2#8733
> chore(ci): remove duplicate `connect_and_accept_http1(..)` function

- linkerd/proxy/http/src/server.rs
see linkerd/linkerd2#8733 for more information on upgrading to hyper 1.0.
this commit is based upon #3456, and #3457.
this commit is also contingent upon hyperium/hyper#3796, which backports the server connection builder's `max_pending_accept_reset_streams()` method.
this commit addresses hyper deprecations in `ServeHttp<N>`, which defines a reusable HTTP/1 and HTTP/2 server for the linkerd proxy.
essentially, this commit replaces the singular `Http<E>` with a pair of http/1 and http/2 specific connection `Builder`s. method names no longer have `http2_*` prefixes, otherwise nothing about the connection setup has been changed. in the `Service` implementation, we delegate to the appropriate builder based upon the protocol version.
> chore(proxy/http): address hyper deprecations in `ServeHttp<N>`

- linkerd/app/test/src/http_util.rs
this commit fixes some warnings that are currently present in `main` when building the project's docs, by mending two broken doc links.
see:
- #3454
- <https://github.com/linkerd/linkerd2/issues/8733>
> docs(app/test): fix unresolved `SendRequest` links

- linkerd/http/box/src/body.rs
hyper 0.14's body type provides an `empty()` method that can be used to construct an empty request or response body.
this commit proposes an equivalent method for `BoxBody`. while it is semantically equivalent to `BoxBody::default()`, it can be helpful to clarify that this constructs an empty body.
<https://docs.rs/hyper/0.14.31/hyper/body/struct.Body.html#method.empty>
see https://github.com/linkerd/linkerd2/issues/8733.
> feat(http/box): `BoxBody::empty()` creates an empty body

- linkerd/app/core/build.rs
if this build script panics due to an invalid proxy version environment variable, the panic can be somewhat cryptic. a message saying `LINKERD2_PROXY_VERSION must be semver` is printed, but the proxy version that caused this is not shown.
this commit adds the version and the error to this panic message.
now, building with an invalid proxy version provides us with the following:
```
; LINKERD2_PROXY_VERSION='invalid' cargo build -p linkerd-app-core
Compiling linkerd-app-core v0.1.0 (/linkerd2-proxy/linkerd/app/core)
error: failed to run custom build command for `linkerd-app-core v0.1.0 (/linkerd2-proxy/linkerd/app/core)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused …
```
> refactor(app/core): build.rs prints invalid proxy version

- Cargo.lock
- linkerd/http/upgrade/Cargo.toml
- linkerd/http/upgrade/src/glue.rs
- linkerd/http/upgrade/src/upgrade.rs
`hyper::Body` is removed in the 1.0 version.
this commit removes it from our upgrade facilities, using a generic body parameter that defaults to BoxBody.
see <https://github.com/linkerd/linkerd2/issues/8733>.
> chore(http/upgrade): replace `hyper::Body` with `BoxBody`

- Cargo.lock
- Cargo.toml
- deny.toml
this commit upgrades to hyper 0.14.32, removing the manifest's `[patch]` section.
hyperium/hyper#3796 backported a method we use when building http/2 connections. #3457 patched the workspace to rely on a git dependency of hyper at commit `a24f0c0a`. this work has been released in version 0.14.32.
this commit also changes `deny.toml`, removing the exception we carved out for hyper in #3457.
for more information, see:
* hyperium/hyper#3796
* linkerd/linkerd2#8733
* https://github.com/hyperium/hyper/commits/0.14.x
* #3457
* 03f55779
> chore(hyper): upgrade to hyper 0.14.32

- .devcontainer/devcontainer.json
- .github/workflows/beta.yml
- .github/workflows/coverage.yml
- .github/workflows/fuzzers.yml
- .github/workflows/markdown.yml
- .github/workflows/nightly.yml
- .github/workflows/pr.yml
- .github/workflows/release-weekly.yml
- .github/workflows/release.yml
- .github/workflows/shellcheck.yml
- .github/workflows/toolchain.yml
- Dockerfile
- justfile
Updates LLVM from 14 to 19.
We pin ubuntu to 24.04 to ensure compatibility.
> chore: bump dev from v44 to v45

- linkerd/proxy/http/src/orig_proto.rs
`UpgradeResponseBody` currently wraps a `hyper::Body`. this type is removed in hyper 1.0.
this commit replaces this with a generic `B`-typed body.
see https://github.com/linkerd/linkerd2-proxy/pull/3479, which performs the same change in `linkerd-http-upgrade`.
see https://github.com/linkerd/linkerd2/issues/8733 for more information on upgrading to hyper 1.0.
> chore(proxy/http): replace `hyper::Body` with `BoxBody`

- linkerd/http/retry/src/replay.rs
see linkerd/linkerd2#8733.
the tests for the replay body use the `hyper::Body` type removed in the 1.0 release.
this commit replaces this with `BoxBody` where possible, and adds comments with context about how to update code once upgrading to hyper 1.0.
see #3467 and #3468 which added `from_static()` and `empty()`, respectively.
> chore(http/retry): use boxed bodies instead of `hyper::Body`

- linkerd/http/upgrade/src/glue.rs
- linkerd/http/upgrade/src/upgrade.rs
- linkerd/proxy/http/src/h1.rs
the `linkerd-http-upgrade` crate supports HTTP/1.1 upgrades. currently, it exposes a number of functions and types in its public interface that are strictly internal helpers. this branch redefines various interfaces and fields as private, to clarify the public interface of the crate.
> refactor(http/upgrade): internal interfaces are private

- linkerd/http/upgrade/src/glue.rs
- linkerd/http/upgrade/src/lib.rs
- linkerd/http/upgrade/src/upgrade.rs
- linkerd/proxy/http/src/h1.rs
some aspects of `linkerd-http-upgrade` are incompatible with the 1.0 interface of the `http` crate (_see: hyperium/http#395, linkerd/linkerd2#8733_).
this new bound requiring that extensions must now be cloneable motivated me to read through this library's internals to gain a lucid understanding of how it works, in order to understand how to gracefully address [this](https://github.com/linkerd/linkerd2-proxy/blob/main/linkerd/http/upgrade/src/upgrade.rs#L25-L26) comment affixed to the `linkerd_http_upgrade::upgrade::Http11Upgrade` request/response extension:
```rust
// Note: this relies on their only having been 2 Inner clones, so don't
// implement `Clone` for this type. [sic]
pub struct Http11Upgrade {
half: Half,
inner: Arc<Inner>,
}
```
broadly, this library deals with some moderately …
> docs(http/upgrade): document `linkerd-http-upgrade`

- linkerd/proxy/transport/src/orig_dst.rs
Fixes a discrepancy between the types used for non Linux vs the types used for Linux based builds in our orig_dst code.
> transport: fix wrong type in non-linux orig_dst_* method

- linkerd/http/retry/src/peek_trailers.rs
`ResponseWithPeekTrailers` wraps an inner service `S`.
upon inspection, it turns out that this structure is no longer used by any code elsewhere in the project.
this commit removes `ResponseWithPeekTrailers`, its associated type aliases, and its `tower::Service<T>` implementation.
> refactor(http/retry): remove unused `ResponseWithPeekTrailers<S>`

- Cargo.lock
- linkerd/http/retry/Cargo.toml
- linkerd/http/retry/src/peek_trailers.rs
https://github.com/linkerd/linkerd2/issues/8733 tracks the upgrade to hyper 1.0.
the `PeekTrailersBody<B>` body middleware, provided by the `linkerd-http-retry` crate, is uniquely positioned to be adversely affected by the changes to the `Body` trait. this type, in order to attempt to peek an inner `B`-typed body's HTTP/2 trailers, has some subtle and nuanced edge cases.
the intent of this type is to only yield the asynchronous task responsible for reading the body _once_. depending on what the inner body yields, and when, this can result in combinations of: no data frames and no trailers, no data frames with trailers, one data frame and no trailers, one data frame with trailers, or two data frames. moreover, depending on which of these are yielded, the body will call `.await` some …
> feat(http/retry): add a unit test suite to `PeekTrailersBody<B>`

- Cargo.lock
- Cargo.toml
- linkerd/app/integration/Cargo.toml
- linkerd/app/integration/src/client.rs
- linkerd/app/integration/src/identity.rs
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/tls/logical/tests.rs
- linkerd/meshtls/rustls/Cargo.toml
- linkerd/meshtls/rustls/src/client.rs
- linkerd/meshtls/rustls/src/creds.rs
- linkerd/meshtls/rustls/src/creds/receiver.rs
- linkerd/meshtls/rustls/src/creds/store.rs
- linkerd/meshtls/rustls/src/creds/verify.rs
- linkerd/meshtls/rustls/src/server.rs
This is a retry of https://github.com/linkerd/linkerd2-proxy/pull/3419, which was reverted by https://github.com/linkerd/linkerd2-proxy/pull/3553.
This includes a fix that caused the control plane to never be ready due to a reduction in the set of supported signature algorithms. See https://github.com/linkerd/linkerd2-proxy/commit/01e0782e3aa1afe9f8d6f79a24a17382e7b6132a for details.
> build(rustls): Upgrade tokio-rustls to 0.26

- linkerd/http/retry/src/peek_trailers.rs
this commit fixes a small, subtle bug in `PeekTrailersBody<B>`.
if wrapping an empty body, the peek body will inspect the wrong `Option<T>` in the trailers field with the following type:
```rust
/// The inner body's trailers, if it was terminated by a `TRAILERS` frame
/// after 0-1 DATA frames, or an error if polling for trailers failed.
///
/// Yes, this is a bit of a complex type, so let's break it down:
/// - the outer `Option` indicates whether any trailers were received by
///   `WithTrailers`; if it's `None`, then we don't *know* if the response
///   had trailers, as it is not yet complete.
/// - the inner `Result` and `Option` are the `Result` and `Option` returned
///   by `HttpBody::trailers` on the inner body. If this is `Ok(None)`, then
///   the body has terminated without …
```
> fix(http/retry): `is_end_stream()` is true for empty bodies

- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/metrics.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/integration/src/tests/telemetry.rs
This change removes the `authority` label on inbound HTTP requests. 
The label is derived from the Host headers on inbound HTTP requests. This means
that the presence of this label can be exploited by a malicious client in order to produce
unbounded increase in the cardinality of the metrics reported in the proxy by sending
a large amount of HTTP requests with random `Host` headers.
> metrics: remove authority label on inbound http metrics

- linkerd/http/retry/src/replay.rs
see linkerd/linkerd2#8733.
#3559 introduced some compatibility facilities to allow us to write code in terms of `http_body_util::BodyExt::frame()`, front-running the upgrade to be performed in #3504.
some `ReplayBody` tests use the defunct `data()` and `trailers()` interfaces. this branch ports _two_ such unit tests. other tests are saved for a fast follow-on, as the `chunk(..)` and `read_to_string(..)` helpers will need some slightly more involved tweaks.
> refactor(http/retry): port some `ReplayBody` tests to `Frame<T>`

- linkerd/http/retry/src/compat.rs
- linkerd/http/retry/src/replay.rs
based on #3564. see linkerd/linkerd2#8733.
this branch upgrades the remaining parts of the `ReplayBody<B>` test suite to poll bodies in terms of `Frame<T>`s.
> refactor(http/retry): port remaining `ReplayBody` tests to `Frame<T>`

- Cargo.lock
- deny.toml
- linkerd/distribute/Cargo.toml
- linkerd/distribute/src/keys.rs
- linkerd/distribute/src/params.rs
- linkerd/distribute/src/service/random.rs
- linkerd/exp-backoff/Cargo.toml
- linkerd/exp-backoff/src/lib.rs
- linkerd/http/route/Cargo.toml
- linkerd/http/route/src/http/filter/inject_failure.rs
- linkerd/pool/p2c/Cargo.toml
- linkerd/pool/p2c/src/lib.rs
- linkerd/proxy/balance/Cargo.toml
- linkerd/proxy/http/Cargo.toml
- linkerd/proxy/tap/Cargo.toml
- linkerd/proxy/tcp/Cargo.toml
- linkerd/tls/route/Cargo.toml
supersedes #3569.
this branch updates [`rand`](https://github.com/rust-random/rand) from 0.8.5 to 0.9.0.
- [release notes](https://github.com/rust-random/rand/releases)
- [changelog](https://github.com/rust-random/rand/blob/master/CHANGELOG.md)
- [commits](https://github.com/rust-random/rand/compare/0.8.5...0.9.0)
note the changes to `rand::distr::weighted::Error`'s variants. see https://github.com/rust-random/rand/pull/1382, and https://github.com/rust-random/rand/pull/1470. in particular, this change: https://github.com/rust-random/rand/pull/1382/files#diff-b0eb1b0ef894742b65e07f23af6cbeffae64ec8311adb6ea606603e978023e0cL116-R113
most other changes in this branch relate to the renaming of `thread_rng()` to `rng()`, and `gen()` to `random()`.
> chore(deps/rand): update to `rand` v0.9.0

- linkerd/http/retry/src/replay.rs
pr's #3564 and #3567, 1eb822f2 and 32042783 respectively, replaced uses of defunct `http_body::Body` trait methods — namely, `data()` and `trailers()`.
this commit updates two remaining uses of `data()` that were missed in this initial pass.
see linkerd/linkerd2#8733 for more information.
> refactor(http/retry): update more `Body::data()` calls

- linkerd/app/src/env.rs
- linkerd/app/src/env/trace.rs
- linkerd/app/src/trace_collector.rs
- linkerd/app/src/trace_collector/otel_collector.rs
It's useful to include these fields in the trace span attributes to help correlate traffic within a cluster.
This propagates these labels through the trace initialization, similar to how we handle the service name (and other labels that last for the entire pod lifetime).
See https://github.com/linkerd/linkerd2/pull/13501 for the corresponding control plane change.
> Include pod UID and container name as optional trace labels

- linkerd/http/retry/src/replay.rs
a `ReplayBody<B>` demands a particular contract of its users: one must not poll two bodies in parallel. this is currently mentioned as an implicit assumption on an internal helper function, `acquire_state<'a>`, here:
https://github.com/linkerd/linkerd2-proxy/blob/main/linkerd/http/retry/src/replay.rs#L127-L131
```rust
/// # Panics
///
/// This panics if another clone has currently acquired the state, based on
/// the assumption that a retry body will not be polled until the previous
/// request has been dropped.
fn acquire_state<'a>(
state: &'a mut Option<BodyState<B>>,
shared: &Mutex<Option<BodyState<B>>>,
) -> &'a mut BodyState<B> {
state.get_or_insert_with(|| shared.lock().take().expect("missing body state"))
}
```
this commit echoes this sentiment on the relevant public-facing parts …
> docs(http/retry): document `ReplayBody::poll_*()` panics

- linkerd/http/retry/src/replay.rs
`ReplayBody<B>` is slightly inconsistent about how it represents the exhaustion of the inner `B`-typed body.
first, in `poll_data()` we poll the inner body, and note that we consider a `None` value for `BodyState::rest` to mean that there is no more work to do.
```rust
// Poll the inner body for more data. If the body has ended, remember
// that so that future clones will not try polling it again (as
// described above).
let mut data = {
// Get access to the initial body. If we don't have access to the
// inner body, there's no more work to do.
let rest = match state.rest.as_mut() {
Some(rest) => rest,
None => return Poll::Ready(None),
};
// ...
};
```
then, in `Body::is_end_stream()`, we write the following to check that the stream is done:
```rust
let is_inner_eos = self
.state …
```
> refactor(http/retry): replayed body is not optional

- linkerd/http/retry/src/replay.rs
this commit makes some small, admittedly subjective tweaks to `ReplayBody::poll_trailers(..)`.
we can make use of the `map_ok` and `map_err` methods that exist to map `Poll::Ready<Result<T, E>>`'s inner `T` to some `U` (_in our case, to record the trailers for later replay_), and to map the error type into a boxed `Error`.
this is a minor tweak, front-running other work to port the `ReplayBody<B>` to http-body 1.0. see https://github.com/linkerd/linkerd2/issues/8733.
> refactor(http/retry): use `Poll::{map_ok, map_err}`

- linkerd/http/retry/src/replay.rs
- linkerd/http/retry/src/replay/buffer.rs
the `ReplayBody<B>` middleware makes use of a `BufList` type to hold a
reference to bytes yielded by the inner body `B`. a `Data` enum is
composed on top to this, to allow bodies to either return (a) a replay
of a previous body, or (b) the iniial bytes yielded by the original
body.
this branch also takes the step of moving some code out of the
`ReplayBody::poll_data(..)` trait method along with inlining
`BufList::push_chunk(..)` , a small helper function that is only used
once.
this is intended to consolidate code related to buffering data yielded
by the underlying `B`-typed body, and extricate logic concerning the
bounding of this buffer from the now defunct `Body::poll_data()` trait
method.
see https://github.com/linkerd/linkerd2/issues/8733 for more information
about upgrading the …
> refactor(http/retry): outline bounded replay buffer

- linkerd/http/retry/src/compat.rs
- linkerd/http/retry/src/replay.rs
- linkerd/http/retry/src/replay/tests.rs
pr https://github.com/linkerd/linkerd2-proxy/pull/3559 (https://github.com/linkerd/linkerd2-proxy/commit/dd4fbcdb6e1d6f4b92684e7cc9517f2f3c5bb3c3) refactored our trailer peeking body middleware to
model its buffering in terms of the `Frame<T>` type used in
`http-body`'s 1.0 release.
this branch performs a similar change for the other piece of body
middleware that super linkerd's retry facilities: `ReplayBody<B>`. the
inner body `B` is now wrapped in the `ForwardCompatibleBody<B>` adapter,
and we now poll it in terms of frames.
NB: polling the underlying in terms of frames has a subtle knock-on
effect regarding when we observe the trailers, in the liminal period
between this refactor and the subsequent upgrade to hyper 1.0, whilst we
must still implement the existing 0.4 interface for …
> feat(http/retry): model `ReplayBody<B>` with `Frame<T>`

- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/labels.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/tests.rs
- linkerd/app/outbound/src/http/logical/policy/route/retry.rs
- linkerd/app/outbound/src/http/logical/policy/router.rs
- linkerd/http/retry/src/lib.rs
The outbound HTTP route labels use multiple ExtractParam implementations to convert a matched route target to set of labels (using an HTTP request).
This change removes the RouteLabelExtract type, in favor of implementing label extraction on the route target type directly.
> refactor(outbound): simplify http route metric labeling

- linkerd/opentelemetry/src/lib.rs
A previous change enabling OpenTelmetry forgot to include attributes from the span itself, in addition to the request level spans as we do in the old OpenCensus exporter. This adds those attributes back in.
> Fix missing attributes in OpenTelemetry traces

- linkerd/app/outbound/src/http/logical/policy/route.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/labels.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/test_util.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics/tests.rs
- linkerd/app/outbound/src/tls/logical/route.rs
- linkerd/app/outbound/src/tls/logical/router.rs
- linkerd/app/outbound/src/tls/logical/tests.rs
- linkerd/proxy/client-policy/src/grpc.rs
- linkerd/proxy/client-policy/src/http.rs
- linkerd/proxy/client-policy/src/tls.rs
The 'hostname' label value is derived from the request URI and can be influenced
by applications. If a client uses a high cardinality of hostname values, this
leads to the proxy exporting many metrics and ultimately exhausting resources.
This change disables the 'hostname' label by default. A new field is outed to
the HTTP and TLS route parameters, `export_hostname_labels`, which can be used
to enable the 'hostname' label; however, this type is not yet configurable.
Changes are required to the proxy API and, ultimately, the policy controller, to
make this field configurable.
When the hostname is not exported, an empty label value is used.
BREAKING: The 'hostname' label is now disabled by default.
> feat(outbound)!: disable 'hostname' metrics label

- linkerd/app/core/src/errors/body.rs
refactor(app/core): prepare rescue body for http-body upgrade
this commit makes some minor alterations to our error recovery body
middleware. see https://github.com/linkerd/linkerd2/issues/8733 for more
information.
this commit removes an `assert!` statement from the implementation of
`<Response<R, B> as Body>::poll_data()`. see the documentation of
`Body::poll_frame()`:
> Once the end of the stream is reached, implementations should
> continue to return [`Poll::Ready(None)`].
https://github.com/hyperium/http-body/commit/1090bfff26884779e026f4cab37a2a3ee165a69d#diff-33aabe8c2aaa7614022addf244245e09bbff576a67a9ae3c6938c8a868201d36R60-R61
to do this, this commit introduces a distinct terminal state
`Inner::Rescued` to represent when the underlying `B`-typed body has
yielded an error and …
> refactor(app/core): prepare rescue body for http-body upgrade

- linkerd/proxy/transport/src/orig_dst.rs
The code that we currently use to obtain `orig_dst` has been borrowed from `net2-rs`.
Since we already have socket2 in our dependency tree, we can simplify the logic by
just using socket2. An added benefit of that is that socket2 provides support for
obtaining `orig_dst` on Windows.
> chore(transport): Use socket2 to obtain orig_dst

- linkerd/app/src/spire.rs
At the moment the fact that SPIRE uses Unix domain sockets prevents us from building
the proxy for non-unix targets. This PR adds special casing that allows us to build for
these targets but makes the spire client fail at runtime. Non-unix support for Spire shall
be introduced at a later stage.
> chore(app/spire): make spire compilation possible for non-linux targets

- linkerd/proxy/transport/src/lib.rs
Right now the proxy can be configured so that `TCP_USER_TIMEOUT` is set on connections.
This functionality is not present for non-linux targets. This introduces a warning in case a user
tries to set `TCP_USER_TIMEOUT` on a proxy that has been compiled for a target other than Linux.
> chore(transport): Ignore TCP_USER_TIMEOUT on non-Linux systems and warn

- linkerd/app/src/trace_collector/otel_collector.rs
- linkerd/opencensus/src/lib.rs
- linkerd/opentelemetry/src/lib.rs
this commit removes these bounds from the
`linkerd_app::trace_collector::otel_collector::SpanExporter<T, S>` and other connected functions.
> chore(app/trace-collector): remove `Default` bounds

- linkerd/app/inbound/src/policy/api.rs
- linkerd/app/inbound/src/policy/config.rs
- linkerd/app/inbound/src/policy/store.rs
- linkerd/app/inbound/src/server.rs
see also, #3651 and #3653 for some related pull requests.
this commit removes `Default` bounds from policy lookup in the inbound proxy. this means that in `linkerd-app`, we can invoke `Inbound::build_policies()` when using hyper 1.x (_see #3504_)
> chore(app/inbound): remove `Default` bounds

- linkerd/app/outbound/src/lib.rs
- linkerd/app/outbound/src/policy/api.rs
see also, #3651 #3653, and #3654 for some related pull requests.
this commit removes `Default` bounds from policy lookup in the outbound proxy. this means that in `linkerd-app`, we can invoke `Outbound::build_policies()` when using hyper 1.x (_see #3504_)
> chore(app/outbound): remove `Default` bounds

- linkerd/proxy/api-resolve/src/resolve.rs
see also, #3651 #3653, #3654, and #3655 for some related pull requests.
this commit removes `Default` bounds from `Resolve<S>`.
> chore(proxy/api-resolve): remove `Default` bounds

- linkerd/service-profiles/src/client.rs
see also, #3651 #3653, #3654, and #3655 for some related pull requests.
this commit removes `Default` bounds from `Client<R, S>` used to create watches on service profiles.
> chore(service-profiles): remove `Default` bounds

- linkerd/opencensus/src/lib.rs
this commit makes some superficial adjustments to import statements in `linkerd-opencensus`. we have a convention of using crate-level symbol groupings in `use` statements. this commit follows that convention.
> nit(opencensus): format use statements

- linkerd/proxy/identity-client/src/certify.rs
https://github.com/linkerd/linkerd2/issues/8733 for more information.
see also, https://github.com/linkerd/linkerd2-proxy/pull/3651 for another related pull request.
this commit removes these bounds from
`linkerd_proxy_identity_client::Certify<C, S>`.
> chore(proxy/identity-client): remove `Default` bounds

- linkerd/app/src/trace_collector/oc_collector.rs
see #3651 and linkerd/linkerd2#8733.
#3651 missed this unused trait bound, which we want to loosen to account for changes in hyper's api.
> chore(app/trace-collector): remove `Default` bound

- .github/dependabot.yml
This change updates the dependabot configuration to group certain ecosystems of dependencies, especially rustls.
> chore(dependabot): group dependency updates

- Cargo.lock
- linkerd/app/inbound/Cargo.toml
- linkerd/app/inbound/src/http/tests.rs
see https://github.com/linkerd/linkerd2-proxy/pull/3559 and https://github.com/linkerd/linkerd2-proxy/pull/3614 for more information on the `ForwardCompatibleBody<B>` wrapper.
this branch updates test code in `linkerd-app-inbound` so that it interacts with request and response bodies via an adapter that polls for frames in a manner consistent with the 1.0 api of `http_body`.
this allows us to limit the diff in https://github.com/linkerd/linkerd2-proxy/pull/3504, which will only need to remove this adapter once using hyper 1.0.
see #3672 and #3673, which perform the same change for `linkerd-app-outbound` and `linkerd-app-integration`, respectively.
> refactor(app/inbound): forward-compatible test code

- Cargo.lock
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/http/logical/policy/route/metrics/test_util.rs
- linkerd/app/outbound/src/http/logical/tests.rs
- linkerd/app/outbound/src/http/logical/tests/headers.rs
- linkerd/app/outbound/src/http/logical/tests/retries.rs
see https://github.com/linkerd/linkerd2-proxy/pull/3559 and https://github.com/linkerd/linkerd2-proxy/pull/3614 for more information on the `ForwardCompatibleBody<B>` wrapper.
this branch updates test code in `linkerd-app-outbound` so that it interacts with request and response bodies via an adapter that polls for frames in a manner consistent with the 1.0 api of `http_body`.
this allows us to limit the diff in https://github.com/linkerd/linkerd2-proxy/pull/3504, which will only need to remove this adapter once using hyper 1.0.
see #3671 and #3673, which perform the same change for `linkerd-app-inbound` and `linkerd-app-integration`, respectively.
> refactor(app/outbound): forward-compatible test code

- Cargo.lock
- linkerd/app/integration/Cargo.toml
- linkerd/app/integration/src/tests/profiles.rs
see https://github.com/linkerd/linkerd2-proxy/pull/3559 and https://github.com/linkerd/linkerd2-proxy/pull/3614 for more information on the `ForwardCompatibleBody<B>` wrapper.
this branch updates test code in `linkerd-app-integration` so that it interacts with request and response bodies via an adapter that polls for frames in a manner consistent with the 1.0 api of `http_body`.
this allows us to limit the diff in https://github.com/linkerd/linkerd2-proxy/pull/3504, which will only need to remove this adapter once using hyper 1.0.
see #3671 and #3672, which perform the same change for `linkerd-app-inbound` and `linkerd-app-outbound`, respectively.
> refactor(app/integration): forward-compatible test code

- linkerd/app/integration/src/tap.rs
this commit makes some cosmetic changes to
`linkerd_app_integration::tap::SyncSvc`'s implementation of
`tower::Service<T>`.
documentation comments are added to clarify something that makes this
service slightly interesting, and notably different from code suitable
for use in production / real-world contexts.
this service wraps an underlying `Client`, and provides a service
implementation that deals with arbitrary `B`-typed request bodies.
this provides a flexible adapter that simplifies test code.
this service, however, *blocks* the calling thread (off-task) to collect
the body into a cheaply-cloneable `Bytes`.
this commit outlines that logic into an associated function and adds
additional documentation noting this property, and the basis for this
assumption.
the bounds placed upon the …
> refactor(app/integration): clarify `<SyncSvc as Service<T>>::call()`

- linkerd/app/integration/src/client.rs
- linkerd/app/integration/src/lib.rs
`linkerd_app_integration::running()` is a public function that is not used by any external callers. this function is used in one place, when setting up test client used for integration tests.
this commit inlines this logic, and moves the associated `Running` type alias down alongside the `Run` enum.
> refactor(app/integration): inline `Running` future

- linkerd/app/integration/src/server.rs
- linkerd/app/integration/src/tests/identity.rs
- linkerd/app/integration/src/tests/shutdown.rs
- linkerd/app/integration/src/tests/telemetry.rs
- linkerd/app/integration/src/tests/transparency.rs
`linkerd_app_integration::tcp` provides a `TcpServer` type that is distinct from the primary `linkerd_app_integration::server::Server` type broadly used in integration tests.
this commit makes a small change to reduce indirection, and clarify that this is constructing a different server implementation from a different submodule.
this removes `linkerd_app_integration::server::tcp()`, and updates test code to call the `tcp::server()` function that this is masking.
> refactor(app/integration): call `tcp::server()` directly

- linkerd/app/integration/src/server.rs
these constants exist, and are generally considered a best practice for these situations.
this commit replaces numeric literals with named constants.
> nit(app/integration): use `OK`, `NOT_FOUND` constants

- linkerd/app/integration/src/tcp.rs
we follow a convention of grouping imported symbols at the crate-level.
this commit tidies up imports in `linkerd_app_integration::tcp` to follow this convention.
> nit(app/integration): tidy `tcp` imports

- linkerd/app/integration/src/tcp.rs
this method is not used by any test code, nor any other internal code.
this commit removes
`linkerd_app_integration::tcp::TcpConn::target_addr()`.
> refactor(app/integration): remove unused `TcpConn::target_addr()`

- linkerd/app/integration/src/client.rs
- linkerd/app/integration/src/lib.rs
- linkerd/app/integration/src/server.rs
- linkerd/app/integration/src/tests/profiles.rs
we are in the process of upgrading to hyper 1.x.
in the process of doing so, we will wish to use our friendly `BoxBody` type, which provides a convenient and reusable interface to abstract over different artitrary `B`-typed request and response bodies.
unfortunately, by virtue of its definition, it is not a `Sync` type:
```rust
pub struct BoxBody {
inner: Pin<Box<dyn Body<Data = Data, Error = Error> + Send + 'static>>,
}
#[pin_project]
pub struct Data {
#[pin]
inner: Box<dyn bytes::Buf + Send + 'static>,
}
```
these are erased `Box<dyn ..>` objects that only ensure `Send`-ness.
rather than changing that, because that is the proper definition of the type, we should update code in our test client and test server to …
> refactor(app/integration): remove artificial `Sync` bounds

- Cargo.lock
- linkerd/opencensus/Cargo.toml
- linkerd/opencensus/src/lib.rs
- linkerd/opentelemetry/Cargo.toml
- linkerd/opentelemetry/src/lib.rs
noticed while addressing `cargo-deny` errors in #3504. these crates include a few unused dependencies, which we can remove. while we are in the neighborhood, we make some subjective tweaks to tidy up these imports.
> chore(deps): remove unused `opencensus`, `opentelemetry` dependencies

- Cargo.lock
https://rustsec.org/advisories/RUSTSEC-2025-0009.html
0.17.11 is vulnerable to RUSTSEC-2025-0009. this commit updates the `ring` dependency to a patched version.
```
; git switch main                                                                                           
Switched to branch 'main'                                                                                   
Your branch is up to date with 'origin/main'.                                                               
; cargo deny check                                                                                          
error[vulnerability]: Some AES functions may panic when overflow checking is enabled.
┌─ /linkerd/linkerd2-proxy/Cargo.lock:262:1
│ …
```
> chore(deps): update to ring 0.17.13

- linkerd/detect/Cargo.toml
this is a follow-on to #3715.
this commit sorts the dependencies in this manifest.
> nit(detect): sort dependencies

- Cargo.toml
- linkerd/app/core/Cargo.toml
- linkerd/http/upgrade/Cargo.toml
- linkerd/proxy/http/Cargo.toml
see https://github.com/linkerd/linkerd2/issues/8733 and https://github.com/linkerd/linkerd2-proxy/pull/3504 for more information.
see also linkerd/drain-rs#36 for a related pull request that updated `drain`'s `tower` dependency. see #3715 (2f97549a) for a related pull request that made `tower` a workspace dependency.
see #3456 (c740b6d8), #3466 (ca50d6bb), #3473 (b87455a9), and #3701 (cf4ef39), for some other previous pr's that moved dependencies to be managed at the workspace level.
> chore(deps): `drain` is a workspace dependency

- linkerd/app/admin/Cargo.toml
- linkerd/app/core/Cargo.toml
- linkerd/pool/p2c/Cargo.toml
- linkerd/proxy/balance/Cargo.toml
- linkerd/proxy/core/Cargo.toml
pr #3715 missed a small handful of cargo dependencies. this commit marks these so that they use the workspace-level tower version.
> chore(deps): `tower` is a workspace dependency

- justfile
Our build can occaisionally fail when the sha is not a valid semver label:
--- stdout
cargo:rustc-env=GIT_SHA=025979070
cargo:rustc-env=LINKERD2_PROXY_BUILD_DATE=2025-03-08T16:32:34Z
--- stderr
thread 'main' panicked at linkerd/app/core/build.rs:18:17:
LINKERD2_PROXY_VERSION must be semver: version='0.0.0-dev.025979070'
error='invalid leading zero in pre-release identifier'
To fix this, the dot is removed so the version string is 0.0.0-dev025979070, which is valid.
> fix(just): make dev versions semver

- linkerd/app/inbound/src/direct.rs
The RefusedNoTarget error type is a remnant of an older version of the direct stack. This commit updates the error message to reflect the current state of the code: we require ALPN-negotiated transport headers on all direct connections.
> fix(inbound): correct error message when transport header is missing

- linkerd/app/core/src/metrics.rs
- linkerd/app/core/src/transport/labels.rs
- linkerd/app/gateway/src/http/tests.rs
- linkerd/app/inbound/src/http.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/tcp/tests.rs
We include a group/version/kind for inbound server resources, but we do not indicate which specific port the server is applied to. This is important context to understand the inbound proxy's behavior, especially when using the default servers.
This change adds a `srv_port` label to inbound server metrics to definitively and consistently indicate the server port used for inbound policy.
This change also adds prometheus_client compatible label formatting for
consistency.
> feat(inbound): include srv_port label in server metrics

- Cargo.lock
- linkerd/app/admin/src/stack.rs
- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/detect/tests.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/lib.rs
- linkerd/app/inbound/src/metrics.rs
- linkerd/app/inbound/src/server.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/metrics.rs
- linkerd/app/outbound/src/protocol.rs
- linkerd/app/outbound/src/sidecar.rs
- linkerd/app/src/lib.rs
- linkerd/http/detect/Cargo.toml
- linkerd/http/detect/src/lib.rs
- linkerd/http/detect/src/metrics.rs
- linkerd/proxy/http/src/lib.rs
This change updates the DetectHttp middleware to record metrics about HTTP
protocol detection. Specfically, it records the the counts of results and a very
coarse histogram of the time taken to detect the protocol.
The inbound, outbound, and admin (via inbound) stacks are updated to record
metrics against the main registry.
<details>
<summary><h3>Example metrics</h3></summary>
```
inbound_tcp_detect_http_duration_seconds_sum{srv_group="",srv_kind="default",srv_name="all-unauthenticated",srv_port="4191"} 0.0019456109999999997
inbound_tcp_detect_http_duration_seconds_count{srv_group="",srv_kind="default",srv_name="all-unauthenticated",srv_port="4191"} 52
inbound_tcp_detect_http_duration_seconds_bucket{le="0.001",srv_group="",srv_kind="default",srv_name="all-unauthenticated",srv_port="4191"} …
```
> feat: instrument HTTP protocol detection metrics

- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/direct/metrics.rs
- linkerd/app/inbound/src/direct/metrics/tests.rs
- linkerd/app/inbound/src/metrics.rs
Inbound proxies may receive meshed traffic directly on the proxy's inbound port
with a transport header, informing inbound routing behavior.
This change updates the inbound proxy to record metrics about the usage of
transport headers, including the total number of requests with a transport
header by session protocol and target port.
<h3>Example metrics</h3>
```
inbound_tcp_transport_header_connections_total{session_protocol="http/2",target_port="8080",target_name="",client_id="web.emojivoto.serviceaccount.identity.linkerd.cluster.local"} 2
```
> feat(inbound): instrument transport header metrics

- linkerd/app/outbound/src/metrics.rs
- linkerd/app/outbound/src/protocol.rs
- linkerd/app/outbound/src/protocol/metrics.rs
- linkerd/app/outbound/src/protocol/tests.rs
The outbound proxy makes protocol decisions based on the discovery response, keyed on a "parent" reference.
This change adds a connection counter, `outbound_tcp_protocol_connections`, that counts dispatched connections by protocol configuration ("http/1", "http/2", "opaq", "tls", "detect")
> feat(outbound): add outbound_tcp_protocol_connections counter

- linkerd2-proxy/Cargo.toml
- linkerd2-proxy/src/rt.rs
The proxy predates the multi-threaded tokio runtime. When switching to it, we added a 'multicore' feature to adopt it incrementally. This has been the only supported configuration for many years now.
This change removes the needless feature flag to simplify the runtime configuration.
> chore(linkerd2-proxy): always enable multicore features

- Cargo.lock
- Cargo.toml
- linkerd/app/Cargo.toml
- linkerd/app/src/lib.rs
- linkerd/workers/Cargo.toml
- linkerd/workers/src/lib.rs
- linkerd2-proxy/src/rt.rs
When the proxy boots up, it needs to select a number of I/O worker threads to allocate to the runtime. This change adds a new environment variable that allows this value to scale based on the number of CPUs available on on the host.
A CORES_MAX_RATIO value of 1.0 will allocate one worker thread per CPU core. A lesser value will allocate fewer worker threads.
The CORES_MIN value sets a lower bound on the number of worker threads to use. The CORES_MAX value sets an upper bound.
> feat(runtime): support CORES_MIN, CORES_MAX, and CORES_MAX_RATIO

- linkerd/http/metrics/Cargo.toml
- linkerd/metrics/Cargo.toml
- linkerd/metrics/src/lib.rs
linkerd-metrics exposes a 'stack' feature but uses a 'linkerd-stack' feature internally. This change cleans this up.
> chore(metrics): clean up feature flagging

- Cargo.lock
- linkerd/app/core/Cargo.toml
- linkerd/app/outbound/Cargo.toml
- linkerd/http/detect/src/metrics.rs
- linkerd/http/prom/Cargo.toml
- linkerd/http/prom/src/body_data/metrics.rs
- linkerd/identity/Cargo.toml
- linkerd/metrics/Cargo.toml
- linkerd/pool/p2c/Cargo.toml
- linkerd/proxy/balance/gauge-endpoints/Cargo.toml
- linkerd/proxy/balance/queue/Cargo.toml
- linkerd2-proxy/Cargo.toml
this updates the prometheus client dependency.
additionally, this commit updates the `kubert-prometheus-tokio` dependency, so that we agree on the client library in use.
> chore(deps): use `prometheus-client` v0.23

- Cargo.lock
- linkerd/http/access-log/Cargo.toml
- linkerd/http/access-log/src/lib.rs
this commit replaces `humantime`, which is no longer maintained, with `jiff`.
see this error when `main` today is built:
```
error[unmaintained]: humantime is unmaintained
┌─ /linkerd/linkerd2-proxy/Cargo.lock:78:1
│
78 │ humantime 2.1.0 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
│
├ ID: RUSTSEC-2025-0014
├ Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0014
├ Latest `humantime` crates.io release is four years old and GitHub repository has
not seen commits in four years. Question about maintenance status has not gotten
any reaction from maintainer: https://github.com/tailhook/humantime/issues/31
* [jiff](https://crates.io/crates/jiff) provides same kind of functionality …
```
> chore(deps): address RUSTSEC-2025-0014

- justfile
#3683 introduced the `os` param into our just file. This parameter was used to set the `_package_name` variable but not the `_target_bin` one. As a result of that the `_strip:` task was failing for windows builds as it was incorrectly looking for a binary that was missing (one without an .exe extension).
This PR adds the following changes: 
- correctly adds the `.exe` extension to `_target_bin` when `os` is windows
- adds the `os` to the name of the produces artifact
The latter means that release artifacts shall be names as: 
```
linkerd2-proxy-v2.286.0-windows-amd64.tar.gz 
linkerd2-proxy-v2.286.0-linux-amd64.tar.gz 
```
> chore(just): add .exe extension to windows binaries

- linkerd/http/upgrade/src/upgrade.rs
- linkerd/proxy/http/src/h1.rs
this branch is motivated by [review feedback](https://github.com/linkerd/linkerd2-proxy/pull/3504#discussion_r1999706761) from #3504. see
linkerd/linkerd2#8733 for more information on upgrading `hyper`. there,
we asked:
> I wonder if we should be a little more defensive about cloning [`HttpConnect`]. What does cloning it mean? When handling a CONNECT request, we can't clone the request, really. (Technically, we can't clone the body, but practically, it means we can't clone the request). Can we easily track whether this was accidentally cloned (i.e. with a custom Clone impl or Arc or some such) and validate at runtime (i.e., in proxy::http::h1) that everything is copacetic?
`linkerd-http-upgrade` provides a `HttpConnect` type that is intended
for use as a response extension. this commit …
> refactor(http/upgrade): remove `HttpConnect` extension

- Cargo.lock
- linkerd/dns/Cargo.toml
- linkerd/dns/src/lib.rs
see also #3782.
this commit addresses breaking changes in the v0.25.0 release of `hickory-resolver`, used by our `linkerd-dns` crate to handle DNS resolution.
see the release notes, here:
<https://github.com/hickory-dns/hickory-dns/releases/tag/v0.25.0>
> 0.25.0 represents a large release for the Hickory DNS project. Over 14
> months since 0.24.0, we've [..] addressed a number of findings from our
> first security audit.
changes that are relevant to us include:
> * Support for TLS using native-tls or OpenSSL has been removed. We now
>   only provide first-party support for rustls (0.23, for DNS over TLS,
>   HTTP/2, QUIC and HTTP/3). We support ring or aws-lc-rs for
>   cryptographic operations both for DNSSEC and TLS. The
>   dns-over-rustls,dns-over-native-tls, dns-over-openssl,
> …
> chore(dns): upgrade to `hickory-resolver` v0.25

- linkerd/dns/name/src/name.rs
this golfs down the return expression in
`NameRef::try_from_ascii_str()`.
rather than binding our `s` to a temporary variable in order to return a `Self(s)` result, we can take the same result and use `Result::map` to convert a `Result<&'a str, InvalidName>` to a
`Result<NameRef<'a>, InvalidName>`.
> nit: golf `NameRef::try_from_ascii_str()`

- linkerd/proxy/transport/src/orig_dst.rs
In #3626, we refactored the origin_dst determination logic to utilize socket2 calls. However, this change inadvertently disrupted IPv6 and dual-stack support, causing the server to fail to start when deployed on such network configurations:
```
WARN ThreadId(01) inbound: linkerd_app_core::serve: Server failed to accept connection error=No such file or directory (os error 2)
```
This change reintroduces detection of the current network family, calling socket2's `original_dst()` or `original_dst_ipv6()` depending on the case.
Tested fine in both IPv6 and dual-stack Kind clusters.
> fix(transport): repair IPv6 support

- justfile
The new installGatewayAPI option is needed to bundle vendored gateway CRDs for testing.
> chore(just): set installGatewayAPI in CRD install

- Cargo.lock
- Cargo.toml
- linkerd/app/gateway/src/server.rs
- linkerd/app/inbound/src/accept.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/logical.rs
- linkerd/app/outbound/src/http/logical/policy.rs
- linkerd/app/outbound/src/http/retry.rs
- linkerd/app/outbound/src/ingress.rs
- linkerd/app/outbound/src/opaq/concrete.rs
- linkerd/app/outbound/src/protocol.rs
- linkerd/app/outbound/src/tls/concrete.rs
- linkerd/retry/src/lib.rs
- linkerd/service-profiles/src/http.rs
- linkerd/service-profiles/src/proto.rs
- linkerd/stack/src/either.rs
- linkerd/stack/src/either/vendor.rs
- linkerd/stack/src/loadshed.rs
- linkerd/stack/src/queue.rs
- linkerd/stack/src/unwrap_or.rs
this commit updates our tower dependency from 0.4 to 0.5.
note that this commit does not affect the `tower-service` and
`tower-layer` crates, reëxported by `tower` itself. the `Service<T>`
trait and the closely related `Layer<S>` trait have not been changed.
the `tower` crate's utilities have changed in various ways, some of
particular note for the linkerd2 proxy. see these items, excerpted from
the tower changelog:
- **retry**: **Breaking Change** `retry::Policy::retry` now accepts `&mut Req` and `&mut Res` instead of the previous mutable versions. This
increases the flexibility of the retry policy. To update, update your method signature to include `mut` for both parameters. ([tower-rs/tower#584])
- **retry**: **Breaking Change** Change Policy to accept &mut self ([tower-rs/tower#681]) …
> chore(deps): upgrade to tower 0.5

- .github/workflows/pr.yml
- justfile
We can run our testing k3d cluster with minimal components enabled. This will speed up the cluster creation and deletion process (i.e. especially in CI).
> chore(ci): disable unnecessary k3s components

- linkerd/dns/src/lib.rs
- linkerd/proxy/dns-resolve/src/lib.rs
this branch makes a small, targeted fix to mitigated the excessive rate of DNS queries described in linkerd/linkerd2#13508. this bounds the rate at which worker tasks returned by `<linkerd_dns_resolve::DnsResolve as tower::Service<T>::call()` will attempt to refresh DNS records.
this branch does so in two small steps: first, the `linkerd_dns::Resolver::resolve_addrs()` function is changed to return a `tokio::time::Instant` instead of a `tokio::time::Sleep`. then, the `resolution` worker is extended with a minimum delay it will wait before continuing.
---
i ran this locally with a small workload, on a local cluster. because the rate of these DNS queries is a factor of the number of control plane clients, i used this job/deployment pair to create 64 servers and a load-generator sending 100 …
> fix(dns-resolve): add a lower-bound TTL for dns refreshing

- linkerd/proxy/resolve/src/recover.rs
this commit addresses a todo comment in the `linkerd-proxy-resolve` crate. this comment mentioned that a `match` block was originally an `if let` block. a clippy lint was locally ignored as well, regarding `match` statements with a single pattern.
contrary to the comment, `if let` *does* work with pin projection, as of today.
> nit(proxy-resolve): address `XXX` comment

- .github/dependabot.yml
this commit introduces a new dependabot group.
this will update all of the crates maintained by the icu4x organization
in lockstep. we depend upon these transitively to handle urls.
```
; cargo tree | rg icu_ | rg 'icu_\w*' --only-matching | sort | uniq
icu_collections
icu_locid
icu_locid_transform
icu_locid_transform_data
icu_normalizer
icu_normalizer_data
icu_properties
icu_properties_data
icu_provider
icu_provider_macros
```
see:
- https://docs.rs/icu/latest/icu/
- https://icu.unicode.org/
- https://github.com/orgs/unicode-org/repositories?type=all
- https://crates.io/crates/idna
- https://github.com/linkerd/linkerd2-proxy/pull/3811
- https://github.com/linkerd/linkerd2-proxy/pull/3812
- https://github.com/linkerd/linkerd2-proxy/pull/3813
> chore(deps): dependabot group for unicode components

- linkerd/app/core/src/dns.rs
- linkerd/app/src/env.rs
`LINKERD2_PROXY_RESOLV_CONF` is an environment variable that ostensibly is used to set the path of the resolver configuration file.
this connects to a `resolv_conf_path` field in the application's dns `Config` structure, but that field is never used.
because it is marked as public, this isn't caught by the compiler's dead code analysis.
see `resolv.conf(5)` for more information.
> refactor(app/core): remove unused dns configuration surface

- linkerd/app/src/lib.rs
this commit changes a message for a debug-level tracing event.
this block builds a trace collector. we can call it that, instead of the more generic term "client". there are many clients being built here, including identity, policy, and destination controller clients.
> nit(app): tweak debug event message

- justfile
The latest edge doesn't properly install gateway API crds. This changes our justfile to install the resources from the upstream release instead of the Linkerd CLI.
> fix(ci): work around broken `linkerd install --crds`

- Cargo.lock
- linkerd/app/core/src/dns.rs
- linkerd/app/core/src/dns/metrics.rs
- linkerd/app/src/lib.rs
- linkerd/dns/Cargo.toml
- linkerd/dns/src/lib.rs
this commit introduces a new metric family tracking the rate and outcome
of dns lookups made by the linkerd2 proxy. this metric family has two
labels, tracking (a) the control plane client responsible for a
particular lookup, (b) the outcome of the lookup.
this metric is named `control_dns_resolutions_total`.
this metric includes labels to count DNS resolutions for each distinct
control plane client, by record type (A/AAAA or SRV), and by outcome
(success or failure).
this commit generally does this via the addition of some new interfaces
to `linkerd-dns`'s `Resolver` structure. the `resolve_addrs()` method is
extended to increment particular counters if they have been installed.
the `linkerd-app` crate's `Dns` type now encapsulates its resolver, and
callers acquire a new resolver by …
> feat(app,dns): add prometheus metrics to `Dns`

- .github/dependabot.yml
this adds `tokio-boring` to the `boring` group.
this will group these crates together and bump them in lockstep.
see, for example:
* #3838
* #3840
> chore(deps): add `tokio-boring` to dependabot group

- Cargo.lock
- linkerd/app/outbound/Cargo.toml
- linkerd/app/outbound/src/http/logical/policy/route/metrics/tests.rs
- linkerd/http/prom/src/record_response.rs
this commit fixes a bug discovered by @alpeb, which was introduced in proxy
v2.288.0.
> The associated metric is `outbound_http_route_request_statuses_total`:
>
> ```
> $ linkerd dg proxy-metrics -n booksapp deploy/webapp|rg outbound_http_route_request_statuses_total.*authors
> outbound_http_route_request_statuses_total{parent_group="core",parent_kind="Service",parent_namespace="booksapp",parent_name="authors",parent_port="7001",parent_section_name="",route_group="",route_kind="default",route_namespace="",route_name="http",hostname="",http_status="204",error=""} 5
> outbound_http_route_request_statuses_total{parent_group="core",parent_kind="Service",parent_namespace="booksapp",parent_name="authors",parent_port="7001",parent_section_name="",route_group="",route_kind="default",route_namespac …
```
> fix(http/prom): record bodies when eos reached

- .github/dependabot.yml
we use the `symbolic-common` and `symbolic-demangle` crates in our dependency tree. these live in the same repo, here: <https://github.com/getsentry/symbolic>
this commit introduces a "group" so that dependabot will upgrade them in lockstep, rather than individually, such as in pull requests like
#3853, #3852, #3857, #3858, or #3860.
> chore(deps): group symbolic dependencies

- linkerd/proxy/client-policy/src/lib.rs
- linkerd/proxy/client-policy/src/tls.rs
In 65db3dd we enabled overriding the behavior to export TLS hostnames for outbound traffic, but we omitted TLS hostname labels.
This change updates the tls module to mirror the http module's behavior.
> fix(client-policy): enable TLS hostnames via overrides

- .devcontainer/devcontainer.json
- .github/copilot-instructions.md
This introduces a GitHub Copilot instructions file under .github to guide AI-driven code generation and updates the devcontainer configuration accordingly.
The new instructions enforce Rust styling, error handling, and tracing conventions across the project. It ensures generated code passes `cargo fmt` and `clippy`, avoids unwraps, and uses structured logging.
> chore(dev): introduce copilot instructions

- linkerd/http/retry/src/replay/tests.rs
the initial replay body, circa the usage of our "compatibility" layer (4b53081, #3598), used to need an extra poll to confirm the absence of trailers before it would report itself as reaching the end of the stream. these tests were added in (afda8a7b3, #3583).
this was an artifact of how the compatibility middleware masked the previous `poll_data()` and `poll_trailer()` methods behind a forward-compatible `poll_frame()`- and `frame()`-oriented interface.
this commit removes these extra calls to `initial.frame().await`, now that the initial body will report the end of stream without an extra call to await a `None`.
* #3598
* #3583
> nit(http/retry): remove extra body poll in tests

- Cargo.lock
- deny.toml
- linkerd/meshtls/Cargo.toml
- linkerd/meshtls/rustls/Cargo.toml
- linkerd/meshtls/rustls/src/backend.rs
- linkerd/meshtls/rustls/src/backend/aws_lc.rs
- linkerd/meshtls/rustls/src/backend/ring.rs
- linkerd/meshtls/rustls/src/creds.rs
- linkerd/meshtls/rustls/src/creds/receiver.rs
- linkerd/meshtls/rustls/src/lib.rs
- linkerd2-proxy/Cargo.toml
- linkerd2-proxy/src/main.rs
This has a few benefits. Primarily this gives us a reasonable path to creating FIPS-enabled builds on architectures other than x86-64, as well as a path away from using BoringSSL as a backend.
Additionally, rustls has been using the aws-lc-rs library as the default backend for a little while now, so this gives us the opportunity to stay in line with the most widely used option in the ecosystem.
> Add aws-lc-rs as optional rustls backend

- linkerd/app/integration/Cargo.toml
this alphabetizes dependencies in `linkerd-app-integration`'s manifest.
> nit(app/integration): sort cargo dependencies

- linkerd/proxy/http/src/client.rs
- linkerd/proxy/http/src/h1.rs
- linkerd/proxy/http/src/orig_proto.rs
this is a small mechanical refactor to the http/1 client.
our http/2 and "orig_proto" clients are tower services. our http/1 client, on the other hand, exposes a concrete inherent method `request`.
to be consistent, this changes our http client to treat this http/1 client as a service as well.
> refactor(proxy/http): http/1 client is a `Service<T>`

- linkerd/app/outbound/src/tcp/connect.rs
- linkerd/app/outbound/src/tcp/tagged_transport.rs
this structure exposes its fields, but those fields are never accessed
elsewhere, aside from test code.
this commit removes the `pub` directives from the address and tls
fields. in their stead, test interfaces are added to allow the
`tagged_transport` test suite to function.
> refactor(app/outbound): `Connect` fields are not pub

- linkerd/app/src/env.rs
- linkerd/dns/src/lib.rs
- linkerd/meshtls/rustls/src/creds.rs
- linkerd/proxy/client-policy/src/http.rs
- linkerd/proxy/client-policy/src/lib.rs
the `linkerd-error` crate includes two functions that can be used to
examine the cause of a dynamic, boxed error. for example, here is the
`is_caused_by()` function, used in some of our error recovery logic:
```rust
/// Determines whether the provided error was caused by an `E` typed error.
pub fn is_caused_by<E: std::error::Error + 'static>(
mut error: &(dyn std::error::Error + 'static),
) -> bool {
loop {
if error.is::<E>() {
return true;
}
error = match error.source() {
Some(e) => e,
None => return false,
};
}
}
```
we rely on [`thiserror`](https://github.com/dtolnay/thiserror/) to
generate boilerplate code for our error structures. this includes an
attribute called `transparent` that will delegate down to an inner
error.
however, this delegation means that the causal chains inspected …
> fix: report error causes properly

- linkerd/proxy/http/src/client.rs
- linkerd/proxy/http/src/orig_proto.rs
this commit introduces a concrete error type for the `orig_proto` upgrade layer.
this layer is used by the proxy's http client to transparently upgrade outbound http/1 traffic to http/2. rather than boxing errors, we define a concrete error type to facilitate inspecting errors in the future.
for now, the top-level http client continues to box errors thrown by the "orig_proto" upgrade client.
**nb:** this is based upon #3894.
> refactor(proxy/http): a concrete `orig_proto` error

- linkerd/app/src/lib.rs
this is a trivial, cosmetic change.
`Config` has two consecutive `impl` blocks in the `linkerd-app` library. these do not include distinct generics or trait bounds, so the methods contained therein do not need to live in two distinct `impl` blocks.
this commit consolidates these blocks.
while we are performing this change, we add two `=== impl T ===` banners, which are used throughout the project as greppable strings to find methods and trait implementations for a given type.
> nit(app): consolidate `impl Config` blocks

- linkerd/meshtls/boring/Cargo.toml
i noticed while examining how our meshtls feature flags interact that these dependencies are not sorted. this runs `:sort` across the dependencies listed in `linkerd-meshtls-boring`'s package manifest.
> chore(meshtls/boring): sort dependencies

- linkerd/app/test/src/lib.rs
`linkerd-app-test` exposes some functions that we never use elsewhere.
this commit removes these functions.
> chore(app/test): remove unused functions

- linkerd/app/src/env.rs
- linkerd/app/src/identity.rs
- linkerd/app/src/spire.rs
This change does two things: 
- adds support for `NamedPipes` to our SPIRE client. This will allow the client to connect to spire agents running on Windows hosts
- renames the `LINKERD2_PROXY_IDENTITY_SPIRE_SOCKET` to `LINKERD2_PROXY_IDENTITY_SPIRE_WORKLOAD_API_ADDRESS` and deprecates the former.
> identity(spire): provide named pipe support for spire

- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/metrics.rs
- linkerd/app/core/src/transport/labels.rs
- linkerd/app/inbound/src/detect.rs
- linkerd/app/inbound/src/direct.rs
- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/tests.rs
- linkerd/app/inbound/src/metrics/authz.rs
- linkerd/app/inbound/src/policy/http.rs
- linkerd/app/inbound/src/policy/tcp.rs
- linkerd/app/outbound/src/http/concrete.rs
- linkerd/app/outbound/src/http/endpoint/tests.rs
- linkerd/app/outbound/src/opaq/concrete.rs
- linkerd/app/outbound/src/tls/concrete.rs
- linkerd/tls/src/client.rs
- linkerd/tls/src/lib.rs
- linkerd/tls/src/server.rs
the linkerd2 proxy implements, registers, and exports Prometheus metrics using a variety of systems, for historical reasons. new metrics broadly rely upon the official [`prometheus-client`](https://github.com/prometheus/client_rust/) library, whose interfaces are reexported for internal consumption in the [`linkerd_metrics::prom`](https://github.com/linkerd/linkerd2-proxy/blob/main/linkerd/metrics/src/lib.rs#L30-L60) namespace.
other metrics predate this library however, and rely on the metrics registry implemented in the workspace's [`linkerd-metrics`](https://github.com/linkerd/linkerd2-proxy/tree/main/linkerd/metrics) library.
* https://github.com/linkerd/linkerd2/issues/13821
linkerd/linkerd2#13821 reported a bug in which duplicate metrics could be observed and subsequently dropped by …
> fix: remove ambiguous metrics registry keys

- linkerd/app/src/env.rs
The inbound and outbound connect backoffs are now set at 500ms. This is very aggressive in practice, especially when an endpoint remains unavailable.
This change increases the maximum backoff durations:
* inbound: 10s
* outbound: 60s
The default minimum backoff durations remain unchanged at 100ms so that failed connections are retried quickly. This change only increases the default _maximum_ backoff so that the timeout increases substantially when an endpoint is unavailable for a longer period of time.
> chore(app): increase default max backoff durations

- linkerd/meshtls/rustls/src/backend/aws_lc.rs
- linkerd/meshtls/rustls/src/backend/ring.rs
This is a strong ciphersuite that's reasonable to include as a supported option. We still prefer CHACHA20_POLY1305 in non-FIPS modes for its speed, as well as keeping CHACHA20_POLY1305 as a backup for older proxies that only support it.
> feat(meshtls): Include AES_256_GCM as a supported ciphersuite

- linkerd/proxy/http/src/h1.rs
When constructing the HTTP/1 client, we configure connection pooling, but notably do not provide a timer implementation to Hyper. This causes hyper's connection pool to be configured without idle timeouts, which may lead to resource leaks, especially for clients that communicate with many virtual hosts.
This change updates the HTTP/1 client builder to use a Tokio timer, which allows Hyper to manage idle timeouts correctly.
> fix(http): fix HTTP/1 client idle timeouts

- linkerd/app/src/env.rs
see also:
* https://github.com/linkerd/linkerd2-proxy/pull/4004
* https://github.com/linkerd/linkerd2/issues/14204
in https://github.com/linkerd/linkerd2-proxy/pull/4004 we fixed an issue related to our HTTP/1.1 client's connection
pool.
this further hedges against future issues related to our HTTP client
exhausting resources available to its container. today, the limit by
default is `usize::MAX`, which is dramatically higher than the practical
limit.
this commit changes the limit for outbound idle connections per-host to
10,000.
> fix(app/env): a lower default maximum per-host connection limit

- linkerd/app/src/env.rs
The inbound connection pool is effectively unlimited. This change configures a default limit of 10K.
> fix(app/env): limit default inbound connection pool size

- Cargo.lock
- linkerd2-proxy/Cargo.toml
- linkerd2-proxy/src/main.rs
tikv-jemallocator supersedes jemallocator. To enable jemalloc profiling, this change updates the dependency and adds a `jemalloc-profiling` feature so that profiling can be enabled at build time.
> chore(deps): update jemallocator 0.5 to tikv-jemallocator 0.6

- linkerd/meshtls/rustls/src/backend/aws_lc.rs
- linkerd/meshtls/rustls/src/backend/ring.rs
This makes two changes to the preferred cipher suite order.
- Prefer AES algorithms over ChaCha20. AES is significantly faster when AES hardware is present, and AES hardware is on all x86 CPUs since ~2010, and all ARM server CPUs for a similar amount of time. For these reasons it's reasonable to default to AES for modern deployments, and it's the same default that `aws-lc-rs` makes anyway.
- Remove ChaCha20 when FIPS is enabled. It's no longer a supported algorithm, so we shouldn't have it as an option.
> fix(tls): Update preferred cipher suite order

- Cargo.lock
- Cargo.toml
- linkerd/app/inbound/Cargo.toml
- linkerd/app/integration/Cargo.toml
- linkerd/app/integration/src/identity.rs
- linkerd/app/outbound/Cargo.toml
- linkerd/meshtls/Cargo.toml
- linkerd/meshtls/rustls/Cargo.toml
- linkerd/meshtls/rustls/src/backend.rs
- linkerd/meshtls/rustls/src/creds.rs
- linkerd/meshtls/rustls/src/creds/receiver.rs
- linkerd/meshtls/rustls/src/creds/store.rs
- linkerd/meshtls/verifier/Cargo.toml
- linkerd/proxy/spire-client/Cargo.toml
Currently, disabling the `ring` feature does not actually disable the dependency across the tree. Doing so requires a couple of tightly coupled steps:
- Making `ring` and `aws-lc` exclusive features, raising a compile error if they are both enabled.
- Removing a direct dependency on some `ring` types, and instead going through `rustls` for equivalent functionality.
- Removing a direct dependency on the `ring` crypto provider for integration tests, and instead using the provider from `linkerd-meshtls`.
- Installing the default crypto provider globally for the process and re-using it when requested, mostly to make the tests pass.
This was tested using a temporary `cargo deny` config that forbid `ring` when `aws-lc-rs` was used, and vice-versa. Note that it doesn't completely remove ring for …
> fix(rustls): Make `ring` and `aws-lc-rs` exclusive features

- .github/workflows/release.yml
- deny.toml
- justfile
This architecture has become too significant of a maintenance burden, and isn't used often enough to justify the associated maintenance cost.
This removes arm/v7 from all the build infrastructure/dockerfiles/etc. Note that arm64 targets are still widely used and well supported.
Related: https://github.com/linkerd/linkerd2/pull/14308
> feat!(ci): Remove arm/v7 support

- Cargo.lock
- linkerd/app/core/Cargo.toml
- linkerd/app/core/src/lib.rs
- linkerd/app/core/src/tls_info.rs
- linkerd/app/src/lib.rs
This includes a small set of metrics about the currently installed rustls crypto provider and the algorithms it is configured to use.
We don't have 100% assurance that a default crypto provider has been installed before registering the metric, but in local testing it never appeared to be a problem. When we refactor the rustls initialization we can add an extra guarantee that we've initialized it by this point.
Example metric:
```
rustls_info{tls_suites="TLS13_AES_128_GCM_SHA256,TLS13_AES_256_GCM_SHA384,TLS13_CHACHA20_POLY1305_SHA256,",tls_kx_groups="X25519,secp256r1,secp384r1,X25519MLKEM768,",tls_rand="AwsLcRs",tls_key_provider="AwsLcRs",tls_fips="false"} 1
```
> feat(tls): Include rustls crypto provider metrics

- linkerd/app/admin/src/server.rs
- linkerd/app/admin/src/stack.rs
- linkerd/app/core/src/metrics.rs
- linkerd/app/core/src/transport/labels.rs
- linkerd/app/inbound/src/metrics.rs
- linkerd/app/inbound/src/metrics/authz.rs
- linkerd/app/inbound/src/metrics/error.rs
- linkerd/app/inbound/src/metrics/error/http.rs
- linkerd/app/inbound/src/metrics/error/tcp.rs
- linkerd/app/outbound/src/metrics.rs
- linkerd/app/outbound/src/metrics/error.rs
- linkerd/app/outbound/src/metrics/error/http.rs
- linkerd/app/outbound/src/metrics/error/tcp.rs
- linkerd/app/src/lib.rs
- linkerd/http/metrics/src/lib.rs
- linkerd/http/metrics/src/requests.rs
- linkerd/http/metrics/src/requests/report.rs
- linkerd/http/metrics/src/requests/service.rs
- linkerd/http/metrics/src/retries.rs
- linkerd/metrics/src/counter.rs
- linkerd/metrics/src/histogram.rs
- linkerd/metrics/src/lib.rs
- linkerd/metrics/src/new_metrics.rs
- linkerd/metrics/src/serve.rs
- linkerd/metrics/src/store.rs
- linkerd/opencensus/src/metrics.rs
- linkerd/opentelemetry/src/metrics.rs
- linkerd/stack/metrics/src/lib.rs
- linkerd/transport-metrics/src/lib.rs
- linkerd/transport-metrics/src/report.rs
`linkerd-metrics` contains a suite of facilities for defining, registering, and serving Prometheus metrics. these predate the [`prometheus-client`](https://crates.io/crates/prometheus-client/) crate, which should now be used for our metrics.
`linkerd-metrics` defines a `prom` namespace, which reëxports symbols from the `prometheus-client` library. as the documentation comment for this submodule notes, this should be used for all new metrics.
https://github.com/linkerd/linkerd2-proxy/blob/6b323d84579d5d7774e733052a281602465ccc2c/linkerd/metrics/src/lib.rs#L30-L60
`linkerd-metrics` still provides its legacy types in the public surface of this library today, which can make it difficult to differentiate between our two metrics implementations.
this branch introduces a new `legacy` namespace, …
> refactor(metrics): introduce a `legacy` namespace

- linkerd/http/classify/src/channel.rs
- linkerd/http/classify/src/lib.rs
`NewBroadcastClassification<C, X, N>` is not used.
`BroadcastClassification<C, S>` is only used by the `gate` submodule in this crate.
this commit removes `NewBroadcastClassification`, since it is unused. this commit demotes `channel` to an internal submodule, since it has no external users.
the reëxport of `BroadcastClassification` is unused, though it is left intact because it _is_ exposed by `NewClassifyGateSet`'s implementation of `NewService<T>`.
> refactor(http/classify): remove unused classification middleware

- linkerd/tls/src/server.rs
this function is an implementation detail for TLS detection middleware.
this does not need to be `pub(crate)`, thereby exposing it to the rest of the `linkerd-tls` crate.
this commit removes this visibility from the `detect_sni()` function.
> refactor(tls): do not export `detect_sni`

- linkerd/rustls/src/crypto.rs
This removes `SECP256R1MLKEM768` as a supported algorithm when FIPS mode is enabled in the proxy.
> fix(tls): Remove post-quantum algorithms from FIPS

- linkerd/app/inbound/src/direct.rs
this type is never used. it can be removed.
> refactor(app/inbound): remove unused `RefusedNoHeader` type

- .github/dependabot.yml
`arbitrary` and `derive_arbitrary` are part of the same repository: <https://github.com/rust-fuzz/arbitrary/>
these should be bumped in lockstep, rather than as separate pull requests. see for example, previously:
- 99f322a9a
- edc35d6e1
> chore(dependabot): add `arbitrary` group

- linkerd/app/inbound/src/policy.rs
this commit replaces comments with documentation comments for some
types in the inbound proxy.
> nit(app/inbound): use documentation comments

- linkerd/router/src/lib.rs
> nit(router): fix comment typo

- linkerd/app/core/src/svc.rs
this `impl` block is ~350 lines, and contains the majority of our
`linkerd_app_core::svc::Stack<S>` interfaces.
this does not need to be marked with this `dead_code` allowance, because
these are public interfaces.
this commit removes this attribute. if future additions include unused
code, we can more narrowly affix this attribute to particular functions.
> chore(app/core): remove `dead_code` allowance for `Stack<S>`

- .github/workflows/release.yml
The update to download-artifact broke the release workflow on PRs.
> fix(release): fix download-artifact paths

- .github/dependabot.yml
this commit introduces a dependabot group that will manage `serde`, and
its constituent crates like `serde_json`, `serde_core`, and
`serde_derive`, in unison.
see redundant pull requests such as linkerd/linkerd2-proxy#4158 and
linkerd/linkerd2-proxy#4159 for a motivating example.
> chore(deps): introduce a `serde` dependabot group

- linkerd/http/route/src/http/filter/redirect.rs
Fixes https://github.com/linkerd/linkerd2/issues/14110
When using a `HTTPRoute` `RequestRedirect` filter with a `ReplacePrefixMatch`, the proxy incorrectly returns an error: `redirect paths must be absolute`.  This is because the validation logic is backwards and it returns this error when the redirect path IS absolute.
We correct the validation logic by inverting it.
> fix(http/route): fix prefix path validation

- linkerd/app/inbound/src/http/router.rs
- linkerd/app/inbound/src/http/router/metrics.rs
- linkerd/app/inbound/src/policy.rs
- linkerd/app/inbound/src/policy/http.rs
https://github.com/linkerd/linkerd2-proxy/pull/4119 introduced a `Permitted<T>` structure, to provide a more formal notion of a `(HttpRoutePermit, T)` tuple.
during review of https://github.com/linkerd/linkerd2-proxy/pull/4180, we had a discussion about how the inbound proxy's http router had metrics layers which were tightly coupled to the notion of a `Permitted<T>`:
> This isn't a hard blocker--but this is unfortunate that we're coupling this impl to the Permitted target type -- target types are usually an _internal implementation detail_ and not a public api that is depended on elsewhere.
> 
> The typical pattern for this would be to have a dump bespoke param in this module like:
> 
> ```rust
> pub enum MetricsVariant { Http, Grpc }
> ```
> 
> and then have our Permitted impl …
> refactor(app/inbound): router metrics middleware are `T`-agnostic

- linkerd/app/inbound/src/http/router/metrics.rs
our metrics layer is generic across an `N`-typed service factory.
this commit introduces types aliases that apply `X`-typed extractor
parameters to the `linkerd-http-prom` middleware, which are unaware of
a concrete metrics extractor.
we use this to reduce the complexity of the `layer()` function's
type signature.
see linkerd/linkerd2-proxy#4180.
NB: based upon linkerd/linkerd2-proxy#4188, and
linkerd/linkerd2-proxy#4186.
> refactor(app/inbound): type aliases specify extractors

- linkerd/app/core/src/svc.rs
this commit introduces an `into_inner()` method to `Layers<L>`.
like the equivalent method for `Stack<S>`, it provides a way to consume
the stack or layer, returning the inner `L`-typed layers.
> feat(app/core): add `Layers::into_inner()`

- linkerd/app/inbound/src/http/router/metrics.rs
- linkerd/app/inbound/src/metrics.rs
this commit introduces an additional layer of telemetry to the inbound
proxy's http router.
either http and grpc metrics are used, depending upon the policy that
authorized a given request.
this is based upon linkerd/linkerd2-proxy#4174, which refactored the
request body telemetry middleware to be metrics agnostic.
this change is based upon a collection of small prerequisite changes:
* linkerd/linkerd2-proxy#4189
* linkerd/linkerd2-proxy#4188
* linkerd/linkerd2-proxy#4187
* linkerd/linkerd2-proxy#4186
* linkerd/linkerd2-proxy#4174
related previous work:
* linkerd/linkerd2-proxy#4165
* linkerd/linkerd2-proxy#4166
* linkerd/linkerd2-proxy#4127
> feat(app/inbound): request body frame size metrics

- linkerd/opentelemetry/src/lib.rs
Our trace span exporter uses batching logic to avoid making excessive requests to the trace collector. It does this by either waiting for the batch buffer to hit a maximum number of spans (currently 1000), or waiting for no spans to be collected in some timeout window (currently 10s).
If a workload emits spans at a slow but consistent rate, say 1 span/s, it would cause the timeout window to never be hit while the buffer slowly fills. At this rate, it would cause spans to not be emitted for a long time.
This replaces the timeout window with an interval timer that attempts to send the currently buffered spans on a consistent interval, regardless of if the collector has sat idle. This interval is set to 10s to match the current idle timeout, but this can be tuned in the future along with the …
> fix(tracing): Flush spans on interval instead of idle timeout

- linkerd/app/inbound/src/http/router/metrics.rs
- linkerd/app/inbound/src/http/router/metrics/labels.rs
- linkerd/app/inbound/src/policy/http.rs
in linkerd/linkerd2-proxy#4180, we noted during review that encoding
prometheus labels for route and parent metadata entails a slightly
unfortunate amount of repetitive boilerplate.
in the outbound proxy, we define a local `RouteLabels` type that
implements the `EncodeLabelSet` and `EncodeLabelSetMut`, which we use to
integrate label sets with the `prometheus_client` SDK.
this commit introduces an equivalent pattern to the inbound proxy. a
`RouteLabels` newtype wrapper over the shared `linkerd_app_core`
structure is introduced, which in turn simplifies the `EncodeLabelSet`
and `EncodeLabelSetMut` implementations of the `RequestCountLabels`,
`ResponseBodyDataLabels`, and `RequestBodyDataLabels` types.
> refactor(app/inbound): consolidate route label encoding

- .devcontainer/devcontainer.json
- .github/workflows/beta.yml
- .github/workflows/coverage.yml
- .github/workflows/fuzzers.yml
- .github/workflows/nightly.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/shellcheck.yml
- .github/workflows/toolchain.yml
- Dockerfile
- linkerd/app/integration/src/tests/profiles.rs
- linkerd/http/prom/src/record_response.rs
- linkerd/http/route/src/grpc/match.rs
- rust-toolchain.toml
- rust v1.90.0
- clippy lints addressed
> build(deps): bump dev to v48

- Cargo.lock
- linkerd/app/core/src/http_tracing.rs
- linkerd/app/src/env.rs
- linkerd/app/src/trace_collector.rs
- linkerd/app/src/trace_collector/otel_collector.rs
There were a few abstractions over the trace backend (enums, etc.) that can be removed now that OpenCensus has been removed in https://github.com/linkerd/linkerd2-proxy/pull/4216.
> chore(tracing): Remove OpenCensus remnants

- linkerd/app/outbound/src/http/logical/policy/route/backend.rs
- linkerd/app/outbound/src/http/logical/policy/route/backend/metrics.rs
- linkerd/app/outbound/src/http/logical/policy/route/metrics.rs
- linkerd/http/prom/src/lib.rs
- linkerd/http/prom/src/record_response.rs
- linkerd/http/prom/src/stream_label.rs
`linkerd_http_prom::record_response` defines a pair of traits that are
used to derive labels for prometheus metrics. this is used to install
telemetry that inspects the response body, which is helpful for
recording response latency, and inspecting gRPC status codes.
this is a helpful model. to help reuse this trait, we hoist it out of
`record_response` and into a dedicated submodule.
> refactor(http/prom): hoist `MkStreamLabel` out of `record_response`
