linkerd/linkerd2-proxy

GOVERNANCE.md, MAINTAINERS.md
For the time being, @briansmith and I will serve as super-maintainers
for the linkerd2-proxy.
=> Adopt Linkerd2's governance

src/control/destination/background.rs, src/lib.rs, src/telemetry/control.rs
When the proxy is shutting down, once there are no more outbound
connections, the sender side of the resolver channel is dropped. In the
admin background thread, when the destination background future is
notified of the closure, instead of shutting down itself, it just busy
loops. Now, after seeing shutdown, the background future ends as well.
While examining this, I noticed all the background futures are joined
togther into a single `Future` before being spawned on a dedicated
current_thread executor. Join in this case is inefficient, since *every*
single time *one* of the futures is ready, they are *all* polled again.
Since we have an executor handy, it's better to allow it to manage each
of the futures individually.
------
I can't prove that this is the cause for …
=> remove busy loop from destination background future during shutdown

src/telemetry/metrics/labels/mod.rs, tests/telemetry.rs
Fixes linkerd/linkerd2#1276.
Currently, metrics with the `tls="no_identity"` label are duplicated.
This is because that label is generated from the `tls_status` label on
the `TransportLabels` struct, which is either `Some(())` or a
`ReasonForNoTls`. `ReasonForNoTls` has a
variant`ReasonForNoTls::NoIdentity`, which contains a
`ReasonForNoIdentity`, but when we format that variant as a label, we
always just produce the string "no_identity", regardless of the value of
the `ReasonForNoIdentity`. 
However, label types are _also_ used as hash map keys into the map that
stores the metrics scopes, so although two instances of
`ReasonForNoTls::NoIdentity` with different `ReasonForNoIdentity`s
produce the same formatted label output, they aren't _equal_, since that
field differs, so they correspond …
=> Add labels for `tls::ReasonForNoIdentity`

src/control/destination/background.rs, src/lib.rs, src/telemetry/control.rs
This reverts commit 4bee7b0b55f6556de45f9999a19293ed2ed2b319.
Signed-off-by: Sean McArthur <sean@buoyant.io>
=> Revert "remove busy loop from destination background future during shutdown (#8)"

src/lib.rs, src/telemetry/control.rs, src/telemetry/sensor/mod.rs, src/telemetry/sensor/transport.rs, src/transparency/server.rs, src/transport/connect.rs, src/transport/connection.rs, src/transport/mod.rs
This allows easier logging configuration for the entire transport system
using the common prefix `conduit_proxy::transport`. Previously logging had to be
controlled separately/additionally for `conduit_proxy::connection`.
=> Move `connection` submodule to `transport`.

src/config.rs, src/control/destination/background.rs, src/control/destination/mod.rs, src/control/util.rs, src/lib.rs, tests/discovery.rs, tests/support/controller.rs
The `Backoff` service wrapper is used for the controller client service
so that if the proxy can't find the controller (there is a connection
error), it doesn't keep trying in a tight loop, but instead waits a
couple seconds before trying again, presuming that the control plane
was rebooting.
When "backing off", a timer would be set, but it wasn't polled, so the
task was never registered to wake up after the delay. This turns out to
not have been a problem in practice, since the background destination
task was joined with other tasks that were constantly waking up,
allowing it to try again anyways.
To add tests for this, a new `ENV_CONTROL_BACKOFF_DELAY` config value
has been added, so that the tests don't have to wait the default 5
seconds.
Signed-off-by: Sean McArthur <sean@buoyant.io>
=> fix control client Backoff to poll its timer when backing off

src/control/destination/background.rs
When the proxy is shutting down, once there are no more outbound
connections, the sender side of the resolver channel is dropped. In the
admin background thread, when the destination background future is
notified of the closure, instead of shutting down itself, it just busy
loops. Now, after seeing shutdown, the background future ends as well.
With #13 merged, and #10 being a separate change, this shouldn't break the proxy again. Related to https://github.com/linkerd/linkerd2/issues/1231
=> remove busy loop from destination background future when shutdown

Cargo.lock, Cargo.toml
Now that inotify-rs/inotify#105 has merged, we will no longer see
rampant CPU use from using the master version of `inotify`. I've updated
Cargo.toml to depend on master rather than on my branch.
=> Point inotify dependency at master

src/lib.rs, src/telemetry/control.rs
This was originally in #8, but I've separated it out since it is conceptually a different thing to fix.
=> spawn individual admin tasks instead of joining all

Cargo.lock, Cargo.toml
=> Upgrade TLS dependencies.

src/telemetry/metrics/process.rs
Fixes linkerd/linkerd2#1239.
The proxy's `process_cpu_seconds_total` metric is currently calculated
incorrectly and will differ from the CPU stats reported by other 
sources. This is because it currently calculates the CPU time by summing
the `utime` and `stime` fields of the stat struct returned by `procinfo`.
However, those numbers are expressed in _clock ticks_, not seconds, so
the metric is expressed in the wrong unit.
This branch fixes this issue by using `sysconf` to get the number of
clock ticks per second when the process sensor is created, and then
dividing `utime + stime` by that number, so that the value is expressed
in seconds.
(Note that the last column in `ps aux` output is the CPU time total)
```
eliza@ares:~$ ps aux | grep linkerd2-proxy | grep -v grep
eliza    40703  0.2 …
```
=> Fix incorrect process_cpu_seconds_total metric

src/lib.rs, src/transport/connection.rs, src/transport/tls/cert_resolver.rs, src/transport/tls/config.rs
Closes linkerd/linkerd2#1272.
Currently, if TLS is enabled but the TLS configuration isn't available
(yet), the proxy will pass through all traffic to the application.
However, the destination service will tell other proxies to send TLS
traffic to the pod unconditionally, so the proxy will pass through TLS
handshakes to the application that are destined for the proxy itself.
In linkerd/linkerd2#1272, @briansmith suggested that we change the 
proxy so that when it hasn't yet loaded a TLS configuration, it will
accept TLS handshakes, but fail them. This branch implements that 
behaviour by making the `rustls::sign::CertifiedKey` in `CertResolver`
optional, and changing the `CertResolver` to return `None` when 
`rustls` asks it to resolve a certificate in that case. The server
config watch …
=> Accept TLS connnections even when TLS configuration isn't available

Cargo.lock
This may help with https://github.com/linkerd/linkerd2/issues/1353, as the hyper upgrade includes https://github.com/hyperium/hyper/pull/1585, which a contributor had noticed and verified reduces TCP churn for them.
=> Update hyper and httparse versions

src/telemetry/sensor/http.rs, src/telemetry/sensor/mod.rs, src/transparency/client.rs, src/transparency/glue.rs, src/transparency/mod.rs, src/transparency/server.rs
Currently, the messages that the proxy logs on errors are often not 
very useful. For example, when an error occurred that caused the proxy
to return HTTP 500, we log a message like this:
```
ERR! proxy={server=in listen=0.0.0.0:4143 remote=127.0.0.1:57416} linkerd2_proxy turning Error caused by underlying HTTP/2 error: protocol error: unexpected internal error encountered into 500
```
Note that:
+ Regardless of what the error actually was, the current log message
*always* says protocol error: unexpected internal error encountered,
which is both fairly unclear *and* often not actually the case.
+ Regardless of whether the error was encountered by an HTTP/1 or 
HTTP/2 client, the error message always includes the string
"underlying HTTP/2 error". This is probably fairly confusing for …
=> Improve error messages in logs

src/lib.rs, src/telemetry/control.rs, src/transport/connection.rs
The way TLS is done for a bound port is fixed based on its role and whatever
the TLS settings are, so it makes sense to configure the TLS aspects of the
bound port during construction. This will also make writing tests easier.
=> Configure listen ports' TLS when constructing them.

benches/record.rs, src/telemetry/event.rs, src/telemetry/metrics/labels/mod.rs, src/telemetry/metrics/mod.rs, src/telemetry/metrics/record.rs, src/telemetry/sensor/transport.rs, tests/telemetry.rs
This branch adds a label displaying the Unix error code name (or the raw
error code, on other operating systems or if the error code was not 
recognized) to the metrics generated for TCP connection failures.
It also adds a couple of tests for label formatting.
=> Add errno label to transport close metrics (when applicable)

Cargo.lock, tests/support/server.rs, tests/transparency.rs
Specifically proxied bodies would make use of an optimization in hyper
that resulted in the connection not knowing (but it did know! just
didn't tell itself...) that the body was finished, and so the connection
was closed. 0.12.7 includes the fix in hyper.
As part of this upgrade, the keep-alive tests have been adjusted to send
a small body, since the empty body was not triggering this case.
I believe this fully fixes https://github.com/linkerd/linkerd2/issues/1353
=> update to hyper 0.12.7 to fix a keep-alive bug

src/bind.rs, src/config.rs, src/control/destination/background.rs, src/lib.rs, src/transport/connection.rs, src/transport/connection_tests.rs, src/transport/mod.rs, src/transport/tls/config.rs, src/transport/tls/mod.rs
Add a simple framework for TLS connection handling and some initial tests
that use it.
An explicit effort has been made to keep the test configuration as close to the
production configuration as possible; e.g. we use regular TCP sockets instead of some
mock TCP sockets. This matters less now, but will matter more later, if/when we
implement more low-level TLS-over-TCP optimizations.
Rename `ConnectionConfig::identity` to `ConnectionConfig::server_identity` to make
it clearer that it is always the identity of the server, regardless of which role
the `ConnectionConfig` is being used in.
=> Add initial tests for client and server connection handling w.r.t. TLS.

Cargo.lock, Cargo.toml
This branch updates the proxy's `h2` dependency to v0.1.11. This version
removes a busy loop when shutting down an idle server
(carllerche/h2#296), and fixes a potential panic when dropping clients
(carllerche/h2#295).
=> Update h2 version to v0.1.11

tests/telemetry.rs
Both tcp_connect_err tests frequently fail, even during local
development. This seems to happen because the proxy doesn't necessarily
observe the socket closure.
Instead of shutting down the socket gracefully, we can just drop it!
This helps the test pass much more reliably.
=> Improve tcp_connect_err test flakiness

src/config.rs, src/control/destination/background/destination_set.rs, src/control/destination/background/mod.rs, src/control/destination/mod.rs, src/control/remote_stream.rs, src/lib.rs, tests/discovery.rs
Required for linkerd/linkerd2#1322.
Currently, the proxy places a limit on the number of active routes
in the route cache. This limit defaults to 100 routes, and is intended
to prevent the proxy from requesting more than 100 lookups from the 
Destination service. 
However, in some cases, such as Prometheus scraping a large number of
pods, the proxy hits this limit even though none of those requests 
actually result in requests to service discovery (since Prometheus 
scrapes pods by their IP addresses). 
This branch implements @briansmith's suggestion in 
https://github.com/linkerd/linkerd2/issues/1322#issuecomment-407161829.
It splits the router capacity limit to two separate, configurable 
limits, one that sets an upper bound on the number of concurrently 
active destination lookups, and …
=> Limit concurrent Destination service queries

Cargo.lock, Cargo.toml, benches/record.rs, src/bind.rs, src/control/destination/background/destination_set.rs, src/control/destination/endpoint.rs, src/control/destination/mod.rs, src/ctx/mod.rs, src/inbound.rs, src/transparency/client.rs, src/transparency/glue.rs, src/transparency/h1.rs, src/transparency/mod.rs, src/transparency/orig_proto.rs, tests/discovery.rs, tests/support/controller.rs, tests/support/server.rs, tests/transparency.rs
When the destination service returns a hint that an endpoint is another
proxy, eligible HTTP1 requests are translated into HTTP2 and sent over
an HTTP2 connection. The original protocol details are encoded in a
header, `l5d-orig-proto`. When a proxy receives an inbound HTTP2
request with this header, the request is translated back into its HTTP/1
representation before being passed to the internal service.
Ref https://github.com/linkerd/linkerd2/issues/1360
=> Add orig-proto which uses HTTP2 between proxies

Cargo.lock, Cargo.toml, src/control/destination/background/client.rs, src/lib.rs
This branch should not make any functional changes.
This branch makes two minor refactorings to the `client` module in 
`control::destination::background`:
1. Remove the `AddOrigin` middleware and replace it with the 
`tower-add-origin` crate from `tower-http`. These middlewares are
functionally identical, but the Tower version has tests.
2. Change `ClientService` from a type alias to a tuple struct. This
means that some of the middleware that are used only in this module
(`LogErrors` and `Backoff`) are no longer part of a publicly visible
type and can be made private to the module.
=> Refactor control::destination::background::client module

src/telemetry/metrics/mod.rs, src/telemetry/metrics/process.rs
The `process` module exposes a `Sensor` type that is different from
other types called `Sensor`. Most `Sensor` types instrument other
types with telemetry. The `process::Sensor` type, on the other hand,
is used to read system metrics from the `/proc` filesystem, returning
a metrics summary.
Furthermore, `telemetry::metrics::Root` owns the process start time
metric.
In the interest of making the telemetry system more modular, this moves
all process-related telemetry concerns into the `process` module.
Instead of exposing a `Sensor` that produces metrics, a single public
`Process` type implements `fmt::Display` directly.
This removes process-related concerns from `telemetry/metrics/mod.rs` to
setup further refactoring along these lines.
=> Fully encapsulate process metrics in `mod process`

src/telemetry/metrics/labels/mod.rs, src/telemetry/metrics/mod.rs, src/telemetry/metrics/record.rs, src/telemetry/metrics/tls_config_reload.rs
Details of TLS configuration reload metrics span several modules.
This change consolidates all of this logic into a single
module with a single public type, `TlsConfigReload`, that supports
recording successful reloads, recording errors, and formatting its
current state.
This sets up further simplifications, eventually leading to the removal
of the `Event` API.
=> Consolidate telemetry::metrics::tls_config_reload

src/telemetry/metrics/labels/errno.rs, src/telemetry/metrics/labels/mod.rs
The `mk_err_enum` macro is only used in one place: the `labels::errno` module.
In order to make the main `labels` module simpler, the macro definition
can by moved into the errno module. If this macro is really generally
useful, it can be factored out later.
=> Move mk_err_enum into errno module

src/telemetry/metrics/mod.rs, src/telemetry/metrics/transport.rs
Metric eviction was introduced to protect against the situation where,
over time, the proxy addresses an effectively unbounded number of
endpoints. Metrics with endpoint-specific dimensions must be removed
over time to prevent a form of memory leak.
Eviction is implemented for transport stats. However, transport stats do
not yet contain per-endpoint dimensions. The eviction logic is
superfluous because transport metrics are bounded and small.
In preparation of changes to transport telemetry, this disables tracking
of transport metrics for eviction. This logic will be restored when we
support per-endpoint transport metrics.
=> Stop tracking transport metrics for eviction

src/telemetry/metrics/http.rs, src/telemetry/metrics/mod.rs, src/telemetry/metrics/process.rs, src/telemetry/metrics/tls_config_reload.rs, src/telemetry/metrics/transport.rs, src/telemetry/mod.rs
The `telemetry::metrics` module has a mix of core metrics types and
application-specific code. I'd like to change this module to only
contain core types. All app-specific module will be moved into
`telemetry`.
In order to make these changes, the `metrics!` macro (and related types)
must be visible to to `telemetry`. This change moves the macro
definition into the parent mod.rs, and makes the `Metric`, `FmtMetric`,
and `Scopes` types public.
In subsequent PRs, app-specific logic will be moved from
`telemetry::metrics` to `telemetry`, and the `telemetry::metrics`
module's public API will be minimized.
=> Make `metrics!` visible within `telemetry`

src/telemetry/metrics/http.rs, src/telemetry/metrics/mod.rs, src/telemetry/metrics/transport.rs
The `Scopes` type should'nt be critical to metrics formatting.
This change makes the `Metric` type unaware of `Scopes` so that other
labeling mechanisms can be used if appropriate.
Follows #55.
=> Make `Metric::fmt_scopes` generic over an Iterator

src/control/destination/background/destination_set.rs, src/control/destination/endpoint.rs, src/control/destination/mod.rs, src/ctx/http.rs, src/ctx/mod.rs, src/ctx/transport.rs, src/telemetry/mod.rs
Only the `DstLabels` and `Serve` types in `metrics` are used outside of
`telemetry`.
This change narrows visibility so that `metrics` is not referenced
outside of `telemetry`.
=> Make `metrics` private to `telemetry`

src/telemetry/metrics/labels.rs, src/telemetry/metrics/mod.rs, src/telemetry/metrics/record.rs, src/telemetry/metrics/transport.rs
Various transport-specific labels are defined in the common
`metrics::labels` module.
In preparation to refactor transport metrics into Sensor and Report
halves, this change moves all transport-specific labels into the
transport metrics module.
=> Consolidate labels into metrics::transport

tests/telemetry.rs
The `tcp_connect_err` tests do not pass on Linux.
I initially observed that the errno produced is ECONNREFUSED on Linux,
not EXFULL, but even changing this does not help the test to pass
reliably, as the socket teardown semantics appear to be slightly
different.
In order to prevent spurious test failures during development, this
change marks these two tests as macos-specific.
=> Mark tcp_connect_err tests as macos-specific

src/telemetry/metrics/mod.rs
005d4f1 made `Metric::fmt_scopes` generic over an Iterator, but
maintained some of the unnecessary type bounds inherited from its
initial implementation.
This change relaxes the constraints on the label value so that it need
not be passed as a reference or be hashable--our only requirement is
that it can be rendered.
=> Relax Metric::fmt_scopes' type bounds

src/telemetry/metrics/labels.rs, src/telemetry/metrics/mod.rs, src/telemetry/metrics/record.rs, src/telemetry/metrics/transport.rs
The `telemetry::metrics::transport` module exposes much of its
implementation details to callers, which makes it difficult to make
changes to how the module is structured. In preparation for further
refactors, this change narrows the module's public API:
All labels and scopes types have been made private. A single, public
`Transports` type has been introduce to describe the entire public
interface of the module. This has been crafted to be free of `event`
types and to have minimal external dependencies.
A new `transport::Eos` type has been introduced to replace the
overloaded `labels::Classification` type -- this type was initially
introduced to model _HTTP response_ classification, but it was
reused for transports. This is an undesirable coupling that will have to
be broken when we start …
=> Narrow transport metric's API

src/telemetry/metrics/transport.rs
Previously, transport metrics have been stored in two "scopes": an
"open" scope, storing metrics by transport class, and a "close" scope
storing metrics by transport and end-of-stream classes.
Instead of storing these as parallel maps, this changes transport
metrics to be stored hierarchically so that the end-of-stream metrics
are stored _within_ the transport metrics type.
This will make it possible to share the transport metrics structure
directly with the transport wrapper so that a global lock need only be
taken at connect-time. Subsequent updates will then be scoped to the
shared transport structure.
This helps to setup linkerd/linkerd2#1430, among other improvements.
Furthermore, the `Scopes` type is no longer used for transport metrics,
since it's much easier to use the full …
=> Store transport metrics hierarchically

src/telemetry/metrics/counter.rs, src/telemetry/metrics/gauge.rs, src/telemetry/metrics/histogram.rs, src/telemetry/metrics/http.rs, src/telemetry/metrics/labels.rs, src/telemetry/metrics/mod.rs, src/telemetry/metrics/prom.rs, src/telemetry/metrics/scopes.rs, src/telemetry/metrics/serve.rs, src/telemetry/metrics/transport.rs, src/telemetry/mod.rs, src/telemetry/process.rs, src/telemetry/tls_config_reload.rs
There are many different types of things that implement `fmt::Display`
in the metrics library: lists of key-value labels, individial label keys
or values, groups of metrics output, etc. While modifying metrics code,
it can be very easy to use something that's not a label in the context
of a label.
=> rfc: Introduce the FmtPrometheus and FmtLabels traits

src/control/destination/background/destination_set.rs, src/control/destination/endpoint.rs, src/control/destination/mod.rs, src/control/pb.rs, src/ctx/http.rs, src/ctx/mod.rs, src/ctx/transport.rs, src/telemetry/metrics/labels.rs, src/telemetry/metrics/mod.rs, src/telemetry/metrics/record.rs, src/telemetry/mod.rs, src/telemetry/tap/match_.rs
The `DstLabels` type has a large and undefined scope. Over time, it's
become critical in a variety of contexts, even outside of the scope of
prometheus endpoint labels.
This change makes `DstLabels` private to the
`telemetry::metrics::labels` module. This more clearly separates the
concerns of prometheus labeling from discovery, etc.
Now, destination metadata includes an index map of arbitrary metadata
labels.
Previously, dst label strings would be formatted eagerly at
service-discovery-time. This change moves this string formatting into
the data path(!). I think this is an acceptable tradeoff temporarily,
while we work to stop constructing RequestLabels in the data path
altogether.
=> Make telemetry::metrics::labels::DstLabels private

.travis.yml
There's no reason that we should ever need to cache proxy binaries
between CI runs.
However, for each pull request build we appear to cache a ~125M
binary in target/debug/linkerd2-proxy.
Cache interactions seem to account for much of our CI times, so any
reduction here may be helpful.
=> travis: Avoid caching proxy binaries

src/telemetry/metrics/labels.rs, src/telemetry/metrics/record.rs, src/telemetry/metrics/transport.rs, src/transport/tls/config.rs
Following #67 and #68, the `labels::TlsStatus` type can be removed in
favor of extending underlying `ctx::transport::TlsStatus` type to
implement `FmtLabels`.
=> Remove the labels::TlsStatus type

.travis.yml
This reverts commit c64d7aa0e5601228786ca5e968710a68cc62afbd.
The CI change introduced in #69 appears to break the master build.
=> Revert "travis: Avoid caching proxy binaries (#69)"

Cargo.lock
There was a bug reported that rustls was corrupting data sometimes due to incomplete handling of nonblocking IO. Reported in https://github.com/hyperium/hyper/issues/1631, and rustls and tokio-rustls have fixed the bug.
=> update rustls for async IO bug

src/telemetry/metrics/mod.rs, src/telemetry/metrics/record.rs, src/telemetry/mod.rs, src/telemetry/transport/mod.rs
In anticipation of removing Transport-related Event types, we want to
separate the concerns of recording transport metrics updates from
reporting them to the metrics endpoint.
The transport module has been split into `Registry` and `Report` types:
`Registry` is responsible for recording updates, and `Report` is
responsible for rendering metrics.
This has the benefit of removing transport metrics from the global metrics
lock.
=> Split transport metrics into read and write halves

src/bind.rs, src/inbound.rs, src/lib.rs, src/telemetry/metrics/record.rs, src/telemetry/sensor/mod.rs
`Bind` was initially written so that a `Sensors` implementation is
optional. Over time, this hasn't proven to be very useful.
In preparation for further changes to HTTP telemetry, this change
simplifies the Bind and Sensors types so that an HTTP sensor is always
required to construct `Bind`.
Test-only constructors have been added to satisfy the case where Sensors
were omitted.
=> Require Sensors for Bind

src/bind.rs, src/control/destination/background/destination_set.rs, src/control/destination/background/mod.rs, src/control/destination/mod.rs, src/control/mod.rs, src/lib.rs, src/outbound.rs, src/svc/mod.rs
The `control::destination` exposes an important trait, `Bind`, that
abstracts the logic of instantiating a new service for an individual
endpoint (i.e., in a load balancer).
This interface is not specific to our service discovery implementation,
and can easily be used to model other types of client factory.
In the spirit of consolidating our HTTP-specific logic, and making the
core APIs of the proxy more visible, this change renames the `Bind`
trait to `NewClient`, simplifies the trait to have fewer type
parameters, and documents this new generalized API.
=> Move `control::Bind` to `svc::NewClient`

src/bind.rs, src/inbound.rs, src/outbound.rs, src/svc/mod.rs, src/svc/reconnect.rs, src/telemetry/http/sensors.rs, src/telemetry/http/service.rs, src/transparency/client.rs, src/transparency/orig_proto.rs
Currently, the layered service implementations that comprise the HTTP
stack are a mix of `Service` and `NewService` types. In the
endpoint-specific stack. `transparency::Client` is the only layer that
actually needs to be a `NewService` if it is wrapped immediately with a
`Reconnect`.
This allows us to remove several `NewService` implementations.
This extracts a new `svc::Reconnect` middleware from `bind`, handling
connection error logging and hiding `tower_reconnect::Error` from outer
layers.
Furthermore, two HTTP/1-specific middlewares have been moved outside of
the TLS rebinding layer, since they are not dependent on TLS
configuration.
Finally, `bind`'s type aliases have been simplified, removing the
`HttpRequest` and `HttpResponse` aliases. By removing these, and
removing …
=> Reorder endpoint-specific HTTP middlewares

src/bind.rs, src/proxy/http/mod.rs, src/proxy/http/normalize_uri.rs
Split proxy infrastructure from `bind`
In order to simplify `bind.rs`, this change moves `NormalizeUri` into
its own module, `proxy::http::normalize_uri`.
This will later become part of the "client stack" built from
`proxy::http`.
=> Move bind::NormalizeUri to its own module in proxy::http

Cargo.lock, Cargo.toml, Dockerfile, src/control/destination/background/client.rs, src/lib.rs, tests/support/mod.rs, timeout/Cargo.toml, timeout/src/lib.rs
The `timeout` module has very little to do with the proxy, specifically.
This change moves it into a dedicated subcrate. This helps to clarify
dependencies and to minimize generic logic in the main proxy crate.
In doing this, an unused implementation of AsyncRead/AsyncWrite for
Timeout was deleted.
Furthermore, the `HumanDuration` type has been copied into
tests/support/mod.rs so that this type need not be part of the timeout
module's public API.
=> Split the `timeout` module into its own subcrate

Cargo.lock, Makefile, lib/metrics/Cargo.toml, lib/metrics/src/lib.rs
commit 2a99dd08bda6dc3b9eb271c1f623be50c2707350
Author: Oliver Gould <ver@buoyant.io>
Date:   Tue Sep 18 22:52:51 2018 +0000
Fix linkerd2-metrics test compilation
The `quickcheck` dependency was lost when the subcrate was split out.
This change restores the dependency.
Fixes linkerd/linker2#1685
commit 80b9fe19434f5703e9fe79bd5de578d81d49f86e (HEAD -> ver/test-fixup, origin/ver/test-fixup)
Author: Oliver Gould <ver@buoyant.io>
Date:   Tue Sep 18 22:54:03 2018 +0000
Run tests for all packages in `make test`
=> Fix linkerd2-metrics test compilation

src/config.rs, src/lib.rs, tests/support/proxy.rs
There are a few crufty remaining references to the `private` and
`public` proxy interfaces. `private` referred to the pod-local side of
the proxy; and `public` the external side.
These terms have been replaced by `inbound` and `outbound` proxies.
The "private forward address" is now the "inbound forward address".
The "private listener" is now the "outbound listener".
The "public listener" is now the "inbound listener".
This change adds new environment variables to support configuration:
- `LINKERD2_PROXY_INBOUND_CONNECT_TIMEOUT`
- `LINKERD2_PROXY_INBOUND_FORWARD`
- `LINKERD2_PROXY_INBOUND_LISTENER`
- `LINKERD2_PROXY_OUTBOUND_CONNECT_TIMEOUT`
- `LINKERD2_PROXY_OUTBOUND_LISTENER`
The old configuration variables have not been removed. Instead, a
warning is logged when such a variable is used …
=> Deprecate PRIVATE/PUBLIC config variables

Cargo.lock, Cargo.toml, lib/timeout/src/lib.rs, src/task.rs
This branch changes the proxy's `trust-dns-resolver` dependency to a
version dependency rather than a Git dependency, since the
`0.10.0-alpha.3` version has the features that we previously required
the git dependency for.
The only changes to the proxy codebase itself were fixes for deprecation
warnings introduced by the dependency upgrade, since it was necessary to
update the minimum `tokio_timer` version as `trust-dns-proto` uses APIs
added in `tokio-timer` v0.2.6. In particular, `tokio_timer::Deadline`
was deprecated and replaced by `Timeout`.
=> Change trust-dns-resolver to a version rather than git dependency

src/app/main.rs, src/proxy/http/client.rs, src/proxy/mod.rs, src/proxy/reconnect.rs
Previously, the `client` module was responsible for instrument reconnects. Now, the reconnect module becomes its own stack layer that composes over NewService stacks.
Additionally, the `proxy::http::client` module can now layer over an underlying Connect stack.
---
This sets up the controller client to become a Stack.
=> Decouple reconnect & connect layers from proxy::http::client

src/transport/addr_info.rs, src/transport/connection.rs
The listener *already* got the remote address when it was accepted, but we drop the value by using `TcpListener::incoming`. By the time we call `socket.peer_addr()`, the connection may have been closed, and thus we were panicking.
By removing the panic here, later code should notice that the connection is closed (when a `read` finds EOF), and it should be dropped gracefully.
For the same reasons (that the connection might already be closed), this reduces the `error!` from `get_original_dst` to just a `warn!`, just as `set_nodelay` is a `warn!`. No need to yell in that case.
Closes https://github.com/linkerd/linkerd2/issues/1787
=> Remove panic when failing to get remote address

lib/stack/src/watch.rs, src/app/main.rs, src/app/outbound.rs
The TLS-configuration-watching logic in `app::outbound::tls_config` need
not be specific to the outbound types, or even TLS configuration.
Instead, this change extends the `watch` stack module with a Stack type
that can satisfy the TLS use case independently of the concrete types at
play.
`app::outbound` now need only implement:
svc::watch::WithUpdate<tls::ClientConnectionConfig> for Endpoint
=> Make a generic Watch stack from outbound::tls_config

src/control/destination/background/client.rs, src/lib.rs, src/proxy/reconnect.rs
The control client implements a backoff service that dampens reconnect
attempts to the control plane by waiting a fixed period of time after a
failure.
Furthermore, the control client logs errors each time a reconnect
attempt fails.
This change moves backoff logic from
`control::destination::background::client` to `proxy::reconnect`.
Because the reconnect module handles connection errors uniformly, muting
repeated errors, it also has enough context to know when a backoff
should be applied -- when the underlying NewService cannot produce a
Service.
If polling the inner service fails once the Service has been
established, we do _not_ want to apply a backoff, since this may
just be the result of a connection being terminated, a process being
restarted, etc.
=> Introduce an optional fixed backoff between reconnects

src/app/main.rs, src/lib.rs, src/proxy/http/balance.rs, src/proxy/resolve.rs
The `proxy::http::balance` module uses the `proxy::resolve::Resolve`
trait to implement a `Discover`.
This coupling between the balance and resolve modules prevents
integrating the destination profile API such that there is a per-route,
per-endpoint stack.
This change makes the `balance` stack generic over a stack that produces
a `Discover`. The `resolve` module now implements a stack that produces
a `Discover` and is generic over a per-endpoint stack.
=> Make `resolve` a stack module

lib/stack/src/either.rs, lib/stack/src/layer.rs, lib/stack/src/lib.rs, lib/stack/src/map_err.rs, lib/stack/src/map_target.rs, lib/stack/src/phantom_data.rs, lib/stack/src/stack_per_request.rs, lib/stack/src/watch.rs, src/app/inbound.rs, src/app/main.rs, src/app/outbound.rs, src/lib.rs, src/proxy/buffer.rs, src/proxy/http/balance.rs, src/proxy/http/client.rs, src/proxy/http/insert_target.rs, src/proxy/http/metrics/mod.rs, src/proxy/http/metrics/service.rs, src/proxy/http/metrics/timestamp_request_open.rs, src/proxy/http/normalize_uri.rs, src/proxy/http/router.rs, src/proxy/limit.rs, src/proxy/reconnect.rs, src/proxy/timeout.rs, src/svc.rs, src/tap/mod.rs, src/tap/service.rs
Previously, stacks were built with `Layer::and_then`. This pattern
severely impacts compile-times as stack complexity grows.
In order to ameliorate this, `app::main` has been changed to build
stacks from the "bottom" (endpoint client) to "top" (serverside
connection) by _push_-ing Layers onto a concrete stack, i.e. and not
composing layers for an abstract stack.
While doing this, we take the oppportunity to remove a ton of
now-unnecessary `PhantomData`. A new, dedicated `phantom_data` stack
module can be used to aid type inference as needed.
Other stack utilities like `map_target` and `map_err` have been
introduced to assist this transition.
Furthermore, all instances of `Layer::new` have been changed to a free
`fn layer` to improve readability.
This change sets up two upcoming changes: a …
=> refactor: Build stacks from bottom-to-top

src/addr.rs, src/app/config.rs, src/app/control.rs, src/app/inbound.rs, src/app/metric_labels.rs, src/app/mod.rs, src/app/outbound.rs, src/app/profiles.rs, src/conditional.rs, src/control/destination/background/destination_set.rs, src/control/destination/background/mod.rs, src/control/destination/mod.rs, src/control/fully_qualified_authority.rs, src/dns.rs, src/host_port.rs, src/lib.rs, src/proxy/http/profiles.rs, src/proxy/http/settings.rs, src/transport/connect.rs, src/transport/connection.rs, src/transport/connection_tests.rs, src/transport/mod.rs
Currently, the proxy uses a variety of types to represent the logical
destination of a request. Outbound destinations use a `NameAddr` type
which may be either a `DnsNameAndPort` or a `SocketAddr`. Other parts of
the code used a `HostAndPort` enum that always contained a port and also
contained a `Host` which could either be a `dns::Name` or a `IpAddr`.
Furthermore, we coerce these types into a `http::uri::Authority` in many
cases.
All of these types represent the same thing; and it's not clear when/why
it's appropriate to use a given variant.
In order to simplify the situtation, a new `host_port` module has been
introduced with `Addr` and `NameAddr` types. A `Addr` may
contain either a `NameAddr` or a `SocketAddr`.
The `Host` value has been removed from the `Settings::Http1` type, …
=> Unify Name/Host/Addr types under Addr

lib/stack/src/either.rs, src/proxy/http/mod.rs
The `linkerd2_stack::Either` type is used to implement Layer, Stack, and
Service for alternate underlying implementations. However, the Service
implementation requires that both inner service emit the same type of
Error.
In order to allow the underlying type to emit different errors, this
chnage uses `Either` to wrap the underlying errors, and implements
`Error` for `Either`.
=> Implement Error for svc::Either

lib/router/src/lib.rs
The router's `Recognize` trait is now essentially a function.
This change provides an implementation of `Recognize` over a `Fn` so
that it's possible to implement routers without defining 0-point marker
types that implement `Recognize`.
=> Allow routers to be implemented with a closure

Cargo.lock, Cargo.toml, lib/never/Cargo.toml, lib/never/src/lib.rs, lib/stack/Cargo.toml, lib/stack/src/lib.rs, src/app/main.rs, src/drain.rs, src/lib.rs, src/proxy/http/router.rs, src/proxy/server.rs, src/transport/connect.rs
Since this stack pieces will never error, we can mark their
`Error`s with a type that can "never" be created. When seeing an `Error
= ()`, it can either mean the error never happens, or that the detailed
error is dealt with elsewhere and only a unit is passed on. When seeing
`Error = Never`, it is clearer that the error case never happens.
Besides helping humans, LLVM can also remove the error branchs entirely.
=> Convert several Stack unit errors into Never

src/app/inbound.rs, src/app/main.rs, tests/support/proxy.rs, tests/transparency.rs
This changes the HTTP router and TCP forwarder for **inbound** connections to always replace the destination IP with `127.0.0.1`. The port is still taken from `SO_ORIGINAL_DST`. This change, combined with some new `iptables` rules, should fix https://github.com/linkerd/linkerd2/issues/1585.
=> change Inbound to always use localhost

Dockerfile
Add the never lib to the proxy Dockerfile so that the proxy docker image can be built.
=> Add never lib to Dockerfile

src/app/control.rs, src/app/main.rs, src/app/metric_labels.rs
There is no telemetry from the controller client currently.
This change adds a new scope (`control_`) of metrics including HTTP
metrics for the client to the proxy-api.
---
```
control_request_total{addr="proxy-api.ver-linkerd.svc.cluster.local:8086",tls="disabled"} 5
control_response_latency_ms_bucket{addr="proxy-api.ver-linkerd.svc.cluster.local:8086",tls="disabled",status_code="200",le="1"} 2
control_response_latency_ms_bucket{addr="proxy-api.ver-linkerd.svc.cluster.local:8086",tls="disabled",status_code="200",le="2"} 2
control_response_latency_ms_bucket{addr="proxy-api.ver-linkerd.svc.cluster.local:8086",tls="disabled",status_code="200",le="3"} 2
control_response_latency_ms_bucket{addr="proxy-api.ver-linkerd.svc.cluster.local:8086",tls="disabled",status_code="200",le="4"} 2 …
```
=> Add controller client metrics

README.md
As stated in the title.  Link was broken, now it's fixed. :)
=> Fix Slack signup link in README.

Cargo.toml
Our test artifacts end up consuming several GB of disk space, largely
due to debug symbols. This can prevent CI from passing, as CI hosts only
have about 9G of real estate.
By disabling debug symbols, we reduce artifact size by >90% (and total
target directory size from 14G to 4G).
Thanks to @hawkw for spotting this.
=> Disable debug symbols for tests

src/proxy/http/orig_proto.rs, tests/transparency.rs
I noticed a pod was seeing this response header, it should be removed before the pod gets it.
=> Ensure l5d-orig-proto header is removed before returning responses

src/app/inbound.rs
Using a downgrade stack is not sufficiently important to log at the INFO
level. Log it at DEBUG.
=> Reduce log level for orig-proto-downgrade

Cargo.lock, Cargo.toml, src/app/dst.rs, src/app/inbound.rs, src/app/main.rs, src/app/outbound.rs, src/tap/grpc/match_.rs, src/tap/grpc/server.rs, src/tap/mod.rs
Route labels are not queryable by tap, nor are they exposed to in tap
events.
This change adds route label matching and adds route labels to events.
Depends on linkerd/linkerd2-proxy-api#17
=> Expose route labels via tap

src/app/profiles.rs
@adleong suggested that profile matching should always be anchored so that users must be explicit about unexpected path components.
This change modifies the Profile client to always build anchored regular expressions.
=> profiles: Add anchors to control-plane provided regexes

Cargo.lock
There were a number of protocol-correctness bug fixes in h2 v0.1.13
=> Update h2 to v0.1.13

src/tap/grpc/server.rs
As we well know, gRPC responses may include the `grpc-status` header
when there is no response payload.
This change ensures that tap response end events include this value when
it is set on response headers, since grpc-status is handled specially
in the Tap API.
=> Record grpc-status from response headers

src/app/main.rs, src/app/outbound.rs
When debugging issues that users believe is related to discovery, it's helpful to get a narrow set of logs out to determine whether the proxy is observing discovery updates.
With this change, a user can inject the proxy with `--proxy-log-level='warn,linkerd2_proxy=info,linkerd2_proxy::app::outbound::discovery=debug'` and the proxy's logs will include messages like:
```
DBUG voting-svc.emojivoto.svc.cluster.local:8080 linkerd2_proxy::app::outbound::discovery adding 10.233.70.98:8080 to voting-svc.emojivoto.svc.cluster.local:8080
DBUG voting-svc.emojivoto.svc.cluster.local:8080 linkerd2_proxy::app::outbound::discovery removing 10.233.66.36:8080 from voting-svc.emojivoto.svc.cluster.local:8080
```
This change also turns-down some overly chatty INFO logging in main.
=> Log discovery updates in the outbound proxy

src/app/profiles.rs, src/proxy/http/profiles.rs
The profile router currently is responsible for driving the state of
profile discovery; but this means that, if a service is not polled for
traffic, the proxy may not drive discovery (so that requests may
timeout, etc).
This change moves this discovery onto a daemon task that sends profile
updates to the service over an mpsc with capacity of 1.
=> profiles: Drive profile discovery on a daemon task

src/app/main.rs, src/proxy/server.rs, src/transport/connection.rs, tests/support/tcp.rs, tests/transparency.rs
This branch changes the proxy's accept logic so that the proxy will no
longer attempt to terminate TLS on ports which are configured to skip
protocol detection. This means that a Linkerd deployment with 
`--tls optional` will no longer break server-speaks-first protocols like
MySQL (although that traffic will not be encrypted). 
Since it's necessary to get the connection's original destination to
determine if it's on a port which should skip protocol detection, I've
moved the SO_ORIGINAL_DST call down the stack from `Server` to
`BoundPort`. However, to avoid making an additional unnecessary syscall,
the original destination is propagated to the server, along with the
information about whether or not protocol detection is enabled. This is
the approach described in …
=> Make TLS accept logic compatible with disabled protocol detection

.travis.yml
This branch replaces the `export CARGO_VERBOSE=1` on CI release-mode
builds with the `travis_wait` script. Verbose mode was previously being
set to prevent long release-mode builds from timing out. However, there
appears to be a bug in `rustc` 1.31.0, which causes the compiler to
crash when building the proxy with verbose mode enabled. Hopefully, this
will fix the build on master.
=> Workaround for Rust 1.31 crash with verbose mode enabled

.travis.yml, tests/tap.rs
It turns out that increasing the recursion limit for the `tap` test
crate _actually_ fixes the compiler error that's broken the last several
builds on master. 
Since I'm now able to locally reproduce the error (which occurs only
when running the tests in release mode), I've verified that this
actually does fix the issue. Thus, I've also reverted the previous
commit (7c35f27ad3e86614c05a2a409c3a8b459cf023ac) which claimed to fix
this issue, as it turns out that was not actually necessary.
=> Actually fix the master CI build

Cargo.lock, src/app/main.rs, src/proxy/http/balance.rs
Adopts changes from https://github.com/tower-rs/tower/pull/134
> balance: Consider new nodes more readily
>
> When a PeakEwma Balancer discovers a single new endpoint, it will not
> dispatch requests to the new endpoint until the RTT estimate for an
> existing endpoint exceeds _one second_. This misconfiguration leads to
> unexpected behavior.
>
> When more than one endpoint is discovered, the balancer may eventually
> dispatch traffic to some of--but not all of--the new enpoints.
>
> This change alters the PeakEwma balancer in two ways:
>
> First, the previous DEFAULT_RTT_ESTIMATE of 1s has been changed to be
> configurable (and required). The library should not hard code a default
> here.
>
> Second, the initial RTT value is now decayed over time so that new
> endpoints will eventually …
=> Improve load balancer configuration

.travis.yml, Cargo.lock, Cargo.toml, src/app/classify.rs, src/app/dst.rs, src/app/main.rs, src/app/profiles.rs, src/lib.rs, src/proxy/http/glue.rs, src/proxy/http/metrics/mod.rs, src/proxy/http/metrics/report.rs, src/proxy/http/metrics/service.rs, src/proxy/http/mod.rs, src/proxy/http/profiles.rs, src/proxy/http/retry.rs, tests/profiles.rs, tests/support/client.rs, tests/support/controller.rs, tests/support/mod.rs
This is a WIP that adds request retries if a service profile includes retry instructions, based on https://github.com/linkerd/linkerd2-proxy-api/pull/16.
=> Profile Retries

Cargo.lock, Cargo.toml
An upstream bug in the `trust-dns-proto` library can cause
`trust-dns-resolver` to leak UDP sockets when DNS queries time out. This
issue appears to be the cause of the memory leak described in
linkerd/linkerd2#2012.
This branch updates the `trust-dns` dependency to pick up the change in
bluejekyll/trust-dns#635, which fixes the UDP socket leak.
I confirmed that the socket leak was fixed by modifying the proxy to
hard-code a 0-second DNS timeout, sending requests to the proxy's
outbound listener, and using
``` lsof -p $(pgrep linkerd2-proxy) ```
to count the number of open UDP sockets. On master, every request to a
different DNS name that times out leaves behind an additional open UDP
socket, which show up in `lsof`, while on this branch, only TCP sockets
remain open after the request …
=> Update trust-dns-resolver to fix UDP socket leak

Cargo.lock, Cargo.toml
carllerche/h2#338 fixes a deadlock in stream reference counts that could
potentially impact the proxy. This branch updates our `h2` dependency to a
version which includes this change.
=> Update h2 to 0.1.15

src/app/main.rs, src/app/mod.rs, src/proxy/http/h1.rs, src/proxy/http/mod.rs, src/proxy/http/strip_header.rs, tests/discovery.rs
It is valuable to inject an ingress controller with LD2. As ingress, the host
header tends to be the external host and most controllers just route directly
back to the IP address of an endpoint. Unfortunately, this makes it so that
Linkerd cannot discover the destination (as that works off the host header).
The outbound router now recognizes request destinations by preferrentially
choosing the `l5d-dst-override` header if it present. This header takes
precedent over the Host header, original dest, etc.
In addition, both the inbound and outbound routers strip this header. The
outbound router strips it after it has used it to determine the authority.
This is done with the `strip_header` layer that was added to the stack.
There are integration tests for this behavior in the discovery tests. …
=> Make outbound router honor `l5d-dst-override` header

src/proxy/canonicalize.rs
Previously, whenever the `canonicalize::Task` future encounters an
error, it logs that error at the error level. However, in many cases,
these errors are transient, and we are able to successfully fall back to
a previously canonicalized name.
This branch changes `canonicalize::Task` to only log at the error level
when there's no previously successful result to fall back to, and log at
the warning level otherwise. In addition, the log message on fallbacks
now indicates that we fell back to a previous canonicalization.
Hopefully, this should make transient errors, such as a slow DNS server,
a little less scary.
Fixes linkerd/linkerd2#2094
=> canonicalize: Only log errors at the WARN level when falling back

Cargo.lock, Cargo.toml, lib/timeout/Cargo.toml, lib/timeout/src/lib.rs, lib/timeout/src/stack.rs, src/app/classify.rs, src/app/config.rs, src/app/dst.rs, src/app/main.rs, src/app/metric_labels.rs, src/app/profiles.rs, src/proxy/http/mod.rs, src/proxy/http/profiles.rs, src/proxy/http/timeout.rs, src/proxy/mod.rs, src/svc.rs, src/tap/grpc/match_.rs, tests/discovery.rs, tests/profiles.rs, tests/support/client.rs, tests/support/controller.rs, tests/support/mod.rs
If a service profile specifies a timeout for a given route, this applies
a timeout waiting for responses on that route.
Timeouts show up in proxy metrics like this:
```
route_response_total{direction="outbound",dst="localhost:80",status_code="504",classification="failure",error="timeout"} 1
```
=>  Add Route timeouts

Cargo.lock, Cargo.toml, lib/fs-watch/Cargo.toml, lib/fs-watch/src/lib.rs, src/tap/grpc/match_.rs, src/transport/connection.rs, tests/support/mod.rs
This branch updates the proxy's dependencies to eliminate multiple
incompatible versions of the `rand` crate. 
Previously we depended on both `rand` 0.4.3 and 0.5.1. After this
branch, we depend on `rand` 0.6.3 (the latest) and 0.5.1. However, PR
#169 will also update `trust-dns-resolver` (the only crate depending on
`rand` 0.5.1) to a version that depends on `rand` 0.6.3, so once both
this branch and #169 are merged, we will depend only on `rand` 0.6.3.
Note that this is a fairly large change to `Cargo.toml` --- it was
necessary to update many of the proxy's dependencies in order to
consolidate on one `rand` version. Additionally, I had to push branches
of some of those dependencies in order to update their `rand`
dependency, so it's currently necessary to patch some of the proxy's …
=> Update dependencies to remove duplicate `rand` versions

Cargo.lock, Cargo.toml, Dockerfile, src/app/config.rs, src/app/main.rs, src/app/profiles.rs, src/control/destination/background/mod.rs, src/control/destination/mod.rs, tests/support/controller.rs
Pick up API changes to the proxy-api where Get and GetProfiles now accept a proxy_id parameter.  We set this parameter to be equal to the proxy's TLS pod identity, which is configured through an environment variable.  Sending this value to the proxy-api allows it to return more tailored results, for example, by looking for service profiles in the proxy's namespace.
=> Set proxy_id in calls to Get and GetProfile

src/app/metric_labels.rs
When `EndpointLabels`s are compared for equality, the `SocketAddr` field is considered as part of the `Hash`. However, the `SocketAddr` field is never formatted. When all labels are otherwise equal, this results in metrics that look like they have redundant scopes.
Removing the `addr: SocketAddr` field from `EndpointLabels` results in equality between sets of labels that may have differed in their destination address, but are otherwise the same.
In reproducing with [booksapp](http://github.com/BuoyantIO/booksapp), there are no longer any redundant metric scopes
```bash
$ kubectl -n linkerd exec -c linkerd-proxy $(kubectl -n linkerd get po | awk '$1 ~ /^linkerd-controller-/ && $3 ~ /^Running$/ { print $1 }' |head -n 1) -- curl -s localhost:4191/metrics   | grep tls= | head …
```
=> Remove destination address from endpoint metric labels

src/proxy/canonicalize.rs
When a canonicalization task fails to resolve a name, our logging is not
particularly clear about the current state of the stack. Specifically,
it's difficult to know whether the stack has resolved the name
successfully before.
With this change, canonicalization failures are logged (at warning, not
error) only when the task has not previously resolved a name.
Subsequent errors are now logged at the debug level (instead of
warning).
=> Log canonicalization warnings on only the first error

lib/fs-watch/src/either_stream.rs, lib/fs-watch/src/lib.rs
fs-watch contains compilation warnings due to an unused macro and a
public enum that is not constructed within the crate. This resolves
these warnings.
=> Fix compilation warnings in fs-watch

.travis.yml, Makefile
Per linkerd/linkerd2#2199, we want to be able to include the proxy's debug symbols in auxiliary diagnostic containers. In order to do this, the process that produces the proxy's binaries also should be responsible for producing its debug symbols.
This change adds a new environment variable, `CARGO_DEBUG`, which the Makefile uses to instrument the build to produce debug symbols. If `objcopy` is available on the local system (i.e. on Linux), then the symbols are copied from the binary into a .obj file, and the executable is stripped from 3.3G down to 9.9M before packaging.
This increases the size of the compressed package artifact by 76% (from 5.0M to 8.8M). This may have similar impacts on build time. This may have similar impacts on build time. To that end, CARGO_DEBUG is not enabled in …
=>  make: Optionally include debug symbols with builds

lib/router/src/lib.rs, src/proxy/http/router.rs, src/proxy/http/settings.rs
The contract to only call `Service::call` after seeing ready from `poll_ready` was just [made strong](https://github.com/tower-rs/tower/pull/161). So, this one step towards making sure we do just that.
Since a router can't call `poll_ready` on all of its inner routes, instead it requires each service be `Clone`, and calls `poll_ready` in its `ResponseFuture`.
=> Update Router to wait for inner poll_ready before calling inner call

Cargo.lock, lib/fs-watch/Cargo.toml, lib/fs-watch/src/lib.rs
The buffer passed to `read(2)` to read inotify events from the inotify
fd must be long enough to fit events with filenames of the maximum
allowable length. The `inotify-rs` library previously always constructed
such a buffer, but as of 1fe4e3885039b9e66f9d93bf0cec11748253c39e, we
are required to provide our own buffer. The buffer we were providing was
insufficiently large for some filenames.
See also the `man` page for `inotify`:
> The behavior when the buffer given to read(2) is too small to return
> information about the next event depends on the kernel version: in
> kernels before 2.6.21, read(2) returns 0; since kernel 2.6.21,
> read(2) fails with the error EINVAL.  Specifying a buffer of size
>
>         sizeof(struct inotify_event) + NAME_MAX + 1
>
> will be sufficient to read at …
=> fs-watch: Use a properly sized buffer for inotify events

lib/metrics/src/serve.rs, lib/router/src/lib.rs, lib/stack/src/either.rs, lib/timeout/src/lib.rs, src/proxy/buffer.rs, src/proxy/canonicalize.rs, src/proxy/http/glue.rs, src/proxy/http/settings.rs
proxy: replace `Error::cause` with `Error::source`
Currently, linkerd2-proxy uses and implements `Error::cause`
for error handling.
This branch removes the use of the deprecated
`Error::cause` method and implements and uses the
`Error::source` method, as [recommended by the
documentation](https://doc.rust-lang.org/std/error/trait.Error.html#method.cause). To implement `Error::source`, there are
static lifetimes added to the `Error` traits. However, this
doesn't remove the [use of `cause2`](https://github.com/DebugSteven/linkerd2-proxy/blob/231cb67b1a2178627bbb304055d408cee1007fd9/src/proxy/http/glue.rs#L226) because
`hyper::Error` doesn't provide a `source` yet:
https://docs.rs/hyper/0.12.24/src/hyper/error.rs.html#289-333.
A separate issue could be opened to use `source` for …
=> replace Error::cause with Error::source (#2370)

src/app/dst.rs, src/proxy/http/profiles.rs, src/proxy/http/timeout.rs
Follow after #194, the `profiles::router` needs to be updated to call `poll_ready` before `call`. I noticed the `profiles::router` is *very* similar to a regular `Router`. So I've refactored it to use one internally, thus getting the poll-ready-then-call fix automatically.
=> Refactor profiles::router on top of linkerd2_router

Cargo.lock
This picks up tower-rs/tower-grpc#115, which adds improved messages to
internal gRPC errors.
=> Bump tower-grpc

src/app/config.rs
In both server and client case, the default value of
MAX_CONCURRENT_STREAMS is `u32::MAX`. However, we currently cap the
inbound and outbound router capacity limits to 100.
This change increases the capacity of both to 10_000.
This will close linkerd/linkerd2#2395 and could possibly address the
issue in linkerd/linkerd2#2363.
Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>
=> perf(router): Increase inbound/outbound router cap.

src/app/inbound.rs, src/app/main.rs, src/app/mod.rs, src/app/outbound.rs, src/proxy/http/add_header.rs, src/proxy/http/mod.rs, tests/discovery.rs
[Context](https://github.com/linkerd/linkerd2/issues/2310)
We now add the `l5d-remote-ip` header to all inbound requests and outbound responses. We also make sure to strip the header before setting so that clients may not set this header.
We were already adding a header in similar style, so in order to deduplicate code, `add_header.rs` holds the generic logic for adding a header to a `http::Request` or `http::Response`. `l5d-client-id` and `l5d-server-id` now also use the same logic in order to add their respective headers.
An additional test module was added to `tests/discovery.rs` that tests the following:
- outbound responses strip `l5d-remote-ip`
- inbound requests strip `l5d-remote-ip`
- outbound responses set `l5d-remote-ip` to the endpoint IP
- inbound requests set `l5d-remote-ip` …
=> Set `l5d-remote-ip` on inbound requests and outbound responses

src/app/main.rs
Currently, listener configuration is spread across multiple parts of our
setup.
This change consolidates all of this configuration, removing some
arguments from `serve()`.
=> main: Consolidate listener configuration

src/app/identity.rs, src/app/main.rs, src/logging.rs, src/transport/connect.rs, src/transport/tls/client.rs, src/transport/tls/listen.rs
This changes initialization logic so that a task is spawn that logs when
identity is provisioned (as observed by stacks). Identity's daemon task is
now spawned on the admin thread with context logging.
Furthermore, the processes's uptime is now logged in log messages so that the
relative time between events is easily observeable. This is borrowed from the
Linux kernel's behavior (i.e. in /var/log/kern.log).
=> Instrument identity with logging

lib/metrics/src/prom.rs, src/app/admin/mod.rs, src/app/admin/readiness.rs, src/app/config.rs, src/app/identity.rs, src/app/main.rs, src/app/mod.rs, tests/support/proxy.rs
The so-called "metrics" server need not only serve metrics. It can also
serve other administrative endpoints, especially those that may be used
as readiness and liveness probes.
A /ready endpoint is exposed that responds successfully when identity
has been loaded.
The `METRICS_LISTEN_ADDR` configuration has been renamed as
`ADMIN_LISTEN_ADDR`.
=> Replace the metrics server with an admin server

lib/metrics/src/prom.rs, src/app/admin/mod.rs, src/app/admin/readiness.rs, src/app/config.rs, src/app/main.rs, src/app/mod.rs, tests/support/proxy.rs
The so-called "metrics" server need not only serve metrics. It can also
serve other administrative endpoints, especially those that may be used
as readiness and liveness probes.
A /ready endpoint is exposed that responds successfully when identity
has been loaded.
The `METRICS_LISTEN_ADDR` configuration has been renamed as
`ADMIN_LISTEN_ADDR`.
=> Replace the metrics server with an admin server (#218)

src/app/config.rs, src/app/control.rs, src/app/main.rs
The controller client's connect timeout setting doesn't actually 
ontrol the connect timeout: it configures the _request_ timeout.
This change fixes the controller by moving the timeout layer
into the connect stack.
Furthermore, the connect timeout and backoff settings have been
updated to be more aggressive in the case of controller communication
and less aggressive when communicating with applications.
=> Fix connect timeouts

src/app/profiles.rs
Each service in the router cache maintains a profile watch on the destination service which is driven by the profile daemon future.  If that service is dropped from the cache, the profile daemon will not realize this until it gets a profile update and attempts to send the profile to the service.  As long as the profile grpc stream is NotReady (i.e. as long as there are no profile updates), the daemon future will live on, even after the service has been dropped.
As services churn into and out of the router cache, this results in more and more daemon futures accumulating.  Each future is associated with a grpc stream to the destination service so this causes an unbounded number of grpc streams to be open to the destination service.  This results in a leak of goroutines and therefore memory …
=> Add a oneshot to notify the profiles daemon if the stream is dropped

src/app/config.rs, src/app/main.rs, src/control/destination/background/destination_set.rs
Without a connect backoff, reconnect can quickly loop, chewing CPU.
Configuring a short backoff makes this better without severely impacting
latency.
An unnecessary log line was also removed, since it interfered with debugging.
=> Configure a short connect backoff

Dockerfile
Upgrade to rust 1.33 and linkerd edge-19.3.3.
Fixup paths for new base container.
=> Fixup dockerfile for edge-19.3.3

src/app/errors.rs, src/app/main.rs, src/app/mod.rs, src/proxy/canonicalize.rs, src/proxy/http/router.rs, tests/discovery.rs
This is just the beginning of it, to be used by other pieces later.
=> Add an http::errors::layer to translate errors

Cargo.lock, src/app/config.rs, src/app/control.rs, src/app/main.rs, src/proxy/http/client.rs, src/proxy/http/h2.rs, src/proxy/server.rs
Expose an environment configuration to override the default stream or
connection level window size of 65,535.
This allows us to test alternate values without having to recompile.
Closes linkerd/linkerd2#2396
Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>
=> Configure HTTP/2 window size

src/app/inbound.rs, src/app/main.rs, src/app/outbound.rs, src/proxy/http/add_header.rs, tests/discovery.rs
The proxy has been instrumented to expose various informational `l5d-`
headers to expose identity and network information that would otherwise
be unaccessible to the application.
However, as described in linkerd/linkerd2#2597, when linkerd is injected
into an ingress pod, its easy to accidentally leak these details to
external applications.
Until we have a better mechanism for flagging external-facing pods,
these headers should be disabled.
=> Disable potentially info-leaking headers

src/app/identity.rs, tests/identity.rs, tests/support/identity.rs
Depends on #227 and #228.
This branch adds a new integration test that asserts that a proxy will
refresh its identity before the specified expiration time.
I also added a `trace` log in the `identity` module that logs the actual
duration we will wait before attempting to refresh. This was useful when
debugging why this test was failing (it was because I neglected to set
the LINKERD2_PROXY_IDENTITY_MIN_REFRESH env var, and it defaulted to 10
seconds). I felt like it was useful to log the actual duration we will
wait as well as the `SystemTime` when the cert expires, but I'm happy to
back that commit off if we don't actually want that log line.
Closes linkerd/linkerd2#2505
=> Add test that proxy refreshes its identity

Dockerfile, src/app/main.rs, src/transport/tls/listen.rs, tests/identity.rs
Currently, the listener task does not multiplex TLS discovery, so one
slow/idle connection can prevent a proxy from transmitting all requests.
This change alters the listener to use buffer_unordered and repurposes
the listener's "connection limit" to control this buffer's capacity
(rather than the total number of connections that may be served).
=> Do not block listener on TLS detection

Cargo.lock, Cargo.toml, lib/task/Cargo.toml, lib/task/src/lib.rs, src/control/destination/mod.rs, src/logging.rs, src/proxy/buffer.rs, src/proxy/reconnect.rs, src/proxy/resolve.rs, src/svc.rs
This avails the proxy of newer load balancer features, an updated buffer
implementation, etc.
The new buffer implementation requires that we implement TypedExecutor
for our logging executor; and more error types have been made dynamic.
--
https://github.com/linkerd/linkerd2-proxy-api/pull/29
=> Upgrade tower

src/tap/grpc/server.rs, src/tap/mod.rs, src/tap/service.rs
This refactors the tap system to not require intermediary channels to
register matches and taps when a request comes through. The Dispatcher
that used to exist in order to prevent tapping more requests than the
limit asked for has been removed. In its place is a shared atomic
counter to keep the count under the limit.
The resulting behavior should be the same. There should be improved
performance as tap registration doesn't need go through a second
channel, and requests don't need to be delayed waiting for the
dispatcher to be able to process its queue.
----
I noticed this because of the need for `S: Service + Clone` on the tap layer, which I'm trying to remove for another reason. However, this seems orthogonal enough to be a separate PR.
=> tap: remove need to clone Services

Cargo.lock, src/app/dst.rs, src/app/inbound.rs, src/app/main.rs, src/app/outbound.rs, src/dns/name.rs, src/proxy/http/client.rs, src/proxy/http/normalize_uri.rs, src/proxy/http/orig_proto.rs, src/proxy/http/settings.rs, src/proxy/reconnect.rs, tests/discovery.rs
Due to the `http::settings::router`, a `buffer` was needed in each
endpoint stack. This meant that the service was always ready, even if
the client were falling over (and reconnecting). In turn, this meant
that the balancer would pick one of these endpoint stacks, because it
was always ready!
This change includes a test of a failing endpoint, that the balancer no
longer assumes it is ready, and has the following functional changes:
- Removed `http::settings::router`, instead the client HTTP settings are
detected as part of the `DstAddr`. This means that each balancer only
has endpoints with the same HTTP settings.
- Removed `buffer` layer from inside the endpoint stacks.
Closes https://github.com/linkerd/linkerd2/issues/2550
=> Remove buffers from endpoint stacks

src/app/config.rs, src/app/main.rs, src/control/destination/background/destination_set.rs, src/control/destination/background/mod.rs, src/control/destination/mod.rs, src/control/remote_stream.rs, tests/discovery.rs
Currently, the proxy enforces a limit on the number of concurrent
queries (i.e., the number of gRPC streams) to the Destination service.
This limit was added based on information about the behaviour of the
Destination service that is now known to be incorrect.
This branch removes the limit on concurrent queries from the proxy's
`control::destination` module. Although it should now be possible to
simplify this code as a result of this change, I've refrained from doing
any major refactoring in this branch --- my intention is to do this
after the DNS fallback behaviour has also been removed, as together with
this change, that will result in a _significant_ simplification of the
module. Additionally, I've removed the tests for the concurrency limit,
as they are no longer relevant.
The …
=> Remove Destination service query concurrency limit

tests/identity.rs, tests/support/client.rs, tests/support/identity.rs, tests/support/mod.rs, tests/support/tap.rs
This branch adds tls capability to the support cient used in tests. In addition to that it adds two tests verifying that a TLS connection is refused in case the identity is not certified yet. This attempts to fix #https://github.com/linkerd/linkerd2/issues/2598 and provide facility to write tests for https://github.com/linkerd/linkerd2/issues/2676. 
As these are still some of my first lines of Rust code, it is advised to approach everything with a healthy dose of doubt :)
=> Assert that TLS connection is refused if identity is not certified yet

Cargo.lock, Cargo.toml, lib/stack/Cargo.toml, src/app/control.rs, src/app/main.rs, src/app/profiles.rs, src/lib.rs, src/proxy/grpc/body.rs, src/proxy/grpc/service.rs, src/proxy/http/glue.rs, src/proxy/http/metrics/service.rs, src/proxy/reconnect.rs, tests/support/client.rs, tests/support/controller.rs, tests/support/mod.rs, tests/support/tap.rs
Tower must be updated in order to pickup tower-rs/tower#281
to address linkerd/linkerd2#2804.
This adopts released crates where possible.
=> Upgrade tower dependencies

src/app/main.rs, src/proxy/http/router.rs
Currently, router `layer`s are constructed with a single argument, a
type implementing `Recognize`. Then, the entire router stack is built
with a `router::Config`. However, in #248, it became necessary to
provide the config up front when constructing the `router::layer`, as
the layer is used in a fallback layer. Rather than providing a separate
type for a preconfigured layer, @olix0r suggested we simply change all
router layers to accept the `Config` when they're constructed (see
https://github.com/linkerd/linkerd2-proxy/pull/248#discussion_r283575008).
This branch changes `router::Layer` to accept the config up front. The
`router::Stack` types `make` function now requires no arguments, and the
implementation of `Service` for `Stack` can be called with any `T` (as
the target is now …
=>  Pass router::Config directly to router::Layer

.travis.yml, src/app/main.rs, src/app/outbound.rs, src/control/destination/background/destination_set.rs, src/proxy/http/balance.rs, src/proxy/http/fallback.rs, src/proxy/http/mod.rs, src/proxy/http/router.rs, src/proxy/resolve.rs
Currently, when no endpoints exist in the load balancer for a
destination, we fail the request. This is because we expect endpoints to
be discovered by both destination service queries _and_ DNS lookups, so
if there are no endpoints for a destination, it is assumed to not exist.
In linkerd/linkerd2#2661, we intend to remove the DNS lookup from the
proxy and instead fall back to routing requests for which no endpoints
exist in the destination service to their SO_ORIGINAL_DST IP address.
This means that the current approach of failing requests when the load
balancer has no endpoints will no longer work.
This branch introduces a generic `fallback` layer, which composes a
primary and secondary service builder into a new layer. The primary 
service can fail requests with an error type that …
=> Load balancers fall back to ORIG_DST when no endpoints exist

src/app/config.rs, src/app/main.rs, tests/support/proxy.rs, tests/tap.rs
This PR aims to fix https://github.com/linkerd/linkerd2/issues/2811. Now if `LINKERD2_PROXY_TAP_DISABLED` is set, the tap is not served at all. The approach taken is that  the `ProxyParts` is changed so the `control_listener` is now an `Option` that will be None if tap is disabled as this control_listener seems to be exclusively used to serve the tap. Feel free to suggest a better approach. 
=> Allow to disable tap via setting an env var

tests/identity.rs, tests/support/client.rs, tests/support/identity.rs, tests/support/mod.rs, tests/support/server.rs
This commit introduces TLS capabilities to the support server as well as
tests to ensure that outbound TLS works even when there is no verified
certificate for the proxy yet. 
Fixes https://github.com/linkerd/linkerd2/issues/2599
=> Assert that outbound TLS works before identity is certified

Cargo.lock
To pick up https://github.com/tokio-rs/mio/pull/939
=> Update mio to 0.6.17

src/lib.rs, src/logging.rs, tests/support/mod.rs
The proxy implements custom log formatting which includes timestamps and
formatted contexts describing the context in which the log line was
recorded. Currently, however, when running the proxy's integration
tests, the default log formatting from the `env_logger` crate rather
than the proxy's format. There are two main reasons why it would be
preferable to use the proxy's log formatting style instead:
* Information in the log contexts and timestamps can be valuable for
debugging a failing test. For example, many log lines don't include
information such as the destination address for a request as they
assume this will be provided by the log context. This can make
understanding log output from tests difficult since the log contexts
are not included.
* In order to debug changes to the log …
=> Use the proxy's log formatting in tests

Cargo.lock
- Fixes write infinite loop when header value doesn't fit in buffer.
=> Update h2 to v0.1.21

Cargo.lock
- Fixes leaked DATA frames if never polled.
Closes https://github.com/linkerd/linkerd2/issues/2863
=> Update h2 to v0.1.23

src/app/main.rs, tests/discovery.rs
When the proxy receives an inbound request, it strips the
`l5d-dst-override` header and ignores its value. Instead, this header
value should be honored in the inbound router as it is in the outbound
router. This will enable service profile discovery from ingresses, for
instance.
This branch changes the inbound router to use the `l5d-override-dst`
header preferentially, with only the `l5d-canonical-dst` header taking
priority over it if it is present. The layer that strips the override
header is moved to under the inbound dst router.
In addition, I've added new tests in the discovery module that assert
that the value of the `l5d-override-dst` header is used for profile
discovery when present, on both the inbound and outbound sides of the
proxy. The inbound tests fail prior to the other …
=> Honor `l5d-override-dst` for inbound service profiles

src/app/main.rs, src/app/outbound.rs, src/control/destination/client.rs, src/control/destination/mod.rs, src/control/destination/resolution.rs, src/proxy/http/balance.rs, src/proxy/http/fallback.rs, src/proxy/resolve.rs, src/svc.rs, tests/discovery.rs
When the DNS fallback behavior was removed from the proxy in #259, the
proxy was changed to fall back to original destination routing _any_
time the control plane indicates that no endpoints exist for a
destination. This is incorrect, as the proxy should always treat the
destination service as authoritative. Additionally, this means that
requests to endpoints which are known to not exist will construct an
unnecessary client service, and eventually fail with a 502 error when
the upstream client connection to the non-existent endpoint ultimately
fails. Instead, the proxy should only fall back when the destination is
outside the search suffixes or the Destination service returns an
`InvalidArgument` response.
This is a much larger change than #263. In particular, the fallback
behavior has …
=> discovery: Fall back only on InvalidArgument, in MakeService

src/app/classify.rs, src/proxy/http/metrics/classify.rs, src/proxy/http/metrics/mod.rs, src/proxy/http/metrics/report.rs, src/proxy/http/metrics/service.rs
The metrics layer did not properly count response errors.
This change makes a response status code optional so that response
errors may be counted when no status code is present.
Fixes linkerd/linkerd2#2934
=> metrics: Classify response errors

Cargo.lock, tests/support/client.rs, tests/support/controller.rs
- Adds `http-body` support.
- Propagates http2 client request cancellation.
- Forces yielding of h1 connections if they are ready too often.
=> Update hyper to v0.12.30

src/app/config.rs
Given that the first request to a service incurs a DNS lookup and 2
discovery lookups, a 1s timeout can be too aggressive for some
environments.
Let's relax this to 3s to allow for more slowness during initialization.
=> Relax the default outbound dispatch timeout to 3s

Cargo.lock, lib/router/Cargo.toml, lib/router/src/cache.rs, lib/router/src/lib.rs, src/proxy/http/profiles.rs, src/proxy/http/router.rs
This change introduces an eviction task for router caches. Few changes were made
in how a router uses a cache; we still use `access` and `reserve` handles for
cache interactions.
The issue this change addresses is that services are only dropped from a router
cache when we have reached that cache's capacity.
We drop a service when it has not received a request within the `max_idle_age`.
When the cache is full, we scan through all the services and check their last
access time. If a service's last access time is longer than `max_idle_age`, then
it is removed.
This strategy is problematic because a service is only removed once the capacity
has been reached. If the capacity of a cache is never reached, then a service's
stack is kept around for the lifetime of that router.
When a router is …
=> Eagerly drop services from the router cache

Cargo.lock, src/app/errors.rs, tests/support/server.rs, tests/transparency.rs
If the proxy's client sees an error that contains an HTTP2 error code,
instead of converting that into a 502 response, this change now
propagates the error code back up the server.
----
I noticed this seems to be problematic, as logs in https://github.com/linkerd/linkerd2/issues/2801 mentioned user applications see:
```
err: {
"code": 1,
"metadata": {
"_internal_repr": {
":status": [
"502"
],
"content-length": [
"0"
],
"date": [
"Tue, 18 Jun 2019 16:30:43 GMT"
]
}
},
"details": "Received http2 header with status: 502"
```
With this change, they'll at least see the relevant HTTP2 error instead.
=> Propagate HTTP2 errors from client RST_STREAMs

Cargo.lock
Includes a fix to treat unexpected frames in cases where we can't be absolutely certain as a stream error, which should help reduce what's seen in https://github.com/linkerd/linkerd2/issues/2918
=> Update h2 to v0.1.25

Cargo.lock
Tried out the hyper "hello world" server with this update, and the request-target in the mentioned issue now works.
Fixes https://github.com/linkerd/linkerd2/issues/3015
=> Update httparse to v1.3.4

src/proxy/http/canonicalize.rs
The proxy's canonicalization queries can persist after the observing
service is dropped.
This change modifies the background resolution task to use tokio-sync so
that it can eagerly cease polling for updates when corresponding service
is dropped.
=> canonicalize: stop resolving when the receiver is dropped

lib/router/src/cache.rs
The router only purges its cache only once per `max_idle_age`, which
means that a route may be idle for ~2x `max_idle_age`.
By removing the interval completely, we can ensure that routes are
evicted in a timely fashion.
=> router: Remove interval from router eviction

src/app/main.rs, src/svc.rs
Our `svc::Builder::fallback_on` combinator was a bit surprising, in that
it worked differently from all other combinators, returning a Layer
instead of a Builder.
This change removes this combinator in an attempt to make the fallback
layering logic more explicit in the stack.
=> fallback: Clarify fallback layering

Cargo.lock, Cargo.toml, lib/metrics/Cargo.toml, lib/metrics/src/gauge.rs, lib/metrics/src/serve.rs, lib/router/Cargo.toml, lib/router/src/cache.rs, lib/router/src/lib.rs, lib/task/Cargo.toml, lib/task/src/lib.rs, src/app/config.rs, src/app/main.rs, src/app/mod.rs, src/app/profiles.rs, src/lib.rs, src/logging.rs, src/main.rs, src/proxy/http/router.rs, src/transport/tls/listen_tests.rs, tests/discovery.rs, tests/identity.rs, tests/profiles.rs, tests/shutdown.rs, tests/support/mod.rs, tests/tap.rs, tests/telemetry.rs, tests/transparency.rs
Currently, the proxy uses the `log` crate for log records, and formats
them using `env_logger`. However, `tracing` is capable of providing
significantly richer scoped, contextual diagnostics, which are
especially valuable in asynchronous systems like the proxy.
In addition, switching to `tracing` is a prerequisite for
dynamically reloading the log level (see linkerd/linkerd2#2005).
This branch replaces `env_logger` with `tracing-fmt`, and the `log`
crate's macros with `tracing`. Log records emitted by our
dependencies can still be consumed as `tracing` events using the
`tracing-log` adapter. A custom `tracing-fmt` formatter is used
to replicate the previous log line formatting; this currently uses the
proxy's log contexts in addition to `tracing` spans. Our homemade
log contexts will be …
=> Replace `log` and `env-logger` with `tracing` and `tracing-fmt`

src/app/dst.rs, src/app/errors.rs, src/app/main.rs, src/app/mod.rs, src/app/outbound.rs, src/proxy/http/mod.rs, tests/identity.rs
This was originally implemented in #280, but has since changed enough that a
new PR is being opened
As part of the Tap hardening project, tap should only be served on TLS
connections. Currently, when the Tap service makes an outbound Tap request, the
`Host` header is the Pod IP of the resource. Service discovery is not attempted
and therefore the Tap service initiates a plaintext connection. The introduction
of the `l5d-require-id` header will allow an outbound request to require the
specified identity on the endpoint it connects to.
The `orig_dst_router` router on outbound requests will set the identity of the
`outbound::Endpoint` to the value of the `l5d-require-id` header if it is
present. This is useful specifically for the case explained above when request
are made with an IP as …
=> Introduce `l5d-require-id` request header

Cargo.lock
Includes fix for `SETTINGS_HEADER_TABLE_SIZE`, ref https://github.com/linkerd/linkerd2/issues/3141
=> Update h2 to v0.1.26

src/app/main.rs, src/app/outbound.rs, src/control/destination/resolution.rs, src/proxy/server.rs, tests/discovery.rs
TLDR: Requests whose target authority is a socket address do not properly fall
back. Requests to unresolvable authorities which are DNS names do fall back as
expected.
In a control plane branch, I have the tap controller properly adding the header
metadata to tap requests, and the pod proxy’s expecting the tap identity the
requests would be coming from. After installing a local build of this control
plane and the proxy that supports `l5d-require-id`, I noticed that the tap
controller’s proxy was still not setting identity on `outbound::Endpoint`s when
the header was there.
I began looking for the `debug!` lines that would be hit in the
`orig_dst_router` because I would expect to be hitting that router, and did not
see them—indicating those requests were still going through the balancer. …
=> Properly fall back in the dst_router

update-rust-version.sh
When running the update-rust-version script, it was easy to run it
without an argument, which breaks existing configuration.
This change improves the script to handle errors, with some other
shell lints addressed.
=> update-rust-version: Check usage

src/app/config.rs, src/app/main.rs, src/app/tap.rs, tests/support/proxy.rs, tests/tap.rs
With linkerd/linkerd2#3155 merging, proxy containers will now always have the `LINKERD2_PROXY_TAP_SVC_NAME` variable in their environment. This variable can now be reliably used to check that the client names of incoming tap requests match this value.
If the values do not match, we will always return the gRPC Unauthenticated status code. If the values do match, we will accept the connection.
If there is no client identity, we will similarly return the gRPC Unauthenticated status code.
Closes linkerd/linkerd2#3157
Closes linkerd/linkerd2#3163
Signed-off by: Kevin Leimkuhler <kleimkuhler@icloud.com>
=> Require identity on tap requests

src/app/dst.rs, src/app/metric_labels.rs, src/app/outbound.rs
Supersedes https://github.com/linkerd/linkerd2-proxy/pull/296
The authority label reflects the concrete dst of the request in the endpoint stack.  In the case of a traffic split, this may be different from the actual authority of the request (i.e. the logical dst).
We add the logical dst as a field on the endpoint target and use this value for the authority label instead of the concrete dst.
The net result is that the authority field reflects the apex service of a traffic split and the `dst_service` label reflects the leaf service.  
E.g.:
```
response_total{authority="authors.default.svc.cluster.local:7001",direction="outbound",dst_control_plane_ns="linkerd",dst_deployment="authors-v2",dst_namespace="default",dst_pod="authors-v2-7cffd4894-crhbw",dst_pod_template_hash="7cffd4894",dst_servi …
```
=> Authority label should reflect logical dst

Cargo.lock, Cargo.toml, lib/stack/Cargo.toml, src/app/identity.rs, src/app/main.rs, src/lib.rs
The `futures_watch` crate is superceded by `tokio::sync::watch`.
This change replaces our single usage of a watch.
=> Replace futures_watch with tokio::sync::watch

src/control/destination/resolution.rs
When destinations idle out of the router cache, the corresponding destination lookup is not cancelled.  This can lead to a build-up of many subscriptions as entries idle out of the cache and are later re-added.  As these subscriptions accumulate, memory usage of the destination service grows, manifesting as a memory leak.
We use a hangup oneshot so that when the resolution is dropped, the daemon will be notified and will terminate.
=> Hangup destination resolutions when dropped

Cargo.lock, Cargo.toml, src/logging.rs
An upstream change tokio-rs/tracing#108 changed how `tracing` represents
`Event`s that are converted from `log::Record`s, so that metadata is
represented as fields on the event rather than as `tracing::Metadata`
This resulted in log records being formatted differently from `tracing`
events in the proxy's log output, with a format that was much harder to
read than the normal formatting for events.
This branch updates the tracing dependency versions, and uses new APIs
added in tokio-rs/tracing#193 to normalize this metadata so that it is
formatted consistently with other events.
Log records, such as those from `h2`, were previously formatted like this:
```
TRCE [     0.662591s] log schedule_pending_open log.target="h2::proto::streams::prioritize" …
```
=> logging: format log records consistently

Cargo.lock, tests/discovery.rs, tests/identity.rs, tests/profile_dst_overrides.rs, tests/profiles.rs, tests/shutdown.rs, tests/support/client.rs, tests/support/controller.rs, tests/support/identity.rs, tests/support/mod.rs, tests/support/proxy.rs, tests/support/server.rs, tests/support/tap.rs, tests/support/tcp.rs, tests/tap.rs, tests/telemetry.rs, tests/transparency.rs
When updating the repo to Rust 2018, some of the test modules were left
without the proper updates.
=> tests: Update to Rust 2018

.travis.yml
In theory, travis's cache of build artifacts is useful for reducing CI
run times from ~30m to ~10m. However, in practice, the cache grows in
excess of 3GB after just a few runs. This frequently causes subsequent
runs to timeout while fetching the cache image, causing spurious
failures and, on master, requiring manual intervention to produce proxy
binaries.
CI needs to be predictable first and fast second; so, until we can
figure out a more robust caching scheme, I propose that we disable
caching from CI so that builds do not require manual intervention.
=> travis: `make clean` after tests

src/app/classify.rs
When a request is canceled by a client, the server seems to just drop
the open response in a way that prevents the server code from being
notified of the reset reason, and so our classification code treats this
as if the stream ended without trailers.
This was previously treated as a failure, but this should be handled as
a success so that cancelations are not mistaken for application errors.
Addresses linkerd/linkerd2#3281
See also linkerd/linkerd2#3282
=> classify: Assume success on missing grpc-status

Cargo.toml, lib/hyper-balance/Cargo.toml, lib/linkerd2-addr/Cargo.toml, lib/linkerd2-conditional/Cargo.toml, lib/linkerd2-dns-name/Cargo.toml, lib/linkerd2-drain/Cargo.toml, lib/linkerd2-identity/Cargo.toml, lib/linkerd2-metrics/Cargo.toml, lib/linkerd2-never/Cargo.toml, lib/linkerd2-proxy-core/Cargo.toml, lib/linkerd2-proxy-resolve/Cargo.toml, lib/linkerd2-router/Cargo.toml, lib/linkerd2-signal/Cargo.toml, lib/linkerd2-stack/Cargo.toml, lib/linkerd2-task/Cargo.toml, lib/linkerd2-timeout/Cargo.toml
Rather than have my name plastered all over the place, let's use the
developer list as the canonical author for this repo.
=> cargo: Set authors to Linkerd Developers

src/app/inbound/mod.rs, src/app/outbound/mod.rs, src/proxy/http/profiles/router.rs
The builder type should only be used when composing layers. Now that we
have `Builder::into_inner`, we need not store a builder in the profile
router.
=> Stop using a Builder in the profile router

.travis.yml
We've seen frequent timeouts in travis. Until this is ported to actions,
let's increase the timeout.
=> travis: Allow 60 minutes for integration tests

src/app/inbound/mod.rs, src/app/main.rs, src/app/outbound/mod.rs, src/proxy/accept.rs, src/proxy/http/profiles/router.rs, src/svc.rs
Service stacks were built from "top" to bottom, so that the concrete
service type is satisied after all middlewares are composed toegether.
This leads to exceedingly complex compiler error messages.
This change adds a `svc::Stack` builder that aids composing layers
around a concrete inner service so that the compiler can more clearly
identity the layer that violates the type contract.
Note: this does *not* appear to improve compile times.
No functional changes are intended.
=> Improve stack-related compiler error messages

Cargo.lock
Includes a fix for client GET requests that explicitly declare a message payload.
Closes https://github.com/linkerd/linkerd2/issues/3310
=> update hyper to v0.12.34

.github/workflows/pull_request_docker.yml, .github/workflows/pull_request_rust.yml, .travis.yml, Dockerfile, update-rust-version.sh
Disables Travis on Pull Requests, replacing it with GitHub Actions.
Travis remains enabled for master builds for the moment.
=> Use GitHub Actions for Pull Requests

.github/workflows/pull_request_docker.yml, .github/workflows/pull_request_rust.yml, update-rust-version.sh
The first version of the action didn't actually use the rust containers
to drive the build. This change pins the ubuntu and rust versions.
Even though the base OS includes rust-1.37, we want to control our rust
version independently.
=> CI: Run tests inside rust container

Cargo.lock, Cargo.toml, src/logging.rs
This branch updates the proxy to depend on 0.1 versions of `tracing-log`
and `tracing-subscriber`, rather than alpha versions. The dependency on
`tracing-fmt` was removed, as that code was moved into
`tracing-subscriber` in tokio-rs/tracing#311.
Additionally, this should now allow us to use filter configuration that
involve dynamic filters on span fields, as well as on static targets.
Note that this may be of limited value *currently*, since the proxy
still uses our sui generis logging contexts rather than `tracing` spans,
but could be useful in the future.
Note that this is a duplicate of #342. I've submitted a new PR since CI
seems to be stuck refusing to build that branch. Therefore, this
closes #342.
=> update tracing crates

.github/actions/release-tag-meta/Dockerfile, .github/actions/release-tag-meta/action.yml, .github/actions/release-tag-meta/entrypoint.sh, .github/workflows/release.yml
The first pass at releases used a container I found on the internet
called `github/ghx`, which provides a CLI interface to github that was
usable within actions. I've contacted the author, who says it is
unmaintained (and the sources for it are not public); so I've elected to
use softprops' release action.
In order to do this, I added a local action that handles the parsing of
the git `refs/*` syntax into the proper release metadata.
=> ci: Use a readymade release action

src/app/config.rs
Port `587` is very commonly used for SMTP, and I think it would be useful to have it included in the default list of ports to skip protocol detection.
For example, the docs for [`sendgrid`](https://sendgrid.com/docs/for-developers/sending-email/rubyonrails/#configure-actionmailer-to-use-sendgrid), [`mailgun`](https://www.mailgun.com/blog/which-smtp-port-understanding-ports-25-465-587) and [`ses`](https://aws.amazon.com/blogs/messaging-and-targeting/debugging-smtp-conversations-part-1-how-to-speak-smtp/) will all mention port `587`, and usually use that in their examples as well, instead of `25`.
=> Add 587 to the list of ports to disable protocol detection

Makefile, README.md
A previous change to the packaging logic accidentally removed the
SHA calculation to `make package`. This restores it.
=> Record SHA of package artifact

src/app/main.rs, src/app/profiles.rs, tests/support/controller.rs
The fact that the proxy sends resolve requests with a scheme value of
`k8s` is an accident of history. Given that this value is currently
unused by the controller, stop setting a scheme value entirely.
=> resolve: Do not send the 'k8s' scheme

.github/actions/remote/Dockerfile, .github/workflows/rust.yml
The linkerd org has dedicated hardware on which our integration tests
can be run.
This change reduces test time from ~80 minutes to...[pending]
=> ci: Run integration tests on dedicated host

Cargo.lock, lib/linkerd2-opencensus/Cargo.toml, lib/linkerd2-opencensus/src/lib.rs, lib/linkerd2-opencensus/src/metrics.rs, src/app/main.rs
Fixes https://github.com/linkerd/linkerd2/issues/3453
Instrument the opencensus exporter with the following metrics:
```
span_export_streams 1
span_export_requests 497
span_exports 994
```
=> Instrument the opencensus exporter

Cargo.lock, Cargo.toml
This picks up several bugfixes, including one for a potential memory
leak (tokio-rs/tracing#366), which probably doesn't occur in the proxy
currently but could be triggered in the future.
=> logging: update tracing-subscriber to 0.1.4

Cargo.lock, Cargo.toml, lib/linkerd2-opencensus/Cargo.toml, lib/linkerd2-proxy-api-resolve/Cargo.toml, lib/opencensus-proto/Cargo.toml, src/tap/grpc/server.rs, tests/support/tap.rs
PR linkerd/linkerd2-proxy-api#33 adds headers to the `RequestInit`,
`ResponseInit`, and `ResponseEnd` tap events. This branch updates the
proxy to populate these fields.
This updates the proxy-api dependency to the tag  `v0.1.10`, or
linkerd/linkerd2-proxy-api@34ab9c848f2cadb6d3e9dc47cca5b1c36adcd59f
=> tap: add headers to tap events

lib/linkerd2-trace-context/src/layer.rs, lib/linkerd2-trace-context/src/propagation.rs, src/app/spans.rs
Nginx uses 8 byte trace ids whereas OpenCensus expects trace ids which are 16 bytes.  When we encounter an 8 byte trace id, we discard it, breaking the trace tree.
When reading trace id headers, we now left-pad trace ids with 0s to 16 bytes.  This is consistent with the way that OpenCensus handles trace ids less than 16 bytes: https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ochttp/propagation/b3/b3.go#L66
We also now log the appropriate error when we fail to emit a span.  This will allow us to distinguish between the scenario when the span receiver has been dropped vs when span conversion fails.
=> Handle 8 byte trace ids

src/proxy/http/client.rs, src/proxy/http/glue.rs, src/proxy/http/h2.rs, src/proxy/http/metrics/mod.rs, src/proxy/http/mod.rs
We no longer rely on the `ClientUsedTls` marker type. Remove it and all
of the type constraints it required.
=> internal: Remove the `ClientUsedTls` response extension

linkerd/app/core/src/trace.rs, linkerd/app/integration/src/lib.rs, linkerd/app/integration/src/proxy.rs, linkerd/app/integration/tests/telemetry.rs
This branch reworks the test-support proxy so that each test gets its
own `tracing` subscriber, rather than sharing a single global
subscriber. Running a whole bunch of tests in parallel with verbose
tracing output turned on is now much snappier.
As a future extension of this, we might want to replace the test-mode
subscriber with a subscriber that, rather than printing to stdout,
writes to a buffer and dumps the whole buffer when the test completes,
along with a message identifying which test the output was collected
from, or with one that prefixes all log lines with the name of the test.
Ideally, this kind of test-specific functionality could be added 
upstream.
=> give each test proxy its own tracing subscriber

Cargo.lock, lib/hyper-balance/Cargo.toml, lib/linkerd2-proxy-resolve/Cargo.toml, lib/linkerd2-proxy-transport/Cargo.toml, lib/linkerd2-reconnect/Cargo.toml, lib/linkerd2-router/Cargo.toml, lib/linkerd2-stack/Cargo.toml, lib/linkerd2-trace-context/Cargo.toml, lib/opencensus-proto/Cargo.toml
```
ID:       RUSTSEC-2019-0011
Crate:    memoffset
Version:  0.2.1
Date:     2019-07-16
URL:      https://rustsec.org/advisories/RUSTSEC-2019-0011
Title:    Flaw in offset_of and span_of causes SIGILL, drops uninitialized memory of arbitrary type on panic in client code
Solution:  upgrade to >= 0.5.0
```
```
ID:       RUSTSEC-2019-0013
Crate:    spin
Version:  0.5.0
Date:     2019-08-27
URL:      https://rustsec.org/advisories/RUSTSEC-2019-0013
Title:    Wrong memory orderings in RwLock potentially violates mutual exclusion
Solution:  upgrade to >= 0.5.2
```
=> Audit Cargo.lock for unused and outdated crates

.github/workflows/docker.yml, Dockerfile, Makefile
Replicate our integration test configuration to also run docker builds
on our remote host.
Furthermore, run these builds in unoptimized mode (since we don't
consume the results).
=> ci: Run docker builds on linkerd-docker host

linkerd/app/core/src/config.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/integration/src/proxy.rs, linkerd/app/src/lib.rs, opencensus-proto/Cargo.toml
The `LINKERD2_PROXY_INBOUND_FORWARD` configuration was implemented to support local testing; but the proxy has evolved to the point where it
needs a proper runtime harness (as in docker or the integration test
infrastructure) to run.
This option is just a bit of debt that should be removed to simplify 
code/diagnostics.
This also disables doctests in the opencensus crate to prevent spurious failures.
Furthermore, the proxy's initial logging has been clarified somewhat.
Closes linkerd/linkerd2#3609
=> Remove the LINKERD2_PROXY_INBOUND_FORWARD config

linkerd/app/core/src/profiles.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/lib.rs, linkerd/proxy/http/src/profiles/router.rs
Currently, the profile_suffixes are wired through into the inbound and
outbound proxies to configure the profile layer.
This change decouples inbound/outbound proxy initialization from this
detail of the profile client.
=> internal: Move suffix-filtering into profiles API

Makefile
`make package` currently builds all crates, including the time-consuming
integration tests. This change ensures that only crates needed to build
the binary are compiled.
=> make: Do not compile integration tests during packaging

Cargo.lock, linkerd/app/core/src/errors.rs, linkerd/app/core/src/lib.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/proxy/http/src/lib.rs, linkerd/router/Cargo.toml, linkerd/router/src/layer.rs, linkerd/router/src/lib.rs
There's nothing HTTP-specific about the router.
This change moves the layer implementations--which unnecessarily enforce
HTTP-specific type requirements--into the generic router crate, relaxing
its type constraints.
=> Make the router HTTP-agnostic

linkerd/app/core/src/profiles.rs, linkerd/proxy/http/src/profiles/mod.rs
All communication on a destination client can become stalled if an individual profile client does not consume profile updates in a timely manner.
This change alters the buffering strategy for profile updates to ensure that the resolution stream is always polled, independently of whether the service is actively being used.
=> profiles: Eagerly read profiles off the wire

linkerd/app/core/src/profiles.rs, linkerd/app/outbound/src/lib.rs, linkerd/router/src/cache.rs, linkerd/router/src/layer.rs, linkerd/router/src/lib.rs, linkerd/router/src/purge.rs
The router's cache purging tasks never complete. This means that
when a router is dropped, it's purge task is leaked into the executor,
possibly holding services.
This change uses an mpsc to ensure that the purge task is notified when
all of the routers using this cache have been dropped.
=> router: Ensure that the purge task completes

linkerd/app/core/src/serve.rs, linkerd/app/inbound/src/lib.rs
The proxy's server does not instrument tracing contexts with the peer's
connection metadata, causing hyper's server logs to be devoid of this
helpful context.
This change adds an _accept_ context that includes the peer's address.
Fixes #3799
=> app-core: Add `accept` context with peer addr

linkerd/app/src/env.rs
Related to #3807, but serves as a more temporary fix until the proxy injector
provides a way for this to be configured from an install.
Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>
=> Remove default for destination lookup subnets

linkerd/app/src/env.rs
Currently, the proxy uses the protocol defaults for HTTP/2 connection
window size (64K). Because this is the same as the stream window size, a
single stream can consume the entire connection window, stalling other
streams.
This change alters the default connection window to be 1MB, supporting
up to 16 stalled streams.
While we primarily care about this setting for client (response)
receiver windows, it seems like a good thing to open the server
(request) receiver window as well (and the configuration is not
currently distinguishable).
=> Configure the HTTP/2 connection window to 1MB

linkerd/app/core/src/classify.rs
Linkerd classifies all gRPC status codes except `OK` as errors. This can negatively affect a gRPC server's success rate, even when it is only returning things like `NOT_FOUND` or `INVALID_ARGUMENT`.
This change narrows down the list of gRPC status codes that are considered an error to:
* UNKNOWN (2)
* DEADLINE_EXCEEDED (4)
* INTERNAL (13)
* UNAVAILABLE (14)
* DATA_LOSS (15)
Please see [this linkerd2 issue](https://github.com/linkerd/linkerd2/issues/3729) for more details.
Signed-off-by: Sergio Castaño Arteaga <tegioz@icloud.com>
=> Classify some gRPC status codes as non-errors

linkerd/app/outbound/src/lib.rs, linkerd/proxy/discover/src/buffer.rs, linkerd/proxy/discover/src/lib.rs
If a load balancer is not polled, i.e. because it is idle/leaked, its
resolution stream can fill up, causing backpressure onto the destination
controller client.
This change implements a timeout for this scenario. When the resolution
buffer is at capacity for a full idle timeout, the background resolution
completes to free its resources.
=> discover: Timeout stalled resolutions

linkerd/addr/src/lib.rs, linkerd/app/core/src/control.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/proxy/http/src/h1.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/normalize_uri.rs
Currently, the `http::normalize_uri` middleware determines absolute-form
authorities by reading request extensions. This hidden coupling makes
changing things fairly difficult. Instead, we can use the target types,
which already hold the relevant info, to determine the absolute-form
authority if needed.
=> http: Use the endpoint type to inform URI normalization

linkerd/opencensus/src/lib.rs
In the opencensus span exporter, we call `poll_ready` on the span send channel sender to determine if there is capacity in this channel to send spans.  However, the channel sender that we `poll_ready` on is a clone of the original and the clone is dropped shortly after the call to `poll_ready`.  This can cause our interest registration to be dropped and the task may not be notified when capacity becomes available.
The clone is unnecessarily and we can remove it.
=> Remove clone in opencensus exporter to ensure task is notified

Cargo.lock, Cargo.toml, linkerd/lock/Cargo.toml, linkerd/lock/src/lib.rs
In order to make a service shareable, a locking middleware can provide
mutually exclusive access without buffering requests.
This middleware is currently unused, but will be used in followup
changes.
=> internal: Introduce a locking middleware

Cargo.lock
Should have been in https://github.com/linkerd/linkerd2-proxy/commit/eb49e697b907f5be4da1376ea69ae9e198092d87
=> Actually update http to v0.1.21

Cargo.lock, Cargo.toml
This branch updates the proxy's `prost` dependency to a patched version
of `prost` 0.5 that incorporates the cahnges in danburkert/prost#268.
This patch fixes a security issue where a malicious protobuf message
could be used to trigger a stack overflow.
We are unfortunately unable to easily update to `prost` 0.6.1, which
includes this fix, as 0.6 updates the `bytes` dependency to 0.5. The
`tokio` 0.1 ecosystem that the proxy currently uses still depends on
0.4, and the breaking changes in 0.5 are quite significant. Therefore,
updating to `bytes` 0.5 would require a lot of fairly large changes to
legacy versions of...pretty much everything (`tokio-io`, `tokio-buf`,
`hyper`, `http-body`...). As we intend to update to `tokio` 0.2 in the
near future, patching all these legacy dependencies is …
=> patch `prost` 0.5 to pick up security fix

linkerd/app/core/src/handle_time.rs, linkerd/app/core/src/telemetry/process.rs, linkerd/metrics/src/counter.rs, linkerd/metrics/src/gauge.rs, linkerd/metrics/src/histogram.rs, linkerd/metrics/src/prom.rs, linkerd/opencensus/src/metrics.rs, linkerd/proxy/transport/src/metrics/mod.rs
The `Counter` and `Gauge` metrics currently hold `u64` values. This
means that all uses need to gaurd access with a `Mutex`.
By changing both types to hold an `AtomicU64`, we can avoid using locks
in some cases.
=> metrics: Make Counter & Gauge atomic

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/core/src/errors.rs, linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/require_identity_on_endpoint.rs, linkerd/error-respond/Cargo.toml, linkerd/error-respond/src/lib.rs
When the proxy encounters errors, it sets the HTTP response code.
However, gRPC applications do not honor HTTP response codes and,
instead, rely on the `grpc-status` response header to be set. Since the
proxy has specialized gRPC support in some other places (namely
metrics/classification), we should attempt to behave well with gRPC
applications.
This change extracts the `errors` module from app-core into a new
`error-respond` crate, which exposes a simplified trait interface.
`app::core::errors` now provides an implementation for these traits that
is able to translate proxy-internal errors to gRPC status codes and
messages.
Fixes linkerd/linkerd2#3493
=> Set grpc-status headers on dispatch errors

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/core/src/trace.rs, linkerd/proxy/transport/Cargo.toml
This commit updates the proxy's `tracing-subscriber` dependency from
0.1.4 to 0.2.0-alpha.4. This alpha includes tokio-rs/tracing#514, which
fixes a pair of issues which prevent spans from being considered closed.
One of these issues exists in 0.1.x as well.
When spans are not considered closed, storage allocated for those spans'
per-span data is not reused. Therefore, this issue results in a memory
leak.
Note that some span storage will still not appear to be
_deallocated_ after this change, but that storage will be reused when
spans are allowed to close correctly.
In addition, I've updated the proxy's `trace` module to remove the
custom formatter. This was used only to add Linkerd's custom logging
contexts to `tracing-subscriber` logs, and as we no longer use the
logging contexts, we …
=> trace: update `tracing-subscriber` to 0.2.0-alpha.4

linkerd/proxy/discover/src/buffer.rs
Users have reported encountering the "discovery task failed" error
message. Unfortunately, the underlying error is only logged at the debug
level, so we can't easily diagnose the underlying issue.
This change raises the logging level of these errors to be WARN so that
they are visible at the default logging levels.
=> discover: Warn on discovery error

linkerd/router/src/cache.rs
We initially opted to pre-allocate the delay queue to avoid allocation
at runtime. However, practically, router capacities are _much_ higher
than their typical usage; so we incur an extra ~1MB+ of allocation that
will never really be used (for outbound routers).
This change initializes the router's DelayQueue with only a single slot
by default. The capacity will be increased at runtime as needed.
=> router: Avoid large up-front allocations

linkerd/app/core/src/errors.rs, linkerd/proxy/http/src/orig_proto.rs
When synthesizing error responses, all errors were sent with the default
HTTP/1.1 response. This change ensures that the request's version is
used when synthesizing a response.
=> errors: Set correct HTTP version on responses

linkerd2-proxy/src/main.rs
Before migrating from `env_logger` to `tracing`, the proxy set up
logging before trying to read a configuration from the environment. This
meant that any errors that occurred while parsing env vars could be
logged at the error level and would be displayed to the user. Since we
log these errors when they occur, the formatted output from the error
types the parsing methods return is pretty minimal.
When we switched to `tracing`, we moved the tracing initialization so
that it occurs _after_ parsing the config from the env. This means that
the event macros for config errors now occur when there is no `tracing`
subscriber to collect and format them. Currently, if an env var is
malformed, we see something like this:
```console
$ LINKERD2_PROXY_DESTINATION_SVC_ADDR="bad" cargo run
Finished dev …
```
=> app: initialize tracing prior to parsing env vars

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/core/src/trace.rs, linkerd/proxy/transport/Cargo.toml
Version 0.0.7 of `sharded-slab` contains a bug where, when the `remove`
method is called with the index of a slot that is not being accessed
concurrently, the slot is emptied but **not** placed on the free list.
This issue meant that, under `tracing-subscriber`'s usage pattern, where
slab entries are almost always uncontended when reused, allocated slab
pages are almost never reused, resulting in unbounded slab growth over
time (i.e. a memory leak).
This commit updates `tracing-subscriber`' to version 0.2.0-alpha.6,
which in turn bumps the `sharded-slab` dependency to v0.0.8, which
includes commit hawkw/sharded-slab@dfdd7ae. That commit fixes this bug.
I've empirically verified that, after running `linkerd2-proxy` under
load with a global `trace` filter that enables a *lot* of spans, heap …
=> trace: update tracing-subscriber to 0.2.0-alpha.5

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/proxy/transport/Cargo.toml
This release makes a number of significant performance improvements when
filtering events emitted through the `log` compatibility layer (such as
from `hyper` and `h2`). See tokio-rs/tracing#586 for details.
Since these performance improvements apply to cases where a filter
_disables_ an event, as well as to enabling events, this should improve
the proxy's performance with the default log configuration, especially
given that `h2` and `hyper` emit a _lot_ of `trace`-level logs in hot
paths. Ignoring those logs should now have a much lower overhead.
In addition, 0.2.1 fixes a bug where `EnvFilter`'s filter selection
differed from the `env_logger` behavior it was intended to emulate. If
the most specific filter directive that applies to a given event did not
enable that  event's level, filter …
=> trace: update `tracing-subscriber` dependency to 0.2.1

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/core/src/errors.rs, linkerd/app/core/src/lib.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/metrics.rs, linkerd/error-metrics/Cargo.toml, linkerd/error-metrics/src/layer.rs, linkerd/error-metrics/src/lib.rs, linkerd/error-metrics/src/service.rs
The proxy handles errors by synthesizing responses; however, depending
on where such an error occurs, it may not be recorded by a metrics
layer.
This change introduces a `request_errors_total` counter that records
the number/kind of errors encountered. This is immediately helpful for
debugging and diagnostics, but could also be helpful to view in the UI.
We may want to revisit this metric, especialy its labels, before relying
on it more prominently. But in the meantime it's extraordinarily useful
as it is.
=> Record a metric of proxy errors

Cargo.lock, Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/core/src/lib.rs, linkerd/app/core/src/metric_labels.rs, linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/metrics.rs, linkerd/stack-metrics/Cargo.toml, linkerd/stack-metrics/src/layer.rs, linkerd/stack-metrics/src/lib.rs, linkerd/stack-metrics/src/service.rs
When diagnosing issues, it can be difficult to reason about the states
of the various caches in the proxy.
This change introduces a set of `stack` metrics to help proxy developers
diagnose issues. The metrics track stack creations, stack deletions, and
the amount of time a given service is not available (via
`stack_poll_total_ms`)
```
:; kubectl exec  -n burn-http deploy/client-burst -c client -- curl -s localhost:4191/metrics |grep -e ^stack
stack_create_total{direction="outbound",name="fallback.endpoint"} 0
stack_create_total{direction="outbound",name="balance.endpoint"} 1
stack_create_total{direction="outbound",name="logical.dst"} 1
stack_create_total{direction="outbound",name="addr"} 1
stack_create_total{direction="outbound",name="source"} 100 …
```
=> Expose the number of service instances in the proxy

Cargo.lock, Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/core/src/svc.rs, linkerd/concurrency-limit/Cargo.toml, linkerd/concurrency-limit/src/lib.rs
Tower's `ConcurrencyLimit` middleware instantiates a new semaphore for
each service created by the layer. However, in an upcoming proxy change,
I'd like to avoid having a single `Service` instance that all requests
must flow through and, instead, wrap a service created for each
connection. In order to enforce a global concurrency limit, the
middleware needs to be changed to share a semaphore across all services
created by the layer.
This presents no functional change to how the concurrency limit is
applied today.
This is basically copy/pasted from https://github.com/tower-rs/tower/blob/v0.1.x/tower-limit/src/concurrency/service.rs
=> concurrency-limit: Share a limit across Services

Cargo.lock, linkerd/lock/src/error.rs, linkerd/lock/src/layer.rs, linkerd/lock/src/lib.rs, linkerd/lock/src/lock.rs, linkerd/lock/src/service.rs, linkerd/lock/src/shared.rs, linkerd/lock/src/test.rs, linkerd/router/Cargo.toml, linkerd/router/src/cache.rs, linkerd/router/src/lib.rs, linkerd/router/src/purge.rs
We used Tokio's Lock implementation in the router's cache
implementation, though we know it can leak under contention.
This change generalizes the Lock to return a guarded value (like Tokio's
lock). This change simplifies the Lock's state management: the Lock may
no longer hold a value, nor can it fail.
The `lock::Service` implementation now holds a `Result<Service,
ServiceError>` so that lock services may still broadcast the inner
service's failure.
=> lock: Generalize to protect a guarded value

linkerd/app/core/src/svc.rs, linkerd/app/outbound/src/lib.rs, linkerd/fallback/src/lib.rs
The fallback middleware currently operates by applying a primary layer
to an underlying service and, if that primary service does not produce a
result, the fallback layer is applied to the underlying service to
produce a result.
This change modifies the middleware to no longer require that the
underlying service be shared by the primary and fallback layers.
Instead, the middleware attempts to produce a result from the underlying
service and, if that fails, the fallback service is used.
This will allow the fallback middleware to be used more flexibly in
upcoming changes.
=> fallback: Operate on Services instead of Layers

linkerd/app/src/env.rs
Even though we expect there to be only a small number of pod-local HTTP services, clients may address the pod by a wide variety of names.  We increase the inbound router capacity so as to not fail requests when this is the case.
=> Increase inbound router capacity default to 10000

Cargo.lock, linkerd/app/core/src/classify.rs, linkerd/app/core/src/errors.rs, linkerd/app/integration/tests/profiles.rs, linkerd/app/outbound/src/lib.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/timeout.rs, linkerd/timeout/Cargo.toml, linkerd/timeout/src/error.rs, linkerd/timeout/src/lib.rs
The `proxy::http::timeout` middleware currently creates HTTP responses
when a timeout is encountered. Instead, we should allow the error to
propagate through the stack as an error so that all synthesized
responses happen in one place.
This change means that we no longer annotate a `status_code` label in
the `route_response_total` metric, though the `classification` and
`error` labels remain unchanged.
We can also avoid using a `tower::util::Either` by encoding the optional
behavior within the implementation (cutting down on compile-time type
bloat).
=> timeout: Do not synthesize HTTP response

linkerd/addr/src/lib.rs
When building an `Authority` value from a DNS name, we should avoid
encoding trailing dots.
=> addr: Avoid trailing dots in authorities

linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/require_identity_on_endpoint.rs
Makes the naming uniform with newer stack modules and relaxes type
constraints to avoid capturing body types in the Layer (i.e. so the
layer can be used across stacks of varying body types).
=> outbound: Relax type constraints in require_identity_on_endpoint

linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/lib.rs, linkerd/stack/src/lib.rs, linkerd/stack/src/map_response.rs
The inbound client may never initiate a TLS connection, but we use a TLS
middleware to ensure the underlying transport is boxed. The BoxedIo type
enforces shutdown semantics differently than the raw TcpStream, and we
rely on this behavior in TCP forwarding.
This change introduces a stack::map_response middleware; and replaces
use of the inbound TLS client with a layer that boxes transports.
=> inbound: Box client transports to ensure shutdown

linkerd/app/core/src/control.rs, linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/identity.rs, linkerd/app/src/lib.rs, linkerd/app/src/oc_collector.rs, linkerd/proxy/http/src/client.rs, linkerd/proxy/http/src/h2.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/transport/src/connect.rs, linkerd/proxy/transport/src/lib.rs, linkerd/proxy/transport/src/metrics/mod.rs, linkerd/proxy/transport/src/tls/client.rs, linkerd/proxy/transport/src/tls/mod.rs, linkerd/proxy/transport/tests/tls_accept.rs, linkerd/stack/src/lib.rs, linkerd/stack/src/map_response.rs
This change:
* Renames `HasPeerAddr` to be `ConnectAddr`. "Peer" is ambiguous, and
not clear about the intended use;
* Creates a named `transport::Connect` service type. This supports the
`svc::connect` stack helper;
* Removes unnecessary type constraints from various modules;
* Simplifies naming & logic in `http::client`;
* Removes redundant trace context information from `http::h2`;
=> Cleanup transport::Connect & http::Client types

linkerd/app/src/identity.rs, linkerd/app/src/oc_collector.rs, linkerd/proxy/identity/src/certify.rs
`proxy::identity::certify::Daemon` unnecessarily requires that the gRPC
client implements `Clone`, despite there being no such logical
requirement in the implementation.
This change removes the `Clone` requirement and the `Lock` from the
identity client's stack. This change also removes the `Lock` from the
`oc_collector`, as it has no `Clone` requirement.
=> Remove Clone requirement from controller clients

linkerd/app/core/src/proxy/server.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs
`proxy::server` accepts a `MakeService` to build an HTTP service for
each connection; but it doesn't properly drive the service before
invoking it (which is a violation of the Service contract, though a
benign one in this instance).
This change uses `stack::NewService` to avoid these readiness concerns.
We also relax unnecessary type constraints.
=> server: Simplify HTTP server type constraints

linkerd/app/outbound/src/endpoint.rs
Our metrics expect the `authority` to be set to the logical address, not
the concrete address (i.e. when TrafficSplit may override the concrete
destination). The concrete service is annotated via endpoint labels.
=> outbound: Set logical address on endpoints

Cargo.lock, linkerd/app/Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/integration/Cargo.toml, linkerd/proxy/api-resolve/Cargo.toml, linkerd/proxy/api-resolve/src/metadata.rs, linkerd/proxy/api-resolve/src/pb.rs, linkerd/proxy/identity/Cargo.toml, linkerd/proxy/tap/Cargo.toml, linkerd/service-profiles/Cargo.toml
This PR uses the latest changes to the proxy-api and consumes the authority override data, adding to the `Metadata` struct
=> Wire authority override coming from discovery

linkerd/http-metrics/src/lib.rs, linkerd/http-metrics/src/requests/report.rs
We export raw histograms for all HTTP metrics layers; but in some cases
these values are never consumed. This change modifies the http metrics
`Report` type to support disabling export of latencies.
This feature is not used yet but will be used in a follow-up.
---
We can revisit how to skip recording as well, but in order to address https://github.com/linkerd/linkerd2/issues/4215 expediently, I think addressing this only on the report-side is a good stopgap.
=> http-metrics: Make latency export optional

linkerd/app/outbound/src/lib.rs, linkerd/app/src/metrics.rs, linkerd/http-metrics/src/lib.rs, linkerd/http-metrics/src/requests/report.rs
339efa8 incorrectly removed the route_actual metrics scope from the
outbound stack. This change restores these metrics but omits latency
buckets from export.
Fixes linkerd/linkerd2#4215
=> Restore the route_actual_response_total metric

linkerd/app/inbound/src/lib.rs
When the inbound proxy serves many unique targets on a single port,
requests may incorrectly timeout (especially, it seems, when the client
is attempting to reconnect).
This change creates an HTTP endpoint stack for each target (i.e.
Authority). This means that requests to distinct targets will always be
transported over distinct  localhost connections.
This problem was reproducible via:
```sh
for _ in $(seq 10) ; do
for i in $(seq -w 100) ; do
host="server-${i}.test.example.com"
curl -sH "Host: $host" 127.0.0.1:4143 -w "$host\t%{http_code}\n"
done
done
```
=> inbound: Do not cache per-endpoint services

linkerd/app/core/src/accept_error.rs, linkerd/app/core/src/serve.rs
I didn't want to propose this in the PR without trying it...
We can eliminate the Box in AcceptError with only a minor inconvenience of adding an extra static constraint.
=> Unbox AcceptError

linkerd/app/src/env.rs, linkerd/app/src/oc_collector.rs
Fixes https://github.com/linkerd/linkerd2/issues/4008
This PR makes the proxy read file present at `/var/run/linkerd/podinfo/labels` and convert it into a `HashMap` and use those labels as attributes for spans/traces. 
https://github.com/linkerd/linkerd2/pull/4199 updates the control-plane helm charts to mount pod labels as file to the proxy coontainer [using downwardAPI](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/)
With these changes, Traces would have pod labels as attributes, Allowing us to directly link jager dashboard links from the Linkerd dashboard (like we do with Grafana), part of https://github.com/linkerd/linkerd2/pull/4177 . This was not possible previously because we didn't have a way to know the distinguish traces …
=> Add Labels from a path as oc-collector attributes

linkerd/app/core/src/admin/mod.rs
Relates to https://github.com/linkerd/linkerd2/issues/3984
Add a `/live` endpoint to the admin server which always returns a 200 success.  This can be used for liveness checking.
=> Add liveness endpoint to admin server

.github/workflows/docker.yml, Dockerfile, Makefile, update-rust-version.sh
Our docker builds do not permit caching of dependencies or intermediate
build artifacts. However, Docker's new (experimental) buildkit features
add this functionality. I've been using this configuration locally for
some time, and it seems generaly useful enough to promote (especially
since this Dockerfile is only intended for development).
This change also untroduces the `PROXY_FEATURES` build-arg so that the
Dockerfile can be used to support profiling builds.
Furthermore, the `update-rust-versions.sh` script has been updated to
check versions and be more permissive about how it replaces versions in
the Dockerfile.
--
@linkerd/proxy-maintainers please verify that you're able to use this workflow, as documented in the Dockerfile.
=> docker: Use buildkit for caching

Makefile
If we run make in a cross-compile environment where the strip binary we
want to use is something else than strip, it is useful to have a STRIP
variable in the Makefile. If STRIP is not set, the default value is the
common strip.
=> Makefile: Use STRIP variable with strip as default

.github/actions/package/Dockerfile, .github/actions/package/expected-checksec.json, .github/actions/package/validate-checksec.sh, .github/workflows/release.yml, Makefile, checksec.sh, update-rust-version.sh
A recent [Twitter thread][mudge] suggested that tools like
[`checksec`][checksec] be used to validate release binaries. Checksec
reports whether modern security features like stack canaries are
employed. Proxy builds appear to do pretty well out-of-the-box.
This change introduces a checksec.sh wrapper that is used by the
Makefile during packaging. A new _package_ github action is introduced
to provide `checksec` and `jq` dependencies at runtime. (Note: the
version of checksec provided by debian does not include JSON output, so
it is instead fetched directly from GitHub).
During an automated release, the generated checksec is compared to an
expected set of values and, if a regression is detected, the release
will fail.
[mudge]: https://twitter.com/dotMudge/status/1249359519471341569 …
=> Add checksec to the release process

Cargo.lock, linkerd/app/core/src/accept_error.rs, linkerd/app/core/src/admin/mod.rs, linkerd/app/core/src/config.rs, linkerd/app/core/src/proxy/server.rs, linkerd/app/core/src/serve.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/env.rs, linkerd/proxy/core/Cargo.toml, linkerd/proxy/core/src/listen.rs, linkerd/proxy/detect/src/lib.rs, linkerd/proxy/tap/src/accept.rs, linkerd/proxy/tcp/src/forward.rs, linkerd/proxy/transport/Cargo.toml, linkerd/proxy/transport/src/tls/accept.rs, linkerd/proxy/transport/tests/tls_accept.rs
This PR changes the Accept trait to return a Future<Item = Future<()>>. The inner future is the one driving the connection while the outer future represents work such as protocol detect. This allows us to time out the outer future independently of the inner one. Additionally a timeout has been introduced to guard against serve first connections that do not run on a standard for the protocol port hanging and causing memory issues.
Fixes linkerd/linkerd2#4069
=> Time out protocol detect futures

Cargo.lock, linkerd/app/Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/core/src/lib.rs, linkerd/app/core/src/serve.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/integration/Cargo.toml, linkerd/app/integration/tests/discovery.rs, linkerd/app/integration/tests/profile_dst_overrides.rs, linkerd/app/integration/tests/profiles.rs, linkerd/app/integration/tests/shutdown.rs, linkerd/app/integration/tests/tap.rs, linkerd/app/integration/tests/telemetry.rs, linkerd/app/integration/tests/transparency.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/admin.rs, linkerd/app/src/lib.rs, linkerd/app/src/tap.rs
This branch begins a "top-down" update of the proxy to use
`std::future`. I've started by commenting out most of the stack, making
the proxy into a raw TCP forwarder/HTTP server that just always returns
`200 OK <eof>`. Then, I've updated the top-level `serve` function to use
`std::future`. This is pretty mechanical, but we _may_ want to consider
doing some refactoring here in the future.
Currently, most of the integration tests are failing, since they test
functionality that is now commented out. I've added `ignore` attributes
temporarily to disable those tests. However, since we are ignoring the
tests rather than disabling them via conditional compilation, we will
still try to build them, so this ensures we don't accidentally break any
of these tests. There is a feature flag, "nyi", that …
=> prepare to update the proxy to use std::future

.github/workflows/release.yml
During testing, we set a hardcoded release version, but this was not
undone.
This fixes the release action by restoring the tag-derived version
string.
=> Undo hardcoded release version

linkerd/http-metrics/src/retries.rs
The retryable HTTP responses that were not retries are only those with the skipped: no_budget label. Actual retries that occured fall under this metric category.
Signed-off-by: Naseem <naseem@transit.app>
=> Adjust metric description.

linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/proxy/http/src/overwrite_authority.rs
The extractor pattern is useful when we need to use additional
configuration or when we don't control the type over which we're
extracting a value (like an http::Request). But in the case of authority
overrides, we have all of the information we need on the target type.
This change replaces the ExtractAuthority strategy with a
CanOverrideAuthority trait that must be implemented by targets.
I've also modified logging to be at the debug level (request
modification seems useful to observe when debugging), and I've renamed
some variables to match the tracing output.
I think, as a follow up, I'd prefer that we call this module
`override_authority` (rather than "overwrite"), as this matches the
naming in the controller/API.
I've also moved `layer => Layer::new`, which is the newer idiom we're …
=> Replace ExtractAuthority with CanOverrideAuthority

linkerd/app/inbound/src/endpoint.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/proxy/http/src/client.rs, linkerd/proxy/http/src/overwrite_authority.rs, linkerd/proxy/http/src/settings.rs
@zaharidichev What do you think of this?
This change modifies the `HasSettings` trait to return a `Settings`
(rather than a reference). The `Settings` type is a simple type with a
few bools, so it's safe to copy freely.
This enables us to implement `HasSettings` for `http::HttpEndpoint` by
overriding the `was_absolute_from` when appropriate without having to
introduce an additional trait
=> Remove the IntoAbsForm trait

linkerd/app/outbound/src/orig_proto_upgrade.rs
OrigProtoUpgrade shouldn't have to know about authority overrides. This
change uses the `HasSettings` implementation on endpoint to hide this
detail.
=> Simplify orig_proto_upgrade

linkerd/app/core/src/svc.rs, linkerd/stack/src/fallback.rs, linkerd/stack/src/lib.rs, linkerd/stack/src/make_ready.rs, linkerd/stack/src/on_response.rs, linkerd/stack/src/oneshot.rs
This branch ports the `linkerd2-stack` crate to use Tower 0.3 and
`std::future` and tokio 0.2's timers. I've also re-enabled the
`push_*` methods for layers exported by that crate.
This change should be pretty straightforward to read, as it's fairly
mechanical in nature. I've basically just changed the code to account
for the new APIs, but the implementation should be quite similar.
=> port stack to std::future

Cargo.lock, linkerd/app/core/src/svc.rs, linkerd/buffer/Cargo.toml, linkerd/buffer/src/dispatch.rs, linkerd/buffer/src/layer.rs, linkerd/buffer/src/lib.rs, linkerd/buffer/src/service.rs
This branch ports the `linkerd2-buffer` to use `std::future` and `tokio`
0.2. I've also re-enabled the `push_spawn_buffer` fns in `svc`.
Like #486 and #487, this change should be pretty straightforward to
read, as it's fairly mechanical in nature. I've basically just changed
the code to account for the new APIs. This one might be a _little_ more
interesting, since it shows off some of the API differences in
`tokio::sync` in 0.2 as well.
=> port buffer to std::future

Cargo.lock, linkerd/app/core/src/svc.rs, linkerd/concurrency-limit/Cargo.toml, linkerd/concurrency-limit/src/lib.rs
This branch updates the `concurrency-limit` middleware to std::future.
The new implementation uses the new owned semaphore permit API added in
Tokio 0.2.19 (tokio-rs/tokio#2421). Similarly to #490, the old
implementation could not be directly translated due to `tokio::sync`'s
`Semaphore` losing its `poll`-based API in 0.2.
=> update concurrency-limit to std::future

linkerd/app/core/src/errors.rs, linkerd/error-respond/src/lib.rs
This branch modifies the `Respond` trait by allowing it to modify the response's body. In errors responder, we wrap the body of the response to allow it to set the GRPC status on trailers in case we get errors when calling `poll_data` on the body. 
Fixes https://github.com/linkerd/linkerd2/issues/4262
=> Handle GRPC body errors

Cargo.lock, linkerd/app/core/src/svc.rs, linkerd/http-box/Cargo.toml, linkerd/http-box/src/request.rs, linkerd/http-box/src/response.rs
This does **not** update the payload module to `std::future`, since we
are still on the futures 0.1 version of Hyper. It only updates the
`tower-service` impls.
This will be necessary to bring back the HTTP clients.
=> update http-box to tower 0.3

linkerd/app/core/src/errors.rs, linkerd/buffer/src/error.rs, linkerd/lock/src/error.rs
In #493, we opted to handle all hyper errors as `UNAVAILABLE` for gRPC
messages.
This change modifies the signature of `http_status` & `set_grpc_status`
so that we can unwrap arbitrary inner errors via `Error::source`. This
reduces some unnecessary special-casing and allows us to more-narrowly
target IO errors
Special thanks to @LucioFranco for guiding me in the right direction on this.
=> Set a grpc-status of UNAVAILABLE only on io errors

linkerd/app/inbound/src/lib.rs
The inbound endpoint stack includes an unneeded buffer/idle/failfast
stack. This stack is buffered where it is cached, so these layers are
unnecessary.
=> inbound: Remove unnecessary buffer

Makefile
Make it possible to to build the linkerd2-proxy for other architectures the than the host architecture with make. This by updating the makefile to be aware of environment variables specifying the target architecture.
=> Adapting makefile for multiarch builds

.github/workflows/release.yml
6166d328 update the Makefile to output binaries in architecture-specific
target directories, but the release action was not updated to reflect
this change.
=> release: Use arch-specific paths

linkerd/concurrency-limit/src/lib.rs
This fixes a bug where the std::future version of
`linkerd-concurrency-limit` fails to drive the wrapped service to
readiness before calling it. Now, the inner service is polled once a
semaphore permit has been acquired.
Shoutout to @LucioFranco for noticing this!
=> fix concurrency-limit not polling inner service

linkerd/buffer/src/dispatch.rs, linkerd/buffer/src/error.rs, linkerd/buffer/src/lib.rs, linkerd/buffer/src/service.rs
The buffer uses a watch to advertise readiness to consumers. This is
intended to:
1. Prevent the out service from becoming ready before the inner service
has initialized.
2. Surface errors to outer services' `poll_ready`.
It, however, currently advertises when the inner service moves into
pending, preventing requests from being admitted to the buffer, and then
basically making consumers race to enter the buffer.
This change also relaxes its use of the ready watch channel, especially
to signal that the task should complete. Instead, the dispatch task
completes as soon as all requests have been processed.
=> Buffer requests while the service is pending

Cargo.lock, Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/core/src/errors.rs, linkerd/errno/Cargo.toml, linkerd/errno/src/lib.rs, linkerd/proxy/transport/Cargo.toml, linkerd/proxy/transport/src/metrics/mod.rs
This change modifies HTTP error-labeling to detect I/O errors
and label them explicitly. Previously all I/O errors were reported as
`unexpected`.
Fixes linkerd/linkerd2#4364
=> Add an `i/o` error label to http metrics

Cargo.lock, linkerd/stack/metrics/Cargo.toml, linkerd/stack/metrics/src/service.rs
I had forgotten that `linkerd2-stack-metrics` is actually kind of load
bearing: the `TrackServiceLayer` is necessary for powering cache
eviction as well as being used for debugging. It turns out that we need
this to create stacks that work.
This branch ports `linkerd2-stack-metrics` to std::future. This change
was pretty trivial; I just updated to use the new `tower::Service`
trait. I also pruned a bunch of dependencies that this crate wasn't
actually using from the Cargo.toml.
=> port stack-metrics to std::future

Cargo.lock, Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/core/src/errors.rs, linkerd/errno/Cargo.toml, linkerd/errno/src/lib.rs, linkerd/proxy/transport/Cargo.toml, linkerd/proxy/transport/src/metrics/mod.rs
This change modifies HTTP error-labeling to detect I/O errors
and label them explicitly. Previously all I/O errors were reported as
`unexpected`.
Additionally, an `errno` label is included when possible.
Fixes linkerd/linkerd2#4364
=> Add an `i/o` error label to http metrics (#512)

Cargo.lock, Cargo.toml, linkerd/admit/Cargo.toml, linkerd/admit/src/lib.rs, linkerd/app/inbound/Cargo.toml, linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/require_identity_for_ports.rs, linkerd/app/src/env.rs
Fairly simple change to bring in the Admit middleware
=> Port admit to std::future

linkerd/app/inbound/src/endpoint.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/normalize_uri.rs
It turns out that most of the tests that can be re-enabled as a result
of #516 expect URIs to be normalized.
Therefore, I ported the `normalize_uri` layer to std::future. This is
a pretty mechanical translation.
=> port normalize_uri to std::future

Cargo.lock, linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/integration/src/client.rs, linkerd/app/integration/tests/transparency.rs, linkerd/buffer/src/service.rs, linkerd/cache/src/layer.rs, linkerd/cache/src/lib.rs, linkerd/proxy/http/Cargo.toml, linkerd/proxy/http/src/client.rs, linkerd/proxy/http/src/glue.rs, linkerd/proxy/http/src/h2.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/normalize_uri.rs, linkerd/proxy/http/src/timeout.rs, linkerd/proxy/http/src/upgrade.rs, linkerd/proxy/transport/Cargo.toml
Now that the HTTP connect- and accept-side machinery has all been
updated to use `std::future`, we can start turning the proxy back
into...a proxy. This branch does so on the inbound side. Much of the
actual functionality (approximately everything not directly required to
actually proxy requests) is still disabled, as a lot of the code still
needs to be updated.
I had to make a few additional changes in order to get the proxy to
compile, primarily to deal with trait bounds on `Service` impls that
were no longer satisfied as a result of changes made to update other
parts of the codebase. I also disabled two more of the  `transparency`
integration tests, both of which tested whether the proxy stripped
connection-level headers from proxied requests. Previously, these were
passing …
=> turn inbound proxy back into a proxy

Cargo.lock, linkerd/error/Cargo.toml, linkerd/error/src/recover.rs, linkerd/proxy/core/Cargo.toml, linkerd/proxy/core/src/resolve.rs, linkerd/proxy/resolve/Cargo.toml, linkerd/proxy/resolve/src/map_endpoint.rs, linkerd/proxy/resolve/src/recover.rs, linkerd/reconnect/src/lib.rs, linkerd/reconnect/src/service.rs
This branch updates the `linkerd2-proxy-resolve` crate to `std::future`.
It also updates the `recover` module in `linkerd2-proxy-error`, which is
a dependency of `resolve`, and `linkerd2-reconnect`, which depends on
`recover` and therefore didn't compile after it was updated.
The `linkerd2-proxy-resolve::recover` code currently only works when the
underlying resolver's resolution and future types are both `Unpin`, and
the backoff type is also `Unpin`. This is because this logic relies a
bit on being able to move these values in and out of `Option`s. I tried
to implement this without requiring these values to be `Unpin`, but the
implementation of the `ResolveFuture`, which drives the resolution until
it's connected and then returns it, was more or less impossible to
translate in its …
=> port `linkerd2-proxy-error::recover` and `linkerd2-proxy-resolve` to std::future

Cargo.lock, linkerd/app/core/src/dns.rs, linkerd/app/integration/src/proxy.rs, linkerd/app/src/lib.rs, linkerd/dns/Cargo.toml, linkerd/dns/src/lib.rs, linkerd/dns/src/refine.rs, linkerd2-proxy/src/main.rs
This branch updates the `linkerd2-proxy-dns` crate to `std::future` and
the latest release of `trust-dns-resolver`, and updates the uses of DNS
in `linkerd2-proxy-app` to track the changes. 
For the most part, this change is pretty straightforward. However, the
`std::future` version of `trust-dns-resolver` changed how the background
task driving DNS resolution is executed. Previously, it was returned by
the `AsyncResolver` constructor, but now, the constructors are `async
fn`s that implicitly spawn the background task on the runtime that
executes them.
Therefore, I had to change how the DNS resolver is constructed. I opted
to build the admin runtime early and have it block on the DNS resolver
construction, and then pass that runtime to the admin thread when it is
spawned. This seemed …
=> update dns to std::future

Cargo.lock, linkerd/exp-backoff/Cargo.toml, linkerd/exp-backoff/src/lib.rs
This is pretty straightforward, but it was necessary to bring
back the destination service client.
=> update `linkerd2-exp-backoff` to std::future

Cargo.lock, linkerd/app/Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/core/src/classify.rs, linkerd/app/core/src/control.rs, linkerd/app/core/src/errors.rs, linkerd/app/src/dst/mod.rs, linkerd/app/src/dst/resolve.rs, linkerd/app/src/env.rs, linkerd/app/src/lib.rs, linkerd/exp-backoff/Cargo.toml, linkerd/exp-backoff/src/lib.rs, linkerd/proxy/http/Cargo.toml
This branch updates the proxy's control-plane client to use
`std::future` and Tonic. This should unblock updating the outbound proxy
(as it needs service discovery) and bringing back service profiles.
=> update controller client to std::future

Cargo.lock, linkerd/proxy/discover/Cargo.toml, linkerd/proxy/discover/src/buffer.rs, linkerd/proxy/discover/src/from_resolve.rs, linkerd/proxy/discover/src/lib.rs, linkerd/proxy/discover/src/make_endpoint.rs
This branch updates the `linkerd2-proxy-discover` crate to use
`std::future` and Tower 0.3.
Overall, this is a fairly mechanical change. The main upstream API
difference is that `tower-discover` is now a trait alias for `Stream`,
rather than a trait that user code can directly implement.
=> update linkerd2-proxy-discover to std::future

linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/prevent_loop.rs, linkerd/app/outbound/src/lib.rs
e77fe181 introduced loop detection to the outbound HTTP proxy. This
change extends this behavior to the inbound HTTP proxy and the TCP
proxy for both inbound and outbound. This helps ensure malicious
requests can't consume proxy resources.
=> Add loop detection to inbound & TCP forwarding

Cargo.lock, linkerd/app/Cargo.toml, linkerd/app/core/src/proxy/server.rs, linkerd/app/integration/tests/discovery.rs, linkerd/app/integration/tests/transparency.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/dst/resolve.rs, linkerd/app/src/lib.rs, linkerd/proxy/api-resolve/Cargo.toml, linkerd/proxy/api-resolve/src/resolve.rs, linkerd/proxy/resolve/src/lib.rs, linkerd/proxy/resolve/src/make_unpin.rs, linkerd/proxy/resolve/src/recover.rs, linkerd/request-filter/Cargo.toml, linkerd/request-filter/src/lib.rs
This branch turns the outbound side of the proxy back into a real proxy,
similarly to what #516 did for the inbound side. Getting outbound to
work again was somewhat more complex, since the outbound side also
requires the load balancer (and, therefore, discovery). In order to get
this all working, it was also necessary to update the
`linkerd2-request-filter` crate (which was quite trivial), as it's
necessary for the resolver to work, and to make some changes in the
resolver so that all trait bounds were satisfied.
In addition, now that both inbound and outbound work, we're now able
to re-enable a large amount of the integration tests in the 
`transparency` and `discovery` modules. Some of these tests are still
disabled, as they either depend on service profiles, HTTP upgrades and …
=> turn outbound back into a proxy

linkerd/app/integration/src/proxy.rs, linkerd/app/integration/tests/transparency.rs, linkerd/app/outbound/src/lib.rs
This change adds (flakey) tests for loop detection. The tests are flakey
because they require static ports to work properly. (We cannot configure
the original dst port to be the same as the interface port if the
interface port is not known).
=> Test loop detection

linkerd/app/core/src/svc.rs, linkerd/stack/src/fallback.rs
This change modifies the fallback layer to inspect error sources
recursively to determine if the given error type is satisfied.
A stack-helper is also added for this case.
=> fallback: Unwrap errors recursively

linkerd/app/core/src/proxy/server.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs
Turns out these _worked_ but i never actually put them back. Whoopsie!
This is necessary for the only integration test that really exercises
reconnects, which relies on these metrics to determine if a connection
exists.
Depends on #526 and will be rebased onto `master-tokio-0.2` when
that branch merges.
=> put back transport metrics

Cargo.lock, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/Cargo.toml, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/orig_proto_upgrade.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/orig_proto.rs
This branch updates the `l5d-orig-proto` upgrade/downgrade code to use
`std::future`, and puts it back in the stack.
It turns out that the integration tests that exercise this don't
actually assert that an upgrade is _performed_ when the hint is sent,
just that sending the hint doesn't _break_ proxy-to-proxy traffic (which
is a bummer, but it's hard to assert that in an integration test). So,
those tests were passing before this branch.
However, I validated that the upgrade is performed by checking the logs:
```
[     0.73767491s] DEBUG proxy{test=main:proxy}:outbound:accept{peer.addr=127.0.0.1:60420}:source{target.addr=127.0.0.1:34913}:logical{addr=transparency.test.svc.cluster.local:80}:balance{addr=transparency.test.svc.cluster.local:80}:endpoint{peer.addr=127.0.0.1:34885}: …
```
=> update protocol upgrades to std::future

Cargo.lock, linkerd/app/core/src/proxy/server.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/integration/src/client.rs, linkerd/app/integration/tests/discovery.rs, linkerd/app/integration/tests/transparency.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/lib.rs, linkerd/reconnect/Cargo.toml, linkerd/reconnect/src/layer.rs, linkerd/reconnect/src/lib.rs, linkerd/reconnect/src/service.rs
This branch updates the `reconnect` middleware to `std::future`.
Updating reconnect was pretty straightforward and mechanical, so it
should be easy to review. 
Most of the complexity was actually in getting the test
`retry_reconnect_errors` which exercises this functionality to pass: the
test uses transport metrics to determine when the proxy has actually
accepted a connection from the test client, so that it can advance to
the next state; it was necessary to re-enable transport metrics for this
to work (see PR #530).
Additionally, there was a subtle change in the test-support client's
behavior that needed to be resolved as well: the test relied on
`Client::request_async` *eagerly* causing the test client to connect to
the proxy when called, rather than when the returned future is polled. …
=> update reconnect to std::future

linkerd/app/inbound/src/lib.rs, linkerd/app/integration/tests/discovery.rs, linkerd/app/outbound/src/lib.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/strip_header.rs
This branch updates `proxy::app::strip_header` module to `std::future`. It is a fairly straightforward change!
=> Update strip_header to std::future

Cargo.lock, Cargo.toml, linkerd/app/Cargo.toml, linkerd/app/gateway/Cargo.toml, linkerd/app/gateway/src/config.rs, linkerd/app/gateway/src/gateway.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/gateway/src/make.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/integration/tests/transparency.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/env.rs, linkerd/app/src/lib.rs, linkerd/dns/src/refine.rs, linkerd/proxy/http/src/lib.rs, linkerd/timeout/src/failfast.rs
When the proxy receives inbound requests without an original dst address
(or with a original dst address matching the inbound listener), the
proxy currently fails these requests.
This change modifies the proxy to attempt to accept these requests and
forward them back through the outbound router.
The gateway requires that all requests are received over an mTLS-secured
connection. It also refines the destination through DNS to determine the
canonical-form name as well as an outbound original dst IP. All
gatewayed destinations must have a suffix as set by the
`LINKERD2_PROXY_GATEWAY_SUFFIXES` environment variable.
All requests that do not meet these criteria are failed with a `403
Forbidden` status.
=> Introduce a gateway between inbound and outbound

linkerd/app/gateway/src/config.rs, linkerd/app/gateway/src/gateway.rs, linkerd/app/gateway/src/make.rs, linkerd/app/src/lib.rs
When the gateway forwards requests, it now adds a [`Forwarded`][mdn] header
including the source identity, the local identity, and the destination
authority.
---
I've tested this manually. I'll follow up with tests as we port this to tokio-0.2 (where the test infra is much friendlier).
Also, the gateway, in general, seems to incur a pretty heavy compile-time hit... we'll have to revisit that post-release as well.
[mdn]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded
=> gateway: Add a Forwarded header

linkerd/app/core/src/errors.rs, linkerd/app/gateway/src/gateway.rs
This ensures that error metrics are recorded and that logging is emitted
uniformly. This also ensures that gRPC requests don't get HTTP error
responses.
=> gateway: Return errors instead of responses

Cargo.lock, linkerd/app/core/src/lib.rs, linkerd/app/core/src/retry.rs, linkerd/app/integration/tests/profiles.rs, linkerd/app/outbound/src/lib.rs, linkerd/retry/Cargo.toml, linkerd/retry/src/lib.rs
This branch updates the proxy's retry implementation to work with
`std::future`. Retries in service profiles now work correctly!
Again, nothing too out of the ordinary to see here. 
Depends on #537 
=> update retries to std::future

linkerd/app/core/src/lib.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/metrics.rs
This branch updates the proxy handle time metric and puts the layer that
records it back in the stack.
Depends on #541 (for `insert`).
=> update handle_time to std::future

linkerd/app/core/src/errors.rs, linkerd/app/gateway/src/gateway.rs, linkerd/app/inbound/src/lib.rs
When the inbound caches gateway services, it eagerly obtains an
outbound service to cache. If the outbound service employs a traffic
split, this inbound service is pinned to a specific leaf, and requests
will never be routed to the other leaf.
This change moves the gateway fallback to be outside all of the inbound
caches, so that outbound splits work as intended.
=> inbound: Do not cache gateway services

Cargo.lock, linkerd/app/integration/tests/identity.rs, linkerd/app/src/identity.rs, linkerd/app/src/lib.rs, linkerd/proxy/identity/Cargo.toml, linkerd/proxy/identity/src/certify.rs
This branch updates the identity service client to use `std::future` and
async/await. Since the identity refresh daemon code ended up being
somewhat tricky to make work with stack pinning, I opted to just replace
it with a new async/await implementation instead.
I've also re-enabled all the identity integration tests.
=> update identity service client to std::future

linkerd/app/core/src/proxy/server.rs, linkerd/app/integration/src/client.rs, linkerd/app/integration/src/server.rs, linkerd/proxy/http/src/client.rs, linkerd/proxy/http/src/h2.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/trace.rs, linkerd/proxy/tap/src/accept.rs
Previously, in the `futures` 0.1 version of the proxy, we provided
`hyper` with a custom executor to propagate `tracing` spans to tasks
spawned by `hyper`. In the process of updating the proxy to
`std::future`, this was removed, meaning that any tasks spawned by hyper
are missing their spans. This makes events recorded by `h2` and so on
hard to debug, especially when many connections are open.
This branch fixes this by adding an implementation of `hyper::Executor`
that propagates the current span when spawning a task.
=> propagate spans to tasks spawned by Hyper

Cargo.lock, linkerd/app/outbound/Cargo.toml, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/require_identity_on_endpoint.rs
This branch updates the `require_identity_on_endpoint` module in
`linkerd2-app-outbound` to `std::future`. 
The tests for this functionality
(`require_id_header::http2::disco_client_connects_to_tls_server` and
`require_id_header::http1::disco_client_connects_to_tls_server`) now
pass; however, they had already been re-enabled (they are tagged as
flaky).
=>  update require_identity_on_endpoint to std::future

linkerd/app/integration/tests/discovery.rs, linkerd/buffer/src/dispatch.rs, linkerd/buffer/src/lib.rs
When `linkerd2-buffer` was updated to `std::future` in PR #505, the
behaviour of the buffer was changed subtly. The previous implementation
of the buffer's `Dispatch` task was _poll-based_; it implemented its
logic in an implementation of `Future::poll` with the following
behavior:
1. Call `poll_ready` on the underlying service, returning `NotReady` if
it is not ready.
2. Broadcast readiness to senders.
3. Call `poll_next` on the channel of requests. If a request is
received, dispatch it to the service. If no request is ready, return
`NotReady` (yield).
Since this was an implementation of the `poll` function, if we yield due
to the request channel being empty, when we are woken again by the next
request, we resume _at the beginning of the `poll` function_.
The new implementation, however, …
=> buffer: drive inner service to readiness when receiving a request

Cargo.lock, linkerd/app/inbound/src/lib.rs, linkerd/app/integration/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/error-metrics/Cargo.toml, linkerd/error-metrics/src/service.rs, linkerd2-proxy/src/main.rs
Looks like the `linkerd2-error-metrics` crate was never updated to
`std::future`. This branch takes care of that and adds back the HTTP
error metrics layers.
This should be a pretty trivial review.
=> update linkerd2-error-metrics to std::future

.github/CODEOWNERS
This CODEOWNERS change will ensure that proxy-maintainers are requested on all PRs.
=> Add a CODEOWNERS

linkerd/app/core/src/proxy/server.rs, linkerd/app/integration/tests/shutdown.rs
Although the `Drain` type which powers the proxy's graceful shutdown
machinery was updated in #482, we were not actually triggering graceful
shutdowns. This is because the Hyper `ConnectionFuture` was wrapped in a
compatibility adapter which did not allow access to the inner future so
that we could call the `graceful_shutdown` method on it. When we updated
to the `std::future` version of Hyper, the graceful shutdown code was
not re-enabled.
This branch puts back the call to `ConnectionFuture::graceful_shutdown`.
It also re-enables the shutdown integration tests, which pass now.
=> make shutdowns less graceless

Cargo.lock, linkerd/app/core/src/admin/mod.rs, linkerd/app/core/src/lib.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/integration/Cargo.toml, linkerd/app/outbound/src/lib.rs, linkerd/buffer/Cargo.toml, linkerd/cache/Cargo.toml, linkerd/dns/Cargo.toml, linkerd/proxy/api-resolve/src/lib.rs, linkerd/proxy/discover/Cargo.toml, linkerd/proxy/http/Cargo.toml, linkerd/proxy/tap/Cargo.toml, linkerd/proxy/transport/Cargo.toml, linkerd/proxy/transport/src/lib.rs, linkerd/proxy/transport/tests/tls_accept.rs, linkerd/service-profiles/Cargo.toml, linkerd/stack/tracing/Cargo.toml, linkerd/trace-context/src/lib.rs
This PR removes a few remaining compiler warnings from
`master-tokio-0.2` and re-adds `deny` attributes for warnings. Also,
I've updated all crates to consistently use `tracing-futures` v0.2
(previously, some crates were on 0.2 while others were still on 0.1).
=> remove & deny warnings; cleanup

linkerd/app/core/Cargo.toml, linkerd/app/core/src/trace.rs, linkerd/app/integration/src/lib.rs
JSON logs can be easily parsed in logging sinks such as Elasticsearch. 
resolves https://github.com/linkerd/linkerd2/issues/2491
cc @hawkw 
Please bare with me as this is my first PR in Rust, unless you count a message change. :)
Could you please break down the anatomy of the following line:
https://github.com/linkerd/linkerd2-proxy/blob/610309ebc240494426f9169000c46da9d5fe9647/linkerd/app/core/src/trace.rs#L12
=> feat: add json log format as an option

Cargo.lock, Cargo.toml, linkerd/app/Cargo.toml, linkerd/app/integration/Cargo.toml, linkerd/dns/name/Cargo.toml
Now that we're on tokio-0.2, we can upgrade tokio-rustls & webpki.
I've moved an updated webpki fork into the linkerd organization.
=> Upgrade tokio-rustls & webpki

Makefile
Add recipe that finds all files in the repository with the MIME type `text/x-shellscript` and runs shellcheck on them.
Signed-off-by: Joakim Roubert <joakim.roubert@axis.com>
=> Makefile: Add shellcheck recipe

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/integration/Cargo.toml, linkerd/proxy/api-resolve/Cargo.toml, linkerd/proxy/identity/Cargo.toml, linkerd/proxy/tap/Cargo.toml, linkerd/service-profiles/Cargo.toml
Tracks the latest master's tonic upgrade. We'll pin a tagged version on
release.
=> Update proxy-api dependencies

linkerd/app/integration/src/client.rs, linkerd/app/integration/src/controller.rs, linkerd/app/integration/src/lib.rs, linkerd/app/integration/src/proxy.rs, linkerd/app/integration/src/server.rs, linkerd/app/integration/tests/discovery.rs, linkerd/app/integration/tests/identity.rs, linkerd/app/integration/tests/profile_dst_overrides.rs, linkerd/app/integration/tests/profiles.rs, linkerd/app/integration/tests/shutdown.rs, linkerd/app/integration/tests/tap.rs, linkerd/app/integration/tests/telemetry.rs, linkerd/app/integration/tests/transparency.rs
Currently, there are a couple of issues that prevent traces emitted by
the proxy's integration tests from being reported correctly. Many of our
tests begin with:
```rust
let _ = trace_init();
```
This doesn't _actually_ do what we want, for two reasons:
* `trace_init` doesn't actually set a trace subscriber as the default,
it just _constructs_ one,
* `let _` drops the value _immediately_.
So, this code is constructing a subscriber and then immediately dropping
it, which does nothing.
In practice, we mostly don't notice this, since the test support
servers, clients, and proxy run in separate threads with their _own_
trace subscribers, which are set up correctly, and very few of the tests
themselves actually emit traces. So even though this does the wrong
thing, everything basically works. …
=> integration: fix missing traces

linkerd/app/outbound/src/lib.rs, linkerd/app/src/lib.rs
This change follows on the refactor in d7b86b01 by splitting the
outbound HTTP endpoint stack into its own constructor in order to
modularize the proxy stacks. The response body is boxed in order to hide
the stack's details (with regard to metrics, tracing, etc).
There is no functional change.
=> outbound: Split HTTP endpoint builder

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/core/src/proxy/server.rs, linkerd/io/src/lib.rs, linkerd/io/src/peek.rs, linkerd/proxy/detect/Cargo.toml, linkerd/proxy/detect/src/lib.rs
The protocol detection middleware is pretty verbose, including a manual
future implementation that manages a complex set of state types.
This can all be simplified with async/await (at the cost of ~2 boxes per connection).
=> Simplify protocol detection with async/await

linkerd/app/outbound/src/lib.rs
It looks like this error was commented out during the 0.2 update, when
the code that emitted it was broken. It was uncommented in the
`is_discovery_rejected` predicate, but not in the `From` impl for
`DiscoveryError`. This branch fixes that.
I am not sure if anything load-bearing depends on this conversion, but
it should at least fix potentially incorrect logs.
=> fix InvalidProfileAddr not converting into DiscoveryRejected

Dockerfile
This change modifies the development dockerfile to wrap build commands
with `/usr/bin/time -v` so that we get diagnostic information (like the
RSS of the build process).
=> Print build diagnostics in docker

Cargo.lock, Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/integration/Cargo.toml, linkerd/app/integration/src/controller.rs, linkerd/app/integration/src/identity.rs, linkerd/app/integration/src/lib.rs, linkerd/app/integration/src/proxy.rs, linkerd/app/integration/src/tap.rs, linkerd/app/integration/tests/discovery.rs, linkerd/app/integration/tests/identity.rs, linkerd/app/integration/tests/profile_dst_overrides.rs, linkerd/app/integration/tests/profiles.rs, linkerd/app/integration/tests/shutdown.rs, linkerd/app/integration/tests/tap.rs, linkerd/app/integration/tests/telemetry.rs, linkerd/app/integration/tests/transparency.rs, linkerd/app/profiling/Cargo.toml, linkerd/app/profiling/src/bin/profile.rs
This branch updates the test support mock control plane components in
`linkerd2-app-integration` to use `std::future`, Tonic, and Tokio 0.2.
Rather than spawning a separate thread for each control plane componwnr
as we did previously, they are now spawned as tasks on the main test
thread's runtime. As discussed in #580, this _may_ make the tests
slightly less flaky and/or slightly faster on CI.
In order to make this compile I had to increase the type length and
recursion limits for all the test crates. I have no idea why this branch
made this necessary. My guess is that the fact that we have ~12MB type
names now is at least part of the cause of linkerd/linkerd2#4676.
Depends on #580
Closes linkerd/linkerd2#3963
=> update test controllers to std::future/Tonic; remove threads

linkerd/app/core/src/svc.rs, linkerd/buffer/src/dispatch.rs, linkerd/buffer/src/layer.rs, linkerd/buffer/src/lib.rs, linkerd/buffer/src/service.rs
The buffer middleware is parameterized on the inner service's repsonse
future, which "leaks" the inner service's type to the outer components
(which slows down compilations).
This changes the signature to instead be parameterized by the response
type, boxing the inner service's response future to avoid exposing its
type signature.
Relates to linkerd/linkerd2#4676
=> buffer: Box the inner service's reponse future

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/integration/Cargo.toml, linkerd/http-metrics/Cargo.toml, linkerd/http-metrics/src/requests/layer.rs, linkerd/http-metrics/src/requests/mod.rs, linkerd/http-metrics/src/requests/report.rs, linkerd/http-metrics/src/retries.rs
Tracing and Tokio both expose a feature flagged optional dependency on
the `parking_lot` crate's `Mutex` and `RwLock` implementations rather
than `std`'s. Enabling this dependency causes these crates to use
`parking_lot` internally with no externally visible API change.
In microbenchmarks of Tokio's synchronization primitives, we've observed
better performance with `parking_lot` vs `std`, and tend to recommend it
in high-performance applications where the cost of another dependency is
acceptable.
This branch enables `tokio` and `tracing`'s `parking_lot` features. I
also removed a bonus dependency on a vintage Tokio version that we must
have missed during the 0.2 update, as it was pulling an incompatible
`parking_lot` version. 
There appears to be some performance improvement under load …
=> enable `parking_lot` locks in dependencies

Cargo.lock, linkerd/app/core/src/control.rs, linkerd/app/core/src/errors.rs, linkerd/app/core/src/svc.rs, linkerd/opencensus/src/lib.rs, linkerd/proxy/http/src/canonicalize.rs, linkerd/proxy/http/src/client.rs, linkerd/proxy/http/src/h2.rs, linkerd/proxy/resolve/src/recover.rs, linkerd/proxy/tap/src/daemon.rs, linkerd/proxy/tap/src/service.rs, linkerd/proxy/tcp/src/forward.rs, linkerd/proxy/transport/src/tls/accept.rs, linkerd/proxy/transport/src/tls/client.rs, linkerd/request-filter/src/lib.rs, linkerd/retry/src/lib.rs, linkerd/router/src/lib.rs, linkerd/service-profiles/src/client.rs, linkerd/stack/src/fallback.rs, linkerd/stack/src/make_ready.rs, linkerd/timeout/src/failfast.rs, linkerd/timeout/src/lib.rs
The `#[project]` attribute is now deprecated.
See https://github.com/taiki-e/pin-project/releases/tag/v0.4.21
=> remove deprecated pin-project attribute

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/core/src/trace.rs
This branch updates the `tracing-subscriber` crate to version 0.2.8,
which adds support for serializing the complete span context with the
JSON formatter, the way the text log subscriber does.
Also, it includes @Pothulapati's change to print thread IDs, which will
be useful for debugging the multithreaded runtime.
=> trace: update tracing-subscriber to 0.2.8; add spans to JSON

Cargo.lock, Cargo.toml, hyper-balance/Cargo.toml, linkerd/app/Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/integration/Cargo.toml, linkerd/http-metrics/Cargo.toml, linkerd/metrics/Cargo.toml, linkerd/proxy/http/Cargo.toml, linkerd/proxy/tap/Cargo.toml
The versions we were waiting for (`hyper` 0.13.7 and `h2` 0.2.6) have
now been released, so we can remove the patches and Git dependencies :D
=> remove git deps on hyper and h2

Cargo.lock, linkerd/app/core/src/metric_labels.rs, linkerd/app/core/src/proxy/server.rs, linkerd/app/core/src/transport/labels.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/admin.rs, linkerd/app/src/env.rs, linkerd/app/src/identity.rs, linkerd/app/src/tap.rs, linkerd/proxy/detect/src/lib.rs, linkerd/proxy/tap/src/accept.rs, linkerd/proxy/tap/src/lib.rs, linkerd/proxy/transport/Cargo.toml, linkerd/proxy/transport/src/tls/accept.rs, linkerd/proxy/transport/src/tls/mod.rs, linkerd/proxy/transport/tests/tls_accept.rs
The `tls::accept` module can be simplified by moving to async/await.
This presents a few opportunities for improvement:
1. The recently-introduced `Detect` trait is used. This sets up further
changes to the accept logic, decoupling protocol detection from the
`Accept` stack/type.
2. The `tls::ReasonForNoIdentity` type has been removed, as it provided
no value; and the `tls::ReasonForNoPeerName` has been updated with
additional states.
3. We now avoid having to use `PrefixedIo` in most cases by using
`TcpStream::peek` with a smaller buffer. The prior behavior is
retained as a fallback in case peek doesn't return enough data.
This comes at the cost of ~2 additional Boxes per connection; but these
will probably be shaved off in a follow-up as the detection logic
becomes more …
=> Move tls::accept to async/await

Cargo.lock, Dockerfile, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd2-proxy/Cargo.toml, linkerd2-proxy/src/main.rs, linkerd2-proxy/src/rt.rs
This branch enables feature-flagged support for using Tokio's
multithreaded runtime when the proxy is given more than two CPU cores to
run on. The proxy's understanding of the system's number of CPUs
reflects cgroups limits, so docker CPU limits are taken into
consideration. 
The multithreaded runtime offers significantly better performance under
load when multiple CPU cores are available. Here's benchmark results
from a run on my 24-thread Ryzen 3900X system, where the proxy, the load
generator, and the test server were all given 8 cores:
```
eliza on noctis in ~
:; nproc --all
24
``` 
Note that the locking in multiple metrics layers doesn't really seem
to have a big impact, as shown by the run with metrics disabled. There 
might be some improvement in high tails from further …
=> add feature-flagged support for multi-threaded Tokio runtime

linkerd2-proxy/Cargo.toml, linkerd2-proxy/src/rt.rs
We don't have any blockers to using the threaded runtime by default.
This change adds the `multicore` feature flag to the default feature
list.
It also modifies the threaded runtime initialization to use all
available cores.
The thread names have been changed from `linkerd2-proxy-worker` to just
`proxy`, which is more consistent with the `admin` thread name. This
should be unambiguous in the context of the process.
=> Add `multicore` to default features

Cargo.lock, linkerd/admit/Cargo.toml, linkerd/app/Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/gateway/Cargo.toml, linkerd/app/inbound/Cargo.toml, linkerd/app/integration/Cargo.toml, linkerd/app/outbound/Cargo.toml, linkerd/buffer/Cargo.toml, linkerd/cache/Cargo.toml, linkerd/concurrency-limit/Cargo.toml, linkerd/dns/Cargo.toml, linkerd/duplex/Cargo.toml, linkerd/http-metrics/Cargo.toml, linkerd/opencensus/Cargo.toml, linkerd/proxy/api-resolve/Cargo.toml, linkerd/proxy/discover/Cargo.toml, linkerd/proxy/http/Cargo.toml, linkerd/proxy/identity/Cargo.toml, linkerd/proxy/resolve/Cargo.toml, linkerd/proxy/tap/Cargo.toml, linkerd/proxy/transport/Cargo.toml, linkerd/reconnect/Cargo.toml, linkerd/request-filter/Cargo.toml, linkerd/retry/Cargo.toml, linkerd/service-profiles/Cargo.toml, linkerd/signal/Cargo.toml, linkerd/stack/tracing/Cargo.toml, linkerd/timeout/Cargo.toml, linkerd2-proxy/Cargo.toml
This picks up upstream changes tokio-rs/tracing#853,
tokio-rs/tracing#868, and tokio-rs/tracing#869 which improve performance
in some use cases. The overhead removed by these changes may already be
amortized enough in the proxy that it's not a problem, but it seems
worth picking up regardless.
=> trace: roll `tracing` and `tracing-subscriber` dependencies

linkerd/app/core/src/trace.rs, linkerd/app/integration/src/proxy.rs
This branch makes a couple minor tweaks to improve tracing with the
multithreaded Tokio runtime. 
It enables the option to print thread IDs when logging trace output,
which should make it somewhat clearer when events occur on different
threads.
Additionally, there's currently an issue where traces are not logged
from the proxy during integration tests. Only traces from the test
support code are logged. This is because we are using `tracing`'s scoped
thread-local dispatcher in the test proxy, so that each test can create
its own subscriber. We set the test's subscriber as the default for the
test proxy thread, but *not* as the global default for all threads.
However, when the multithreaded runtime is enabled, the default runtime
returned by `tokio::runtime::Runtime::new` is now a …
=> trace: tweak tracing & test support for the multithreaded runtime

linkerd/timeout/src/failfast.rs
Currently, the FailFast middleware is not cloneable, as it maintains
state including a timeout future.
This change modifies FailFast to implement Clone. When the module is
cloned, it reverts to the open state.
This has no impact on the current proxy, but when the stack gets cloned
(as required by an upcoming change), this will have the effect that
connections do not share failfast state. This seems better than adding a
Lock or Buffer just to accomodate this.
=> Make FailFast cloneable

Cargo.lock, linkerd/app/core/src/proxy/mod.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/proxy/http/Cargo.toml, linkerd/proxy/http/src/detect.rs, linkerd/proxy/http/src/lib.rs
In preparation for upcoming simplifications, this moves the HTTP
detection/serving logic into the linkerd2_proxy_http crate.
=> Move HTTP detection & server into linkerd2_proxy_http

linkerd/app/integration/tests/tap.rs
The `tap::grpc_headers_end` test passes locally but is flakey in CI.
=> Mark tap integration tests as flakey

Cargo.lock, linkerd/admit/Cargo.toml, linkerd/app/Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/gateway/Cargo.toml, linkerd/app/inbound/Cargo.toml, linkerd/app/integration/Cargo.toml, linkerd/app/outbound/Cargo.toml, linkerd/buffer/Cargo.toml, linkerd/cache/Cargo.toml, linkerd/concurrency-limit/Cargo.toml, linkerd/dns/Cargo.toml, linkerd/duplex/Cargo.toml, linkerd/http-metrics/Cargo.toml, linkerd/opencensus/Cargo.toml, linkerd/proxy/api-resolve/Cargo.toml, linkerd/proxy/discover/Cargo.toml, linkerd/proxy/http/Cargo.toml, linkerd/proxy/identity/Cargo.toml, linkerd/proxy/resolve/Cargo.toml, linkerd/proxy/tap/Cargo.toml, linkerd/proxy/transport/Cargo.toml, linkerd/reconnect/Cargo.toml, linkerd/request-filter/Cargo.toml, linkerd/retry/Cargo.toml, linkerd/service-profiles/Cargo.toml, linkerd/signal/Cargo.toml, linkerd/stack/tracing/Cargo.toml, linkerd/timeout/Cargo.toml, linkerd2-proxy/Cargo.toml
This branch makes the following dependency updates:
```
:; cargo update -p tracing -p tracing-core -p tracing-subscriber -p tokio-trace
Updating crates.io index
Updating git repository `https://github.com/hawkw/tokio-trace`
Updating regex v1.2.1 -> v1.3.9
Updating regex-syntax v0.6.11 -> v0.6.18
Updating thread_local v0.3.6 -> v1.0.1
Updating tracing v0.1.18 -> v0.1.19
Updating tracing-attributes v0.1.9 -> v0.1.10
Updating tracing-core v0.1.12 -> v0.1.14
Updating tracing-subscriber v0.2.10 -> v0.2.11
```
In particular, the `tracing-core` update picks up upstream change
tokio-rs/tracing#908, which fixes a bug where filtering would fail to
take the fastest fast path in many cases. This time, there's a slight,
but actually noticeable, latency reduction in the proxy benchmarks:
Signed-off-by: …
=> trace: update tracing dependencies

linkerd/proxy/api-resolve/src/resolve.rs, linkerd/proxy/core/src/lib.rs, linkerd/proxy/core/src/resolve.rs, linkerd/proxy/discover/src/from_resolve.rs, linkerd/proxy/discover/src/lib.rs, linkerd/proxy/discover/src/make_endpoint.rs, linkerd/proxy/resolve/src/make_unpin.rs, linkerd/proxy/resolve/src/map_endpoint.rs, linkerd/proxy/resolve/src/recover.rs
This PR removes the `Resolution` and replaces it with a `TryStream<Ok = Update<Endpoint>, Error>`.  This will allow us to treat any resolution as a normal `Stream` and as a consequence make it easier to  transition state machine based stream implementations to using `async-stream`. 
In addition a ResolutionStreamExt trait is defined that abstracts away the fact that we expect this stream to never end (i.e. should never return `None`)
=> Remove `Resolution` trait

Dockerfile
The proxy identity-initializing wrapper is responsible for generating a CSR and
key for the proxy upon startup. These files (located in `end-entity/`) are used
by the proxy for establishing identity.
When mocking identity, we'd like to be able to provide a pre-generated CSR and
key so that we can expect certain certificates in the Signed certificate
request.
Therefore, when building a proxy to be used with mock identity there should be a
way to remove this wrapper so that the identity files are not overwritten.
Introduce a new `SKIP_IDENTITY_WRAPPER` build-arg that when set, removes the
proxy identity-initializing script that is run at starup.
The use of it below will build a proxy with the `mock-orig-dst` feature and skip
identity generation.
```
:; docker buildx build . --build-arg …
```
=> Add build arg for skipping identity wrapper

linkerd/app/integration/src/proxy.rs, linkerd/app/integration/tests/transparency.rs, linkerd/app/src/lib.rs
Whilst implementing #601 I encountered non-determinism due to the way the integration tests don't wait for termination of the proxy thread. The changes in this PR make join_servers explicitly signal shutdown, then wait on a oneshot channel for the thread to signal draining has completed, before finally joining the thread. Simply joining the thread after signaling shutdown is insufficient as this will block the "primary" tokio runtime preventing graceful shutdown of HTTP2 connections, which rely on the clients running in the "primary" tokio runtime to be responsive.
Unfortunately the proxy appears to intentionally wait for TCP upstreams to terminate first, which requires explicit termination of the TCP client in these tests.
=> Wait for proxy thread to terminate in integration tests

linkerd/app/integration/tests/discovery.rs
The outbound dispatch timeout test was disabled. It's worth testing.
=> Re-enable outbound timeout test

Cargo.lock, linkerd/addr/src/lib.rs, linkerd/app/core/src/lib.rs, linkerd/app/core/src/svc.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/src/dst/mod.rs, linkerd/app/src/dst/permit.rs, linkerd/app/src/dst/resolve.rs, linkerd/app/src/env.rs, linkerd/request-filter/src/lib.rs, linkerd/service-profiles/Cargo.toml, linkerd/service-profiles/src/client.rs
linkerd/linkerd2#3916 added support for resolving service profiles for
IP addresses to the Destination service. This branch updates the proxy's
profiles client to look up profiles for IP addresses, rather than always
rejecting addresses that are IPs rather than DNS names.
Similarly to the Destination service-discovery client, a new
`LINKERD2_PROXY_DESTINATION_PROFILE_NETWORKS` enviroment variable is
used to configure a list of subnets to match which IPs the proxy will
look up profiles for. By default, this is empty. Since the logic for
filtering requests to a service based on IPs and DNS prefixes is now
identical between the profile and destination clients, I factored it out
into a new layer that's used for both.
Fixes linkerd/linkerd2#4877
=> profiles: perform profile resolution for IP addresses

Cargo.lock, linkerd/app/outbound/src/lib.rs, linkerd/proxy/discover/Cargo.toml, linkerd/proxy/discover/src/buffer.rs, linkerd/proxy/discover/src/lib.rs, linkerd/proxy/discover/src/make_endpoint.rs
The discovery layer handles both building a service for each discovered
endpoint, as well as a buffer that fails when the service is not polled
(i.e. because it has been leaked somehow).
This coupling doesn't match other use cases though when, for instance,
the client may not be used frequently, as is the case for
proxy-to-control-plane communication.
This change decouples these layers so that the buffering is decoupled
from endpoint-service construction.
=> Decouple discovery buffering from endpoint conversion

Cargo.lock, linkerd/app/outbound/src/lib.rs, linkerd/app/src/identity.rs, linkerd/app/src/lib.rs, linkerd/app/src/oc_collector.rs, linkerd/proxy/discover/Cargo.toml, linkerd/proxy/discover/src/buffer.rs, linkerd/proxy/discover/src/lib.rs, linkerd/proxy/discover/src/make_endpoint.rs
This incorporates https://github.com/linkerd/linkerd2-proxy/pull/631 to avoid the watchdog/buffer on control plane discovery.
=> Avoid buffering control plane discovery

Cargo.lock, linkerd/app/integration/src/controller.rs, linkerd/proxy/api-resolve/src/resolve.rs, linkerd/proxy/core/src/resolve.rs, linkerd/proxy/discover/Cargo.toml, linkerd/proxy/discover/src/from_resolve.rs, linkerd/proxy/resolve/src/map_endpoint.rs, linkerd/proxy/resolve/src/recover.rs
The recovery layer needs to maintain its own cache for reconcilation (in
addition to the other cache layers we keep). This caching can be
eliminated by introducing a resolve::Update::Reset state that implicitly
remotes all endpoints not present in the endpoint set.
=> resolve: Add a Reset state

Cargo.lock, linkerd/app/Cargo.toml, linkerd/app/integration/Cargo.toml, linkerd/app/integration/src/controller.rs, linkerd/app/integration/src/lib.rs, linkerd/app/integration/src/server.rs
The proxy's integration tests depend on the `net2` crate, which has been
deprecated and replaced by `socket2`. Since `net2` is no longer actively
maintained, `cargo audit` will warn us about it, so we should replace it
with `socket2`.
While I was making this change, I was curious why we were manually
constructing and binding these sockets at all, rather than just using
`tokio::net::TcpListener::bind`. After some archaeology, I determined
that this was added in linkerd/linkerd2#952, which added a test that
requires a delay between when a socket is _bound_ and when it starts
_listening_. `tokio::net::TcpListener::bind` (as well as the `std::net`
version) perform these operations together. Since this wasn't obvious
from the test code, I went ahead and moved the new `socket2` version of
this …
=> test: replace `net2` dependency with `socket2`

linkerd/app/core/src/dns.rs, linkerd/app/src/lib.rs, linkerd/dns/src/lib.rs, linkerd/dns/src/refine.rs
DNS resolutions are run on the admin runtime. This requires an
unnecessary layer of indirection around the resolver, including an MPSC.
Now that we allow the main runtime to use more than one thread, it's
preferable to do this discovery on the main runtime and we can simplify
the implementation.
=> dns: Run DNS resolutions on the main runtime

Cargo.lock, linkerd/app/core/src/control.rs, linkerd/app/core/src/dns.rs, linkerd/app/core/src/lib.rs, linkerd/app/src/identity.rs, linkerd/app/src/lib.rs, linkerd/app/src/oc_collector.rs, linkerd/dns/Cargo.toml, linkerd/dns/src/lib.rs, linkerd/dns/src/refine.rs, linkerd/proxy/dns-resolve/Cargo.toml, linkerd/proxy/dns-resolve/src/lib.rs, linkerd2-proxy/src/main.rs
```
commit 6057920256be10d5a55aef38424d0c224dd033b1 (HEAD -> ver/dns-srv, origin/ver/dns-srv)
Merge: b3808cc5 bff503e7
Author: Oliver Gould <ver@buoyant.io>
Date:   Tue Aug 25 01:29:59 2020 +0000
Merge branch 'ver/dns-fg' into ver/dns-srv
This merge removes some try_stream! uses to satisfy `Unpin`
requirements.
commit bff503e74b5ea4798a81fc343ea649cd84e19397 (origin/ver/dns-fg, ver/dns-fg)
Author: Oliver Gould <ver@buoyant.io>
Date:   Tue Aug 25 00:17:24 2020 +0000
dns: Run DNS resolutions on the main runtime
DNS resolutions are run on the admin runtime. This requires an
unnecessary layer of indirection around the resolver, including an MPSC.
Now that we allow the main runtime to use more than one thread, it's
preferable to do this discovery on the main runtime and we can simplify
the …
```
=> Control plane load balancing

linkerd/app/core/src/config.rs, linkerd/app/core/src/control.rs, linkerd/app/core/src/svc.rs, linkerd/app/src/dst/mod.rs, linkerd/app/src/env.rs, linkerd/app/src/identity.rs, linkerd/app/src/lib.rs, linkerd/app/src/oc_collector.rs, linkerd/http-box/src/payload.rs, linkerd/http-metrics/src/requests/mod.rs, linkerd/opencensus/src/lib.rs
We construct three control plane clients. All of the clients are
basically the same (at least with regard to the stack/configuration).
Rather than duplicate this logic throughout the code, we can unify it in
the `control` module (hiding the details of how the client is built).
This change modifies how the OpenCensus collector client is
instantiated. The `SpanExporter` no longer constructs a new client each
time it wishes to initiate a stream, opting to just clone a single
client instead.
This change also fixes reconnect logic for these clients. When the
control client balancer was introduced, the reconnect layer incorrectly
wrapped the balancer (instead of the endpoint). This has been corrected.
=> Unify control plane client construction

linkerd/dns/src/lib.rs
Unfrotunatelly due to https://github.com/bluejekyll/trust-dns/issues/1171 we can not see NoRecordsFound errors. There is not a stong type we can rely on and therefore we need to read the actual proto message to determine that we have gotten a negative resolution and return an empty list of IPs
=> Recognize NXDomain Errors

linkerd/app/gateway/src/lib.rs, linkerd/app/gateway/src/make.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/prevent_loop.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/service-profiles/src/client.rs, linkerd/service-profiles/src/http/mod.rs
The `HasDestination` trait isn't particularly useful, as it's basically
just `AsRef<Addr>`.
This change updates the `GetRoutes` signature to support this; and it
updates the inbound target type to store an `Addr` instead of an
`Option<NameAddr>` (so `Target` will be suitable for this in an upcoming
change).
=> service-profiles: Eliminate the HasDestination trait

linkerd/app/outbound/src/lib.rs
The outbound proxy handles discovery rejection error with a fallback
router. The current implementation does not allow for middlewares
to wrap errors in a general fashion.
This change updates the `is_discovery_rejecte` function to examine
aribitrary error types to determine if the underlying error matches the
known types.
=> outbound: Make discovery error detection generic

linkerd/app/integration/tests/discovery.rs
I don't know why this was disabled.
=> Restore disabled portion of profile override test

linkerd/app/core/src/classify.rs, linkerd/app/core/src/dst.rs, linkerd/app/core/src/retry.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/service-profiles/src/client.rs, linkerd/service-profiles/src/http/concrete.rs, linkerd/service-profiles/src/http/mod.rs, linkerd/service-profiles/src/http/service.rs, linkerd/service-profiles/src/lib.rs
* Renames `Routes` to `Profile`;
* Renames `GetRoutes` to `GetProfile`;
* Renames `WeightedAddr` to `Target`; and
* Scope `Route` & co within `http` module.
=> service-profiles: Cleanup crate organization

Cargo.lock, Cargo.toml, linkerd/proxy/http/src/balance.rs
We need tower-rs/tower@ad348d8 for an upcoming change. This PR updates
the tower dependency in anticipation of this change. The `Balance`
constructor has changed.
=> Update tower to tower-rs/tower@ad348d8

linkerd/app/outbound/src/lib.rs
The DiscoveryError type is unused. Remove it.
=> outbound: Remove unused error type

linkerd/app/core/src/control.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/proxy/transport/src/connect.rs, linkerd/proxy/transport/tests/tls_accept.rs
The connect module can use the more standard `Into<SocketAddr>`. No need
for a special trait.
=> Eliminate the ConnectAddr trait

linkerd/app/gateway/src/lib.rs, linkerd/app/gateway/src/make.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/service-profiles/src/http/route_request.rs, linkerd/service-profiles/src/split.rs
Using tuples for stack targets (particularly, the input targets of the
route_request and split modules) is a bit brittle.  Instead, we can use
`AsRef` on the target type to access the profile receiver.
This change introduces new target types to be used to satisfy these
traits, and generally cleans up stack construction.
=> profiles: Do not rely on tuples as stack targets

linkerd/app/core/src/control.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/orig_proto_upgrade.rs, linkerd/proxy/http/src/client.rs, linkerd/proxy/http/src/h2.rs
There's a lot of needless boilerplate around the HTTP client, mostly due
to manual future implementations. These have been converted to boxed
futures.
Furthermore, the HasSettings trait has been eliminated, in favor of
AsRef.
=> proxy-http: Remove unneeded boilerplate

linkerd/app/gateway/src/config.rs, linkerd/app/gateway/src/make.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/orig_proto_upgrade.rs, linkerd/app/outbound/src/prevent_loop.rs, linkerd/proxy/http/src/canonicalize.rs
The outbound `endpoint::Target` type is generic to the point of being
useless.
This change modifies the stack target types to be either `HttpLogical`,
`HttpConcrete`, or `HttpEndpoint`. Furthermore, the `canonicalize`
middleware no longer uses a bespoke trait, instead opting for
`AsRef` + `AsMut`.
This sets up further changes to the outbound HTTP stack.
=> outbound: Clarify Http target types

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/proxy/http/src/detect.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/normalize_uri.rs
In b59172a, we moved the NormalizeUri logic into the HTTP server, but
this misses downgraded requests.
This change extracts NormalizeUri from the server, putting it back on
the HTTP stack so that it can be applied after `orig_proto::Downgrade`
is applied on the inbound proxy.
=> http: Put normalize_uri back on the stack

linkerd/app/core/src/serve.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/proxy/http/src/detect.rs
The tracing context includes redundnant information, particularly about
the traffic target.
This change modifies the accept stack to include both the source peer and
target addresses in the `accept` context; and the target address has
been removed from intermediate contexts, many of which can be moved to
the debug level now.
=> tracing: Elide redundant info in tracing contexts

linkerd/stack/src/switch.rs
The cache requires the service type to be `Clone`, but 
`MakeSwitch` doesn't implement `Clone`, even when all
of its constituents services do. We can add a derive to 
fix this, and now everything compiles.
=> fix missing clone impl for MakeSwitch

linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/require_identity_on_endpoint.rs, linkerd/cache/benches/cache.rs, linkerd/cache/src/layer.rs, linkerd/cache/src/lib.rs, linkerd/dns/src/refine.rs, linkerd/http-classify/src/layer.rs, linkerd/http-metrics/src/requests/layer.rs, linkerd/proxy/http/src/header_from_target.rs, linkerd/proxy/http/src/insert.rs, linkerd/proxy/http/src/normalize_uri.rs, linkerd/proxy/http/src/timeout.rs, linkerd/proxy/tap/src/service.rs, linkerd/retry/src/lib.rs, linkerd/router/src/lib.rs, linkerd/service-profiles/src/discover.rs, linkerd/service-profiles/src/http/route_request.rs, linkerd/service-profiles/src/split.rs, linkerd/stack/src/map_target.rs, linkerd/stack/src/new_service.rs, linkerd/stack/src/on_response.rs, linkerd/stack/tracing/src/lib.rs
The cache used to implement logic in its `poll_ready`; but this was
changed some time ago. Otherwise, the cache is synchronous and
infallible, much like the `NewService` trait.
This change modifies `NewService` to take a mutable reference, as needed
by the cache; and it modifies the cache to implement `NewService`
instead of `Service`.
The stacks then coerce the cache back into a service (via `into_make`)
to satisfy the buffer's requirements. It is expected that this buffering
will be decoupled from the cache in a followup change.
=> cache: Implement NewService

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/service-profiles/src/discover.rs, linkerd/service-profiles/src/lib.rs
The profile discovery layer is always coerced to a NewService. This
change formalizes this to avoid stack boilerplate.
While we're here, the GetProfile trait has ben simplified to avoid
exposing poll_ready in its public API. Instead, we provide an impl of
Service for GetProfile that does this (though it's not currently
needed).
=> Implement profile discovery as a NewService

linkerd/app/src/env.rs
The current default DNS refinement timeout is 100ms. This does not seem to be enough as we can observe refinement timeouts. The result of that is that discovery fails and there is no provided identitiy, resulting in the traffic not being tlsed. 
A repro for this can be found here #4992.
=> Increase default Dns canonicalize timeout

linkerd/app/core/src/admin/mod.rs, linkerd/app/core/src/serve.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/tap.rs, linkerd/proxy/http/src/detect.rs, linkerd/proxy/transport/src/metrics.rs, linkerd/proxy/transport/src/tls/accept.rs, linkerd/proxy/transport/tests/tls_accept.rs, linkerd/stack/src/switch.rs
This change modifies `serve` to take a `NewService` instead of a
`MakeService`. Services specific to the accept stack have been
updated as well
`DetectHttp` has been updated to work as either a `MakeService` or
`NewService` -- the asynchronous version is still needed by the outbound
proxy (until caching is changed).
`DetectTls` is now purely a `NewService`.
=> Update the accept stack to use NewService

linkerd/proxy/transport/src/lib.rs, linkerd/proxy/transport/src/listen.rs
The server sets the wrong local address, mistakenly using the peer
address instead.
=> transport: Fix server address metadata

linkerd/app/core/src/svc.rs, linkerd/app/outbound/src/lib.rs
The spawn-ready layer was removed in 1382e32fa; but this means that
endpoint-level services aren't necessarily driven to readiness. This
can manifest in TLS detection timeouts, since a client may not be driven
through the TLS handshake.
This change removes the `push_spawn_ready` helper, because it's really a
`push_make_spawn_ready` and the make layer is totally superfluous.
=> outbound: Restore spawn-ready

linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs
For outbound requests, the src address is always an ephemeral port on
localhost, which isn't particularly valuable. Futhermore, as we add
caching outside of HTTP detection, this becomes annoying to track.
This changes the outbound stack to always use a `None` src addr.
=> outbound: Explicitly ignore the source address for tap

linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/tests.rs, linkerd/app/src/dst/permit.rs, linkerd/proxy/http/src/detect.rs, linkerd/proxy/http/src/version.rs, linkerd/stack/src/switch.rs
Currently, the `DetectHttp` layer always builds both HTTP and TCP
stacks, even though only one is needed. Furthermore, we lose the
information about which protocol was detected--it's never passed into
the http stack (and instead must be inferred from individual requests).
This change modifies the `DetectHttp` layer to only build inner services
as needed, after the protocol has been detected.
Furthermore, outbound caching has been moved up from the tcp balancer to
wrap the HTTP detection layer. This was necessary so that the tcp
balancer could be built instantaneously as a NewService while still
being cloneable. This means that, for each outbound target ip:port, we
will reuse HTTP and TCP stacks.
However, HTTP routing remains dependent on per-request metadata. This is
expected to change in …
=> http: Lazily build http/tcp stacks

linkerd/app/gateway/src/make.rs, linkerd/app/outbound/src/endpoint.rs
Presently, the proxy extracts the required identity from the
`l5d-required-identity` header into the `HttpLogical` target type when
it is present, and builds endpoint stacks which require that identity.
This was previously necessary because service discovery couldn't be
performed for pod IPs, only for authorities. However, this is no longer
the case, and we can now just use the identity returned by service
discovery for these stacks. This means the required identity can be
removed from the `HttpLogical` target, and identities in `HttpEndpoint`
targets are only provided by the destination metadata.
Fixes linkerd/linkerd2#5029
=> outbound: remove required identity from `HttpLogical`

Cargo.lock, linkerd/dns/name/src/name.rs, linkerd/service-profiles/Cargo.toml, linkerd/service-profiles/src/client.rs, linkerd/service-profiles/src/lib.rs
Service profiles may include an optional service name, which is
especially useful if the profile is resolved by IP. This change attempts
to parse this value as a DNS name. If the default (empty) name is
returned, no name is exposed.
=> profiles: Expose the fully_qualified_name

Cargo.lock, linkerd/app/core/src/svc.rs, linkerd/app/src/dst/mod.rs, linkerd/app/src/dst/permit.rs, linkerd/request-filter/Cargo.toml, linkerd/request-filter/src/lib.rs
The request filter takes ownership of the request but does not support
changing its type. Furthermore, the trait requires that the error type
be named even though it always coerced to an `Error`.
This change cleans up the request-filter module as follows:
- The `RequestFilter` trait is now named `FilterRequest` (traits
generally are verbs). This type now has a `Request` type attribute
instead of an `Error` type attribute.
- The `Service` has been renamed to `RequestFilter` and the
`RequstFilterLayer` type has been eliminated.
- The manual future implementation can be eliminated with `Either`.
- The stack helper has been removed, as it's only used in one place.
=> request-filter: Allow altering request type

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/proxy/http/src/version.rs, linkerd/stack/tracing/src/lib.rs
* Modify stack-tracing to set contexts on the initial new_service/make_service invocation (and not just the resulting future/service)
* Tighten up the HTTP context. `http{version=http/1.x}` was verbose and redundant
=> tracing: Set contexts in new_service/make_service

linkerd/proxy/discover/src/buffer.rs, linkerd/proxy/discover/src/make_endpoint.rs
In 571f4cba we accidentally introduced a busy-loop on resolution stream
termination; and, furthermore, the buffer layer returns an error when
the inner stream terminates.
This change alters both of these to gracefully propagate stream
termination.
=> discover: Allow resolution streams to terminate

linkerd/app/core/src/metric_labels.rs, linkerd/app/core/src/transport/labels.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs
In order to have `linkerd edges` return non-empty values for a raw TCP
connection's `CLIENT_ID`, the proxy's `tcp_open_total` metric needs to
include the `client_id` label for inbound connections, like the
`request_total` metrics for http connections does.
This PR changes the `TlsStatus` metric label type to include a peer
identity in the `Conditional::Some` case, rather than `()`. This means
that all metrics with TLS labels will now include the peer identity as
a label.
I've manually verified that this works by running Linkerd locally and
scraping the metrics:
For example, here's an excerpt from Grafana:
```
tcp_open_total{peer="src",direction="inbound",tls="no_identity",no_tls_reason="no_tls_from_remote"} 44
tcp_open_total{peer="dst",direction="inbound",tls="no_identity",no_tls_reason="l …
```
=> metrics: add peer identities to all TLS metric labels

linkerd/app/core/src/lib.rs, linkerd/app/integration/src/tests/telemetry.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/tests.rs, linkerd/app/src/dst/default_resolve.rs, linkerd/app/src/dst/mod.rs, linkerd/app/src/dst/permit.rs, linkerd/app/src/dst/resolve.rs, linkerd/proxy/api-resolve/src/metadata.rs, linkerd/proxy/transport/src/tls/mod.rs
When the resolver rejects resolution, we currently propagate that error
so that it can be handled via fallback. And due to recent HTTP router
changes, these resolution errors can propagate up across splits, etc.
This change simplifies this behavior by instead synthesizing a
resolution with a default endpoint.
The `not_http` reason has been removed, as it's no longer useful.
=> outbound: Return a default endpoint on reject

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/proxy/http/src/detect.rs
The `AcceptHttp` service is stateful. It builds the underlying HTTP,
HTTP/2, and TCP service stacks lazily the first time they're needed.
This interacts badly with the derived implementation of `Clone`: if it's
cloned before the state is set, the state will only be set for the
clone, rather than for the original instance in the cache. Since
`Prefix` clones and oneshots the underlying service (`AcceptHttp`), this
means that we rebuild the HTTP, HTTP/2, and TCP stacks on every
connection to the same orig dest. This basically breaks caching for
everything other than service profile discovery, causing us to do new
destination discovery for every connection to the same original
destination. Which...isn't great.
This branch fixes this issue by removing the `Clone` impl from
`AcceptHttp` and …
=> fix AcceptHttp being rebuilt for every connection

linkerd/app/core/src/metric_labels.rs, linkerd/app/core/src/retry.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/require_identity_for_ports.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/http-metrics/src/requests/layer.rs, linkerd/proxy/transport/src/metrics.rs
The `TransportLabels` trait & types serve no real purpose and can be
better-expressed via `Into`.
This change replaces the `TransportLabels` trait with an `Into`
constraint.  Furthermore, HTTP metrics have been updated to coerce the
target by-reference, without cloning the whole target.
=> metrics: Coerce targets to metric labels by-reference

linkerd/app/gateway/src/make.rs, linkerd/app/outbound/src/allow_discovery.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/tests.rs
We have target types like `{Http,Tcp}{Logical,Concrete,Endpoint}` that
differ only superficially between the HTTP and TCP variants. This
results in unnecessary, duplicate trait impls.
This change consolidates these targets as `Logical`, `Concrete`, and
`Endpoint`, all of which are generic over the protocol type. We provide
`Tcp*` and `Http*` trait aliases as a shorthand and compatibility.
=> outbound: Unify TCP & HTTP target types

Cargo.lock, linkerd/app/core/src/lib.rs, linkerd/app/core/src/spans.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/stack/src/lib.rs, linkerd/trace-context/Cargo.toml, linkerd/trace-context/src/layer.rs, linkerd/trace-context/src/lib.rs, linkerd/trace-context/src/propagation.rs
TraceContext relies on some older idioms like a manual future
implementaton.
This change replaces the `TraceContextLayer` type with a
`TraceContext::layer` function and the `ResponseFuture` implementation
with an (optionally) boxed response future. The response future is boxed
only when tracing is active.
No functional changes/
=> trace-context: Simplify implementation with async

linkerd/app/core/src/config.rs, linkerd/app/core/src/lib.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/integration/src/proxy.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/tests.rs, linkerd/app/src/env.rs, linkerd/service-profiles/src/client.rs, linkerd/service-profiles/src/lib.rs
The outbound proxy skips protocol detection when the target port is in a
configured list. But there's nothing that actually sets this
configuration currently. Now that we lookup profiles before protocol
detection, we can use the profile response to provide a more granular
per-endpoint hint.
This change stops honoring the
`LINKERD2_PROXY_OUTBOUND_PORTS_DISABLE_PROTOCOL_DETECTION` environment
variable. Service profiles are now used exclusively to determine whether
protocol detection should be skipped for outbound connections.
=> outbound: Use profile to inform protocol detection

linkerd/app/inbound/src/lib.rs, linkerd/app/integration/src/tests/orig_proto.rs
linkerd/linkerd2#5069 reports that proxied requests can incorrectly
end up in the absolute-form. This happens because URI normalization is
applied after protocol downgrade (where the absolute-form is annotated
explicitly).
This change improves the inbound orig-proto test to detect this bug and
fixes it by performing normalization before protocol downgrade so that
the downgrade layer's behavior is not overridden.
=> inbound: Fix URI normalization for orig-proto requests

linkerd/app/gateway/src/config.rs, linkerd/app/gateway/src/gateway.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/gateway/src/make.rs, linkerd/app/src/lib.rs
The gateway has two deficiencies:
* Using the outbound proxy port for the outbound original dst leads to
the incorrect port being used in the `l5d-dst-canonical` header. Now,
we instead use the proper port with an unroutable IP address.
* Because the source cluster's outbound proxy strips `Host` headers,
there's no `Host` present on gatewayed HTTP/1 requests. Now, the
`Host` header is updated on all gatewayed HTTP/1 requests.
=> gateway: Ensure proper outbound metadata

linkerd/app/core/build.rs, linkerd/app/core/src/telemetry/build_info.rs
The `git_version` typically includes only a tag name without a SHA. But
symbolic tags don't necessarily disambiguate commits. This change adds a
`git_sha` label that includes the output of `git rev-parse --short HEAD`
to identify the actual commit behind the tag.
=> telemetry: Include git SHA in build_info

Cargo.lock, linkerd/app/core/src/admin/mod.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/Cargo.toml, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/tests/tcp.rs, linkerd/io/Cargo.toml, linkerd/io/src/boxed.rs, linkerd/io/src/lib.rs, linkerd/io/src/prefixed.rs, linkerd/io/src/sensor.rs, linkerd/proxy/http/src/client_addr.rs, linkerd/proxy/http/src/detect.rs, linkerd/proxy/http/src/lib.rs
We recently stopped exposing source addresses on outbound Tap metadata,
but this causes some confusion in the Tap UIs.
This change introduces an `io::PeerAddr` trait that is implemented by
all `Io` types and a `proxy::http:SetClientAddr` middleware that inserts
a `ClientAddr` type onto requests. This middleware is now applied by the
`DetectHttp` server to ensure the HTTP stack can access the source
address.
=> outbound: Set source address in Tap metadata

linkerd/app/outbound/src/tests/tcp.rs
This PR adds a new test asserting that service profiles are only
resolved for original destination IPs within the specified search
networks. Also, I updated the existing tests so that the mock connectors
for endpoints which are expected to be plaintext actually assert that no
server identity was provided.
=> outbound: test profile search nets filtering

linkerd/app/outbound/src/tests/tcp.rs, linkerd/app/test/src/connect.rs
Depends on #714
This branch adds new tests for updating TCP destinations by adding and
removing endpoints. The first test asserts that when new endpoints are
added to a load balancer, some connections after they are added are
routed to the new endpoint. The other test asserts that when endpoints
are removed, they no longer receive connections.
I've also done some more test cleanup & boilerplate removal.
=> outbound: test load balancer adding/removing TCP endpoints

linkerd/app/src/env.rs
The configuration logic includes a default set of ports to skip, but
with linkerd/linkerd2#5093, this policy is lifted into configuration.
With that change, these hardcoded defaults can be removed from the
proxy.
=> Remove hardcoded list of ports to skip

linkerd/app/core/src/admin/mod.rs, linkerd/metrics/src/serve.rs
The metrics server has a lot of needless boilerplate logic. This change
simplifies the `Service` impl to a single, synchronous `fn serve`,
eliminates unneeded error types, and relaxes type constraints where
possible.
=> admin: Simplify metrics server

linkerd/tracing/src/lib.rs, linkerd/tracing/src/uptime.rs
In logs, we emit timestamps as time fractional seconds since the process
started. These timestamps are intended to be formatted at a fixed
length, but we don't properly truncate nanoseconds to fit the 6-digit
field we leave for subsecond time.
This change converts nanoseconds to microseconds when formatting
the uptime so that the value fits into six digits. It also adds a test
to validate this behavior.
=> tracing: Fix time formatting to ensure alignment

Cargo.lock, linkerd/app/integration/Cargo.toml, linkerd/app/test/Cargo.toml, linkerd/proxy/transport/Cargo.toml, linkerd/stack/Cargo.toml, linkerd/tracing/Cargo.toml
This picks up the following upstream changes:
* tokio-rs/tracing#1064, which fixes a bug where creating a subscriber
would allocate a large amount of memory that was not actually used
* tokio-rs/tracing#1058, which significantly reduces the overhead of
entering and exiting spans
Together, these changes should improve proxy performance when tracing is
enabled.
=> trace: update `tracing-subscriber` to 0.2.14

linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/prevent_loop.rs
Currently, loopback connections are detected using the `PreventLoop`
layer, which returns an error when the target address' port matches the
proxy listener's port. The inbound router currently uses a `Fallback`
layer to detect this error and send loopback traffic to a loopback
service (the mutlicluster gateway).
This branch changes the inbound proxy to dispatch loopback connections
to the multicluster gateway using a `MakeSwitch` layer instead. The
`MakeSwitch` layer inspects the target type and applies a predicate to
it that determines which of two services to make. This is essentially
the same behavior as using the fallback on error layer, but with fewer
steps.
=> inbound: use MakeSwitch for loopback

linkerd2-proxy/src/rt.rs
When testing the proxy (i.e. outside of Kubernetes), it can be desirable
to limit the number of cores the proxy uses. This change introduces a
`LINKERD2_PROXY_CORE` environment that overrides the `num-cpus`-based
detection.
=> Allow specifying the number of available cores via the env

linkerd/app/core/src/config.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/test_util.rs, linkerd/app/src/env.rs, linkerd/proxy/http/src/client.rs, linkerd/proxy/http/src/h1.rs
When an HTTP/1.1 client has many concurent requests, it may create an
arbitrary number of TCP connections. These connections are retained for
90s before they are dropped. In HTTP/1.1. applications communicate at
high concurrency, this can lead to elevated memory requirements.
Similar behavior is observed with HTTP/2 clients (i.e. when using mesh
protocol upgrades) if the application communicates with many unique
services, as is the case for Prometheus.
To address this issue, we want to be more aggressive about tearing down
idle/unused clients. This is primarily achieved by reducing the outbound
"max idle age" setting to 5s, which matches the default Kubernetes DNS
TTL. On the inbound side, the max idle age is set to 20s, as the number
of clients is typically on the order of <5. …
=> http: Configure client connection pools

linkerd/app/src/env.rs, linkerd/proxy/http/src/detect.rs, linkerd/proxy/http/src/h2.rs
This branch enables HTTP/2 PING frames in the proxy's HTTP/2 clients and
servers. The timeout for responding to a PING frame is configured based
on the `{INBOUND, OUTBOUND}_{CONNECT, ACCEPT}_KEEPALIVE` env variables,
and the interval between PING frames is currently 1/4th of the timeout.
I'm happy to change that if anyone has better ideas.
Collecting metrics related to H2 PINGs probably requires support in 
Hyper that doesn't currently exist, so this PR doesn't add that. We 
can implement metrics in a follow-up, as it's lower priority.
Closes linkerd/linkerd2#1580
=> h2: enable HTTP/2 keepalive PING frames

.github/workflows/docker.yml, .github/workflows/release.yml, .github/workflows/rust.yml
In order to prevent runaway tests from consuming actions resources, we
set reasonable default timeouts for each job. This replaces the default
6 hour(!) timeout.
=> actions: Add timeouts to GitHub workflows

linkerd/app/outbound/src/server.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/tests.rs, linkerd/app/test/src/resolver.rs, linkerd/io/src/lib.rs
This branch fixes a bug where TLS would never be used for endpoint hints
provided by service profile discovery, even when the profile endpoint
metadata has an identity. This is because the wrong conversion was used
when mapping a `Logical` target into a `tcp::Endpoint`, which always
ignored the profile endpoint metadata.
Additionally, I've added tests for the new behavior added in this
branch, including one which reproduced the above issue, and one for
connection error propagation.
=> add tests; fix profile endpoint TLS ID being ignored

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/integration/Cargo.toml, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/server.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/tests.rs, linkerd/app/test/src/resolver.rs, linkerd/io/src/lib.rs, linkerd/proxy/api-resolve/Cargo.toml, linkerd/proxy/api-resolve/src/lib.rs, linkerd/proxy/api-resolve/src/pb.rs, linkerd/proxy/identity/Cargo.toml, linkerd/proxy/tap/Cargo.toml, linkerd/service-profiles/Cargo.toml, linkerd/service-profiles/src/client.rs, linkerd/service-profiles/src/lib.rs, linkerd/stack/src/fail_on_error.rs, linkerd/stack/src/lib.rs, linkerd/stack/src/switch.rs
Profile resolutions may provide an endpoint response when the
target is a pod or otherwise known endpoint. When these endpoints fail
requests with an I/O error, we assume that the endpoint is defunct and
fail the service so that subsequent connections require a new
resolution.
=> outbound: Skip endpoint resolution on profile hint

linkerd/addr/src/lib.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/outbound/src/tcp/tests.rs, linkerd/app/src/env.rs, linkerd/app/test/src/profile.rs, linkerd/dns/name/src/name.rs, linkerd/dns/name/src/suffix.rs, linkerd/dns/src/lib.rs, linkerd/identity/src/lib.rs, linkerd/identity/src/test_util.rs, linkerd/proxy/api-resolve/src/pb.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/transport/src/tls/conditional_accept.rs, linkerd/service-profiles/src/client.rs
We use `TryFrom<&[u8]>` in many cases we can use `FromStr`. This is a
minor cleanup of these type coersions.
=> Add a FromStr for dns::Name

Cargo.lock, linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/server.rs, linkerd/cache/Cargo.toml, linkerd/cache/src/lib.rs, linkerd/stack/Cargo.toml, linkerd/stack/src/box_new_service.rs, linkerd/stack/src/lib.rs
Caches are typically wrapped with buffers so that they can be shared
across connections. These buffers can be eliminated if the cache itself
becomes cloneable; and this is easily achieved with a
`parking_lot::RwLock`: the cache first obtains a read lock to clone the
inner service and a write lock is only obtained when the service is not
in the cache.
It turns out that the buffers have an important side effect, though: the
buffers hide the inner service type, which drastically reduces the
amount of memory needed to compile the linkerd2-proxy crate. To
replicate this, this change introduces a `stack::BoxNewService` which
can be used to hide the type signature of a `NewService`.
Benchmarks indicate that this improves p50 latency by 2ms for HTTP/2
traffic at 100 concurrenct requests.
=> cache: Make the cache cloneable with RwLock

linkerd/app/outbound/src/http/mod.rs, linkerd/app/outbound/src/http/tests.rs, linkerd/app/test/src/connect.rs
This commit adds a test that when service profile discovery provides an
endpoint directly, connection errors for HTTP traffic are forwarded to
the client directly, rather than synthesizing HTTP error responses. This
is similar to the test I added in #741, except it's for an HTTP client
rather than a raw TCP client.
This test currently fails on `main`.
=> outbound: add test for fwding conn errors to HTTP clients

linkerd/app/core/src/errors.rs
The proxy will synthesize responses for some error conditions.
Currently, there's special logic for synthesizing errors for gRPC
requests: we emit `grpc-status` and `grpc-message` trailers rather than
HTTP status codes for gRPC requests. However, we *don't* currently set a
`content-type` header for gRPC error responses. This makes some clients
angry.
This commit adds a `content-type: application/grpc` header to
synthesized error responses for gRPC requests.
Fixes linkerd/linkerd2#5273
=> errors: set `content-type` for synthesized grpc errors

linkerd/app/src/env.rs
We've received reports that the default in-flight limit may be too
small. Now that the proxy can consume multiple cores, it seems wise to
increase the default from 10K to 100K.
This bound should prevent high-traffic workloads from hitting the
in-flight limit in all but extreme cases, while still protecting the
proxy against infinite growth.
=> Increase the default buffer capacity to 100K

linkerd/app/src/env.rs
There are seperate settings for the default in-flight request limit and
the proxy's buffer capacity, but we've chosen a single default.
This change restores the buffer capacity to 10K while raising the
in-flight request limit to 100K. This is intended to allow the proxy to
support services that do not respond promptly that may legitimitately
have <100K pending requests.
=> Change default max-in-flight and buffer-capacity

linkerd/io/src/boxed.rs, linkerd/io/src/lib.rs, linkerd/io/src/prefixed.rs, linkerd/io/src/sensor.rs, linkerd/proxy/http/src/detect.rs
The io::PeerAddr trait assumes that the peer addr lookup is infallible,
panicking the process when the call fails. In practice, however, this
call can fail when a system is under load.
This change modifies the `io::PeerAddr` trait to allow this lookup to
fail. When it fails, we propagate this failure to the connection's task.
=> io: Make peer_addr fallible

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/exp-backoff/src/lib.rs, linkerd/proxy/http/src/balance.rs, linkerd/proxy/tap/Cargo.toml, linkerd/proxy/tcp/Cargo.toml, linkerd/proxy/tcp/src/balance.rs, linkerd/service-profiles/src/split.rs, linkerd/trace-context/Cargo.toml, linkerd/trace-context/src/propagation.rs
While testing another program, I was reminded that `SmallRng` can have
surprising behavior when cloned: since a SmallRng's internal state is
stored in a field, each clone ends up in the same state such that each
clone produces the same sequence of values.
Furthermore, the use of `SmallRng::from_entropy` uses `getrandom`
internally, which can be quite slow, especially compared to the
alternative `SmallRng::from_rng(&mut thread_rng())`.
It doesn't appear that any of our uses of `SmallRng` are particularly
problematic -- i.e. the services that hold a `SmallRng` are not cloned,
so we shouldn't be in a place where we always use a single value.
However, in the spirit of being defensive to this scenario, this change
avoid storing a `SmallRng` in Layer and NewService implemetnations so
that each …
=> Audit uses of SmallRng to avoid cloning

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/server.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/server.rs
In preparation for an upcoming change that decouples HTTP detection
logic from server initialization, this chagne renames `DetectHttp` to
`NewServeHttp` and `AcceptHttp` to `ServeHttp`.
=> Rename DetectHttp to NewServeHttp

linkerd/app/core/src/svc.rs, linkerd/app/gateway/src/config.rs, linkerd/app/gateway/src/gateway.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/server.rs, linkerd/app/test/src/service.rs, linkerd/http-box/src/body.rs, linkerd/http-box/src/lib.rs, linkerd/http-box/src/request.rs, linkerd/http-box/src/response.rs, linkerd/proxy/http/src/client.rs, linkerd/proxy/http/src/glue.rs, linkerd/proxy/http/src/h1.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/orig_proto.rs, linkerd/proxy/http/src/server.rs, linkerd/proxy/http/src/upgrade.rs
HTTP bodies are represented by the `Body` trait in the `HttpBody` crate.
Hyper re-exports this trait as `HttpBody`, and provides its own concrete
type named `Body`, implementing this trait. Previously, Hyper provided
its own trait, named `Payload`.
In the proxy, there are several types implementing `Body`. The naming
scheme for these types is inconsistent: some of them are named `Body`,
and others are named `Payload`. This makes it somewhat unclear what
these names refer to, especially when they show up in compiler errors
like "expected type 'Body', but found type 'Body'." 
This branch renames these types to use a more consistent naming scheme:
* The `Body` type in `linkerd2_proxy_http::glue` is now named
`UpgradeBody`, since it deals with handling HTTP/1.1 upgrades,
* The `Payload` type …
=> http: more consistent names for body types

linkerd/io/src/boxed.rs, linkerd/io/src/lib.rs, linkerd/io/src/prefixed.rs, linkerd/io/src/sensor.rs
Since `poll_read_buf` and `poll_write_buf` are now free functions in
`tokio-util::io`, rather than trait methods on `AsyncRead` and
`AsyncWrite`, it's no longer necessary for us to provide type-erased
implementations of them. Therefore, the `Io` trait in
`linkerd2-proxy-io` can be made much simpler --- now, its job is *just*
to give a single trait for the trait object inside a `BoxedIo`, as trait
objects may not have multiple non-marker traits.
This branch simplifies  `Io` to just be `AsyncRead + AsyncWrite +
PeerAddr`, and removes the `poll_read_buf_erased` and
`poll_write_buf_erased` methods. It also unseals `Io`, since it's no
longer responsible for ensuring correct propagation of vectored writes.
There should be no functional changes in this PR.
Signed-off-by: Eliza Weisman …
=> io: simplify the `Io` trait

Cargo.lock, linkerd/app/core/src/admin/mod.rs, linkerd/app/outbound/src/tcp/tests.rs, linkerd/app/test/src/lib.rs, linkerd/tracing/Cargo.toml, linkerd/tracing/src/level.rs, linkerd/tracing/src/lib.rs
This branch improves how traces are displayed in tests. In particular,
I've made the following changes:
* When running tests, use a "test writer" that participates in libtest's
output capturing. Now, traces from tests will be displayed grouped
together when the test fails, rather than printed to the console as
soon as they occur. Logs can now be printed for successful tests using
`cargo test -- --show-output`, and will still be grouped by test.
* Because test traces are now captured, enable a more verbose default
filter for tests. The logs will no longer be spammed to the console,
so it's okay to have more verbose logging on by default when tests
fail.
* Disabled thread IDs in test mode. The tests run single-threaded
proxies, and the new-style stack tests are completely single threaded. …
=> trace: nicer traces in tests, clean up trace configuration

linkerd/app/core/src/serve.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/ingress.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/retain.rs
Middlewares, especially the cache, may want to use RAII to detect when a
service is idle, but the TCP server and HTTP routers drop services as
soon as the request is dispatched.
This change modifies the TCP server to hold its per-connection service until
all work on that connection is complete. It also introduces a new
`http::Retain` middleware that clones its inner service into repsonse
bodies.
This is necesarry for upcoming cache eviction changes to address
linkerd/linkerd2#5334.
=> Ensure that services are held as long they are being used

linkerd/app/outbound/src/http/tests.rs, linkerd/app/outbound/src/server.rs, linkerd/app/outbound/src/tcp/tests.rs, linkerd/app/test/src/connect.rs, linkerd/io/src/boxed.rs
This branch adds some new stack tests for simple HTTP/1 and HTTP/2
meshed and unmeshed outbound requests. These tests also assert that TCP
load balancers are not constructed when HTTP traffic is detected.
The hope was that the panic on constructing TCP balancers would catch a
bug that exists in #744, but that issue appears to be related to the
cache instead. Still, it's probably worth having these tests.
=> outbound: add stack tests for http

linkerd/app/core/src/svc.rs, linkerd/cache/Cargo.toml, linkerd/cache/src/lib.rs
In b0cf2fbb, the proxy moved eviction to be controlled by a background
task; but this scheme spawned a task every time a service was dropped.
This change modifies the cache to only spawn a single task per cached
service and use a notification channel to signal drops. This reduces
memory pressure, especially for HTTP caches.
This change also improves cache logging diagnostics.
=> cache: Only spawn a single task per cache entry

Cargo.lock, linkerd/app/integration/src/proxy.rs, linkerd/app/test/Cargo.toml, linkerd/app/test/src/lib.rs
PR #766 changed the proxy tests to set a much more verbose default log
filter, relying on libtest's output capturing to prevent the tests from
spamming stdout when they don't fail. However, the integration tests run
the proxy in a separate thread, and libtest can't currently capture
output from spawned threads. This results in a bunch of unnecessary
noise when running the integration tests.
When Rust 1.49.0 is released, we should revisit this, as output capturing
will work for spawned threads.
This branch changes the integration tests so that the spawned proxy
thread uses the old filter settings instead. We still get more detailed
output from stack tests, and from the main test threads in the
integration tests. I removed some code that would set the value of the
log level env vars, since …
=> test: make integration tests shut up

linkerd/app/core/src/metrics.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/server.rs
Now that TCP stacks are getting more complex, it's worth differentiating
them with a protocol label. This change also renames 'source' stacks to
'server' stacks.
=> Add a protocol label to stack metrics

Cargo.lock, linkerd/tracing/Cargo.toml, linkerd/tracing/src/tasks.rs
This branch updates the `tokio-trace` crate, which we use to implement
the task-tracking endpoint, to a version that depends on Tokio 0.3. This
is necessary for task tracking to work, and also removes an unnecessary
Tokio 0.2 dep from our dependency tree.
Also, the future type name field was removed in Tokio 0.3, since it's
_far_ too long to be useful, and was replaced with spawn locations.
Hopefully, this will make task tracking significantly more useful, and
reduce the memory overhead.
=> trace: update task-tracking to Tokio 0.3

.github/workflows/rust.yml, Cargo.lock, hyper-balance/Cargo.toml, linkerd/app/gateway/Cargo.toml, linkerd/buffer/Cargo.toml, linkerd/http-metrics/Cargo.toml, linkerd/metrics/Cargo.toml, linkerd/opencensus/Cargo.toml, linkerd/proxy/discover/Cargo.toml, linkerd/proxy/transport/Cargo.toml, linkerd/proxy/transport/src/listen.rs, linkerd/stack/Cargo.toml, linkerd/timeout/Cargo.toml
Some subcrates have unneeded or outdated dependencies. This change
updates most of them. The opencensus and trace-context traits should be
updated in a followup.
=> Ensure each crate can be built indpendently

Makefile, hyper-balance/src/lib.rs, linkerd/app/integration/src/lib.rs, linkerd/app/integration/src/tests/discovery.rs, linkerd/app/integration/src/tests/identity.rs, linkerd/app/integration/src/tests/shutdown.rs, linkerd/app/integration/src/tests/telemetry.rs, linkerd/app/integration/src/tests/transparency.rs, linkerd/app/src/env.rs, linkerd/dns/name/src/name.rs, linkerd/drain/src/lib.rs, linkerd/http-metrics/src/requests/mod.rs, linkerd/metrics/src/counter.rs, linkerd/metrics/src/histogram.rs, linkerd/proxy/http/src/detect.rs, linkerd/proxy/transport/tests/tls_accept.rs
There are some lints that are obfuscated by macros, so the integration
tests have some blanket allows.
=> Apply clippy to all targets, including tests

linkerd/app/outbound/src/http/tests.rs, linkerd/app/outbound/src/tcp/tests.rs, linkerd/proxy/api-resolve/src/metadata.rs, linkerd/proxy/api-resolve/src/pb.rs
Endpoint weights are unused. This change removes weights from the
metadata struct.
=> Remove weights from endpoint metadata

linkerd/app/src/env.rs
The proxy fails connections that do not complete protocol detection
within a given timeout. This timeout has been derived from the
request-level dispatch timeout; but in practice, many applications may
create idle connections, i.e. in a connection pool, and distribute
requests over them as requests or events come into the application.
In order to better-support these applications, we want to extend the
detection timeout to permit idle connections to be established without
failing them eagerly; though we do not want to increase the
request-level dispatch timeout, as that can lead to undesirable memory
pressure and request-level latency.
This change creates a dedicated pair of configurations for the detection
timeout, decoupled from the dispatch timeout, and sets its default to
10s.
=> Default the protocol detection timeout to 10s

linkerd/app/src/identity.rs, linkerd/proxy/identity/src/certify.rs, linkerd/proxy/identity/src/metrics.rs
Depends on #787.
This commit adds a new `identity_cert_refresh_count` counter metric,
which tracks the number of times the proxy's identity certificate has
been successfully refreshed by the Identity service.
This change was fairly straightforward, but I did make a few internal
changes so that the counter could be passed into the daemon task. This
resulted in a couple things moving around, but the moved code is largely
unchanged.
In the future we may want to count cert refresh errors as well, possibly
adding labels for successes/failures, or a new metric tracking errors.
=> identity: add `identity_cert_refresh_count` metric

linkerd/app/inbound/src/lib.rs, linkerd/proxy/http/src/orig_proto.rs
This change adds a helper, `orig_proto::Downgrade::layer`, to simplify
stack initialization.
=> Simplify orig_proto::Downgrade intializaiton

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/server.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/normalize_uri.rs
In order to simplify stack initialization, this change renames the
`MakeNormalizeUri` type to `NewNormalizeUri` and adds a `layer` helper.
=> Simplify http::normalize_uri initialization

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/server.rs, linkerd/app/outbound/src/tcp/balance.rs, linkerd/app/outbound/src/tcp/connect.rs, linkerd/proxy/tcp/src/forward.rs
Add a `tcp::Forward::layer` helper to simplify stack initialization.
=> Simplify tcp::Forward stack initialization

linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/require_identity_on_endpoint.rs
Add a `NewRequireIdentity::layer` helper to simplify the outbound HTTP
stack.
=> Simplify outbound endpoint stack creation

linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/ingress.rs, linkerd/stack/src/router.rs
NewRouter initialization is needlessly verbose.
This change reduces boilerplate by adding a `NewRouter::layer` helper.
=> Simplify NewRouter initialization

linkerd/app/core/src/control.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/http-metrics/src/requests/mod.rs, linkerd/http-metrics/src/requests/service.rs
This change replaces the http_metrics::requests::Layer type with an
anonymous helper and removes the unneeded `MakeService` and future
implementations.
=> Simplify HTTP metrics initialization

Cargo.lock, linkerd/app/src/env.rs
This change adds startup configuration checks to ensure that:
1. Identity is required on the inbound port; and
2. The inbound port is not included in the opaque ports list.
This helps to ensure that the inbound proxy port is only used to
securely proxy opaque transport messages (as well as HTTP requests for
multicluster gateways).
=> Add checks to ensure support for opaque transport

linkerd/app/core/src/control.rs, linkerd/app/outbound/src/tcp/connect.rs, linkerd/proxy/transport/src/tls/client.rs, linkerd/proxy/transport/src/tls/mod.rs, linkerd/proxy/transport/tests/tls_accept.rs
The tls::client module uses an old-style manual future implementation,
which makes it difficult to read.
This change replaces the `client::ConnectLayer` type with an anonymous
helper function and replaces the manual future state machine with an
async block.
=> Simplify tls::client module

linkerd/app/gateway/src/config.rs, linkerd/app/gateway/src/gateway.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/server.rs, linkerd/app/src/lib.rs, linkerd/app/test/src/service.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/server.rs
The `proxy::http` module re-exports the boxed _module_ so that all uses
are referenced like `http::boxed::BoxBody`. This is needlessly verbose.
This change re-exports the `BoxBody`, `BoxRequest`, and `BoxResponse`
types directly from the `http` module to simplify references as, e.g.
`http::BoxBody`.
=> http: Simplify http::boxed type references

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/resolve.rs, linkerd/app/outbound/src/server.rs, linkerd/app/outbound/src/tcp/balance.rs, linkerd/app/outbound/src/tcp/connect.rs, linkerd/app/outbound/src/tcp/opaque_transport.rs
We've grown a bunch of type constraints that don't actually influence
compilation. This change removes unnecessary constraints.
=> Simplify stack type constraints

linkerd/app/core/src/config.rs, linkerd/app/core/src/control.rs, linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/tcp/connect.rs, linkerd/app/outbound/src/test_util.rs, linkerd/app/src/env.rs, linkerd/proxy/transport/src/connect.rs, linkerd/proxy/transport/src/lib.rs, linkerd/proxy/transport/src/listen.rs, linkerd/proxy/transport/tests/tls_accept.rs
This change makes it clearer that these are concrete types and not
abstract traits. It also removes the `svc::connect` helper, as its
overly specialized.
This is intended to setup decoupling TCP connections from the
inbound/outbound stacks so that we can setup the entire stack without
interacting with OS sockets.
=> Rename transport types to ConnectTcp and BindTcp

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/tests.rs, linkerd/app/src/lib.rs, linkerd/app/src/tap.rs, linkerd/proxy/tap/src/lib.rs, linkerd/proxy/tap/src/registry.rs, linkerd/proxy/tap/src/service.rs
This change updates the tap module to look more like our other modules.
Instead of building a layer that is passed into stack builders, the tap
module now only produces its registry and stacks are instrumented with
the (renamed) `NewTapHttp::layer` helper.
This change removes the unused MakeService implementation and replaces
the manual future implementation with a boxed async closure.
=> tap: Simplify tap initialization

linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/server.rs, linkerd/stack/src/lib.rs, linkerd/stack/src/unwrap_or.rs
The `NewOptional` module's name is a bit misleading. This change renames
it to `NewUnwrapOr` which is a slightly better analog of what it
actually does.
=> stack: Rename NewOptional to NewUnwrapOr

linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/src/lib.rs, linkerd/stack/src/fail.rs, linkerd/stack/src/lib.rs
In order to make the inbound stack testable without initializing OS
sockets, this change decouples the inbound stack from its TCP client,
passing in an abstract implementation to `inbound::Config::build`.
This change introduces a new `stack::Fail` module that always fails.
This is used to ensure that connections targeting the inbound server
without an opaque port are not forwarded, removing the need for
endpoint-level loop prevention.
=> inbound: Decouple inbound stack from TCP connections

Cargo.lock, Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/core/src/lib.rs, linkerd/app/inbound/src/endpoint.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/integration/src/tests/transparency.rs, linkerd/app/outbound/src/tcp/opaque_transport.rs, linkerd/transport-header/Cargo.toml, linkerd/transport-header/build.rs, linkerd/transport-header/proto/header.proto, linkerd/transport-header/src/lib.rs
Transport headers may be used for non-opaque traffic, i.e., for
multicluster.
This change renames the module and changes the transport preface to
reflect this.
=> Rename opaque-transport to transport-header

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/core/src/control.rs
tower-http is not actually production ready, and our git depenency now
introduces outdated crate dependencies. This change replaces the use of
`tower-request-modifier` with a simple one-off service.
This ends up being a net reduction in code.
=> Remove dependency on tower-http

Cargo.lock, linkerd/app/Cargo.toml, linkerd/app/core/Cargo.toml, linkerd/app/core/src/addr_match.rs, linkerd/app/outbound/Cargo.toml
We depend on both ipnet v1 and ipnet v2. This change updates all
dependencies to v2.
=> Update ipnet to v2

Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/core/src/control.rs, linkerd/app/core/src/lib.rs, linkerd/app/gateway/src/config.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/gateway/src/make.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/tcp/connect.rs, linkerd/app/src/admin.rs, linkerd/app/src/dst.rs, linkerd/app/src/identity.rs, linkerd/app/src/oc_collector.rs, linkerd/app/src/tap.rs, linkerd/proxy/transport/src/tls/accept.rs, linkerd/proxy/transport/src/tls/client.rs, linkerd/proxy/transport/tests/tls_accept.rs
There's only one reason we may lack a local identity: when it's
explicitly disabled.
This change decouples the local identity types from the
`ReasonForNoPeerName` conditional, as local identity has nothing to do
with peer names. We instead represent local identity as a simple
`Option` type.
=> Represent local identity as an Option

linkerd/app/integration/src/proxy.rs, linkerd/app/integration/src/tests/tap.rs, linkerd/app/src/env.rs
This is required as part of linkerd/linkerd2#5326 because the tap env variables
will no longer always be set.
There is a dependency on identity being enabled for tap to work. The
status of tap is determined by the `ENV_TAP_SVC_NAME` env variable being set
or not set.
- If identity is disabled, tap is disabled, but a warning is issued if
`ENV_TAP_SVC_NAME` is set.
- If identity is enabled, the status of tap is determined by
`ENV_TAP_SVC_NAME`.
=> Remove tap status being explicitly set in config

linkerd/tracing/src/lib.rs
When configuring the `tracing` subscriber to emit JSON logs, we're
currently configuring it to use a JSON _event_ formatter, but not a
JSON _field_ formatter. This means that span and event fields are
formatted with the default field format, `key=val`, which is not valid
JSON. This results in parse errors when logging events in a span with
fields, and we format those fields as an error message instead. See
linkerd/linkerd2#5520.
Typically, the simplest way to configure a JSON `fmt` layer is to use
the `.json()` method. This sets both the event formatter *and* the field
formatter to emit JSON. However, since we are sharing some event
formatter configuration across the JSON and plaintext logging modes, the
proxy doesn't use this method; instead, it sets the JSON mode on the
event formatter …
=> tracing: fix incorrect field format when logging in JSON

linkerd/app/integration/src/controller.rs, linkerd/app/integration/src/identity.rs, linkerd/app/integration/src/proxy.rs, linkerd/app/integration/src/server.rs, linkerd/app/integration/src/tcp.rs, linkerd/app/integration/src/tests/identity.rs, linkerd/app/integration/src/tests/transparency.rs, linkerd/app/test/src/lib.rs, linkerd/tracing/src/lib.rs
In stack tests, we set a fairly verbose `tracing` filter, since the logs
are captured by libtest and only printed if a test fails or when the
`--show-output` flag is passed. However, in integration tests, we
disable most tracing, because earlier versions of Rust did not support
output capturing for spawned threads, and the integration tests run the
proxy in a separate thread (see #771).
Now that we're on Rust 1.49, however, libtest now supports output
capturing for spawned threads, so this PR changes the integration tests
to enable more verbose logging. This should help with debugging test
failures.
I made a few other minor improvements to tracing in tests. In
particular:
* Share the *same* tracing subscriber between the test thread and the
test proxy. This should resolve the issue where …
=> integration: improve tracing in tests

linkerd/app/inbound/src/lib.rs, linkerd/proxy/http/src/server.rs
In order to set up for a TCP gateway implementation, this change
decouples HTTP protocol detection (and TCP fallback) from the HTTP
server stack.
In doing so, this change restructures the inbound builder helpers (and
renames them).
=> inbound: Separate HTTP server logic from protocol detection

linkerd/app/core/src/errors.rs
When the proxy hits a fail-fast error when proxying gRPC messages, it
reports 'max-concurrency exhausted' in the `grpc-message` response
header. This is because failfast was introduced to bound the time a
service may be at-concurrency; but now failfast is used everywhere a
request may be buffered to bound the time a request can stay in the
proxy: if a buffered service fails to become ready within a timeout, the
service goes into 'fail-fast' so that requests are failed eagerly until
the service is ready.
Recently, we've improved failfast errors to indicate which failfast is
being triggered. This change replaces the _max-concurrency exhausted_
`grpc-message` with this more-descriptive error message.
=> Correct gRPC 'max-concurrency exhausted' error messages

linkerd/timeout/src/failfast.rs
Failfast errors can be difficult to track down. This change updates the
failfast module to emit more descriptive log messages. A `WARN`-level
message is emitted when a service enters failfast.
=> failfast: Improve diagnostic logging

Dockerfile
This change updates the base docker image to use
ghcr.io/linkerd/proxy:edge-21.1.2. This removes a dependency on the old
gcr.io repository.
=> Update the base docker image

linkerd/stack/src/request_filter.rs, linkerd/stack/src/result.rs
`stack::ResultService` cannot implement `Clone` because it holds an
error type. This error is always coerced to `Error`, so its type is
unimportant.
This change wraps the service's error type in an `Arc` (instead of an
`Option`) so that `ResultService` can safely be cloned.
=> stack: Implement Clone for ResultService

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/server.rs, linkerd/app/src/env.rs
When a Service is in failfast, the inner service is only polled as new
requests are processed. This means it's theoretically possible for
certain service tasks to be starved.
This change ensures that these layers are paired with a `SpawnReady`
layer to ensure that the inner service is always driven to readiness.
This could potentially explain behavior as described in
linkerd/linkerd2#5183; though we don't have strong evidence to support
that. This seems like a healthy defensive measure, in any case.
This change also improves stack commentary to favor larger descriptive
comments over layer-level annotations.
While auditing services for readiness, an unnecessary buffer has been
removed from the ingress HTTP stack.
=> Ensure services in failfast can become ready

linkerd/app/integration/src/lib.rs, linkerd/app/integration/src/metrics.rs, linkerd/app/integration/src/tests/discovery.rs, linkerd/app/integration/src/tests/profiles.rs, linkerd/app/integration/src/tests/telemetry.rs, linkerd/app/integration/src/tests/transparency.rs
This branch changes the metrics integration tests so that we no longer
make assertions about metrics by searching the entire metrics scrape for
a specific string. Instead, we now have a simple builder API for
constructing a type that tries to parse the metrics scrape to find
individual metrics with certain label combinations and/or values.
Advantages of the new approach include:
- it's not ordering dependent --- changing the label ordering doesn't
change whether or not the match succeeds. for example, changes
like #856 won't break the tests.
- the presence of *additional* labels doesn't break the assertions
(although we may want to add an "exact" matching mode in case we
*do* want to assert that other labels are not present).
- metrics can easily be matched with and without values
- the …
=> tests: replace string matching on metrics with parsing

Cargo.lock, linkerd/app/inbound/src/lib.rs, linkerd/io/Cargo.toml, linkerd/io/src/either.rs, linkerd/io/src/lib.rs, linkerd/io/src/prefixed.rs, linkerd/tls/src/accept.rs
`tls::accept` has a `Detectable` trait which allows TLS detection to use
`TcpStream::peek`; but this is inflexible if we want to wrap `TcpStream`
with any additional behavior and it limits our ability to write tests
for this module.
This change introduces a new `io::Peek` trait to model
`TcpStream::peek` and removes the `tls::accept::Detectable` trait.
=> Decouple tls::accept from TcpStream

linkerd/app/core/src/transport/labels.rs
When the server terminates a TLS connection on which there is no client
ID (for instance, when the identity service gets a proxy's first
identity request), the `tls` label is not set to _true_.
This change explicitly handles this case, reporting an empty `client_id`
label.
=> metrics: Handle NoPeerIdFromRemote properly

linkerd/app/integration/src/client.rs, linkerd/app/integration/src/tests/telemetry.rs
Currently, the metrics tests have a bunch of code that's repeated
between tests in the inbound and outbound directions. This makes
modifying the tests much more painful, since the code needs to be
changed multiple times. Also, the file is hard to navigate.
This commit changes this by factoring out the shared code into functions
which are called by the differing code (e.g. metrics labels) as
parameters. This means that the common behavior is only defined once, so
it should be somewhat easier to edit. This has a significant advantage
over the approach we use elsewhere, where similar tests are generated by
macros: it doesn't mess up the compiler diagnostics for errors in the
tests. We may want to refactor other tests to use a similar style in the
future.
=> test: reduce repetition in metrics tests

Cargo.lock
This release reduces the cost of using `SpawnReady` by eliminating
unnecessary allocations.
=> Update to tower v0.4.4

linkerd/app/core/src/metrics.rs, linkerd/app/inbound/src/target.rs, linkerd/app/integration/src/metrics.rs, linkerd/app/integration/src/tests/telemetry.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/opaque_transport.rs
This branch builds on #861 and adds `target_addr` labels to HTTP metrics
as well as transport metrics. These labels contain a string
representation of the original destination address of the connection on
which that request was sent.
Additionally, I've made some more improvements to the metrics tests:
after the test code failed to catch a missing commma in labels, I
changed the metrics matching code to check that the metric is correctly
formatted, as well as containing the expected labels and values.
Furthermore, after rebasing onto `main` made some labels in tests added
in this PR incorrect, I modified the tests so that a majority of the
expected labels are defined in a single place by the text fuxtures,
since they don't actually differ between tests.
=> metrics: add `target_addr` labels to HTTP metrics

linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/prevent_loop.rs, linkerd/app/inbound/src/require_identity.rs
Currently, the inbound proxy handles direct connections--connections
where the original destination is the inbound proxy port--in two places.
TCP forwarding is handled distinctly from HTTP forwarding (for
gateways).
This change modifies the inbound proxy to dispatch these connections to
a dedicated `direct` stack that does its own protocol detection and
routing.
This sets up to (1) modify the server to configure ALPN on only these
connections and (2) support transport-header-based gateway routing.
=> inbound: Handle direct connections with a dedicated stack

linkerd/app/core/src/admin/mod.rs, linkerd/app/src/admin.rs, linkerd/app/src/lib.rs, linkerd/metrics/src/serve.rs, linkerd/tracing/src/level.rs, linkerd/tracing/src/lib.rs, linkerd/tracing/src/tasks.rs
This branch refactors the proxy admin endpoint to build a server stack
using the same primitives used for the proxy servers. This is intended
primarily to allow us to easily add metrics to the admin server by just
slotting in the existing proxy metrics layers.
This change also has some side benefits:
* We now reuse more existing code for building the admin server, rather
than writing separate versions of our accept & serve HTTP code
specifically for admin,
* We now support HTTP/2 for the admin server :)
=> admin: stackify admin server

linkerd/app/core/src/admin/mod.rs, linkerd/app/integration/src/client.rs, linkerd/app/integration/src/tests/telemetry.rs, linkerd/app/src/admin.rs, linkerd/app/src/lib.rs
This PR adds HTTP request/response, transport, and stack metrics for the
admin server to the proxy's inbound metrics. The `target_addr` labels
added in #861 and #866 disambiguate these metrics from other inbound
metrics.
I've also added new tests for admin server metrics.
Since the admin server serves a known set of HTTP paths, I'd like to add
per-path metrics to the admin metrics as well. We could do this by using
the existing service profiles code to add profile metrics to the admin
server with a hard-coded service profile. As this is probably a bigger
change, I'll work on this in a follow-up branch.
=> admin: add metrics

linkerd/app/outbound/Cargo.toml, linkerd/app/outbound/src/tcp/opaque_transport.rs
When running tests, we encounter panics like:
```
tcache_thread_shutdown(): unaligned tcache chunk detected
```
Disabling tracing-subscriber eliminates these panics. This change
disables the tracing subscriber for these tests until the underlying
issue is resolved.
=> test: Disable tracing-subscriber by default

linkerd/app/inbound/src/direct.rs, linkerd/app/inbound/src/http.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/target.rs
This change splits up the inbound stack as follows:
commit c32b5cc114325e5506eb0a6ea65c517658356cbd
inbound: Decouple HTTP server from router
This change moves the RequestTarget router from the http_server stack to
the http_router and direct stacks.
This sets up decoupling the target types for these stacks, as both
stacks should share HTTP server logic but may route requests
differently.
commit c739c29ed0f5ef0f6da01139c818e9d66591fca9
inbound: Extract stacks into a separate files
This change creates new inbound::http and inbound::direct modules that
handle stack constructions.
No functional change.
=> inbound: Split stack into modules

linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/lib.rs, linkerd/stack/src/switch_ready.rs
The `SpawnReady` module is used by the inbound stack to short-circuit
the profile stack when resolutions are not forthcoming (i.e. because the
destination service is unavailable).
This changes the module as follows:
- Logs about important state transitions are now emitted at DEBUG
instead of TRACE;
- The poll_ready function has been restructured for clarity,
including additional comments;
- When an error is encountered while waiting, the state transitions back
to primary. Errors are always terminal for `poll_ready`;
- The module's tests have been updated to use `time:pause`;
- The error-propagation test has been split into two tests because it's
not appropriate to continue polling the service after an error; and
- Finally, the inbound HTTP logical stack has been modified so that the
both …
=> Improve diagnostics around the SwitchReady module

linkerd/app/inbound/src/target.rs, linkerd/app/outbound/src/target.rs, linkerd/service-profiles/src/lib.rs, linkerd/service-profiles/src/split.rs
The profiles stack expects targets to satisfy `Param<Addr>`, which is
ambiguous. This change introduces a `profiles::LogicalAddr` type and updates
the target types to provide `Param<profiles::LogicalAddr>`.
=> profiles: Use a LogicalAddr param type

linkerd/app/src/lib.rs
When spot-checking proxy metrics, it's extraordinarily helpful to be
able to spot-check the proxy's build info by having it be the last line
in the metrics output. #787 introduced identity metrics, appending them
to the end of the report.
This change moves identity metrics to the start of the metrics dump so
that build_info remains the final metric emitted.
=> metrics: Report build_info metric last

linkerd/app/inbound/src/direct.rs, linkerd/app/inbound/src/http/mod.rs, linkerd/app/outbound/src/http/mod.rs
122d263d introduced session protocol hints to the transport header, but
the inbound direct stack was not updated to use this hint when deciding
whether to pass connections to the TCP gateway.
This change:
1. Updates the inbound direct stack to use the header-provided hint so
that, when set, HTTP detection can simply be skipped -- the value is
used to inform the HTTP server directly.
2. The outbound proxy could incorrectly set the protocol hint to the
original protocol, ignoring HTTP/2 upgrade hinting. This has been
fixed.
These changes have been tested against Linkerd2's multicluster
integration tests.
=> Use transport header protocol hint for HTTP gateway

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/server.rs, linkerd/proxy/http/src/normalize_uri.rs
Between stable-2.8.1 and v2.124.0, the inbound proxy changed so
that orig-proto requests would not be properly normalized,
breaking compatibility between 2.8.1 clients and recent servers.
This was fixed in 2a645b72 on main, but main includes many other
changes since v2.124.0. This change backports the important parts
of the change to v2.124.0 to ensure that inbound proxies normalize
downgraded requests.
Once merged, we'll tag `release/v2.124.1` off of the `release/v2.124`
branch and then wire that through for a stable-2.9.3 release.
=> Backport 2a645b72 to v2.124.0

.github/workflows/docker.yml, .github/workflows/release.yml, .github/workflows/rust.yml
GitHub is deprecating short shas in GitHub actions.
This change updates our actions to use full SHAs. It also updates
actions/checkout to v2.
=> actions: Update actions to use full SHAs

linkerd/app/inbound/src/http/mod.rs, linkerd/app/inbound/src/target.rs, linkerd/app/outbound/src/http/mod.rs, linkerd/proxy/http/src/normalize_uri.rs
The NormalizeUri module needs is configured with a fallback authority in
case we're dealing with poorly-formed HTTP requests (i.e., HTTP/1.0).
Currently, the module is parameterized on a `SocketAddr`, because on the
outbound side this makes sense as a default value. But on the inbound
side, especially in a gateway configuration, it doesn't make sense to
support a default value. It's better to just fail the request early.
This change updates the NormalizeUri type to require its targets to be
parameterized on a DefaultAuthority type. This type provides an
_optional_ `http::uri::Authority` so the target may provide a named
value (i.e., from a service profile response) when appropriate. It will
also enable us to omit a default when appropriate.
=> http: Parameterize normalize_uri::DefaultAuthority

linkerd/app/inbound/src/direct.rs, linkerd/app/inbound/src/http/mod.rs, linkerd/app/inbound/src/http/tests.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/target.rs, linkerd/app/outbound/src/http/mod.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/server.rs, linkerd/app/src/admin.rs, linkerd/proxy/http/src/server.rs
The HTTP server requires that targets are in the form `(Version, T)`.
This is inflexible, though.
This change updates the HTTP server to instead require that targets
satisfy `Param<Version>` so that tuple types are not required. This
requires the introduction of a new HttpAccept type in the inbound proxy.
=> http: Parameterize the HTTP server

linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/http/mod.rs, linkerd/app/inbound/src/target.rs, linkerd/proxy/http/src/insert.rs
The `http::insert` module provides a utility to insert the target value
into each request's HTTP extensions. But it's not always desirable to
insert the entire target. We may want only insert a single parameter
from the target.
This change replaces the `insert::target` module with an
`insert::NewInsert` type that uses `Param` to extract a value from the
target.
In doing this, I also noticed that 58c78596 changed the extension type
needed by tap::Inspect. This change fixes this and sets up further
improvements to use narrower-scoped param types so that this can't break
as easily moving forward.
=> Update http::Insert to use `Param`

Cargo.lock, deny.toml
* Picks up tokio v1.1.1 which fixes a potential memory leak tokio-rs/tokio#3477
* Updates `log` to remove an outdated dependency on `cfg-if`
---
```
:; cargo update
Updating git repository `https://github.com/linkerd/webpki`
Updating crates.io index
Updating git repository `https://github.com/linkerd/linkerd2-proxy-api`
Updating git repository `https://github.com/hawkw/tokio-trace`
Updating bumpalo v3.4.0 -> v3.6.0
Removing cfg-if v0.1.10
Updating data-encoding v2.3.1 -> v2.3.2
Updating flate2 v1.0.19 -> v1.0.20
Updating js-sys v0.3.46 -> v0.3.47
Updating libc v0.2.82 -> v0.2.84
Updating log v0.4.13 -> v0.4.14
Updating rand v0.8.2 -> v0.8.3
Updating serde v1.0.120 -> v1.0.123
Updating syn v1.0.58 -> v1.0.60
Updating thread_local v1.1.1 -> v1.1.2
Updating tinyvec v1.1.0 -> v1.1.1
Updating …
```
=> Update crate dependencies

linkerd/app/inbound/src/target.rs, linkerd/app/outbound/src/ingress.rs, linkerd/stack/src/router.rs
The `Router` service looks at each request to produce a routing key; but
it may not always be possible to satisfy a key for al requests. In these
cases, we currently need to encode the error case into the key type and
fail request on its inner stack. This is needlessly cumbersome.
This change modifies the `router::RecognizeRoute` trait to return a
`Result` so that requests can be failed eagerly by the router.
=> stack: Make the router fallible

Cargo.lock, linkerd/app/inbound/src/direct.rs, linkerd/app/inbound/src/http/mod.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/server.rs, linkerd/app/outbound/src/tcp/balance.rs, linkerd/app/outbound/src/tcp/tests.rs, linkerd/stack/metrics/Cargo.toml, linkerd/stack/metrics/src/service.rs
Our stack metrics are generally applied outside of failfast modules
so we have no insight into how long services are actually stuck in
pending.
This PR addresses this as follows:
1. The stack metrics `Service` impl no longer implements `Clone`. It
doesn't really make sense to track idleness across clones. Stacks
that require clone are no longer tracked by metrics.
2. `poll_total_ms` is now updated on each pending poll so that we need
not wait until a state change to update the value; and
3. All applicable uses of failfast have been updated to include stack
metrics. This gives us a better sense of the behavior of buffered
services.
=> Track stack metrics within failfast

linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/http/mod.rs, linkerd/app/outbound/src/http/tests.rs, linkerd/app/outbound/src/resolve.rs, linkerd/app/outbound/src/server.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/balance.rs, linkerd/app/outbound/src/tcp/opaque_transport.rs, linkerd/app/outbound/src/tcp/tests.rs
The outbound balancers are always built, even when there is no
resolveable concrete address.
This change modifies the outbound `Concrete` target to require a
resolveable address. When no address is present, the balancer stack is
skipped in favor of an endpoint stack.
=> outbound: Avoid building balancers when no concrete name

linkerd/addr/src/lib.rs, linkerd/app/gateway/src/config.rs, linkerd/app/gateway/src/gateway.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/gateway/src/make.rs, linkerd/app/inbound/src/direct.rs, linkerd/app/inbound/src/http/mod.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/require_identity.rs
When handling the HTTP gateway connections, the inbound proxy includes
the client's ID in the gateway's cache key so that a gateway service is
created for each (client, target) pair. Furthermore, the HTTP server
cache includes client _addresses_ in its key, so that a service is
cached for each _connection_ (which makes no sense).
In preparation for TCP gateway support, this change simplifies
inbound gateway handling by creating distinct target types used only by
the direct stack. Connections that lack identity or a target are failed
as early as possible, simplifying the gateway implementation. Client
identity is provided to gateway by setting the identity as a request
extension before the service is cached.
=> inbound: Cache HTTP gateways per destination

linkerd/proxy/http/src/detect.rs
1b97e57 changed HTTP detection to bias towards correctness. Instead of
performing a single read, the HTTP detection module reads data until a
newline is encountered so that a dispositive determination can be made.
Practically, this causes many non-HTTP protocols to fail with a
connection timeout because a newline is never transmitted.
This change reverts the HTTP detection logic to perform a single read
and to use that data to make a determination. A minimum of 14B is
required to handle a connection as HTTP.
=> Bias HTTP detection towards availability

linkerd/app/gateway/src/lib.rs, linkerd/app/inbound/src/direct.rs, linkerd/app/inbound/src/http/mod.rs, linkerd/app/inbound/src/http/tests.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/test_util.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/lib.rs
18e568a changed how outbound stacks are built--replacing free functions
with an `Outbound` builder type.
This change applies this pattern to the inbound proxy, reducing
boilerplate.
=> Simplify inbound stack composition

Cargo.lock
Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0020
hyper's HTTP server code had a flaw that incorrectly understands some requests
with multiple transfer-encoding headers to have a chunked payload, when it
should have been rejected as illegal. This combined with an upstream HTTP proxy
that understands the request payload boundary differently can result in
"request smuggling" or "desync attacks".
=> Update Hyper for  RUSTSEC-2021-0020

Cargo.lock, hyper-balance/Cargo.toml, linkerd/app/gateway/Cargo.toml, linkerd/app/integration/Cargo.toml, linkerd/app/test/Cargo.toml, linkerd/buffer/Cargo.toml, linkerd/cache/Cargo.toml, linkerd/concurrency-limit/Cargo.toml, linkerd/drain/Cargo.toml, linkerd/error-metrics/Cargo.toml, linkerd/error-respond/Cargo.toml, linkerd/http-classify/Cargo.toml, linkerd/opencensus/Cargo.toml, linkerd/proxy/api-resolve/Cargo.toml, linkerd/proxy/core/Cargo.toml, linkerd/proxy/discover/Cargo.toml, linkerd/proxy/http/Cargo.toml, linkerd/proxy/tap/Cargo.toml, linkerd/proxy/tcp/Cargo.toml, linkerd/reconnect/Cargo.toml, linkerd/retry/Cargo.toml, linkerd/stack/metrics/Cargo.toml, linkerd/tls/Cargo.toml, linkerd/trace-context/Cargo.toml
The recently released v0.4.5 of Tower includes a change to
`tower::buffer` to use `tokio-util`'s `PollSemaphore`, which should
reduce allocations when polling `Buffer` services. Additionally, it
includes a fix for `tracing` spans not being propagated to the tasks
spawned by the `SpawnReady` middleware.
=> update Tower to v0.4.5

Cargo.lock, linkerd/channel/Cargo.toml, linkerd/channel/src/lib.rs
The `linkerd-channel` crate currently uses a custom wrapper around
`tokio::sync::Semaphore` to permit polling the semaphore manually, by
boxing the futures returned by `Semaphore::acquire_owned`. This means
that every time a message is sent to the channel, reserving capacity
requires allocating and deallocating a `Box`.
The `tokio-util` crate now has a `PollSemaphore` type which allows
polling the semaphore to acquire permits without requiring an allocation
per message. This is implemented using the `ReusableBoxFuture` type, which
allows using a single allocation per sender for every `acquire_owned`
future that sender creates.
This should be somewhat more efficient and also reduces the complexity
of our code a bit.
=> channel: use `tokio-util`'s `PollSemaphore`

.github/workflows/rust.yml, Cargo.lock, linkerd/app/core/Cargo.toml, linkerd/app/core/src/control.rs, linkerd/dns/src/lib.rs
The `dns` module currently swallows resolution errors so that these
errors never hit the error handler.
This change modifies the `dns` module to propagate these errors so they
are handled by the resolver recovery module. The control plane's
recovery implementation is updated to log these errors and to use the
DNS TTL for backoffs, when present.
We now see errors like:
WARN ThreadId(01) identity: linkerd_app_core::control: Failed to resolve control-plane component error=no record found for name: linkerd-identity-headless.linkerd.svc.cluster.local. type: SRV class: IN
=> Log warnings when controller components do not resolve

linkerd/app/core/src/control.rs, linkerd/app/core/src/metrics.rs, linkerd/app/core/src/svc.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/inbound/src/direct.rs, linkerd/app/inbound/src/http/mod.rs, linkerd/app/inbound/src/http/tests.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/target.rs, linkerd/app/outbound/src/http/mod.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/connect.rs, linkerd/app/outbound/src/tcp/mod.rs, linkerd/app/outbound/src/tcp/opaque_transport.rs, linkerd/app/test/src/connect.rs, linkerd/app/test/src/http_util.rs, linkerd/app/test/src/resolver.rs
This is a purely superificial change that shortens a very common import.
=> Re-export stack::Param as svc::Param

Cargo.lock, linkerd/proxy/transport/Cargo.toml, linkerd/proxy/transport/src/listen.rs, linkerd/tls/tests/tls_accept.rs
The TCP listener creates an async-stream of accepted connections; but
the tokio-stream crate provides a stream utilitity for TCP listeners.
This change swaps the implementation of BindTcp. The tokio-stream
implementation should be lighter-weight to compile; and this sets up for
refactoring the listener so that TCP binding is not required for tests.
=> transport: Replace async-stream with tokio-stream

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/test_util.rs, linkerd/app/src/env.rs, linkerd/app/src/lib.rs
The inbound and outbound proxy stacks & servers are constructed in the
`app` module. This change moves all inbound & outbound server
initialization into the `inbound` and `outbound` modules.
This simplifies `app` initialization and removes redundant server address
logging.
=> Move proxy stack initialization into modules

Cargo.lock, deny.toml, linkerd/proxy/core/Cargo.toml
This PR updates the dependency on `tracing-futures` to 0.2.5, which
updates that crate to depend on `pin-project` 1.0. After removing one
last `pin-project` 0.4 dependency, we can now remove `pin-project` from
the duplicate dependency versions allowlist!
=> update tracing-futures, rm old pin-project

linkerd/app/core/src/config.rs, linkerd/app/core/src/control.rs, linkerd/app/core/src/serve.rs, linkerd/app/inbound/src/direct.rs, linkerd/app/inbound/src/http/tests.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/target.rs, linkerd/app/inbound/src/test_util.rs, linkerd/app/outbound/src/http/tests.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/tests.rs, linkerd/app/outbound/src/test_util.rs, linkerd/app/src/env.rs, linkerd/app/test/src/connect.rs, linkerd/proxy/transport/src/addrs.rs, linkerd/proxy/transport/src/connect.rs, linkerd/proxy/transport/src/lib.rs, linkerd/proxy/transport/src/listen.rs, linkerd/tls/tests/tls_accept.rs
Throughout the codebase, we handle many types of `SocketAddr`s. It's
easy to use these instances in an incorrect context.
In preparation for upcoming changes to listen module and target types,
this change introduces a family of new-types to disambiguate these uses:
- `ClientAddr`  -- a client's (ephemeral) address
- `ServerAddr`  -- a server's address
- `OrigDstAddr` -- an address set by the `SO_ORIGINAL_DST` socket option
Additionally, `Local` and `Remote` address types are introduced to
further disambiguate the above types:
- `Remote<ClientAddr>` -- a server connection's peer address
- `Local<ServerAddr>`  -- a server connection's local address
- `Remote<ServerAddr>` -- a client connection's peer address
- `Local<ClientAddr>`  -- a client connection's local address
A special …
=> transport: Introduce address new-types

linkerd/app/core/src/config.rs, linkerd/app/inbound/src/test_util.rs, linkerd/app/outbound/src/test_util.rs, linkerd/app/src/env.rs, linkerd/proxy/transport/src/connect.rs, linkerd/proxy/transport/src/lib.rs, linkerd/proxy/transport/src/listen.rs, linkerd/tls/tests/tls_accept.rs
When handling `Duration` values, it can be ambiguous as to the value's
intended use.
This change introduces a `Keepalive` new-type that wraps an optional
`Duration`. This will allow keepalive values to be parameterized without
ambiguity (in future changes).
=> transport: Introduce a Keepalive type

linkerd/app/Cargo.toml, linkerd/app/integration/Cargo.toml, linkerd/app/outbound/Cargo.toml, linkerd/app/outbound/src/tcp/connect.rs
linkerd/linkerd2#5764 reports proxy OOMs, apparently caused by traffic
looping from the outbound proxy back to the inbound proxy. While we
don't understand the underlying circumstances, we should *never* proxy
outbound connections on the loopback interface in normal operation.
This change modifies the outbound TCP connection stack to prevent
connections on loopback addresses. A feature flag, `allow-loopback`, is
provided to disable this functionality. This is necessary so that our
local integration tests can continue to pass.
=> outbound: Prevent connections on the loopback interface

linkerd/signal/src/lib.rs
Currently, The proxy builds fail on windows because of the absence
of `future::preludes`. That does not seem to be required anymore
and the windows ctrl_c signal can be used similar with that of
the unix signals.
This PR updates the `shutdown` fn in imp for windows to be just
like the unix ones. I'm aware that the proxy is not intended to be ran
on windows machines but this was a easy fix to make builds work.
Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>
=> make proxy builds work on windows

linkerd/identity/src/lib.rs
TLS 1.3 has been available in rustls for a while now, giving us some
confidence that it's stable.
This change adds TLS 1.3 to the list of supported TLS versions. With
this change, proxies will prefer TLS 1.3 when both peers include this
change and will downgrade to TLS 1.2 when communicating with an older
proxy version.
I've tested that this behaves as expected by upgrading just the
emojivoto app's _web_ and _voting_ services with debug logging. Older
proxies communicate with newer proxies via TLS 1.2 and newer proxies
communicate via TLS 1.3.
=> Add support for TLS v1.3

Cargo.lock, linkerd/app/inbound/Cargo.toml, linkerd/app/outbound/Cargo.toml, linkerd/app/test/Cargo.toml, linkerd/cache/Cargo.toml, linkerd/proxy/http/Cargo.toml, linkerd/stack/Cargo.toml, linkerd/tls/Cargo.toml
This picks up tokio-rs/tracing#1247, tokio-rs/tracing#1248,
tokio-rs/tracing#1251, and tokio-rs/tracing#1254. Collectively, these
changes should result in a significant performance improvement when
using `tracing-log`'s compatibility layer for converting legacy `log`
records to `tracing` events.
Since we have some dependencies which use the `log` crate, this should
hopefully reduce the overhead of those dependencies' logging. I'm not
sure how much `log` we have in the hot path by this point, but it's
probably a good idea to pick up the change regardless.
=> deps: update `tracing-subscriber` to 0.2.16

linkerd/tracing/Cargo.toml, linkerd/tracing/src/lib.rs
In order to ensure that disabled `log` records are skipped by taking the
fastest path the `log` crate offers whenever possible, we should set the
`log` max level every time the `tracing` filter is reloaded.
This branch changes the proxy to...do that.
I'll also add this in the reloading stuff upstream, but I wanted to get it 
working in the proxy first, before doing another `tracing-subscriber`
release.
=> trace: set `log` global max level when reloading

linkerd/app/gateway/src/lib.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/target.rs, linkerd/app/outbound/src/http/detect.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/src/admin.rs, linkerd/detect/src/lib.rs, linkerd/proxy/http/src/detect.rs
In 95498395, the detect service was modified to handle detect timeouts
gracefully; but, we can't differentiate this situration from other
detection mismatches.
In order to use the detect trait more generally--especially for TLS
detection, this change modifies the `Detect` trait to pass an error into
the inner stack when detection fails. Uses are updated to either fail on
or log when an error is countered, as appropriate. This will be relied
on in followup changes.
Furthermore, the `Detect` trait's I/O type is moved to be a
trait-generic (rather than a method-generic) so that implementations may
impose further type constraints.
=> detect: Surface timeouts to inner stack

linkerd/app/integration/src/tests/telemetry.rs, linkerd/proxy/transport/src/metrics.rs
The TCP connection histogram is pretty useless in its current form: its
granularity in milliseconds is generally unsuited to long-lived
connections; and it ends up being extremely high cardinality.  And on
top of all that, the value isn't currently consumed in our UIs.
This change removes the `tcp_connection_duration_ms` histogram from the
proxy.
Relates to linkerd/linkerd2#5818
=> Remove the tcp_connection_duration_ms histogram

linkerd/app/core/src/serve.rs
Per linkerd/linkerd2#5331, it seems that "Connection closed" log
messages, which in many cases are compltely innocuous, cause concern
when people see them in production.
This change moves these messages from the INFO to DEBUG log level so
that they are only observed when explicilty configured.
=> server: Log connection closed messages at DEBUG

linkerd/app/core/src/serve.rs
8c87c5de updated the server to log errors at DEBUG; but this will hide
proxy-generated errors like detection timeouts.
This change logs all i/o errors at DEBUG and restores other errors to
the INFO level.
=> server: Log non-i/o errors at INFO

linkerd/app/outbound/src/lib.rs
In ingress mode, the HTTP endpoint stack is not configured with the TCP
endpoint layers, so outbound connections are not properly tracked in
metrics.
This change restores this functionality.
=> ingress: Instrument outbound TCP metrics

linkerd/app/inbound/src/lib.rs
The inbound proxy caches each HTTP server stack, but this stack's cache
key includes client address information, so this cache ends up requiring
an entry per connection and stacks are not reused.
This change removes this unnecessary cache.
=> inbound: Remove unnecessary connection stack cache

linkerd/app/outbound/src/http/mod.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/opaque_transport.rs
The outbound proxy's `Endpoint` target-type is currently coupled with
the `Logical` type and it contains two `SocketAddr` values that are
undifferentiated.
This change updates the `Endpoint` type to be decoupled from the
`Logical` type and to hold a single `addr` value.
=> outbound: Simplify Endpoint type

linkerd/app/gateway/src/gateway.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/outbound/src/discover.rs, linkerd/app/outbound/src/http/mod.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/mod.rs, linkerd/app/outbound/src/tcp/opaque_transport.rs, linkerd/app/outbound/src/tcp/tests.rs
The outbound stack is ambiguous about the type of orig_dst/target
address it uses.
This change modifies the outbound stack types to use the `OrigDstAddr`
type. The outbound stacks now error when an `OrigDstAddr` type is not
present.
=> outbound: Use the OrigDstAddr type in stack targets

linkerd/app/gateway/src/lib.rs, linkerd/app/integration/src/tests/telemetry.rs, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/http/tests.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/resolve.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/connect.rs, linkerd/app/outbound/src/tcp/logical.rs, linkerd/app/outbound/src/tcp/tests.rs, linkerd/app/test/src/profile.rs
The endpoint resolver module currently has a fixed dependency on the
`Concrete` and `Endpoint` target types.
This change extracts endpoint-type construction so that the HTTP logical
stack is agnostic of its endpoint target type. It also updates the
`EndpointFromMetadata` type to be responsible for marking identity as
disabled when appropriate. Finally, we are able to re-enable the
outbound TLS hinting test.
=> outbound: Decouple the resolver from concrete target types

linkerd/app/core/src/errors.rs
Currently, the proxy tears down connections on unhandled errors, unless
those errors are timeouts. We special-case errors which are timeouts and
don't close connection in those cases.  However, this can result in
connections failing to be torn down when the host is unreachable. If the
proxy continues trying to reconnect after a connection error, the
connection error won't be what makes it to the errors layer --- instead,
the request will eventually time out while reconnecting. This gets the
request 503ed, but the connection remains open --- which, when a client
is trying to talk to a stale endpoint, results in the connection
entering a stuck state.
This branch fixes this by removing the special-case logic for timeouts,
and always tearing down connections. I validated this change using the …
=> errors: always teardown connections on errors

linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/http/mod.rs, linkerd/proxy/http/src/header_from_target.rs, linkerd/proxy/http/src/lib.rs
The module responsible for adding HTTP headers from target types expects
the target to be coerced to a `HeaderValue`. This means that a target
can only instrument a single header; and it creates some ambiguity.
This change updates the header insertion module to use a Param-type to
represent a key-value header pair, making uses clearer.
=> http: Parameterize header module

linkerd/duplex/src/lib.rs, linkerd/proxy/http/src/upgrade.rs
The `linkerd_duplex` crate emits trace events for every read and write
operation performed, but these events don't make it clear which peer
performed the read or write. This branch adds names to the trace event
to make it possible to determine whether a read/write was performed by
the source or destination peer.
This does make the `Duplex` struct two words larger. Not sure if we
care. It might theoretically be possible to encode this using type
parameters to avoid the `&'static str`s; I'm not sure if this is worth
adding some wacky code to avoid two words of string constant pointer.
=> duplex: include src/dst peer in logs

Cargo.lock, linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/http/mod.rs, linkerd/app/outbound/src/tcp/logical.rs, linkerd/stack/tracing/Cargo.toml, linkerd/stack/tracing/src/lib.rs
The stack-tracing module eagerly initiates its spans once per service;
but when the service is cached, this locks the service to its original
parent span so that log messages from subsequent accessors appear to
have the wrong parent span information.
This change modifies the stack tracing helper to (1) be
NewService-specific and (2) to initiate unique spans for each call. The
instrumented `Service` constructs a new span the first time `poll_ready`
is called, and consumes that span in `call`, so the `poll_ready`s that
drive a service to readiness and the subsequent `call` that consumes
that readiness are both considered one individual span for that request.
=> Make stack trace initialization lazy

linkerd/app/outbound/src/ingress.rs, linkerd/proxy/http/src/lib.rs
The ingress-mode outbound proxy currently does not work as expected:
resolutions are performed for each unique endpoint so that a service
with 10 endpoints would manifest as 10 distinct balancers (with 20
resolutions).
While we should ultimately rework the outbound stack to have target
types that prevent this problem (i.e. by removing the original
destination address from the Logical target type), this change
implements a hack to avoid the observed cardinality issues: In
ingress-mode, the original destination address is now mocked out with an
IP address of 0.0.0.0 so that only a single cache entry is created per
logical destination.
=> outbound: Mock the original destination address in ingress-mode

linkerd/app/core/src/serve.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/src/admin.rs, linkerd/app/src/lib.rs, linkerd/app/src/tap.rs
The TCP server currently returns an error if an `accept(2)` call fails
with an error. This error can cause the proxy to panic.
This change handles this error gracefully, emitting a warning. The
server task no longer returns a Result-type.
=> Prevent server errors from panicking the proxy

linkerd/duplex/src/lib.rs
In testing Postgres dumps through Linkerd, we see some situations where
data is written to rustls but does not become visible to the client.
Rustls documents that written data may need to be flushed.
This change updates the `HalfDuplex::copy_into` function to flush data
when all available data has been read. This change also increases the
copy buffer from 4KB to 64KB to reduce processing overhead.
---
Relates to linkerd/linkerd2#5539
Image available at `ghcr.io/olix0r/l2-proxy:flush.863b537b`
=> duplex: Ensure written data is flushed

linkerd/proxy/dns-resolve/src/lib.rs
When a controller client is configured with a fixed IP address and not a
resolveable name, we build that client with a resolution that terminates
immediately after the client is configured with the fixed address. This
causes warnings to be emmited even though the client is configured
properly.
This change updates theses resolutions to avoid termination so these
warnings are not logged.
=> Prevent fixed-address resolutions from ending

linkerd/app/outbound/src/http/mod.rs, linkerd/proxy/http/src/lib.rs, linkerd/proxy/http/src/override_authority.rs
The authority override module still uses a dedicated trait,
`CanOverrideAuthority`. This change replaces this trait with a newtype,
`AuthorityOverride`, which is provided via `Param`.
=> http: Parameterize authority overriding

linkerd/app/core/src/errors.rs, linkerd/app/core/src/serve.rs, linkerd/app/inbound/src/direct.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/inbound/src/prevent_loop.rs, linkerd/app/outbound/src/discover.rs, linkerd/app/outbound/src/ingress.rs
Our default TCP server sets an info-level tracing span that includes the
client IP and port. This client-level metadata is potentially
high-cardinality, it's not helpful on the outbound side, and it is only
rendered in rare situations.
This change modifies the server to set its `accept` span on the debug
level. The inbound and outbound proxies handle setting info-level spans
with the relevant metadata -- the inbound proxy includes only a server
port, and the outbound includes the original dst address. The error
responder has been modified to include the client address in warning
messages so that it need not be derived from span metadata.
=> tracing: Avoid high-cardinality client in INFO spans

linkerd/app/core/src/lib.rs
The control plane may return a FailedPrecondition error when the cluster
is in an unexpected state -- when there are more than one pod for a
single IP address. The proxy currently retries these lookups ad nauseum.
This change updates the proxies error handling to avoid retries when
this error is returned.
=> Handle FailedPrecondition errors from the control plane

linkerd/app/gateway/src/lib.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/http/tests.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/logical.rs, linkerd/app/outbound/src/tcp/tests.rs
ebf67d6b moved endpoint construction logic out of the logical stacks. This
created more boilerplate than hoped. Realistically, the logical stack needs to
be responsible for its inner target types.
This change moves endpoint construction into each logical stack so that
it need not be configured on each instantiation, simplifying resolver type
constraints.
=> outbound: Configure endpoint construction in logical stack

linkerd/app/gateway/src/lib.rs, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/mod.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/connect.rs, linkerd/app/outbound/src/tcp/mod.rs, linkerd/app/outbound/src/tcp/opaque_transport.rs
In order to make the server and logical stack more flexible, we need to
make stacks generic over their input target type.
This change modifies the innermost `tcp::connect` stack to not depend on
a concrete target type, instead relying on `Param` constraints. A new
`tcp::Connect` target type is introduced to be constructed by the TCP
connect stack.
=> outbound: Decouple the TCP connect stack from the target type

linkerd/tls/src/server/mod.rs
When the proxy performs inbound TLS detection, it may break TLS streams
for application-terminated TLS connections.
Typically, inbound TLS detection does not actually need to buffer data
from the socket to determine the SNI value for a connection. However,
non-proxy clients may send enough ClientHello extensions such that
detection cannot be completed from a single peek of 512B. In this
situation, the proxy buffers data from the socket to determine the
SNI value, but it unfortunately does not preserve this buffered data as
it forward the connection.
This change updates the TLS detection logic to properly preserve any
data buffered from the socket in forwarded connections.
=> tls: Fix inbound I/O when TLS detection fails

linkerd/app/src/admin.rs
The HTTP detect module may fail to detect an HTTP protocol if the first
read does not return at least 14 bytes. This has caused spurious
failures as described in linkerd/linkerd2#5672.
This change updates the admin server's protocol detection to handle
these connections as HTTP/1 so that the HTTP server can try to process
them and fail on its own if the connection really is not HTTP.
=> admin: Handle connections that fail protocol detection

linkerd/app/gateway/src/gateway.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/outbound/src/http/mod.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/tests.rs
When the proxy is in `ingress` mode, requests with different `l5d-dst-override` headers but the same address share the same key in the cache. This causes consecutive requests to the same address to all go to the value of the first `l5d-dst-override` header, ignoring the header values of later requests—unless the services are evicted from the cache.
This occurs because each key into the cache is calculated based off `LogicalAddr`'s `orig_dst` and `protocol` fields ([source](https://github.com/linkerd/linkerd2-proxy/blob/main/linkerd/app/outbound/src/target.rs#L115-L120)). When the proxy is in `ingress` mode, the value of `orig_dst` is overridden to `0.0.0.0:port` ([source](https://github.com/linkerd/linkerd2-proxy/blob/main/linkerd/app/outbound/src/ingress.rs#L180-L185)). This results in …
=> Fix caching in ingress mode

Cargo.lock, linkerd/proxy/discover/Cargo.toml, linkerd/proxy/discover/src/buffer.rs
This commit replaces the use of `linkerd-channel`'s pollable MPSC in the
`linkerd_discover` crate's `buffer` module with `tokio-util`'s
[`sync::PollSender`][1] type, which also implements a pollable sender.
The `PollSender` type is likely more efficient than our channel
implementation, since it uses the [`ReusableBoxFuture`][2] type from
`tokio-util`, which avoids allocating a `Box` for _every_ message sent
to the channel, and instead reuses a single allocation. It also wraps
the `tokio::sync::mpsc` `Sender`, rather than reimplementing the
capacity limit on top of the `UnboundedSender` type. This reduces
complexity and should hopefully be less error-prone.
[1]: https://docs.rs/tokio-util/0.6.5/tokio_util/sync/struct.PollSender.html
[2]: …
=> discover: replace `linkerd-channel` with `tokio-util` `PollSender`

Cargo.lock, linkerd/concurrency-limit/Cargo.toml, linkerd/concurrency-limit/src/lib.rs
Currently, our concurrency limit middleware uses
`tokio::sync::Semaphore` to implement the concurrency limit. Because
acquiring permits from the `Semaphore` type is only possible via the
`acquire` and `acquire_owned` methods, which are `async fn`s returning
unameable futures that are `!Unpin`, we cannot simply poll the semaphore
in `poll_ready`. Instead, to allow polling the concurrency limit service
to acquire a permit, we box the `acquire_owned` future in `poll_ready`.
This means that every time we try to acquire a new concurrency limit
permit, we must allocate a new box.
The `tokio-util` crate has a [`PollSemaphore`][1] type which allows
wrapping a `tokio::sync::Semaphore` to add a `poll_acquire` method to
poll the semaphore to acquire a permit. Unlike our implementation, …
=> concurrency-limit: use `tokio-util`'s `PollSemaphore`

linkerd/proxy/http/fuzz/.gitignore, linkerd/proxy/http/src/detect.rs
The HTTP detection fuzzer fails if all data is not read from the socket;
but there is no expectation that the `DetectHttp` will read all data
from the socket--it only reads to the point where it can make a
determination about whether the stream appears to be HTTP; and it may
leave unread data on the socket.
This change replaces the use of a mocked I/O type with a duplex stream
so that leftover data does not cause a test failure.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33130
=> http: Do not fail fuzz tests when all IO is not read

linkerd/proxy/transport/src/orig_dst.rs
fix signature mismatching which causes compiling failure for non-linux target
=> compile: fix signature mismatching which causes compiling failure for non-linux target

Cargo.lock, Cargo.toml, deny.toml, linkerd/dns/fuzz/Cargo.toml
Our fuzz tests trigger a panic in trust-dns when resolving names through
the search path (i.e., in `/etc/hosts`) as described in
bluejekyll/trust-dns#1447.
This change patches our trust-dns dependencies to use include
bluejekyll/trust-dns@6dfc671 (which has not yet been released to
crates.io)
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33123
=> Update trust-dns to fix possible panic

linkerd/addr/src/lib.rs
Currently, the `Addr::to_http_authority` method panics when called on a
`SocketAddr` which is an IPv6 address with port 80. This method does not
panic when called with IPv4 addresses, or with IPv6 addresses whose
ports are *not* port 80. This was initially caught by oss-fuzz; see
[here][1] for details.
The panic occurs because when an IPv6+ address occurs in an authority,
it must be within square brackets, as per [RFC3986, Section 3.2][2]. The
square brackets distinguish between colons in the IPv6 address and the
colon separating the address and port. When the `SocketAddr`'s port is
not port 80, we format it including the port, and the `fmt::Display`
output from IPv6 `SocketAddr`s includes the square brackets as expected.
However, when the socket's port *is* port 80, we have special logic …
=>  addr: fix `to_http_authority` panic with IPv6

linkerd/app/gateway/src/gateway.rs, linkerd/app/gateway/src/lib.rs, linkerd/app/outbound/src/discover.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/http/detect.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/http/mod.rs, linkerd/app/outbound/src/http/tests.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/lib.rs, linkerd/app/outbound/src/logical.rs, linkerd/app/outbound/src/target.rs, linkerd/app/outbound/src/tcp/tests.rs, linkerd/app/test/src/service.rs
Currently, the outbound proxy's `Logical` target type contains an
`Option<profiles::Receiver>`. When no profile is discovered, this field
is set to `None`; the per-profile layers in the logical stack do nothing
when this field is `None`. However, we still *construct* this whole
stack for all destinations, even those without logical addresses.
This PR refactors the outbound proxy so that the `Logical` targets
*always* have discovered profiles, and the logical stack is skipped when
no profile is discovered. Profile discovery still returns an
`Option<profiles::Receiver>`, but we unwrap it in one place immediately
after the profile discovery layer, and skip directly to the endpoint
stack when it is `None`.
This means that we can now avoid constructing layers like traffic split
etc when there …
=> outbound: skip logical stacks when no profile is discovered

linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/tcp/logical.rs, linkerd/service-profiles/src/split.rs
This branch builds on #963 by changing the traffic split service to
require its target type implement `Param<profiles::Receiver>` rather
than requiring `Param<Option<profiles::Receiver>>`. This lets us
simplify the implementation significantly by removing the "default" case
that's built when no profile was discovered.
Depends on #963
=> split: change traffic splits to require a profile

linkerd/app/inbound/src/http/mod.rs, linkerd/app/inbound/src/target.rs
This is similar to PR #963 but on the inbound side. Since the inbound
proxy only requires logical targets in the HTTP profile route layers,
this change is much simpler --- protocol detection etc are all above the
profile resolution layer. We can simply add an `UnwrapOr` layer that
skips the profile route layers.
This change is much less important than the corresponding outbound
change, but the two changes together will permit us to simplify the
profile route layer by taking a `Param<profiles::Receiver>` rather than
a `Param<Option<profiles::Receiver>>`.
This does also require adding an additional `BoxResponse` layer to erase
differing response body types based on whether or not profile route
metrics are recorded.
=> inbound: only build profile route stacks when a profile is resolved

linkerd/app/inbound/src/target.rs, linkerd/app/outbound/src/target.rs, linkerd/service-profiles/src/http/route_request.rs
This branch changes the `linkerd_service_profiles::http::route_request`
layer to require a `Param<profiles::Receiver>` rather than a
`Param<Option<profiles::Receiver>>` target type. This is possible
because the inbound and outbound logical destination stacks are now only
built when a profile is resolved (as of PRs #963 and #966).
Depends on #964
Depends on #966
=> profiles: make receiver param in `route_request` non-optional 

linkerd/app/src/admin.rs
fce8c4ae updated the admin server to try to handle connections that fail
HTTP detection. The intent of this was to handle connections that
don't emit any HTTP request within the first few seconds of the
connection. However, we also try to handle connections on which we have
read data and affirmatively indicated that the connection is not HTTP.
These connections manifest with errors about an invalid HTTP method,
which can be ambiguous to users.
This change handles this latter case explicitly with an error that
describes the client so that users have better diagnostics without
having to enable debug logging.
=> admin: Fail connections when HTTP detection fails

Cargo.lock, linkerd/app/inbound/Cargo.toml, linkerd/app/inbound/fuzz/fuzz_targets/fuzz_target_1.rs, linkerd/app/inbound/src/http/mod.rs, linkerd/transport-header/Cargo.toml, linkerd/transport-header/fuzz/fuzz_targets/fuzz_target_raw.rs, linkerd/transport-header/fuzz/fuzz_targets/fuzz_target_structured.rs, linkerd/transport-header/src/lib.rs
This PR is an effort to generalise the inbound fuzzer by allowing it to sending an arbitrary number of random packets. 
This PR also moves the structs used by the structure-aware to be defined outside the fuzz_*.rs files. This solves the coverage compilation problems we currently have - as such, following this PR we will be able to get nice coverage reports shown by OSS-Fuzz.
Signed-off-by: davkor <david@adalogics.com>
=> app: inbound: fuzzer: generalise fuzzers and solve coverage build

linkerd/app/src/admin.rs
We've recently updated the admin server to assume that protocol
detection timeouts indicate that the client was just HTTP/1; but this
will almost never be true for meshed connections, which are transported
over HTTP/2.
This change updates the fallback logic to account for this. Detection
timeouts on meshed connections are now assumed to be HTTP/2. When we get
TLS connections that we can't terminate, we now return an error message
that includes the SNI value to more clearly indicate that the client
expected an alternate server identity.
=> admin: Assume meshed connections are HTTP/2

Cargo.lock, linkerd/app/inbound/fuzz/Cargo.lock, linkerd/app/inbound/src/http/mod.rs, linkerd/app/inbound/src/http/tests.rs, linkerd/app/integration/src/client.rs, linkerd/app/integration/src/tests/transparency.rs, linkerd/app/outbound/src/http/tests.rs, linkerd/app/test/Cargo.toml, linkerd/app/test/src/http_util.rs, linkerd/app/test/src/lib.rs
Currently, the inbound HTTP fuzz tests are failing when the fuzzer
generates invalid HTTP headers and the proxy rejects the request by
closing the connection:
<details>
<summary>Failing fuzz test logs:</summary>
```
Apr 26 10:06:12.697  INFO fuzz_target_1: running with input requests=[HttpRequestSpec { http_method: false, uri: "ookm$o", header_name: "o\"mooookm$o", header_value: " " }, HttpRequestSpec { http_method: false, uri: "o", header_name: "o", header_value: "" }]
Apr 26 10:06:12.701 DEBUG linkerd_proxy_http::server: Creating HTTP service version=Http1
Apr 26 10:06:12.701  INFO linkerd_app_test::http_util: connecting client with settings=Builder { exec: Exec, h09_responses: false, h1_title_case_headers: false, h1_read_buf_exact_size: None, h1_max_buf_size: None, h2_builder: Config { …
```
=> fuzz: allow client requests to fail 

linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/tcp/opaque_transport.rs
The `outbound::Endpoint::logical_addr` field must currently _always_ be
set, even when it just duplicates the endpoint's target address and
there is no "logical" address.
This change makes this field optional and changes its type to require a
`LogicalAddr` (as returned by a profile lookup).
As a result of this, the `authority` endpoint metrics label is now only
set when a logical address is present.
=> outbound: Make the Endpoint::logical_addr field optional

linkerd/app/test/Cargo.toml, linkerd/tracing/Cargo.toml, linkerd/tracing/src/lib.rs
Currently, the use of ANSI terminal color codes by `tracing-subscriber`
is controlled by a feature flag, which is only eenabled by
`dev-dependencies` when building tests. However, despite this, the
feature flag appears to still be enabled in release builds --- despite
`cargo tree -e features -e no-dev -i tracing-subscriber` indicating that
it isn't enabled by any non-dev dependency.
Since this results in mangled logs in Kubernetes (fluentd doesn't handle
ANSI escape codes), this branch changes the proxy's tracing setup to
explicitly disable them outside of tests.
=> trace: explicitly disable ANSI terminal colors

linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/lib.rs, linkerd/tls/src/client.rs
The ingress-mode proxy has some simplistic support for TCP forwarding;
but this is somewhat of a misfeature. Specifically, we don't do any
mTLS/discovery for these connections, so detection failures can manifest
as unexpected insecure connections.
For now, we should remove TCP-forwarding support from ingress-mode
proxies. This will help support further simplifications to the
ingress-mode proxy.
=> outbound: Do not support TCP-forwarding in ingress-mode

linkerd/app/inbound/src/http/tests.rs, linkerd/app/outbound/src/http/tests.rs, linkerd/app/outbound/src/tcp/tests.rs, linkerd/app/test/src/connect.rs, linkerd/app/test/src/http_util.rs, linkerd/app/test/src/lib.rs, linkerd/io/src/lib.rs
The tcp endpoint stack requires that connectors return `io::Result`, but
the connector mock uses Boxed error types. This change modifies the
mocked connector to use io::Errors.
We also improve re-exports from the linkerd_io module to reduce import
boilerplate.
=> tests: Use io::Error in mocked connector

linkerd/app/gateway/src/lib.rs, linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/discover.rs, linkerd/app/outbound/src/endpoint.rs, linkerd/app/outbound/src/http/detect.rs, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/http/server.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/logical.rs, linkerd/app/outbound/src/tcp/logical.rs
Version 1.50 of the Rust compiler introduced a regression
(https://github.com/rust-lang/rust/issues/84873) that results in the
compiler using extremely large amounts of memory (and eventually getting
OOM killed) when compiling code involving very large nested types. This
regression is triggered by a number of future types in the proxy.
This branch introduces several `BoxService` layers, primarily around
`Switch` layers, to reduce the size of future types, so that the proxy
can successfully be compiled on Rust 1.50+.
This branch does *not* update the toolchain version. The Rust 1.51
toolchain also introduces some new clippy lints, which trigger on some
code patterns that are very common in the current proxy. Therefore, the
diff from a compiler update will be much larger than just adding …
=> prepare for Rust 1.50+ by boxing large futures

Cargo.lock, linkerd/app/core/src/lib.rs, linkerd/app/inbound/fuzz/Cargo.lock, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/mod.rs, linkerd/app/outbound/src/http/require_id_header.rs, linkerd/proxy/http/Cargo.toml, linkerd/proxy/http/fuzz/Cargo.lock, linkerd/proxy/http/src/lib.rs
The `proxy::http::identity_from_header` helper is only used in one place
and doesn't need to be exposed by the proxy::http module. Similarly the
`L5D_REQUIRE_ID` constant does not need to be used outside of the
outbound HTTP endpoint stack, though it is defined in `app::core`.
This change renames the `require_identity_on_endpoint` to
`require_id_header` and consolidates all related logic & constants into
the module. The module is now responsible for clearing the header as
well (rather than pairing the module with a generic strip-header layer).
=> http: Remove `identity_from_header` helper

.github/workflows/rust.yml
The fuzzer build CI takes >2x as long as any other CI task.
This change moves the fuzzer building CI task to use a matrix of targets
so that they may be built in parallel. Furthermore, fuzzers are now
excluded from the check task.
=> ci: Use a matrix of fuzzer targets

linkerd/app/inbound/src/lib.rs, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/logical.rs
This change ~halves compile-time and memory usage of release builds
Before this change:
Command being timed: "cargo build -p linkerd2-proxy --release"
User time (seconds): 3233.32
System time (seconds): 49.02
Percent of CPU this job got: 583%
Elapsed (wall clock) time (h:mm:ss or m:ss): 9:22.92
Maximum resident set size (kbytes): 57377268
With this change:
Command being timed: "cargo build -p linkerd2-proxy --release"
User time (seconds): 1935.21
System time (seconds): 32.59
Percent of CPU this job got: 594%
Elapsed (wall clock) time (h:mm:ss or m:ss): 5:31.18
Maximum resident set size (kbytes): 23842208
=> outbound: Box HTTP endpoint stack

linkerd/app/core/src/control.rs
When there are multiple replicas of a controller--especially the
destination controller--the proxy creates a load balancer to distribute
requests across all controller pods.
linkerd/linkerd2#6146 describes a situation where controller connections
fail to be established because the client stalls for 50s+ between
initiating a connection and sending a TLS ClientHello, long after the
server has timed out the idle connection.
As it turns out, the controller client does not necessarily drive all of
its endpoints to readiness. Because load balancers are designed to
process requests when only a subset of endpoints are available, the load
balancer cannot be responsible for driving all endpoints in a service to
readiness and we need a `SpawnReady` layer that is responsible for
driving individual …
=> control: Ensure endpoints are driven to readiness

linkerd/trace-context/src/service.rs
Query string in Span name makes additional noise to Jaeger operation filter as on picture below.
Suggest to use path only for span name but still use path and query in `http.path` property.
=> Make span name without query string

linkerd/app/core/src/lib.rs, linkerd/app/core/src/svc.rs, linkerd/app/inbound/src/http/mod.rs, linkerd/app/outbound/src/http/endpoint.rs, linkerd/app/outbound/src/http/logical.rs, linkerd/app/outbound/src/ingress.rs, linkerd/app/outbound/src/lib.rs, linkerd/tls/src/client.rs
In f8cc918e, we started requiring the `l5d-dst-override` header. As
described in linkerd/linkerd2#6157, this breaks some ingress
configurations, especially those that may route to out-of-cluster
resources.
This change restores original-dst-addr routing for requests that do not
include the `l5d-dst-override` header.
Internally, this change centralizes the `DST_OVERRIDE_HEADER` and
related utilities to the ingress module, as no other modules should have
to know anything about it.
=> ingress: Restore original dst address routing

linkerd/app/core/src/control.rs, linkerd/app/src/dst.rs, linkerd/app/src/oc_collector.rs, linkerd/proxy/identity/src/certify.rs
We currently build the identity client at startup and hold it to be used
fairly infrequently: the client is used once per day by default, and
even in extremely aggressive scenarios is unlikely to be used more
frequently than once every few minutes. As such, there's very little
benefit to holding the client (and buffers, DNS resolutions, etc) open
continually. Instead, it seems preferable to instantiate the identity
client only as it's needed.
Practically, we see issues like linkerd/linkerd2#6184 where the identity
client may try to reconnect to stale endpoints when the identity
deployment is rescheduled (because there aren't a steady stream of
requests on this client).
This change makes the controller stack a `NewService<()>` so that
clients can be instantiated lazily. The identity module …
=> control: Build the identity client each time it's used

linkerd/app/core/src/telemetry/process.rs
On MacOS, the module `telemetry::process` in `linkerd-app-core` fails
to build because the `info!` macro is used on non-Linux systems, but
it is not imported.
=> Fix MacOS conditional build in telemetry::process
