src/telemetry/sensor/transport.rs
src/transport/connection.rs

Reduce visibility of some `transport::connection` items.

---

Dockerfile
src/bind.rs
src/control/destination/endpoint.rs
src/telemetry/control.rs
src/telemetry/mod.rs
src/transparency/protocol.rs
tests/telemetry.rs

Signed-off-by: Markus Jais <markusjais@googlemail.com>
no code changes, just some fixed typos in comments and Dockerfile

fixed some typos in comments and Dockerfile

---

src/control/destination/background/mod.rs

This is strictly a refactor which should make no functional changes.
Currently, the function used to construct new Destination service
queries (`Background::query_destination_service_if_relevant`) is a
function rather than a method on `Background`, although it takes as an
argument a field from `Background`. This is because in some cases, it is
called where `self.destinations` is borrowed mutably, preventing `self`
from being borrowed immutably.
Right now, this means that one additional field has to be passed
explicitly. However, in order to add the limit on active Destination
service queries, it was necessary to add two additional fields to
`Background` that have to be passed to this function. Since these
arguments should always come from fields on `Background`, it would be
preferable for …

refactor: Make `Background::query_destination_service_if_relevant` into a method

---

src/transparency/h1.rs
tests/transparency.rs

Closes https://github.com/linkerd/linkerd2/issues/1407

strip other connection-level headers from HTTP/1

---

src/bind.rs

`bind::BoundService` wraps a `Reconnect` service and handles its Connect
errors. However, `BoundService` exposes `Reconnect`'s Error type to
callers even though these errors can never be returned.
Furthermore, `Reconnect` is allowed be polled after returning an error,
triggering the inner service to be rebuilt. We needlessly duplicate this
logic in `BoundService`.
Before splitting this file up into smaller chunks, let's update
`BoundService` to more narrowly adhere to `Reconnect`s API:
- Only the inner error type is returned. `unreachable!` assertions
have been made where error variants cannot be returned.
- Do not "rebind" the stack explicitly. Instead, let `Reconnect` do
this.
- Now BoundService::call may panic if invoked before poll_ready. It's a
programming error, since `Reconnect` …

Remove redundant reconnect logic

---

Cargo.lock

Includes some bug fixes around HTTP parsing, and better HTTP/1.0 keep-alive handling.

Update http and hyper crates

---

src/transport/connection.rs

I was looking at https://github.com/linkerd/linkerd2/issues/1803, and was lefting wondering what address could be causing those errors. This adds the address to the error message if there is a TCP connect error.

include address in TCP connect error messages

---

lib/metrics/src/counter.rs

This implements Prometheus reset semantics for counters, in order to
preserve precision when deriving rate of increase.
Wrapping is based on the fact that Prometheus models counters as `f64`
(52-bits mantissa), thus integer values over 2^53 are not guaranteed to
be correctly exposed.

metrics/counter: wrap values over 2^53

---

src/transport/connection.rs

Signed-off-by: David Capino <david.capino@gmail.com>

Minor spelling error in connection.rs comments

---

tests/support/client.rs
tests/support/mod.rs
tests/support/tap.rs
tests/tap.rs

Notably, I wrote these before pulling in #152, and the test was failing, and then after rebasing, the test passes!

Add basic tap integration tests

---

Cargo.lock
Cargo.toml

Fixes DATA padding and leaked connection window capacity.

Update h2 to v0.1.14

---

Makefile
README.md

Signed-off-by: Jon Richards <jon.richards@nordstrom.com>

Add clean target

---

Makefile

Signed-off-by: Jon Richards <jon.richards@nordstrom.com>

Add missing fetch for test-flakey

---

CONTRIBUTING.md

See https://github.com/linkerd/linkerd2/pull/1331/commits/f833f5659c3b36eabcf65c30ebf46537b05b4954
Signed-off-by: Jon Richards <jon.richards@nordstrom.com>

Update for linkerd2 slack channel

---

.travis.yml
tests/discovery.rs
tests/telemetry.rs

Just trying this out to see if it passes, if it does, I'll remove all the `flaky_test` cfgs as well.

Try reducing CI flakiness by reducing RUST_TEST_THREADS to 1

---

src/transport/connection.rs
src/transport/tls/config.rs
src/transport/tls/mod.rs

Closes https://github.com/linkerd/linkerd2/issues/1359

Remove TLS fallback-to-plaintext if handshake fails

---

Cargo.lock
Cargo.toml

Update *ring* to 0.14.6

---

tests/discovery.rs

closes [linkerd2/2565](https://github.com/linkerd/linkerd2/issues/2565)

make outbound_dest_limit_does_not_limit_dns test flakey

---

Cargo.lock
Cargo.toml
src/app/config.rs
src/app/errors.rs
src/app/main.rs
src/proxy/http/glue.rs
src/proxy/mod.rs
src/proxy/shed.rs
tests/support/client.rs
tests/transparency.rs

Also adds configuration for inbound and outbound max-in-flight requests.

Add load shedding when over max-in-flight requests.

---

Cargo.lock

Hopefully the solution to https://github.com/linkerd/linkerd2/issues/2813

Update h2 to v0.1.19

---

src/proxy/http/metrics/report.rs

This branch changes the `proxy::http_metrics::Report` type so that when
the metrics report has a prefix (such as "route" or "control", etc), the
prefix is included in log lines emitted by the report.
Since the log line produced by `Report` includes the number of entries
in the metrics registry for that `Report`, this should make it much
easier to see which metrics scope that count corresponds to.

metrics: Include the prefix of a Report in log lines

---

src/proxy/http/h2.rs
tests/transparency.rs

Closes https://github.com/linkerd/linkerd2/issues/2942

Fix HTTP2 requests that don't have an :authority

---

src/app/tap.rs

replace macros with a function

---

src/tap/grpc/server.rs

A bug currently exists in the tap code where response streams never end
when reaching the limit on the number of events. Since these streams
never end, the tap controller never restarts them, causing the
user-facing tap output to hang.
This is due to a bug introduced in 073a1beb4a7cd709c6b1eaa56a319c1829a94d11. The `Dispatch` future
previously was responsible for holding a sender to the events channel,
and cloning it into each tapped service. In that change, the `Dispatch`
type was removed, and the cloned sender was moved to the `Tap` struct.
The `Dispatch` future was dropped when the limit is reached, but the
`Tap` struct is not. This means that the final sender is never dropped,
and the events stream never ends.
This commit fixes the bug by moving the sender into `Shared`, which
`Tap` …

tap: fix tap response streams never ending

---

lib/linkerd2-signal/src/lib.rs
src/telemetry/errno.rs

Fix compile error on windows

---

tests/discovery.rs
tests/support/controller.rs

The `discovery` tests attempt to simulate the scenario where the destination
service responds with an `InvalidArgument` gRPC status so the proxy
knows to skip balancing. The tests don't accurately simulate this
behavior, however.
The destination controller [eagerly fails such requests][1], rather than
successfully returning a stream that fails immediately. At the protocol
level, this causes the `grpc-status` to be encoded in the firt and only
HTTP response header frame, rather than in a trailer (i.e after the
initial `END_HEADERS` frame was sent indicating the begining of the
respnose steram); and in tower, this causes the initial response future
to fail.
This change modifies the mock controller and discovery tests so that
tests can fail the response eagerly without initiating the …

tests: Properly simulate destination errors

---

linkerd/proxy/transport/src/listen.rs

Just cleaning up an unused sock I found lying around.

Cleanup unused sock

---

.github/actions/package/Dockerfile

I must have really been rushing when cleaning the checksec PR up for
merge after testing. This gets a working script.

Fix the checksec URL

---

linkerd/app/core/src/errors.rs

The changes to the `Respond` trait eliminate the need for our
implementation to track the repsonse-body type via `PhantomData`.

Remove unneeded PhantomData

---

Cargo.lock
linkerd/router/Cargo.toml
linkerd/router/src/lib.rs

This is a purely mechanical update that makes the API 
changes I'm sure you've all gotten pretty used to by now.

port router to std::future

---

Cargo.lock
hyper-balance/Cargo.toml
hyper-balance/src/lib.rs
linkerd/proxy/http/src/lib.rs

This will be the first step in the process of picking up the new Hyper.

update hyper-balance to std::future and hyper 0.13

---

linkerd/buffer/src/dispatch.rs

fix delay pinning

---

profiling/benchmark.sh
profiling/plot.sh
profiling/profiling-heap.sh
profiling/profiling-perf.sh
profiling/profiling-util.sh
profiling/run-proxy.sh

Signed-off-by: Joakim Roubert <joakim.roubert@axis.com>

Fix shellcheck issues in shell scripts

---

.github/CODEOWNERS
Makefile

Cherry-picks two changes from master to master-tokio-0.2

Cherry-pick changes from master

---

CONTRIBUTING.md
profiling/README.md

Change docs references from "master" to "main"

---

linkerd/opencensus/src/lib.rs

In the `futures` 0.1 version of the OpenCensus module, the `tower-grpc`
response future for the client-streaming RPC was never polled, because
we did not need the server response for that RPC. At the time, this was
fine, as `tower-grpc` still established the connection and ensured
messages were sent to the server. However, after updating to `tonic`,
this was no longer the case --- the response future is now responsible
for establishing the connection. This means spans are no longer sent to
the OpenCensus collector.
Due to an issue where the cloud integration tests were silently failing
to run, we missed this regression.
This PR fixes the regression by ensuring that we drive the response
future.
I'd like to rewrite this code to use async-await rather than the manual
state machine, but this …

opencensus: drive rsp future to establish conn

---

.github/actions/package/Dockerfile
.github/workflows/release.yml
Makefile

@cpretzer @olix0r 
Tested in local fork: 
- https://github.com/aliariff/linkerd2-proxy/actions/runs/162476791
Resulting tag:
- https://github.com/aliariff/linkerd2-proxy/releases/tag/release%2Ftest-13
Signed-off-by: Ali Ariff <ali.ariff12@gmail.com>

Add multi arch release artifacts

---

linkerd/stack/src/new_service.rs

This change adds a utility for casting a NewService into a MakeService.
This aids an upcoming refactor, but it is not strictly tied to those changes.

stack: Add NewService::into_make_service

---

linkerd/proxy/http/src/client.rs
linkerd/proxy/http/src/h2.rs

This branch adds some DEBUG- and TRACE-level spans to HTTP clients and
client connections. These are hidden by default but may be useful when
debugging, or for generating tracing flamegraphs (as in PR #614).

add richer verbose spans to HTTP clients

---

Dockerfile

Pick up changes described in linkerd/linkerd2#4873

Update proxy-identity to edge-20.8.2

---

linkerd/app/core/src/control.rs

Arbitrary (unexpected) DNS errors can blow up the control client.
Instead, we should try to backoff & recover from these unexpected
errors.
Related to #639.

control: Recover from failed resolutions

---

linkerd/app/core/src/svc.rs
linkerd/app/inbound/src/lib.rs
linkerd/app/outbound/src/lib.rs

This change updates and extends the diagnostic stack checks that we use
during development. No functional changes.

svc: Update stack diagnostic checks

---

linkerd/app/inbound/src/lib.rs
linkerd/app/inbound/src/prevent_loop.rs

a233e1af altered the accept stack so that both TCP and HTTP stacks are
instantiated prior to performing detection on a socket. This will allow
us to cache these stacks for each destination.
However, this eager binding broke the gateway fallback logic, since the
TCP stack's failure invalidated the HTTP stacks' fallback to the
gateway.
This change moves loop detection onto the TCP connection stack so this
eager binding does not fail.
Fixes linkerd/linkerd2#4943

inbound: Apply loop detection on the connect stack

---

linkerd/app/inbound/src/lib.rs
linkerd/app/outbound/src/lib.rs
linkerd/app/src/lib.rs

The inbound and outbound configs bind an accept stack to the listener
via serve::serve; but this makes it infeasible to test the accept stacks
without actually binding a socket.
This change moves the server binding into the main app initialization so
that the inbound and outbound stacks can be built without a listener.

app: Decouple stacks from listeners

---

linkerd/stack/src/fallback.rs

This change adds an impementation of `NewService` for `Fallback`.
The returned service holds a primary service and the means to build a
fallback service if the primary service errors before becoming ready.

Implement fallback for NewService

---

Cargo.lock
linkerd/app/Cargo.toml
linkerd/app/core/Cargo.toml
linkerd/app/integration/Cargo.toml
linkerd/opencensus/Cargo.toml
linkerd/proxy/api-resolve/Cargo.toml
linkerd/proxy/identity/Cargo.toml
linkerd/proxy/tap/Cargo.toml
linkerd/proxy/tap/src/grpc/match_.rs
linkerd/proxy/tap/src/grpc/server.rs
linkerd/service-profiles/Cargo.toml
opencensus-proto/Cargo.toml

proxy-api v0.1.14 includes two new fields on profile resolutions. It
also has been updated to use tonic-0.3. This change pulls in these
updated dependencies.

Update proxy-api and tonic

---

linkerd/tracing/src/lib.rs

When the proxy log level is set to `off`, the proxy now skips all
tracing initialization and disables the tracing admin endpoints. This
allows us to minimize the overhead of tracing in benchmarks and
performance-critical environments.
This has a noticeable impact on _memory_. In local tests, we see
`main` use around ~24MB with the log level set to `off`. With this
branch, memory comes down to ~16MB.

tracing: Support disabling tracing entirely

---

linkerd/concurrency-limit/src/lib.rs

The concurrency-limit module holds permits until the response future is
dropped. This is fine in theory, but we have reports of clients hitting
the concurrency limit unexpectedly.
This change ensures that the permit is released immediately as soon as
the inner future becomes ready, regardless of how long the response
future is held. This also adds trace logging when the permit is
released.

concurrency-limit: Drop permit on readiness

---

Cargo.lock
Makefile
linkerd/metrics/Cargo.toml
linkerd/metrics/src/counter.rs
linkerd/metrics/src/lib.rs
linkerd/metrics/src/summary.rs

Also fix broken summary support; and ensure that all features are
checked in CI.

metrics: Add support for microsecond counters

---

linkerd/proxy/http/src/strip_header.rs

The `strip_header::Layer` type is unnecessary. This change eliminates it
in favor of an anonymous type.

Remove the strip_header::Layer type

---

linkerd/app/inbound/src/lib.rs

The `BoxedIo` type no longer provides special shutdown logic. This
change removes an unncessary box from the inbound connector.

Remove box from inbound connector

---

linkerd/service-profiles/src/client.rs

When an invalid duration is provided by the control plane, retry budget
conversion can panic. This error is triggered by quickcheck tests.
This change explicitly handles these negative values to avoid panicking.

service-profiles: Prevent Duration coercion panics

---

Cargo.lock
Cargo.toml
deny.toml
linkerd/app/Cargo.toml
linkerd/app/core/Cargo.toml
linkerd/app/integration/Cargo.toml
linkerd/opencensus/Cargo.toml
linkerd/proxy/api-resolve/Cargo.toml
linkerd/proxy/identity/Cargo.toml
linkerd/proxy/tap/Cargo.toml
linkerd/service-profiles/Cargo.toml
opencensus-proto/Cargo.toml

Updates the proxy-api version to tagged release.

Update tonic to v0.4

---

linkerd/app/inbound/src/lib.rs

In 1a7de34a, the inbound proxy was updated to hold a unified `direct`
stack; but in this change we started doing HTTP protocol detection even
when a transport header is present. But, currently, the existence of a
transport header indicates that the connection is likely opaque and so
such protocol detection must not be performed.
This change updates the direct stack to avoid HTTP detection when a
transport header is present.

inbound: Avoid HTTP detection when a transport header is present

---

Cargo.lock

https://github.com/tokio-rs/tokio/releases/tag/tokio-1.1.0

Update tokio to v1.1.0

---

linkerd/app/gateway/src/lib.rs

80f432d0 updated the gateway to use the transport header metadata for
request routing, but this ignored the request-level HTTP version which
may be modified by orig-proto downgrading.
This change reintroduces a request router onto the HTTP gateway so that
the request version may be used.

Fix HTTP gateway for protocol downgrading

---

GOVERNANCE.md
MAINTAINERS.md

Update links to refer to the `main` branch.

Update MAINTAINERS to point at the main repo

---

linkerd/app/outbound/src/endpoint.rs
linkerd/app/outbound/src/lib.rs

This change renames `endpoint_override` to be `profile_endpoint`:
"override" implies some behavior is being superceded, but in this case
we're simply getting endpoint metadata in place of logical/concrete
metadata.

Polish profile-based endpoint stack

---

linkerd/app/outbound/src/tcp/connect.rs

the TCP forward stack is target-agnostic. This change relaxes the hard
dependency on the `Endpoint` target type.

Decouple tcp forward stack from Endpoint target

---

Dockerfile

pickup `linkerd-await` wrapper in docker build

---

linkerd/app/core/src/retry.rs

The core retry policy doesn't actually need to be generic: it's only
ever constructed with the `WithBody` type. This change simplifies the
retry types by removing unneeded generics.

retry: Remove generic types from `Retry` policy

---

linkerd/app/core/src/retry.rs
linkerd/http-retry/src/lib.rs

Currently, the decision of whether or not a request can be retried is
made in the `clone_request` implementation for the `Retry` type in
`linkerd_app_core`. This is problematic, because by the time
`clone_request` is called, the request body has _already_ been wrapped
in a `ReplayBody`. The `ReplayBody` will buffer _regardless_ of whether
or not it's cloned. This means that the maximum length to buffer doesn't
_actually_ stop us from buffering --- it just determines whether we will
actually attempt to retry on failure, and whether we will retain that
buffer past when the request ends. The request will still buffer all
body data, but it will be dropped when the single instance of the body
is dropped. This means that for very long streaming bodies, we may
buffer increasingly large amounts …

retry: only wrap bodies when a request can be retried

---

.github/workflows/rust.yml
linkerd/http-box/src/erase_request.rs
opencensus-proto/opencensus/proto/trace/v1/trace.proto
opencensus-proto/src/lib.rs

Some errors occur when I run `cargo doc`. Here are some screenshots showing error details.

docs: Fix some compile errors that occur in `cargo doc`

---

linkerd/app/core/src/metrics/mod.rs
linkerd/app/core/src/metrics/tcp_accept_errors.rs
linkerd/app/core/src/transport/labels.rs
linkerd/app/inbound/src/target.rs
linkerd/app/outbound/src/endpoint.rs
linkerd/metrics/src/new_metrics.rs

Simplifies the error metrics signature

Seal the TargetAddr label type in app::core

---

linkerd/app/inbound/src/detect.rs

Per-port server policies include protocol hinting that is not currently
honored.
This change modifies the inbound detect stacks to only perform HTTP
detection when the server policy indicates that detection should be
pefromed. It also honors the per-port detect timeout configuration. When
a port is documented as HTTP/1, HTTP/2, or gRPC, protocol detection is
skipped and the configuration is used instead.
When the port's protocol is documented to be application TLS, we check
that authorization policies apply but we do not explicitly enforce that
application TLS was present, since we may _additionally_ apply mesh TLS
in these situations.

inbound: Use policy protocol configurations

---

linkerd/service-profiles/src/client.rs

The profile client may be cloned to be shared across connections and
requests. This change stores the context token in an `Arc<str>` so
cloning gthe profile client doesn't require heap allocation. Now the
context token is re-allocated each time a gRPC request is issued. This
is much less frequent than the stack is cloned and also totally
unavoidable with prost.

profiles: Share context-token allocations across instances

---

linkerd/app/integration/src/tests/transparency.rs
linkerd/proxy/http/src/h1.rs

When the proxy transports `CONNECT` requests, the client silently
ignores `content-length` and `transport-encoding` response headers, as
it should. When the proxy passees these headers to the hyper server, it
errors (as is dictated by the RFC).
This change updates the HTTP client to remove these headers from
responses so that the proxy no longer propagates these illegal headers.
Fixes linkerd/linkerd2#8539

http: Strip illegal headers from CONNECT responses

---

README.md

Update README to mention just and devcontainers

---

justfile

dev: Fix the `just docker` recipe

---

justfile

Signed-off-by: spacewander <spacewanderlzx@gmail.com>

docs: update justfile man page link

---

linkerd/tls/src/server.rs

The TLS detection code holds a ~512B buffer when peeking on a socket to
parse an SNI value from a client connection. This is done to avoid a
heap allocation--this optimization is probably premature.
Per a conversation with @carllerche, holding data across an `await` is a
painful anti-pattern that can have severe performance impacts, since the
generated `Future` ends up holding all of this data (on the stack).
Instead, our default behavior should be to use a heap-allocated data
structure for any data that crosses an async `await`.
This change eliminates the stack-allocated buffer in our TLS server in
favor of a heap-allocated buffer.

tls: Avoid holding a large buffer across await

---

.devcontainer/devcontainer.json
.github/workflows/actions.yml
.github/workflows/beta.yml
.github/workflows/check-all.yml
.github/workflows/check-each.yml
.github/workflows/coverage.yml
.github/workflows/deps.yml
.github/workflows/integration.yml
.github/workflows/lint.yml
.github/workflows/nightly.yml
.github/workflows/test.yml
.github/workflows/toolchain.yml

dev: Update to fix protobuf includes

---

.devcontainer/devcontainer.json
.github/actions/list-changed-crates/Dockerfile
.github/workflows/actions.yml
.github/workflows/beta.yml
.github/workflows/check-all.yml
.github/workflows/check-each.yml
.github/workflows/coverage.yml
.github/workflows/deps.yml
.github/workflows/integration.yml
.github/workflows/lint.yml
.github/workflows/nightly.yml
.github/workflows/shellcheck.yml
.github/workflows/test.yml
.github/workflows/toolchain.yml

* Fix yarn installation
* Add Rust MUSL toolchain
* Replace `json5-to-json` with friendlier `j5j`
* Add `step` CLI

dev: Update devcontainer to v30

---

linkerd/dns/src/lib.rs

See https://github.com/linkerd/linkerd2/discussions/9227
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

chore(dns): clean up outdated comment

---

linkerd/app/core/src/svc.rs
linkerd/app/gateway/src/lib.rs
linkerd/app/inbound/src/http/router.rs
linkerd/app/outbound/src/discover.rs
linkerd/app/outbound/src/http/logical.rs
linkerd/app/outbound/src/ingress.rs
linkerd/app/outbound/src/tcp/logical.rs

Follow-up from 5d0b2260 (#2118)

Rename Stack::push_cache to push_idle_cache

---

linkerd/addr/src/lib.rs

The `dns::Name` type holds a `String`. We currently use `NameAddr`s throughout the proxy, cloning them frequently.
To reduce allocation overhead of these clones, this change updates `NameAddr` to hold its inner `Name` by reference.

Make NameAddr cheaper to clone

---

README.md

README: comment just-cargo and make it more clear
Signed-off-by: Loong <loong.dai@intel.com>

README: comment just-cargo and make it more clear

---

linkerd/app/outbound/src/http/logical/policy.rs
linkerd/service-profiles/src/client.rs

* Reduce verbosity of per-request route debug logging
* Increase profile resolution logging to debug

outbound: Simplify discovery debug logging

---

linkerd/app/outbound/src/discover.rs

The outbound::discover module spawns a task to watch profiles for updates, but this task does not stop when the associated receiver is dropped.
This changes the task to exit when the policy channel is closed.

outbound: Eagerly cancel synthesized profile task

---

linkerd/app/outbound/src/http/logical/tests.rs

This branch adds a new test for failure accrual in load balancers with multiple endpoints. This test asserts that endpoints whose circuit breakers have tripped will not be selected by a load balancer.

outbound: test load balancer behavior with failure accrual

---

linkerd/app/core/src/classify.rs

The gRPC protocol always sets the HTTP response status code to 200 and instead communicates failures in a grpc-status header sent in a TRAILERS frame. Linkerd uses the HTTP response status code to determine if a response is successful, and therefore will consider all gRPC responses successful regardless of their gRPC status code. This means that functionality such as retries and circuit breaking do not function correctly with gRPC traffic.
We update the Http classifier to look for the presence of a `Content-Type: application/grpc` header and use Grpc response classification when it is set.

Classify grpc requests properly in the http classifier

---

.codecov.yml
.github/workflows/coverage.yml

Configure codecov to skip the PR status checks for now.

Add a .codecov.yml

---

linkerd/app/outbound/src/http/concrete/tests.rs

And add a reminder to remove some parts of this test in the future.

test: Improve error reporting in gauges_endpoints

---

linkerd/app/core/src/config.rs
linkerd/app/outbound/src/http/concrete.rs
linkerd/app/outbound/src/http/concrete/balance.rs
linkerd/app/outbound/src/http/concrete/tests.rs

No functional changes. Setup for changes to come.

outbound: Move HTTP balancer into its own module

---

.devcontainer/devcontainer.json
.gitignore
.vscode/settings.json

Adds .vscode/settings.json to .gitignore.
This allows per-user workspace configurations.

vscode: Move workspace settings to devcontainer

---

linkerd/app/src/env.rs

Found [this issue](https://github.com/linkerd/linkerd2/issues/10299) while looking for easy Rust related issues, hopefully it is still relevant.

Change inbound port check log level to debug.

---

linkerd/pool/src/lib.rs

This eliminates annoying warnings.

docs: Fix bad reference link

---

Cargo.lock

* Downgrade clang-sys to v1.8.1
* Downgrade rustc-hash to v1.1.0

build(deps): Remove yanked dependency versions

---

linkerd/proxy/http/src/stream_timeouts.rs

The previous implementation of the stream timeout errors did not properly wrap error type so they could be discovered by the metrics middleware. This change fixes the error wrapping so that the underlying error type is discoverable as a source.
This change also fixes a request header timeout calculation. This feature is not currently exposed to the router stack.

fix(stream_timeouts): Fix Error type classification

---

.github/workflows/pr.yml
justfile

Simple typo fix in the justfile and associated github workflow.

Fix typo in justfile recipe

---

linkerd/http/prom/src/count_reqs.rs

this is a light documentation pass outlining how the request counting middleware fits together.
this was selfishly done for my own edification, but felt worth proposing as a commit for other future readers. :memo:

docs(http/prom): Document request count middleware

---

linkerd/app/outbound/src/opaq.rs

To fix a regression in 7eadac4d9, where authority labels are not properly set on legacy TCP metrics, this commmit uses the profile-provided authority when it is set.

fix(outbound): fall back to profile-provided authority

---

linkerd/app/integration/src/server.rs

elsewhere in our codebase, we follow a pattern that can be called a "new service". this is a `Service<T>` whose response `S` is itself a `Service<U>`.
new services are often useful for dealing with particular connection semantics, and provide us a way to model a connection that services many requests.
our test server code makes use of a `Svc`, which wraps a reference to a map of uri's and routes. there is an associated `NewSvc` type that does not provide any material benefit. this `NewSvc` type is a `Service<()>` that never exerts backpressure, nor performs any action besides `Arc::clone`ing the map of routes.
this commit golfs down `linkerd_app_integration::server::Server`, by directly cloning the routes into a `Svc(_)`, without the need for polling a future or handling an (impossible) …

refactor(app/integration): remove inert `NewService<T>`

---

linkerd/app/integration/src/server.rs

the test server implementation in `linkerd_app_integration` defines an `BoxError` alias. we have a boxed error type in `linkerd_app_core::Error` that achieves the same purpose, that we can use instead.
this commit replaces this type alias with a reëxport of `linkerd_app_core::Error`.
see also #3685, which removed another similar alias.

refactor(app/integration): use `linker_app_core::Error`

---

linkerd/app/integration/src/client.rs
linkerd/app/integration/src/server.rs

we follow a convention of an empty line between functions. this branch contains some commits that add and remove an empty lines to follow the broader conventions in the codebase.

nit(app/integration): add/remove whitespace for consistency

---

linkerd/app/inbound/src/direct.rs

Currently, TCP metrics are not logged for HTTP requests coming in through the tagged transport header stack.
This adds that instrumentation, like we do for the opaque and gateway stacks already present.

fix(inbound): Instrument http requests in tagged transport stack

---

linkerd/stack/src/switch_ready.rs

this commit makes a noöp change to the `SwitchReady<A, B>` machinery provided by our `linkerd-stack` library.
this commit is a small refactor that is intended to pave the way for an impending upgrade to tower v0.5, which notably includes breaking changes to the `tower::util::Either<A, B>` service.
as of tower v0.5, by way of https://github.com/tower-rs/tower/pull/637, the `Either<A, B>` service is no longer itself a `Future`. so, we can instead use the future provided by `futures`.
for more information, see:
* https://github.com/linkerd/linkerd2/issues/8733
* https://github.com/linkerd/linkerd2-proxy/pull/3504
* https://github.com/linkerd/linkerd2-proxy/pull/3504/files#r1988082658
* https://github.com/tower-rs/tower/pull/637

refactor(stack/switch_ready): use `Either<A, B>` future

---

linkerd/stack/src/loadshed.rs

this commit performs a small refactor to one of the unit tests in `linkerd-stack`'s load-shedding middleware.
this adds a span to the worker tasks spawned in this test, so that tracing logs can be associated with particular oneshot services.
see #3744 for more information on upgrading our tower dependency. this is cherry-picked from investigations on that branch related to breaking changes in 0.5 related to the `Buffer` middleware.
after this change, logs now look like this:
```
; RUST_LOG="trace" cargo test -p linkerd-stack buffer_load_shed -- --nocapture
running 1 test
[     0.002770s] TRACE worker{id=oneshot1}: tower::buffer::service: sending request to buffer worker
[     0.002809s] TRACE worker{id=oneshot2}: tower::buffer::service: sending request to buffer worker
[     0.002823s] …
```

refactor(stack/loadshed): unit test instruments spawned tasks

---

Cargo.lock
deny.toml

this commit updates our `icu_*` dependencies.
see:
* #3811
* #3812
* #3813
* #3815

chore(deps): update unicode dependencies

---

linkerd/app/inbound/src/lib.rs
linkerd/app/inbound/src/server.rs

NB: this is based upon
https://github.com/linkerd/linkerd2-proxy/pull/4135.
as we did for `into_tcp_connect()`, we can move this method into the
`server` submodule, the only place it is used.

refactor(app/inbound): move `push_tcp_forward()` `server`
